import { ChangeDetectionStrategy, Component, OnDestroy, OnInit, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Subscription } from 'rxjs';
import { AlertsRealtimeService } from '../alerts/alerts-realtime.service';
import { AdminShell } from '../../shared/admin-shell/admin-shell';
import { ExportJob, ReportCatalogItem, ReportDataRow, ReportsApiService } from './reports-api.service';

@Component({selector:'app-reports-dashboard-page',imports:[AdminShell,FormsModule],changeDetection:ChangeDetectionStrategy.OnPush,template:`
<app-admin-shell [adminType]="platform?'platform':'customer'" [pageTitle]="platform?'Platform reports & exports':'Reports & exports'" eyebrow="Phase 15 · Server-authorized reporting">
  <p class="boundary">{{platform?'Platform scope is validated by the server.':'All tenant and store scope is derived and revalidated by the server.'}} Large exports run in the worker; the browser receives only paged report rows and short-lived download access.</p>
  @if(error()){<p role="alert" class="error">{{error()}}</p>}
  <section class="panel filters"><h2>Run report</h2><label>Report<select [(ngModel)]="reportType">@for(item of catalog();track item.reportType){<option [ngValue]="item.reportType">{{item.name}}</option>}</select></label><label>From<input type="datetime-local" [(ngModel)]="from"></label><label>To<input type="datetime-local" [(ngModel)]="to"></label><label>Store IDs<input placeholder="7, 8" [(ngModel)]="stores"></label><button type="button" (click)="run()">Run paged report</button><label>Format<select [(ngModel)]="format"><option [ngValue]="1">CSV</option><option [ngValue]="2">Excel</option><option [ngValue]="3">PDF</option></select></label><button type="button" (click)="queue()">Queue export</button></section>
  <section class="panel"><h2>Report results</h2><p>{{rows().length}} of {{totalRows()}} rows loaded; export larger data asynchronously.</p><div class="table"><b>Domain</b><b>Store</b><b>Metric</b><b>Value</b><b>Label</b>@for(row of rows();track $index){<span>{{row.domain}}</span><span>{{row.storeId??'Tenant-wide'}}</span><span>{{row.metric}}</span><span>{{row.value}}</span><span>{{row.label}}</span>}</div></section>
  <section class="panel"><h2>Export queue</h2><p>Real-time: {{realtime.connectionState()}}. Polling remains authoritative after reconnect.</p>@for(job of jobs();track job.id){<article class="job"><b>Export {{job.id}} · {{formatName(job.format)}}</b><span>{{statusName(job.status)}} · {{job.progress}}%</span><progress max="100" [value]="job.progress"></progress><small>Expires {{job.expiresUtc}}</small>@if(job.error){<span class="error">{{job.error}}</span>}@if(job.status===4){<button type="button" (click)="retry(job.id)">Retry failed export</button>}@if(job.canDownload){<button type="button" (click)="download(job.id)">Download</button>}</article>}</section>
</app-admin-shell>`,styles:[`:host{display:block}.boundary{border-left:4px solid var(--color-accent);padding:.8rem 1rem}.panel{background:var(--color-surface);border:1px solid var(--color-border);border-radius:var(--radius-sm);margin-bottom:1rem;padding:1rem}.filters{display:grid;grid-template-columns:repeat(4,minmax(9rem,1fr));gap:.7rem}.filters label,.job{display:grid;gap:.35rem}.filters input,.filters select{background:var(--color-background);border:1px solid var(--color-border);color:var(--color-text);padding:.6rem}.panel button{background:var(--color-accent);border:0;border-radius:var(--radius-sm);color:var(--color-on-accent);font-weight:700;padding:.65rem}.table{display:grid;grid-template-columns:repeat(5,minmax(8rem,1fr));overflow:auto}.table>*{border-bottom:1px solid var(--color-border);padding:.45rem}.job{border-bottom:1px solid var(--color-border);padding:.7rem 0}.error{color:var(--color-danger)}@media(max-width:850px){.filters{grid-template-columns:1fr 1fr}}`],})
export class ReportsDashboardPage implements OnInit,OnDestroy{
  private readonly api=inject(ReportsApiService);private readonly route=inject(ActivatedRoute);protected readonly platform=this.route.snapshot.data['scope']==='platform';protected readonly realtime=inject(AlertsRealtimeService);private readonly subscriptions=new Subscription();protected readonly catalog=signal<ReportCatalogItem[]>([]);protected readonly rows=signal<ReportDataRow[]>([]);protected readonly jobs=signal<ExportJob[]>([]);protected readonly totalRows=signal(0);protected readonly error=signal('');protected reportType=1;protected format=1;protected from='2026-08-01T00:00';protected to='2026-08-26T00:00';protected stores='';
  ngOnInit():void{this.api.catalog(this.platform).subscribe({next:x=>{this.catalog.set(x);if(x.length)this.reportType=x[0].reportType;},error:()=>this.fail('Unable to load report catalog.')});this.loadJobs();if(!this.platform){this.subscriptions.add(this.realtime.events$.subscribe(event=>{if(event.eventType.startsWith('export.'))this.loadJobs();}));void this.realtime.start();}}
  ngOnDestroy():void{this.subscriptions.unsubscribe();}
  protected run():void{this.api.run(this.reportType,this.filter(),this.platform).subscribe({next:x=>{this.rows.set(x.rows);this.totalRows.set(x.totalRows);},error:()=>this.fail('Report request was rejected.')});}
  protected queue():void{this.api.queue(this.reportType,this.format,this.filter(),this.platform).subscribe({next:()=>this.loadJobs(),error:()=>this.fail('Export request was rejected.')});}
  protected retry(id:number):void{this.api.retry(id,this.platform).subscribe({next:()=>this.loadJobs(),error:()=>this.fail('Export retry was rejected.')});}
  protected download(id:number):void{this.api.ticket(id,this.platform).subscribe({next:x=>window.location.assign(this.api.downloadUrl(id,x.token,this.platform)),error:()=>this.fail('Download access is unavailable or expired.')});}
  protected statusName(value:number):string{return({1:'Queued',2:'Processing',3:'Completed',4:'Failed',5:'Expired'} as Record<number,string>)[value]??'Unknown';}protected formatName(value:number):string{return({1:'CSV',2:'Excel',3:'PDF'} as Record<number,string>)[value]??'Unknown';}
  private loadJobs():void{this.api.jobs(this.platform).subscribe({next:x=>this.jobs.set(x),error:()=>this.fail('Unable to load export queue.')});}
  private filter(){return{fromUtc:new Date(this.from).toISOString(),toUtc:new Date(this.to).toISOString(),storeIds:this.platform?[]:this.stores.split(',').map(x=>Number(x.trim())).filter(x=>Number.isSafeInteger(x)&&x>0),page:1,pageSize:100};}
  private fail(message:string):void{this.error.set(message);}
}
