using CustSearch.Domain.Enums;

namespace CustSearch.Domain.Entities;

public sealed class TenantStoragePolicy
{
    private TenantStoragePolicy(){}
    private TenantStoragePolicy(long tenantId,DateTime now){ArgumentOutOfRangeException.ThrowIfNegativeOrZero(tenantId);TenantId=tenantId;StorageEnabled=true;StorageQuotaBytes=2L*1024*1024*1024;DefaultRetentionDays=15;MotionSnapshotRetentionDays=15;MotionClipRetentionDays=15;FalsePositiveRetentionDays=3;UnreviewedEvidenceRetentionDays=15;ConfirmedIncidentRetentionDays=30;WarningPercent=80;CriticalPercent=90;AllowSnapshots=true;AllowMotionClips=true;AutoCleanupEnabled=true;QuotaPressurePolicy=QuotaPressurePolicy.StopNewClips;CreatedUtc=Utc(now);UpdatedUtc=CreatedUtc;}
    public long Id{get;private set;}public long TenantId{get;private set;}public bool StorageEnabled{get;private set;}public long StorageQuotaBytes{get;private set;}public int DefaultRetentionDays{get;private set;}public int MotionSnapshotRetentionDays{get;private set;}public int MotionClipRetentionDays{get;private set;}public int FalsePositiveRetentionDays{get;private set;}public int UnreviewedEvidenceRetentionDays{get;private set;}public int ConfirmedIncidentRetentionDays{get;private set;}public int WarningPercent{get;private set;}public int CriticalPercent{get;private set;}public bool AllowSnapshots{get;private set;}public bool AllowMotionClips{get;private set;}public bool AutoCleanupEnabled{get;private set;}public QuotaPressurePolicy QuotaPressurePolicy{get;private set;}public DateTime CreatedUtc{get;private set;}public DateTime UpdatedUtc{get;private set;}public byte[]?RowVersion{get;private set;}
    public static TenantStoragePolicy CreateDefault(long tenantId,DateTime now)=>new(tenantId,now);
    public void Configure(bool enabled,long quotaBytes,int defaultDays,int snapshotDays,int clipDays,int falsePositiveDays,int unreviewedDays,int confirmedDays,int warning,int critical,bool allowSnapshots,bool allowClips,bool autoCleanup,QuotaPressurePolicy pressure,DateTime now){if(quotaBytes is<1048576 or>10995116277760)throw new ArgumentOutOfRangeException(nameof(quotaBytes));if(new[]{defaultDays,snapshotDays,clipDays,falsePositiveDays,unreviewedDays,confirmedDays}.Any(x=>x is<1 or>3650))throw new ArgumentOutOfRangeException(nameof(defaultDays));if(warning is<1 or>99||critical<=warning||critical>100)throw new ArgumentOutOfRangeException(nameof(warning));if(!Enum.IsDefined(pressure))throw new ArgumentOutOfRangeException(nameof(pressure));StorageEnabled=enabled;StorageQuotaBytes=quotaBytes;DefaultRetentionDays=defaultDays;MotionSnapshotRetentionDays=snapshotDays;MotionClipRetentionDays=clipDays;FalsePositiveRetentionDays=falsePositiveDays;UnreviewedEvidenceRetentionDays=unreviewedDays;ConfirmedIncidentRetentionDays=confirmedDays;WarningPercent=warning;CriticalPercent=critical;AllowSnapshots=allowSnapshots;AllowMotionClips=allowClips;AutoCleanupEnabled=autoCleanup;QuotaPressurePolicy=pressure;UpdatedUtc=Utc(now);}
    public int RetentionDays(CameraEvidenceType type)=>type switch{CameraEvidenceType.MotionSnapshot=>MotionSnapshotRetentionDays,CameraEvidenceType.MotionClip=>MotionClipRetentionDays,CameraEvidenceType.SecuritySnapshot or CameraEvidenceType.SecurityClip=>UnreviewedEvidenceRetentionDays,_=>DefaultRetentionDays};
    private static DateTime Utc(DateTime x)=>x.Kind==DateTimeKind.Utc?x:throw new ArgumentException("Timestamp must be UTC.");
}

public sealed class TenantStorageUsage
{
    private TenantStorageUsage(){}
    private TenantStorageUsage(long tenantId,long quota,DateTime now){TenantId=tenantId;QuotaBytes=quota;LastCalculatedUtc=Utc(now);}
    public long TenantId{get;private set;}public long QuotaBytes{get;private set;}public long UsedBytes{get;private set;}public long SnapshotBytes{get;private set;}public long MotionClipBytes{get;private set;}public long SecurityEvidenceBytes{get;private set;}public long OtherBytes{get;private set;}public DateTime LastCalculatedUtc{get;private set;}public DateTime?LastCleanupUtc{get;private set;}public DateTime?LastReconciledUtc{get;private set;}public byte[]?RowVersion{get;private set;}
    public static TenantStorageUsage Create(long tenantId,long quota,DateTime now)=>new(tenantId,quota,now);
    public void SetQuota(long quota,DateTime now){if(quota<UsedBytes)throw new InvalidOperationException("Storage quota cannot be below current usage.");QuotaBytes=quota;LastCalculatedUtc=Utc(now);}
    public void Reserve(CameraEvidenceType type,long bytes,DateTime now){ArgumentOutOfRangeException.ThrowIfNegativeOrZero(bytes);if(UsedBytes>QuotaBytes-bytes)throw new InvalidOperationException("Tenant evidence storage quota is full.");UsedBytes+=bytes;if(type==CameraEvidenceType.MotionSnapshot)SnapshotBytes+=bytes;else if(type==CameraEvidenceType.MotionClip)MotionClipBytes+=bytes;else if(type is CameraEvidenceType.SecuritySnapshot or CameraEvidenceType.SecurityClip)SecurityEvidenceBytes+=bytes;else OtherBytes+=bytes;LastCalculatedUtc=Utc(now);}
    public void Release(CameraEvidenceType type,long bytes,DateTime now,bool cleanup){if(bytes<0||bytes>UsedBytes)throw new ArgumentOutOfRangeException(nameof(bytes));UsedBytes-=bytes;if(type==CameraEvidenceType.MotionSnapshot)SnapshotBytes-=bytes;else if(type==CameraEvidenceType.MotionClip)MotionClipBytes-=bytes;else if(type is CameraEvidenceType.SecuritySnapshot or CameraEvidenceType.SecurityClip)SecurityEvidenceBytes-=bytes;else OtherBytes-=bytes;LastCalculatedUtc=Utc(now);if(cleanup)LastCleanupUtc=LastCalculatedUtc;}
    public void Reconcile(long snapshotBytes,long motionClipBytes,long securityEvidenceBytes,long otherBytes,DateTime now,bool cleanup){if(new[]{snapshotBytes,motionClipBytes,securityEvidenceBytes,otherBytes}.Any(x=>x<0))throw new ArgumentOutOfRangeException(nameof(snapshotBytes));var used=checked(snapshotBytes+motionClipBytes+securityEvidenceBytes+otherBytes);if(used>QuotaBytes)throw new InvalidOperationException("Reconciled storage usage exceeds the tenant quota.");SnapshotBytes=snapshotBytes;MotionClipBytes=motionClipBytes;SecurityEvidenceBytes=securityEvidenceBytes;OtherBytes=otherBytes;UsedBytes=used;LastCalculatedUtc=Utc(now);LastReconciledUtc=LastCalculatedUtc;if(cleanup)LastCleanupUtc=LastCalculatedUtc;}
    private static DateTime Utc(DateTime x)=>x.Kind==DateTimeKind.Utc?x:throw new ArgumentException("Timestamp must be UTC.");
}

public sealed class CameraEvidence
{
    private CameraEvidence(){}
    private CameraEvidence(long tenantId,long storeId,long cameraId,long?motionEventId,long?securityIncidentId,CameraEvidenceType type,string objectKey,long size,string contentType,byte[]hash,DateTime captured,DateTime retention,bool restricted,bool pinned,string serviceId,string eventId,string idempotencyKey,string ingestionHash,DateTime now){TenantId=tenantId;StoreId=storeId;CameraId=cameraId;MotionEventId=motionEventId;SecurityIncidentId=securityIncidentId;EvidenceType=type;StorageObjectKey=Required(objectKey,500);FileSizeBytes=size;ContentType=Required(contentType,100);ContentHash=hash.Length==32?hash.ToArray():throw new ArgumentException("SHA-256 hash is required.");CapturedUtc=Utc(captured);RetentionUntilUtc=Utc(retention);if(RetentionUntilUtc<CapturedUtc)throw new ArgumentOutOfRangeException(nameof(retention));IsRestricted=restricted;IsPinned=pinned;ServiceId=Required(serviceId,100);SourceEventId=Required(eventId,150);IdempotencyKey=Required(idempotencyKey,150);IngestionHash=Required(ingestionHash,64);CreatedUtc=Utc(now);}
    public long Id{get;private set;}public long TenantId{get;private set;}public long StoreId{get;private set;}public long CameraId{get;private set;}public long?MotionEventId{get;private set;}public long?SecurityIncidentId{get;private set;}public CameraEvidenceType EvidenceType{get;private set;}public string StorageObjectKey{get;private set;}=string.Empty;public long FileSizeBytes{get;private set;}public string ContentType{get;private set;}=string.Empty;public byte[]ContentHash{get;private set;}=[];public DateTime CapturedUtc{get;private set;}public DateTime RetentionUntilUtc{get;private set;}public bool IsRestricted{get;private set;}public bool IsPinned{get;private set;}public DateTime?DeletedUtc{get;private set;}public string?DeleteReason{get;private set;}public string ServiceId{get;private set;}=string.Empty;public string SourceEventId{get;private set;}=string.Empty;public string IdempotencyKey{get;private set;}=string.Empty;public string IngestionHash{get;private set;}=string.Empty;public DateTime CreatedUtc{get;private set;}public byte[]?RowVersion{get;private set;}public bool IsDeleted=>DeletedUtc.HasValue;
    public static CameraEvidence Create(long tenantId,long storeId,long cameraId,long?motionEventId,long?securityIncidentId,CameraEvidenceType type,string objectKey,long size,string contentType,byte[]hash,DateTime captured,DateTime retention,bool restricted,bool pinned,string serviceId,string eventId,string idempotencyKey,string ingestionHash,DateTime now)=>new(tenantId,storeId,cameraId,motionEventId,securityIncidentId,type,objectKey,size,contentType,hash,captured,retention,restricted,pinned,serviceId,eventId,idempotencyKey,ingestionHash,now);
    public void MarkDeleted(DateTime now,string reason){if(IsDeleted)return;DeletedUtc=Utc(now);DeleteReason=Required(reason,200);}
    private static string Required(string x,int max){ArgumentException.ThrowIfNullOrWhiteSpace(x);var v=x.Trim();return v.Length<=max?v:throw new ArgumentOutOfRangeException(nameof(x));}private static DateTime Utc(DateTime x)=>x.Kind==DateTimeKind.Utc?x:throw new ArgumentException("Timestamp must be UTC.");
}
