using CustSearch.Domain.Enums;

namespace CustSearch.Domain.Entities;

/// <summary>Authoritative per-camera motion/health rule configuration; detections remain observations.</summary>
public sealed class CameraMotionRule
{
    private CameraMotionRule(){}
    private CameraMotionRule(long tenantId,long storeId,long cameraId,string ruleCode,string ruleName,bool zoneRequired,DateTime utcNow)
    {ArgumentOutOfRangeException.ThrowIfNegativeOrZero(tenantId);ArgumentOutOfRangeException.ThrowIfNegativeOrZero(storeId);ArgumentOutOfRangeException.ThrowIfNegativeOrZero(cameraId);TenantId=tenantId;StoreId=storeId;CameraId=cameraId;RuleCode=Required(ruleCode,100).ToUpperInvariant();RuleName=Required(ruleName,150);ZoneRequired=zoneRequired;CreatedUtc=Utc(utcNow);UpdatedUtc=CreatedUtc;}
    public long Id{get;private set;}public long TenantId{get;private set;}public long StoreId{get;private set;}public long CameraId{get;private set;}public string RuleCode{get;private set;}=string.Empty;public string RuleName{get;private set;}=string.Empty;public bool IsEnabled{get;private set;}public decimal MinimumConfidence{get;private set;}public int Sensitivity{get;private set;}public int MinimumDurationSeconds{get;private set;}public int CooldownSeconds{get;private set;}public TimeOnly?StartTime{get;private set;}public TimeOnly?EndTime{get;private set;}public string DaysOfWeek{get;private set;}="*";public bool EvidenceSnapshotEnabled{get;private set;}public bool EvidenceClipEnabled{get;private set;}public int EvidencePreEventSeconds{get;private set;}public int EvidencePostEventSeconds{get;private set;}public AlertSeverity Severity{get;private set;}public bool CreateAlert{get;private set;}public bool RealtimeNotificationEnabled{get;private set;}public bool ZoneRequired{get;private set;}public long?ZoneId{get;private set;}public DateTime CreatedUtc{get;private set;}public DateTime UpdatedUtc{get;private set;}public byte[]?RowVersion{get;private set;}
    public static CameraMotionRule Create(long tenantId,long storeId,long cameraId,string ruleCode,string ruleName,bool zoneRequired,DateTime utcNow)=>new(tenantId,storeId,cameraId,ruleCode,ruleName,zoneRequired,utcNow);
    public void Configure(string ruleName,bool enabled,decimal confidence,int sensitivity,int minimumDurationSeconds,int cooldownSeconds,TimeOnly?startTime,TimeOnly?endTime,string daysOfWeek,bool snapshot,bool clip,int preSeconds,int postSeconds,AlertSeverity severity,bool createAlert,bool realtime,long?zoneId,DateTime utcNow)
    {if(confidence is<0 or>1)throw new ArgumentOutOfRangeException(nameof(confidence));if(sensitivity is<1 or>100)throw new ArgumentOutOfRangeException(nameof(sensitivity));if(minimumDurationSeconds is<0 or>86400)throw new ArgumentOutOfRangeException(nameof(minimumDurationSeconds));if(cooldownSeconds is<0 or>86400)throw new ArgumentOutOfRangeException(nameof(cooldownSeconds));if((startTime is null)!=(endTime is null))throw new ArgumentException("Schedule start and end must be supplied together.");if(preSeconds is<0 or>300||postSeconds is<0 or>300)throw new ArgumentOutOfRangeException(nameof(preSeconds));if(!Enum.IsDefined(severity))throw new ArgumentOutOfRangeException(nameof(severity));if(ZoneRequired&&zoneId is null)throw new ArgumentException("This rule requires an active camera zone.",nameof(zoneId));RuleName=Required(ruleName,150);IsEnabled=enabled;MinimumConfidence=confidence;Sensitivity=sensitivity;MinimumDurationSeconds=minimumDurationSeconds;CooldownSeconds=cooldownSeconds;StartTime=startTime;EndTime=endTime;DaysOfWeek=Required(daysOfWeek,27);EvidenceSnapshotEnabled=snapshot;EvidenceClipEnabled=clip;EvidencePreEventSeconds=preSeconds;EvidencePostEventSeconds=postSeconds;Severity=severity;CreateAlert=createAlert;RealtimeNotificationEnabled=realtime;ZoneId=zoneId;UpdatedUtc=Utc(utcNow);}
    private static string Required(string value,int max){ArgumentException.ThrowIfNullOrWhiteSpace(value);var normalized=value.Trim();return normalized.Length<=max?normalized:throw new ArgumentOutOfRangeException(nameof(value));}
    private static DateTime Utc(DateTime value)=>value.Kind==DateTimeKind.Utc?value:throw new ArgumentException("Timestamp must be UTC.",nameof(value));
}
