using CustSearch.Domain.Enums;

namespace CustSearch.Domain.Entities;

/// <summary>Tenant-owned integration configuration containing opaque secret references, never secret values.</summary>
public sealed class IntegrationConfiguration
{
    private IntegrationConfiguration() { }
    private IntegrationConfiguration(long tenantId,string provider,IntegrationType integrationType,bool enabled,string endpointBaseUrl,string?credentialReference,string?webhookSigningSecretReference,int timeoutSeconds,int retryMaxAttempts,int retryBaseDelaySeconds,DateTime utcNow)
    {
        ArgumentOutOfRangeException.ThrowIfNegativeOrZero(tenantId);ValidateEnum(integrationType,nameof(integrationType));TenantId=tenantId;Provider=Required(provider,100);IntegrationType=integrationType;Enabled=enabled;EndpointBaseUrl=Endpoint(endpointBaseUrl);CredentialReference=Optional(credentialReference,200);WebhookSigningSecretReference=Optional(webhookSigningSecretReference,200);ValidatePolicy(timeoutSeconds,retryMaxAttempts,retryBaseDelaySeconds);TimeoutSeconds=timeoutSeconds;RetryMaxAttempts=retryMaxAttempts;RetryBaseDelaySeconds=retryBaseDelaySeconds;CreatedUtc=Utc(utcNow);UpdatedUtc=CreatedUtc;
    }
    public long Id{get;private set;} public long TenantId{get;private set;} public string Provider{get;private set;}=string.Empty; public IntegrationType IntegrationType{get;private set;} public bool Enabled{get;private set;} public string EndpointBaseUrl{get;private set;}=string.Empty; public string?CredentialReference{get;private set;} public string?WebhookSigningSecretReference{get;private set;} public string?PreviousWebhookSigningSecretReference{get;private set;} public DateTime?PreviousSigningSecretValidUntilUtc{get;private set;} public int TimeoutSeconds{get;private set;} public int RetryMaxAttempts{get;private set;} public int RetryBaseDelaySeconds{get;private set;} public DateTime CreatedUtc{get;private set;} public DateTime UpdatedUtc{get;private set;} public byte[]?RowVersion{get;private set;}
    public static IntegrationConfiguration Create(long tenantId,string provider,IntegrationType integrationType,bool enabled,string endpointBaseUrl,string?credentialReference,string?webhookSigningSecretReference,int timeoutSeconds,int retryMaxAttempts,int retryBaseDelaySeconds,DateTime utcNow)=>new(tenantId,provider,integrationType,enabled,endpointBaseUrl,credentialReference,webhookSigningSecretReference,timeoutSeconds,retryMaxAttempts,retryBaseDelaySeconds,utcNow);
    public void Update(string provider,IntegrationType integrationType,bool enabled,string endpointBaseUrl,int timeoutSeconds,int retryMaxAttempts,int retryBaseDelaySeconds,DateTime utcNow){ValidateEnum(integrationType,nameof(integrationType));Provider=Required(provider,100);IntegrationType=integrationType;Enabled=enabled;EndpointBaseUrl=Endpoint(endpointBaseUrl);ValidatePolicy(timeoutSeconds,retryMaxAttempts,retryBaseDelaySeconds);TimeoutSeconds=timeoutSeconds;RetryMaxAttempts=retryMaxAttempts;RetryBaseDelaySeconds=retryBaseDelaySeconds;UpdatedUtc=Utc(utcNow);}
    public void RotateReferences(string?credentialReference,string?signingSecretReference,int signingGraceMinutes,DateTime utcNow){ArgumentOutOfRangeException.ThrowIfNegative(signingGraceMinutes);ArgumentOutOfRangeException.ThrowIfGreaterThan(signingGraceMinutes,1440);utcNow=Utc(utcNow);if(credentialReference is not null)CredentialReference=Optional(credentialReference,200);if(signingSecretReference is not null){var next=Optional(signingSecretReference,200);if(!string.Equals(next,WebhookSigningSecretReference,StringComparison.Ordinal)){PreviousWebhookSigningSecretReference=WebhookSigningSecretReference;PreviousSigningSecretValidUntilUtc=PreviousWebhookSigningSecretReference is null?null:utcNow.AddMinutes(signingGraceMinutes);WebhookSigningSecretReference=next;}}UpdatedUtc=utcNow;}
    public bool SupportsInbound=>IntegrationType is IntegrationType.InboundWebhook or IntegrationType.Bidirectional or IntegrationType.Api;
    public bool SupportsOutbound=>IntegrationType is IntegrationType.OutboundWebhook or IntegrationType.Bidirectional or IntegrationType.Api;
    private static void ValidatePolicy(int timeoutSeconds,int retryMaxAttempts,int retryBaseDelaySeconds){ArgumentOutOfRangeException.ThrowIfLessThan(timeoutSeconds,1);ArgumentOutOfRangeException.ThrowIfGreaterThan(timeoutSeconds,120);ArgumentOutOfRangeException.ThrowIfLessThan(retryMaxAttempts,1);ArgumentOutOfRangeException.ThrowIfGreaterThan(retryMaxAttempts,10);ArgumentOutOfRangeException.ThrowIfLessThan(retryBaseDelaySeconds,1);ArgumentOutOfRangeException.ThrowIfGreaterThan(retryBaseDelaySeconds,300);}
    private static string Endpoint(string value){var endpoint=Required(value,500);if(!Uri.TryCreate(endpoint,UriKind.Absolute,out var uri)||!string.Equals(uri.Scheme,Uri.UriSchemeHttps,StringComparison.OrdinalIgnoreCase)||!string.IsNullOrEmpty(uri.UserInfo)||uri.IsLoopback)throw new ArgumentException("Integration endpoint must be an absolute non-loopback HTTPS URL.",nameof(value));return uri.AbsoluteUri.TrimEnd('/');}
    private static void ValidateEnum<T>(T value,string name)where T:struct,Enum{if(!Enum.IsDefined(value))throw new ArgumentOutOfRangeException(name);}
    private static string Required(string value,int max){ArgumentException.ThrowIfNullOrWhiteSpace(value);var result=value.Trim();return result.Length<=max?result:throw new ArgumentOutOfRangeException(nameof(value));}
    private static string?Optional(string?value,int max)=>string.IsNullOrWhiteSpace(value)?null:Required(value,max);
    private static DateTime Utc(DateTime value)=>value.Kind==DateTimeKind.Utc?value:throw new ArgumentException("Timestamp must be UTC.",nameof(value));
}

/// <summary>Durable inbound receipt proving idempotency without retaining the full sensitive request body.</summary>
public sealed class IntegrationInboundEvent
{
    private IntegrationInboundEvent() { }
    private IntegrationInboundEvent(long tenantId,long integrationConfigurationId,string providerEventId,string idempotencyKey,string eventType,int contractVersion,string payloadHash,string correlationId,DateTime providerTimestampUtc,DateTime receivedUtc)
    {ArgumentOutOfRangeException.ThrowIfNegativeOrZero(tenantId);ArgumentOutOfRangeException.ThrowIfNegativeOrZero(integrationConfigurationId);ArgumentOutOfRangeException.ThrowIfLessThan(contractVersion,1);TenantId=tenantId;IntegrationConfigurationId=integrationConfigurationId;ProviderEventId=Required(providerEventId,200);IdempotencyKey=Required(idempotencyKey,200);EventType=Required(eventType,100);ContractVersion=contractVersion;PayloadHash=Required(payloadHash,64);CorrelationId=Required(correlationId,64);ProviderTimestampUtc=Utc(providerTimestampUtc);ReceivedUtc=Utc(receivedUtc);Status=IntegrationInboundEventStatus.Accepted;}
    public long Id{get;private set;} public long TenantId{get;private set;} public long IntegrationConfigurationId{get;private set;} public string ProviderEventId{get;private set;}=string.Empty; public string IdempotencyKey{get;private set;}=string.Empty; public string EventType{get;private set;}=string.Empty; public int ContractVersion{get;private set;} public string PayloadHash{get;private set;}=string.Empty; public string CorrelationId{get;private set;}=string.Empty; public DateTime ProviderTimestampUtc{get;private set;} public DateTime ReceivedUtc{get;private set;} public DateTime?ProcessedUtc{get;private set;} public IntegrationInboundEventStatus Status{get;private set;}
    public static IntegrationInboundEvent Accept(long tenantId,long integrationConfigurationId,string providerEventId,string idempotencyKey,string eventType,int contractVersion,string payloadHash,string correlationId,DateTime providerTimestampUtc,DateTime receivedUtc)=>new(tenantId,integrationConfigurationId,providerEventId,idempotencyKey,eventType,contractVersion,payloadHash,correlationId,providerTimestampUtc,receivedUtc);
    public void MarkProcessed(DateTime utcNow){Status=IntegrationInboundEventStatus.Processed;ProcessedUtc=Utc(utcNow);}
    private static string Required(string value,int max){ArgumentException.ThrowIfNullOrWhiteSpace(value);var result=value.Trim();return result.Length<=max?result:throw new ArgumentOutOfRangeException(nameof(value));}
    private static DateTime Utc(DateTime value)=>value.Kind==DateTimeKind.Utc?value:throw new ArgumentException("Timestamp must be UTC.",nameof(value));
}

/// <summary>Committed outbound request consumed only by the background dispatcher.</summary>
public sealed class IntegrationOutboxMessage
{
    private IntegrationOutboxMessage() { }
    private IntegrationOutboxMessage(long tenantId,long integrationConfigurationId,string provider,string destination,string eventType,int contractVersion,string payloadJson,string payloadHash,string correlationId,string idempotencyKey,int maxAttempts,int retryBaseDelaySeconds,DateTime createdUtc)
    {ArgumentOutOfRangeException.ThrowIfNegativeOrZero(tenantId);ArgumentOutOfRangeException.ThrowIfNegativeOrZero(integrationConfigurationId);ArgumentOutOfRangeException.ThrowIfLessThan(contractVersion,1);ArgumentOutOfRangeException.ThrowIfLessThan(maxAttempts,1);ArgumentOutOfRangeException.ThrowIfLessThan(retryBaseDelaySeconds,1);TenantId=tenantId;IntegrationConfigurationId=integrationConfigurationId;Provider=Required(provider,100);Destination=Required(destination,500);EventType=Required(eventType,100);ContractVersion=contractVersion;PayloadJson=Required(payloadJson,32000);PayloadHash=Required(payloadHash,64);CorrelationId=Required(correlationId,64);IdempotencyKey=Required(idempotencyKey,200);MaxAttempts=maxAttempts;RetryBaseDelaySeconds=retryBaseDelaySeconds;CreatedUtc=Utc(createdUtc);NextAttemptUtc=CreatedUtc;Status=IntegrationOutboxStatus.Pending;}
    public long Id{get;private set;} public long TenantId{get;private set;} public long IntegrationConfigurationId{get;private set;} public string Provider{get;private set;}=string.Empty; public string Destination{get;private set;}=string.Empty; public string EventType{get;private set;}=string.Empty; public int ContractVersion{get;private set;} public string PayloadJson{get;private set;}="{}"; public string PayloadHash{get;private set;}=string.Empty; public IntegrationOutboxStatus Status{get;private set;} public int AttemptCount{get;private set;} public int MaxAttempts{get;private set;} public int RetryBaseDelaySeconds{get;private set;} public DateTime NextAttemptUtc{get;private set;} public int?LastResponseCode{get;private set;} public string?LastError{get;private set;} public string CorrelationId{get;private set;}=string.Empty; public string IdempotencyKey{get;private set;}=string.Empty; public DateTime CreatedUtc{get;private set;} public DateTime?DeliveredUtc{get;private set;} public DateTime?CompletedUtc{get;private set;} public byte[]?RowVersion{get;private set;}
    public static IntegrationOutboxMessage Queue(long tenantId,long integrationConfigurationId,string provider,string destination,string eventType,int contractVersion,string payloadJson,string payloadHash,string correlationId,string idempotencyKey,int maxAttempts,int retryBaseDelaySeconds,DateTime createdUtc)=>new(tenantId,integrationConfigurationId,provider,destination,eventType,contractVersion,payloadJson,payloadHash,correlationId,idempotencyKey,maxAttempts,retryBaseDelaySeconds,createdUtc);
    public void StartAttempt(DateTime utcNow,TimeSpan lease){if(Status is IntegrationOutboxStatus.Delivered or IntegrationOutboxStatus.DeadLetter)throw new InvalidOperationException("Terminal integration delivery cannot be processed.");utcNow=Utc(utcNow);ArgumentOutOfRangeException.ThrowIfLessThanOrEqual(lease,TimeSpan.Zero);if(utcNow<NextAttemptUtc)throw new InvalidOperationException("Integration delivery is not due.");AttemptCount++;Status=IntegrationOutboxStatus.Processing;NextAttemptUtc=utcNow+lease;LastError=null;}
    public void MarkDelivered(int responseCode,DateTime utcNow){if(Status!=IntegrationOutboxStatus.Processing)throw new InvalidOperationException("Only a processing delivery can succeed.");LastResponseCode=responseCode;Status=IntegrationOutboxStatus.Delivered;DeliveredUtc=Utc(utcNow);CompletedUtc=DeliveredUtc;LastError=null;}
    public void MarkFailed(int?responseCode,string error,bool permanent,DateTime utcNow){if(Status!=IntegrationOutboxStatus.Processing)throw new InvalidOperationException("Only a processing delivery can fail.");utcNow=Utc(utcNow);LastResponseCode=responseCode;LastError=Required(error,2000);if(permanent||AttemptCount>=MaxAttempts){Status=IntegrationOutboxStatus.DeadLetter;CompletedUtc=utcNow;return;}Status=AttemptCount==1?IntegrationOutboxStatus.Failed:IntegrationOutboxStatus.Retrying;var multiplier=Math.Pow(2,AttemptCount-1);NextAttemptUtc=utcNow.AddSeconds(Math.Min(3600,RetryBaseDelaySeconds*multiplier));}
    public void RetryManually(DateTime utcNow){if(Status is not(IntegrationOutboxStatus.DeadLetter or IntegrationOutboxStatus.Failed))throw new InvalidOperationException("Only failed or dead-letter deliveries can be retried manually.");Status=IntegrationOutboxStatus.Retrying;AttemptCount=0;NextAttemptUtc=Utc(utcNow);CompletedUtc=null;DeliveredUtc=null;LastError=null;LastResponseCode=null;}
    private static string Required(string value,int max){ArgumentException.ThrowIfNullOrWhiteSpace(value);var result=value.Trim();return result.Length<=max?result:throw new ArgumentOutOfRangeException(nameof(value));}
    private static DateTime Utc(DateTime value)=>value.Kind==DateTimeKind.Utc?value:throw new ArgumentException("Timestamp must be UTC.",nameof(value));
}

/// <summary>Payload-free audit record for inbound and outbound integration delivery activity.</summary>
public sealed class IntegrationDeliveryLog
{
    private IntegrationDeliveryLog() { }
    private IntegrationDeliveryLog(long tenantId,long integrationConfigurationId,long?inboundEventId,long?outboxMessageId,string correlationId,string provider,IntegrationDirection direction,IntegrationDeliveryStatus status,long durationMilliseconds,int?httpStatusCode,string?errorCategory,DateTime createdUtc)
    {ArgumentOutOfRangeException.ThrowIfNegativeOrZero(tenantId);ArgumentOutOfRangeException.ThrowIfNegativeOrZero(integrationConfigurationId);if(inboundEventId.HasValue)ArgumentOutOfRangeException.ThrowIfNegativeOrZero(inboundEventId.Value);if(outboxMessageId.HasValue)ArgumentOutOfRangeException.ThrowIfNegativeOrZero(outboxMessageId.Value);if(inboundEventId.HasValue==outboxMessageId.HasValue)throw new ArgumentException("Exactly one integration delivery source is required.");if(!Enum.IsDefined(direction))throw new ArgumentOutOfRangeException(nameof(direction));if(!Enum.IsDefined(status))throw new ArgumentOutOfRangeException(nameof(status));ArgumentOutOfRangeException.ThrowIfNegative(durationMilliseconds);TenantId=tenantId;IntegrationConfigurationId=integrationConfigurationId;InboundEventId=inboundEventId;OutboxMessageId=outboxMessageId;CorrelationId=Required(correlationId,64);Provider=Required(provider,100);Direction=direction;Status=status;DurationMilliseconds=durationMilliseconds;HttpStatusCode=httpStatusCode;ErrorCategory=Optional(errorCategory,100);CreatedUtc=Utc(createdUtc);}
    public long Id{get;private set;} public long TenantId{get;private set;} public long IntegrationConfigurationId{get;private set;} public long?InboundEventId{get;private set;} public long?OutboxMessageId{get;private set;} public string CorrelationId{get;private set;}=string.Empty; public string Provider{get;private set;}=string.Empty; public IntegrationDirection Direction{get;private set;} public IntegrationDeliveryStatus Status{get;private set;} public long DurationMilliseconds{get;private set;} public int?HttpStatusCode{get;private set;} public string?ErrorCategory{get;private set;} public DateTime CreatedUtc{get;private set;}
    public static IntegrationDeliveryLog RecordInbound(long tenantId,long integrationConfigurationId,long inboundEventId,string correlationId,string provider,long durationMilliseconds,DateTime createdUtc)=>new(tenantId,integrationConfigurationId,inboundEventId,null,correlationId,provider,IntegrationDirection.Inbound,IntegrationDeliveryStatus.Accepted,durationMilliseconds,200,null,createdUtc);
    public static IntegrationDeliveryLog RecordOutbound(long tenantId,long integrationConfigurationId,long outboxMessageId,string correlationId,string provider,IntegrationDeliveryStatus status,long durationMilliseconds,int?httpStatusCode,string?errorCategory,DateTime createdUtc)=>new(tenantId,integrationConfigurationId,null,outboxMessageId,correlationId,provider,IntegrationDirection.Outbound,status,durationMilliseconds,httpStatusCode,errorCategory,createdUtc);
    private static string Required(string value,int max){ArgumentException.ThrowIfNullOrWhiteSpace(value);var result=value.Trim();return result.Length<=max?result:throw new ArgumentOutOfRangeException(nameof(value));}
    private static string?Optional(string?value,int max)=>string.IsNullOrWhiteSpace(value)?null:Required(value,max);
    private static DateTime Utc(DateTime value)=>value.Kind==DateTimeKind.Utc?value:throw new ArgumentException("Timestamp must be UTC.",nameof(value));
}
