using CustSearch.Domain.Enums;

namespace CustSearch.Domain.Entities;

/// <summary>Durable, authorization-snapshotted asynchronous export request.</summary>
public sealed class ExportJob
{
    private ExportJob(){}
    private ExportJob(long requestedByUserId,long?tenantId,ReportType reportType,ExportFormat format,string filterJson,string authorizedStoreIdsJson,DateTime createdUtc,DateTime expiresUtc)
    {ArgumentOutOfRangeException.ThrowIfNegativeOrZero(requestedByUserId);if(tenantId is<=0)throw new ArgumentOutOfRangeException(nameof(tenantId));if(!Enum.IsDefined(reportType))throw new ArgumentOutOfRangeException(nameof(reportType));if(!Enum.IsDefined(format))throw new ArgumentOutOfRangeException(nameof(format));RequestedByUserId=requestedByUserId;TenantId=tenantId;ReportType=reportType;Format=format;FilterJson=Required(filterJson,4000);AuthorizedStoreIdsJson=Required(authorizedStoreIdsJson,4000);Status=ExportJobStatus.Queued;CreatedUtc=Utc(createdUtc);ExpiresUtc=Utc(expiresUtc);if(ExpiresUtc<=CreatedUtc)throw new ArgumentOutOfRangeException(nameof(expiresUtc));}
    public long Id{get;private set;}public long RequestedByUserId{get;private set;}public long?TenantId{get;private set;}public long?AlertId{get;private set;}public ReportType ReportType{get;private set;}public ExportFormat Format{get;private set;}public string FilterJson{get;private set;}=string.Empty;public string AuthorizedStoreIdsJson{get;private set;}=string.Empty;public ExportJobStatus Status{get;private set;}public byte Progress{get;private set;}public DateTime CreatedUtc{get;private set;}public DateTime?StartedUtc{get;private set;}public DateTime?CompletedUtc{get;private set;}public DateTime ExpiresUtc{get;private set;}public string?Error{get;private set;}public string?FilePath{get;private set;}public string?FileName{get;private set;}public string?ContentType{get;private set;}public int AttemptCount{get;private set;}public Guid?LeaseId{get;private set;}public DateTime?LeaseExpiresUtc{get;private set;}public byte[]RowVersion{get;private set;}=[];
    public static ExportJob Queue(long requestedByUserId,long?tenantId,ReportType reportType,ExportFormat format,string filterJson,string authorizedStoreIdsJson,DateTime createdUtc,DateTime expiresUtc)=>new(requestedByUserId,tenantId,reportType,format,filterJson,authorizedStoreIdsJson,createdUtc,expiresUtc);
    public void LinkAlert(long alertId){ArgumentOutOfRangeException.ThrowIfNegativeOrZero(alertId);if(AlertId.HasValue)throw new InvalidOperationException("Export alert is already linked.");AlertId=alertId;}
    public void Claim(Guid leaseId,DateTime utcNow,DateTime leaseExpiresUtc){if(Status!=ExportJobStatus.Queued)throw new InvalidOperationException("Only queued exports can be claimed.");ArgumentOutOfRangeException.ThrowIfEqual(leaseId,Guid.Empty);var now=Utc(utcNow);var leaseExpiry=Utc(leaseExpiresUtc);if(leaseExpiry<=now)throw new ArgumentOutOfRangeException(nameof(leaseExpiresUtc));Status=ExportJobStatus.Processing;Progress=1;StartedUtc??=now;LeaseId=leaseId;LeaseExpiresUtc=leaseExpiry;AttemptCount++;Error=null;}
    public void ReportProgress(byte progress,Guid leaseId){RequireLease(leaseId);if(progress is<1 or>99)throw new ArgumentOutOfRangeException(nameof(progress));Progress=Math.Max(Progress,progress);}
    public void Complete(string filePath,string fileName,string contentType,Guid leaseId,DateTime utcNow){RequireLease(leaseId);FilePath=Required(filePath,1000);FileName=Required(fileName,260);ContentType=Required(contentType,150);Status=ExportJobStatus.Completed;Progress=100;CompletedUtc=Utc(utcNow);LeaseId=null;LeaseExpiresUtc=null;Error=null;}
    public void Fail(string error,Guid leaseId,DateTime utcNow){RequireLease(leaseId);Error=Required(error,2000);Status=ExportJobStatus.Failed;Progress=0;CompletedUtc=Utc(utcNow);LeaseId=null;LeaseExpiresUtc=null;}
    public void Retry(DateTime utcNow){if(Status!=ExportJobStatus.Failed)throw new InvalidOperationException("Only failed exports can be retried.");if(ExpiresUtc<=Utc(utcNow))throw new InvalidOperationException("Expired exports cannot be retried.");Status=ExportJobStatus.Queued;Progress=0;CompletedUtc=null;Error=null;}
    public void Expire(DateTime utcNow){if(Utc(utcNow)<ExpiresUtc)throw new InvalidOperationException("Export retention has not elapsed.");Status=ExportJobStatus.Expired;Progress=0;FilePath=null;FileName=null;ContentType=null;LeaseId=null;LeaseExpiresUtc=null;}
    private void RequireLease(Guid leaseId){if(Status!=ExportJobStatus.Processing||LeaseId!=leaseId)throw new InvalidOperationException("The export processing lease is not valid.");}
    private static string Required(string value,int max){ArgumentException.ThrowIfNullOrWhiteSpace(value);var v=value.Trim();return v.Length<=max?v:throw new ArgumentOutOfRangeException(nameof(value));}
    private static DateTime Utc(DateTime value)=>value.Kind==DateTimeKind.Utc?value:throw new ArgumentException("Timestamp must be UTC.",nameof(value));
}
