using CustSearch.Domain.Enums;

namespace CustSearch.Domain.Entities;

/// <summary>Purpose-specific customer consent that is authoritative for recognition eligibility.</summary>
public sealed class CustomerRecognitionConsent
{
    private CustomerRecognitionConsent(){}
    private CustomerRecognitionConsent(long tenantId,long customerId,RecognitionConsentType consentType,string purpose,DateTime grantedUtc,DateTime?expiresUtc,string consentVersion,long capturedByUserId,string?evidenceReference)
    {ArgumentOutOfRangeException.ThrowIfNegativeOrZero(tenantId);ArgumentOutOfRangeException.ThrowIfNegativeOrZero(customerId);ArgumentOutOfRangeException.ThrowIfNegativeOrZero(capturedByUserId);if(!Enum.IsDefined(consentType))throw new ArgumentOutOfRangeException(nameof(consentType));TenantId=tenantId;CustomerId=customerId;ConsentType=consentType;Purpose=Required(purpose,200);GrantedUtc=Utc(grantedUtc);if(expiresUtc.HasValue&&Utc(expiresUtc.Value)<=GrantedUtc)throw new ArgumentOutOfRangeException(nameof(expiresUtc));ExpiresUtc=expiresUtc;ConsentVersion=Required(consentVersion,50);CapturedByUserId=capturedByUserId;EvidenceReference=Optional(evidenceReference,500);CreatedUtc=GrantedUtc;}
    public long Id{get;private set;}public long TenantId{get;private set;}public long CustomerId{get;private set;}public RecognitionConsentType ConsentType{get;private set;}public string Purpose{get;private set;}=string.Empty;public DateTime GrantedUtc{get;private set;}public DateTime?ExpiresUtc{get;private set;}public DateTime?WithdrawnUtc{get;private set;}public string ConsentVersion{get;private set;}=string.Empty;public long CapturedByUserId{get;private set;}public string?EvidenceReference{get;private set;}public DateTime CreatedUtc{get;private set;}
    public static CustomerRecognitionConsent Grant(long tenantId,long customerId,RecognitionConsentType consentType,string purpose,DateTime grantedUtc,DateTime?expiresUtc,string consentVersion,long capturedByUserId,string?evidenceReference)=>new(tenantId,customerId,consentType,purpose,grantedUtc,expiresUtc,consentVersion,capturedByUserId,evidenceReference);
    public bool IsActiveAt(DateTime utcNow)=>WithdrawnUtc is null&&GrantedUtc<=Utc(utcNow)&&(!ExpiresUtc.HasValue||ExpiresUtc>utcNow);
    public void Withdraw(DateTime utcNow){if(WithdrawnUtc.HasValue)throw new InvalidOperationException("Consent is already withdrawn.");var now=Utc(utcNow);if(now<GrantedUtc)throw new ArgumentOutOfRangeException(nameof(utcNow));WithdrawnUtc=now;}
    private static string Required(string value,int max){ArgumentException.ThrowIfNullOrWhiteSpace(value);var normalized=value.Trim();return normalized.Length<=max?normalized:throw new ArgumentOutOfRangeException(nameof(value));}
    private static string?Optional(string?value,int max)=>string.IsNullOrWhiteSpace(value)?null:Required(value,max);
    private static DateTime Utc(DateTime value)=>value.Kind==DateTimeKind.Utc?value:throw new ArgumentException("Timestamp must be UTC.",nameof(value));
}

/// <summary>Encrypted derived biometric template metadata; raw enrollment images are never represented.</summary>
public sealed class BiometricTemplate
{
    private BiometricTemplate(){}
    private BiometricTemplate(long tenantId,long storeId,long customerId,long consentId,byte[]ciphertext,byte[]nonce,byte[]authenticationTag,string encryptionKeyReference,string algorithm,string templateVersion,DateTime createdUtc)
    {ArgumentOutOfRangeException.ThrowIfNegativeOrZero(tenantId);ArgumentOutOfRangeException.ThrowIfNegativeOrZero(storeId);ArgumentOutOfRangeException.ThrowIfNegativeOrZero(customerId);ArgumentOutOfRangeException.ThrowIfNegativeOrZero(consentId);if(ciphertext.Length==0||nonce.Length!=12||authenticationTag.Length!=16)throw new ArgumentException("Protected template material is invalid.");TenantId=tenantId;StoreId=storeId;CustomerId=customerId;ConsentId=consentId;EncryptedTemplate=[..ciphertext];Nonce=[..nonce];AuthenticationTag=[..authenticationTag];EncryptionKeyReference=Required(encryptionKeyReference,200);Algorithm=Required(algorithm,50);TemplateVersion=Required(templateVersion,50);Status=BiometricTemplateStatus.Active;CreatedUtc=Utc(createdUtc);}
    public long Id{get;private set;}public long TenantId{get;private set;}public long StoreId{get;private set;}public long CustomerId{get;private set;}public long ConsentId{get;private set;}public byte[]EncryptedTemplate{get;private set;}=[];public byte[]Nonce{get;private set;}=[];public byte[]AuthenticationTag{get;private set;}=[];public string EncryptionKeyReference{get;private set;}=string.Empty;public string Algorithm{get;private set;}=string.Empty;public string TemplateVersion{get;private set;}=string.Empty;public BiometricTemplateStatus Status{get;private set;}public DateTime CreatedUtc{get;private set;}public DateTime?DisabledUtc{get;private set;}public DateTime?DeletedUtc{get;private set;}public DateTime?RetentionUntilUtc{get;private set;}
    public static BiometricTemplate Enroll(long tenantId,long storeId,long customerId,long consentId,byte[]ciphertext,byte[]nonce,byte[]authenticationTag,string encryptionKeyReference,string algorithm,string templateVersion,DateTime createdUtc)=>new(tenantId,storeId,customerId,consentId,ciphertext,nonce,authenticationTag,encryptionKeyReference,algorithm,templateVersion,createdUtc);
    public void DisableAndErase(DateTime utcNow,DateTime retentionUntilUtc){var now=Utc(utcNow);var retention=Utc(retentionUntilUtc);if(retention<now)throw new ArgumentOutOfRangeException(nameof(retentionUntilUtc));Status=BiometricTemplateStatus.Deleted;DisabledUtc??=now;DeletedUtc=now;RetentionUntilUtc=retention;EncryptedTemplate=[];Nonce=[];AuthenticationTag=[];}
    private static string Required(string value,int max){ArgumentException.ThrowIfNullOrWhiteSpace(value);var normalized=value.Trim();return normalized.Length<=max?normalized:throw new ArgumentOutOfRangeException(nameof(value));}
    private static DateTime Utc(DateTime value)=>value.Kind==DateTimeKind.Utc?value:throw new ArgumentException("Timestamp must be UTC.",nameof(value));
}

/// <summary>Reviewable match candidate; creation never changes the authoritative track/customer association.</summary>
public sealed class RecognitionCandidate
{
    private RecognitionCandidate(){}
    private RecognitionCandidate(long tenantId,long storeId,long personTrackSessionId,long biometricTemplateId,long customerId,string requestId,string purpose,decimal confidence,decimal quality,decimal?secondBestConfidence,RecognitionCandidateStatus status,string?reviewReason,DateTime createdUtc)
    {ArgumentOutOfRangeException.ThrowIfNegativeOrZero(tenantId);ArgumentOutOfRangeException.ThrowIfNegativeOrZero(storeId);ArgumentOutOfRangeException.ThrowIfNegativeOrZero(personTrackSessionId);ArgumentOutOfRangeException.ThrowIfNegativeOrZero(biometricTemplateId);ArgumentOutOfRangeException.ThrowIfNegativeOrZero(customerId);ValidateScore(confidence,nameof(confidence));ValidateScore(quality,nameof(quality));if(secondBestConfidence.HasValue)ValidateScore(secondBestConfidence.Value,nameof(secondBestConfidence));if(status is not(RecognitionCandidateStatus.PendingReview or RecognitionCandidateStatus.Ambiguous))throw new ArgumentOutOfRangeException(nameof(status));TenantId=tenantId;StoreId=storeId;PersonTrackSessionId=personTrackSessionId;BiometricTemplateId=biometricTemplateId;CustomerId=customerId;RequestId=Required(requestId,150);Purpose=Required(purpose,200);Confidence=confidence;Quality=quality;SecondBestConfidence=secondBestConfidence;Status=status;ReviewReason=Optional(reviewReason,500);CreatedUtc=Utc(createdUtc);}
    public long Id{get;private set;}public long TenantId{get;private set;}public long StoreId{get;private set;}public long PersonTrackSessionId{get;private set;}public long BiometricTemplateId{get;private set;}public long CustomerId{get;private set;}public string RequestId{get;private set;}=string.Empty;public string Purpose{get;private set;}=string.Empty;public decimal Confidence{get;private set;}public decimal Quality{get;private set;}public decimal?SecondBestConfidence{get;private set;}public RecognitionCandidateStatus Status{get;private set;}public DateTime CreatedUtc{get;private set;}public DateTime?ReviewedUtc{get;private set;}public long?ReviewedByUserId{get;private set;}public string?ReviewReason{get;private set;}
    public static RecognitionCandidate Create(long tenantId,long storeId,long personTrackSessionId,long biometricTemplateId,long customerId,string requestId,string purpose,decimal confidence,decimal quality,decimal?secondBestConfidence,RecognitionCandidateStatus status,string?reviewReason,DateTime createdUtc)=>new(tenantId,storeId,personTrackSessionId,biometricTemplateId,customerId,requestId,purpose,confidence,quality,secondBestConfidence,status,reviewReason,createdUtc);
    public void Review(bool accept,long reviewedByUserId,string reason,DateTime utcNow){ArgumentOutOfRangeException.ThrowIfNegativeOrZero(reviewedByUserId);if(Status is not(RecognitionCandidateStatus.PendingReview or RecognitionCandidateStatus.Ambiguous))throw new InvalidOperationException("Candidate is no longer awaiting review.");Status=accept?RecognitionCandidateStatus.Accepted:RecognitionCandidateStatus.Rejected;ReviewedByUserId=reviewedByUserId;ReviewReason=Required(reason,500);ReviewedUtc=Utc(utcNow);}
    private static void ValidateScore(decimal value,string name){if(value is<0 or>1)throw new ArgumentOutOfRangeException(name);}
    private static string Required(string value,int max){ArgumentException.ThrowIfNullOrWhiteSpace(value);var normalized=value.Trim();return normalized.Length<=max?normalized:throw new ArgumentOutOfRangeException(nameof(value));}
    private static string?Optional(string?value,int max)=>string.IsNullOrWhiteSpace(value)?null:Required(value,max);
    private static DateTime Utc(DateTime value)=>value.Kind==DateTimeKind.Utc?value:throw new ArgumentException("Timestamp must be UTC.",nameof(value));
}
