import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component, Input, OnChanges, SimpleChanges, computed, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { AuthSessionService } from '../../core/auth/auth-session.service';
import { PERMISSIONS } from '../../core/auth/permission-catalog';
import { CustomerPreferences, PreferenceType, PreferencesApiService } from './preferences-api.service';

/** Embedded Phase 10 customer preference section. Factual signals and derived scores are intentionally shown separately. */
@Component({selector:'app-customer-preferences-panel',standalone:true,imports:[CommonModule,ReactiveFormsModule],changeDetection:ChangeDetectionStrategy.OnPush,
styles:[`:host{display:block}.card{border:1px solid #ddd;border-radius:12px;padding:16px}.cols{display:grid;grid-template-columns:1fr 1fr;gap:16px}.muted{opacity:.65}.chips{display:flex;gap:6px;flex-wrap:wrap}.chip{border:1px solid #ddd;border-radius:999px;padding:5px 9px}form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}input,select,button{min-height:38px;padding:7px;border:1px solid #ccc;border-radius:8px}.wide{grid-column:1/-1}.error{color:#b3261e}@media(max-width:760px){.cols,form{grid-template-columns:1fr}}`],
template:`<section class="card"><h2>Preferences</h2><p class="muted">Factual signals stay separate from recalculated interest scores. Purchase signals come only from Phase 8 billing.</p>@if(error()){<p class="error">{{error()}}</p>}@if(data();as d){<div class="cols"><div><h3>Derived scores</h3><div class="chips">@for(x of d.scores;track x.id){<span class="chip">{{label(x.preferenceType)}}: {{x.value||('#'+x.referenceId)}} · {{x.score}}</span>}@empty{<span class="muted">No recalculated scores yet.</span>}</div></div><div><h3>Factual signals</h3><ul>@for(x of d.signals;track x.id){<li>{{label(x.preferenceType)}} — {{x.value||('#'+x.referenceId)}} · {{source(x.source)}} @if(x.confidence!==null){({{x.confidence}}%)}</li>}@empty{<li class="muted">No factual preference signals.</li>}</ul></div></div>@if(canManage()){<h3>Manual staff tag</h3><form [formGroup]="form" (ngSubmit)="addTag()"><input type="number" formControlName="storeId" placeholder="Store ID"><select formControlName="preferenceType"><option [ngValue]="1">Category</option><option [ngValue]="2">Product</option><option [ngValue]="3">Brand</option><option [ngValue]="4">Price range</option><option [ngValue]="5">Tag</option></select><input type="number" formControlName="referenceId" placeholder="Reference ID (optional)"><input formControlName="value" placeholder="Value / label"><input type="number" formControlName="confidence" placeholder="Confidence 0-100"><input formControlName="reason" placeholder="Reason / note"><button class="wide" [disabled]="form.invalid||saving()">Add factual tag</button></form><button type="button" (click)="recalculate()" [disabled]="saving()">Recalculate from factual signals</button>}}</section>`})
export class CustomerPreferencesPanel implements OnChanges{
 @Input({required:true}) customerId=0;private readonly api=inject(PreferencesApiService);private readonly session=inject(AuthSessionService);private readonly fb=inject(FormBuilder);protected readonly data=signal<CustomerPreferences|null>(null);protected readonly error=signal('');protected readonly saving=signal(false);protected readonly canManage=computed(()=>this.session.hasPermission(PERMISSIONS.preferencesManage));
 protected readonly form=this.fb.group({storeId:[null as number|null,[Validators.required,Validators.min(1)]],preferenceType:[5 as PreferenceType,Validators.required],referenceId:[null as number|null],value:['',Validators.maxLength(200)],confidence:[100,[Validators.min(0),Validators.max(100)]],reason:['',Validators.maxLength(500)]});
 ngOnChanges(changes:SimpleChanges){if(changes['customerId']&&this.customerId>0)this.load();}
 protected addTag(){if(this.form.invalid)return;const v=this.form.getRawValue();if(!v.storeId)return;this.saving.set(true);this.api.addCustomerTag(this.customerId,{storeId:v.storeId,preferenceType:(v.preferenceType??5) as PreferenceType,referenceId:v.referenceId||null,value:v.value?.trim()||null,signalScore:null,confidence:v.confidence??100,reason:v.reason?.trim()||null}).subscribe({next:x=>{this.data.set(x);this.saving.set(false);this.error.set('');},error:e=>this.fail(e)});}
 protected recalculate(){this.saving.set(true);this.api.recalculateCustomer(this.customerId).subscribe({next:x=>{this.data.set(x);this.saving.set(false);this.error.set('');},error:e=>this.fail(e)});}
 protected label(t:number){return['','Category','Product','Brand','Price range','Tag'][t]??'Preference';}protected source(s:number){return['','Manual staff','Purchase','Category interaction','Voice confirmed'][s]??'Source';}
 private load(){if(!this.session.hasPermission(PERMISSIONS.preferencesView))return;this.api.customer(this.customerId).subscribe({next:x=>this.data.set(x),error:e=>this.fail(e)});}private fail(e:any){this.saving.set(false);this.error.set(e?.error?.message??e?.message??'Preference request failed.');}
}
