import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component, Input, OnChanges, SimpleChanges, computed, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { AuthSessionService } from '../../core/auth/auth-session.service';
import { PERMISSIONS } from '../../core/auth/permission-catalog';
import { HouseholdPreferences, PreferenceType, PreferencesApiService } from './preferences-api.service';

/** Phase 10 Household preference panel. Only active verified HouseholdMembers contribute to member/aggregate scores. */
@Component({selector:'app-household-preferences-panel',standalone:true,imports:[CommonModule,ReactiveFormsModule],changeDetection:ChangeDetectionStrategy.OnPush,
styles:[`:host{display:block}.card{border:1px solid #ddd;border-radius:12px;padding:16px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.muted{opacity:.65}.chip{display:inline-block;border:1px solid #ddd;border-radius:999px;padding:5px 9px;margin:3px}form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}input,select,button{min-height:38px;padding:7px;border:1px solid #ccc;border-radius:8px}.wide{grid-column:1/-1}.error{color:#b3261e}@media(max-width:760px){.grid,form{grid-template-columns:1fr}}`],
template:`<section class="card"><h2>Household preferences</h2><p class="muted"><strong>Verified members only.</strong> Visit Party / Co-Visit is not Household/family and is never used to create this summary.</p>@if(error()){<p class="error">{{error()}}</p>}@if(data();as d){<div class="grid"><div><h3>Shared aggregate</h3>@for(x of d.aggregateScores;track x.preferenceType+'-'+x.referenceId+'-'+x.value){<span class="chip">{{label(x.preferenceType)}}: {{x.value||('#'+x.referenceId)}} · {{x.score}}</span>}@empty{<p class="muted">No verified-member scores yet.</p>}<h3>Explicit shared tags</h3><ul>@for(t of d.sharedTags;track t.id){<li>{{label(t.preferenceType)}} — {{t.value}}</li>}@empty{<li class="muted">No explicit Household tags.</li>}</ul></div><div><h3>Verified member breakdown</h3>@for(m of d.verifiedMembers;track m.customerId){<p><strong>{{m.customerName}}</strong></p><div>@for(s of m.scores;track s.id){<span class="chip">{{s.value||('#'+s.referenceId)}} · {{s.score}}</span>}@empty{<span class="muted">No scores</span>}</div>}@empty{<p class="muted">No visible verified members.</p>}</div></div>@if(canManage()){<h3>Add explicit shared tag</h3><form [formGroup]="form" (ngSubmit)="addTag()"><select formControlName="preferenceType"><option [ngValue]="1">Category</option><option [ngValue]="2">Product</option><option [ngValue]="3">Brand</option><option [ngValue]="4">Price range</option><option [ngValue]="5">Tag</option></select><input type="number" formControlName="referenceId" placeholder="Reference ID (optional)"><input formControlName="value" placeholder="Shared tag / value"><select formControlName="source"><option [ngValue]="1">Customer provided</option><option [ngValue]="2">Staff verified</option><option [ngValue]="3">Admin verified</option></select><input class="wide" formControlName="reason" placeholder="Reason / note"><button class="wide" [disabled]="form.invalid||saving()">Add Household tag</button></form>}}</section>`})
export class HouseholdPreferencesPanel implements OnChanges{
 @Input({required:true}) householdId=0;private readonly api=inject(PreferencesApiService);private readonly session=inject(AuthSessionService);private readonly fb=inject(FormBuilder);protected readonly data=signal<HouseholdPreferences|null>(null);protected readonly error=signal('');protected readonly saving=signal(false);protected readonly canManage=computed(()=>this.session.hasPermission(PERMISSIONS.preferencesManage));
 protected readonly form=this.fb.group({preferenceType:[5 as PreferenceType,Validators.required],referenceId:[null as number|null],value:['',[Validators.required,Validators.maxLength(200)]],source:[2,Validators.required],reason:['',Validators.maxLength(500)]});
 ngOnChanges(changes:SimpleChanges){if(changes['householdId']&&this.householdId>0)this.load();}
 protected addTag(){if(this.form.invalid)return;const v=this.form.getRawValue();this.saving.set(true);this.api.addHouseholdTag(this.householdId,{preferenceType:(v.preferenceType??5) as PreferenceType,referenceId:v.referenceId||null,value:(v.value??'').trim(),source:v.source??2,reason:v.reason?.trim()||null}).subscribe({next:x=>{this.data.set(x);this.saving.set(false);this.error.set('');},error:e=>this.fail(e)});}
 protected label(t:number){return['','Category','Product','Brand','Price range','Tag'][t]??'Preference';}
 private load(){if(!this.session.hasPermission(PERMISSIONS.preferencesView))return;this.api.household(this.householdId).subscribe({next:x=>this.data.set(x),error:e=>this.fail(e)});}private fail(e:any){this.saving.set(false);this.error.set(e?.error?.message??e?.message??'Household preference request failed.');}
}
