import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { AuthSessionService } from '../../core/auth/auth-session.service';
import { PERMISSIONS } from '../../core/auth/permission-catalog';
import { AdminShell } from '../../shared/admin-shell/admin-shell';
import { preferenceErrorMessage } from './preference-error';
import { PreferenceAudit, PreferencesApiService, VoiceCategoryCandidate, VoiceSession, VoiceSetting } from './preferences-api.service';

/** Phase 10 dynamic per-store voice settings, server-resolved category aliases, confirmation flow and audit UI. “Aasha Add” remains only an example/default. */
@Component({selector:'app-voice-preferences-page',standalone:true,imports:[CommonModule,ReactiveFormsModule,AdminShell],changeDetection:ChangeDetectionStrategy.OnPush,
styles:[`:host{display:block}.wrap{padding:24px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.card{border:1px solid #ddd;border-radius:12px;padding:16px}.muted{opacity:.65}.error{color:#b3261e}.ok{color:#147d32}form{display:grid;gap:8px}input,select,button{min-height:40px;padding:8px;border:1px solid #ccc;border-radius:8px}.actions{display:flex;gap:8px;flex-wrap:wrap}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:8px;border-bottom:1px solid #eee}@media(max-width:850px){.grid{grid-template-columns:1fr}}`],
template:`<app-admin-shell><main class="wrap"><h1>Dynamic voice settings</h1><p class="muted">Trigger phrase and aliases are store-specific. “Aasha Add” is only an example/default. Voice text never creates a random category: the server resolves an existing category or configured category alias.</p>@if(error()){<p class="error">{{error()}}</p>}@if(message()){<p class="ok">{{message()}}</p>}<div class="grid"><section class="card"><h2>Load store</h2><form [formGroup]="storeForm" (ngSubmit)="loadStore()"><input type="number" formControlName="storeId" placeholder="Store ID"><button [disabled]="storeForm.invalid">Load voice settings</button></form>@if(setting();as s){<h3>Store {{s.storeId}}</h3><form [formGroup]="settingForm" (ngSubmit)="saveSetting()"><input formControlName="triggerKeyword" placeholder="Trigger phrase"><input formControlName="aliases" placeholder="Trigger aliases comma separated"><select formControlName="responseMode"><option>InApp</option><option>Toast</option><option>Voice</option><option>InAppAndVoice</option></select><input formControlName="languageCode" placeholder="Language code e.g. en-IN"><input type="number" formControlName="listeningTimeoutSeconds" placeholder="Listening timeout seconds"><input type="number" formControlName="minimumRecognitionConfidence" placeholder="Minimum confidence"><label><input type="checkbox" formControlName="isEnabled"> Enabled</label><label><input type="checkbox" formControlName="requireConfirmation"> Require confirmation before CRM write</label><label><input type="checkbox" formControlName="requireConfirmationForAmbiguousCategory"> Confirm ambiguous category</label><button [disabled]="settingForm.invalid||!canConfigure()||saving()">Save voice settings</button></form>}</section>
<section class="card"><h2>Voice command test</h2><p class="muted">Select the customer explicitly, then use this store’s configured trigger. Ambiguous categories require a server-returned candidate selection before any CRM write.</p><form [formGroup]="voiceForm" (ngSubmit)="startVoice()"><input type="number" formControlName="customerId" placeholder="Customer ID"><input formControlName="triggerText" placeholder="Configured trigger phrase"><button [disabled]="voiceForm.invalid||!canUse()||saving()">Start listening</button></form>@if(session();as x){<p>Status: <strong>{{statusLabel(x.status)}}</strong></p><form [formGroup]="interpretForm" (ngSubmit)="interpret()"><input formControlName="recognizedText" placeholder="Recognized category text, e.g. Banarasi Sadi"><input type="number" formControlName="recognitionConfidence" placeholder="Recognition confidence">@if(candidates().length>1){<label>Resolved candidates<select formControlName="selectedCategoryId"><option [ngValue]="null">Select category</option>@for(c of candidates();track c.categoryId){<option [ngValue]="c.categoryId">{{c.categoryName}} ({{c.categoryCode}})</option>}</select></label>}<button [disabled]="interpretForm.invalid||saving()">Resolve category</button></form>@if(x.status===2){<div class="actions"><button type="button" (click)="confirm()">Confirm CRM write</button><button type="button" (click)="reject()">Reject</button></div>}}</section>
<section class="card"><h2>Category voice alias</h2><p class="muted">Aliases map speech variants to an existing category; they never auto-create categories.</p><form [formGroup]="aliasForm" (ngSubmit)="addAlias()"><input type="number" formControlName="categoryId" placeholder="Existing category ID"><input formControlName="aliasText" placeholder="Alias, e.g. Banarasi Sadi"><input formControlName="languageCode" placeholder="Language code"><label><input type="checkbox" formControlName="tenantWide"> Tenant-wide alias</label><button [disabled]="aliasForm.invalid||!canManageAliases()||saving()">Add category alias</button></form></section></div>
@if(canAudit()){<section class="card" style="margin-top:16px"><h2>Preference & voice audit</h2><button type="button" (click)="loadAudit()">Refresh audit</button><table><thead><tr><th>Time</th><th>Action</th><th>Store</th><th>Correlation</th></tr></thead><tbody>@for(a of audit();track a.id){<tr><td>{{a.createdUtc|date:'medium'}}</td><td>{{a.action}}</td><td>{{a.storeId||'-'}}</td><td>{{a.correlationId}}</td></tr>}@empty{<tr><td colspan="4">No preference/voice audit events.</td></tr>}</tbody></table></section>}</main></app-admin-shell>`})
export class VoicePreferencesPage{
 private readonly api=inject(PreferencesApiService);private readonly sessionSvc=inject(AuthSessionService);private readonly fb=inject(FormBuilder);protected readonly setting=signal<VoiceSetting|null>(null);protected readonly session=signal<VoiceSession|null>(null);protected readonly candidates=signal<VoiceCategoryCandidate[]>([]);protected readonly audit=signal<PreferenceAudit[]>([]);protected readonly error=signal('');protected readonly message=signal('');protected readonly saving=signal(false);protected readonly canConfigure=computed(()=>this.sessionSvc.hasPermission(PERMISSIONS.voiceCommandsConfigure));protected readonly canUse=computed(()=>this.sessionSvc.hasPermission(PERMISSIONS.voiceCommandsUse));protected readonly canAudit=computed(()=>this.sessionSvc.hasPermission(PERMISSIONS.voiceCommandsAudit));protected readonly canManageAliases=computed(()=>this.sessionSvc.hasPermission(PERMISSIONS.storeCategoriesManage));
 protected readonly storeForm=this.fb.group({storeId:[null as number|null,[Validators.required,Validators.min(1)]]});
 protected readonly settingForm=this.fb.nonNullable.group({triggerKeyword:['',Validators.required],aliases:'',responseMode:'InAppAndVoice',languageCode:'en-IN',listeningTimeoutSeconds:[30,[Validators.min(3),Validators.max(120)]],minimumRecognitionConfidence:[70,[Validators.min(0),Validators.max(100)]],isEnabled:true,requireConfirmation:true,requireConfirmationForAmbiguousCategory:true});
 protected readonly voiceForm=this.fb.group({customerId:[null as number|null,[Validators.required,Validators.min(1)]],triggerText:['',Validators.required]});
 protected readonly interpretForm=this.fb.group({recognizedText:['',Validators.required],recognitionConfidence:[90,[Validators.required,Validators.min(0),Validators.max(100)]],selectedCategoryId:[null as number|null]});
 protected readonly aliasForm=this.fb.nonNullable.group({categoryId:[0,[Validators.required,Validators.min(1)]],aliasText:['',[Validators.required,Validators.maxLength(150)]],languageCode:['en-IN',[Validators.required,Validators.maxLength(20)]],tenantWide:false});
 protected loadStore(){const id=this.storeForm.getRawValue().storeId;if(!id)return;this.clear();this.api.voiceSetting(id).subscribe({next:s=>{this.setting.set(s);this.settingForm.setValue({triggerKeyword:s.triggerKeyword,aliases:s.aliases.join(', '),responseMode:s.responseMode,languageCode:s.languageCode,listeningTimeoutSeconds:s.listeningTimeoutSeconds,minimumRecognitionConfidence:s.minimumRecognitionConfidence,isEnabled:s.isEnabled,requireConfirmation:s.requireConfirmation,requireConfirmationForAmbiguousCategory:s.requireConfirmationForAmbiguousCategory});if(this.canAudit())this.loadAudit();},error:e=>this.fail(e)});}
 protected saveSetting(){const s=this.setting();if(!s||this.settingForm.invalid)return;const v=this.settingForm.getRawValue();this.saving.set(true);this.api.saveVoiceSetting(s.storeId,{triggerKeyword:v.triggerKeyword.trim(),responseMode:v.responseMode,isEnabled:v.isEnabled,requireConfirmationForAmbiguousCategory:v.requireConfirmationForAmbiguousCategory,aliases:v.aliases.split(',').map(x=>x.trim()).filter(Boolean),languageCode:v.languageCode.trim(),requireConfirmation:v.requireConfirmation,listeningTimeoutSeconds:v.listeningTimeoutSeconds,minimumRecognitionConfidence:v.minimumRecognitionConfidence}).subscribe({next:x=>{this.setting.set(x);this.saving.set(false);this.message.set('Voice settings saved.');},error:e=>this.fail(e)});}
 protected startVoice(){const storeId=this.setting()?.storeId??this.storeForm.getRawValue().storeId;const v=this.voiceForm.getRawValue();if(!storeId||!v.customerId||!v.triggerText)return;this.saving.set(true);this.candidates.set([]);this.interpretForm.patchValue({selectedCategoryId:null});this.api.startVoice({storeId,customerId:v.customerId,triggerText:v.triggerText.trim()}).subscribe({next:x=>{this.session.set(x);this.saving.set(false);this.message.set('Listening session started.');},error:e=>this.fail(e)});}
 protected interpret(){const x=this.session();if(!x||this.interpretForm.invalid)return;const v=this.interpretForm.getRawValue();this.saving.set(true);this.api.interpretVoice(x.id,{recognizedText:(v.recognizedText??'').trim(),recognitionConfidence:v.recognitionConfidence??0,selectedCategoryId:v.selectedCategoryId??null,reason:'Voice command UI'}).subscribe({next:r=>{this.session.set(r.session);this.candidates.set(r.candidates);this.saving.set(false);this.message.set(r.resolutionMessage??(r.needsCategorySelection?'Select a category.':'Category resolved.'));},error:e=>this.fail(e)});}
 protected confirm(){const x=this.session();if(!x)return;this.api.confirmVoice(x.id).subscribe({next:s=>{this.session.set(s);this.message.set('Voice preference confirmed and recorded.');this.loadAudit();},error:e=>this.fail(e)});}protected reject(){const x=this.session();if(!x)return;this.api.rejectVoice(x.id).subscribe({next:s=>{this.session.set(s);this.message.set('Voice proposal rejected; no preference write was created.');this.loadAudit();},error:e=>this.fail(e)});}
 protected addAlias(){const storeId=this.setting()?.storeId??this.storeForm.getRawValue().storeId;const v=this.aliasForm.getRawValue();if(!v.categoryId||!v.aliasText.trim()||(!v.tenantWide&&!storeId))return;this.saving.set(true);this.api.addCategoryAlias(v.categoryId,{storeId:v.tenantWide?null:storeId??null,aliasText:v.aliasText.trim(),languageCode:v.languageCode.trim()}).subscribe({next:()=>{this.saving.set(false);this.message.set('Category alias added.');this.aliasForm.patchValue({aliasText:''});this.loadAudit();},error:e=>this.fail(e)});}
 protected loadAudit(){const storeId=this.setting()?.storeId??this.storeForm.getRawValue().storeId??undefined;this.api.audit(undefined,storeId).subscribe({next:x=>this.audit.set(x),error:e=>this.fail(e)});}protected statusLabel(v:number){return['','Listening','Pending confirmation','Confirmed','Rejected','Expired'][v]??'Unknown';}
 private clear(){this.error.set('');this.message.set('');}private fail(e:unknown){this.saving.set(false);this.error.set(preferenceErrorMessage(e,'Voice request failed.'));}
}
