import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { AuthSessionService } from '../../core/auth/auth-session.service';
import { PERMISSIONS } from '../../core/auth/permission-catalog';
import { AdminShell } from '../../shared/admin-shell/admin-shell';
import { PreferenceAudit, PreferenceType, PreferencesApiService, VoiceSession, VoiceSetting } from './preferences-api.service';

/** Phase 10 dynamic per-store voice settings, confirmation flow and audit UI. “Aasha Add” is only an example/default. */
@Component({selector:'app-voice-preferences-page',standalone:true,imports:[CommonModule,ReactiveFormsModule,AdminShell],changeDetection:ChangeDetectionStrategy.OnPush,
styles:[`:host{display:block}.wrap{padding:24px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.card{border:1px solid #ddd;border-radius:12px;padding:16px}.muted{opacity:.65}.error{color:#b3261e}.ok{color:#147d32}form{display:grid;gap:8px}input,select,button{min-height:40px;padding:8px;border:1px solid #ccc;border-radius:8px}.actions{display:flex;gap:8px;flex-wrap:wrap}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:8px;border-bottom:1px solid #eee}@media(max-width:850px){.grid{grid-template-columns:1fr}}`],
template:`<app-admin-shell><main class="wrap"><h1>Dynamic voice settings</h1><p class="muted">Trigger phrase and aliases are store-specific. “Aasha Add” is only an example/default and is never hard-coded as the only valid trigger.</p>@if(error()){<p class="error">{{error()}}</p>}@if(message()){<p class="ok">{{message()}}</p>}<div class="grid"><section class="card"><h2>Load store</h2><form [formGroup]="storeForm" (ngSubmit)="loadStore()"><input type="number" formControlName="storeId" placeholder="Store ID"><button [disabled]="storeForm.invalid">Load voice settings</button></form>@if(setting();as s){<h3>Store {{s.storeId}}</h3><form [formGroup]="settingForm" (ngSubmit)="saveSetting()"><input formControlName="triggerKeyword" placeholder="Trigger phrase"><input formControlName="aliases" placeholder="Aliases comma separated"><select formControlName="responseMode"><option>InApp</option><option>Toast</option><option>Voice</option><option>InAppAndVoice</option></select><input formControlName="languageCode" placeholder="Language code e.g. en-IN"><input type="number" formControlName="listeningTimeoutSeconds" placeholder="Listening timeout seconds"><input type="number" formControlName="minimumRecognitionConfidence" placeholder="Minimum confidence"><label><input type="checkbox" formControlName="isEnabled"> Enabled</label><label><input type="checkbox" formControlName="requireConfirmation"> Require confirmation before CRM write</label><label><input type="checkbox" formControlName="requireConfirmationForAmbiguousCategory"> Confirm ambiguous category</label><button [disabled]="settingForm.invalid||!canConfigure()||saving()">Save voice settings</button></form>}</section>
<section class="card"><h2>Voice command test</h2><p class="muted">Use the actual store trigger/alias. Recognition only proposes a preference; configured confirmation controls the write.</p><form [formGroup]="voiceForm" (ngSubmit)="startVoice()"><input type="number" formControlName="customerId" placeholder="Customer ID"><input formControlName="triggerText" placeholder="Trigger phrase"><button [disabled]="voiceForm.invalid||!canUse()||saving()">Start listening</button></form>@if(session();as x){<p>Status: <strong>{{statusLabel(x.status)}}</strong></p><form [formGroup]="interpretForm" (ngSubmit)="interpret()"><input formControlName="recognizedText" placeholder="Recognized preference/category"><input type="number" formControlName="recognitionConfidence" placeholder="Recognition confidence"><select formControlName="preferenceType"><option [ngValue]="1">Category</option><option [ngValue]="2">Product</option><option [ngValue]="3">Brand</option><option [ngValue]="4">Price range</option><option [ngValue]="5">Tag</option></select><input type="number" formControlName="referenceId" placeholder="Reference ID (optional)"><input formControlName="value" placeholder="Value / label"><button [disabled]="interpretForm.invalid||saving()">Interpret proposal</button></form>@if(x.status===2){<div class="actions"><button type="button" (click)="confirm()">Confirm</button><button type="button" (click)="reject()">Reject</button></div>}}</section></div>
@if(canAudit()){<section class="card" style="margin-top:16px"><h2>Preference & voice audit</h2><button type="button" (click)="loadAudit()">Refresh audit</button><table><thead><tr><th>Time</th><th>Action</th><th>Store</th><th>Correlation</th></tr></thead><tbody>@for(a of audit();track a.id){<tr><td>{{a.createdUtc|date:'medium'}}</td><td>{{a.action}}</td><td>{{a.storeId||'-'}}</td><td>{{a.correlationId}}</td></tr>}@empty{<tr><td colspan="4">No preference/voice audit events.</td></tr>}</tbody></table></section>}</main></app-admin-shell>`})
export class VoicePreferencesPage{
 private readonly api=inject(PreferencesApiService);private readonly sessionSvc=inject(AuthSessionService);private readonly fb=inject(FormBuilder);protected readonly setting=signal<VoiceSetting|null>(null);protected readonly session=signal<VoiceSession|null>(null);protected readonly audit=signal<PreferenceAudit[]>([]);protected readonly error=signal('');protected readonly message=signal('');protected readonly saving=signal(false);protected readonly canConfigure=computed(()=>this.sessionSvc.hasPermission(PERMISSIONS.voiceCommandsConfigure));protected readonly canUse=computed(()=>this.sessionSvc.hasPermission(PERMISSIONS.voiceCommandsUse));protected readonly canAudit=computed(()=>this.sessionSvc.hasPermission(PERMISSIONS.voiceCommandsAudit));
 protected readonly storeForm=this.fb.group({storeId:[null as number|null,[Validators.required,Validators.min(1)]]});
 protected readonly settingForm=this.fb.nonNullable.group({triggerKeyword:['',Validators.required],aliases:'',responseMode:'InAppAndVoice',languageCode:'en-IN',listeningTimeoutSeconds:[15,[Validators.min(3),Validators.max(120)]],minimumRecognitionConfidence:[70,[Validators.min(0),Validators.max(100)]],isEnabled:true,requireConfirmation:true,requireConfirmationForAmbiguousCategory:true});
 protected readonly voiceForm=this.fb.group({customerId:[null as number|null,[Validators.required,Validators.min(1)]],triggerText:['',Validators.required]});
 protected readonly interpretForm=this.fb.group({recognizedText:['',Validators.required],recognitionConfidence:[90,[Validators.required,Validators.min(0),Validators.max(100)]],preferenceType:[1 as PreferenceType,Validators.required],referenceId:[null as number|null],value:[''],});
 protected loadStore(){const id=this.storeForm.getRawValue().storeId;if(!id)return;this.clear();this.api.voiceSetting(id).subscribe({next:s=>{this.setting.set(s);this.settingForm.setValue({triggerKeyword:s.triggerKeyword,aliases:s.aliases.join(', '),responseMode:s.responseMode,languageCode:s.languageCode,listeningTimeoutSeconds:s.listeningTimeoutSeconds,minimumRecognitionConfidence:s.minimumRecognitionConfidence,isEnabled:s.isEnabled,requireConfirmation:s.requireConfirmation,requireConfirmationForAmbiguousCategory:s.requireConfirmationForAmbiguousCategory});if(this.canAudit())this.loadAudit();},error:e=>this.fail(e)});}
 protected saveSetting(){const s=this.setting();if(!s||this.settingForm.invalid)return;const v=this.settingForm.getRawValue();this.saving.set(true);this.api.saveVoiceSetting(s.storeId,{triggerKeyword:v.triggerKeyword.trim(),responseMode:v.responseMode,isEnabled:v.isEnabled,requireConfirmationForAmbiguousCategory:v.requireConfirmationForAmbiguousCategory,aliases:v.aliases.split(',').map(x=>x.trim()).filter(Boolean),languageCode:v.languageCode.trim(),requireConfirmation:v.requireConfirmation,listeningTimeoutSeconds:v.listeningTimeoutSeconds,minimumRecognitionConfidence:v.minimumRecognitionConfidence}).subscribe({next:x=>{this.setting.set(x);this.saving.set(false);this.message.set('Voice settings saved.');},error:e=>this.fail(e)});}
 protected startVoice(){const storeId=this.setting()?.storeId??this.storeForm.getRawValue().storeId;const v=this.voiceForm.getRawValue();if(!storeId||!v.customerId||!v.triggerText)return;this.saving.set(true);this.api.startVoice({storeId,customerId:v.customerId,triggerText:v.triggerText.trim()}).subscribe({next:x=>{this.session.set(x);this.saving.set(false);this.message.set('Listening session started.');},error:e=>this.fail(e)});}
 protected interpret(){const x=this.session();if(!x||this.interpretForm.invalid)return;const v=this.interpretForm.getRawValue();this.saving.set(true);this.api.interpretVoice(x.id,{recognizedText:(v.recognizedText??'').trim(),recognitionConfidence:v.recognitionConfidence??0,preferenceType:(v.preferenceType??1) as PreferenceType,referenceId:v.referenceId||null,value:v.value?.trim()||null,reason:'Voice command UI'}).subscribe({next:s=>{this.session.set(s);this.saving.set(false);this.message.set(s.status===2?'Confirmation required.':'Voice preference confirmed.');},error:e=>this.fail(e)});}
 protected confirm(){const x=this.session();if(!x)return;this.api.confirmVoice(x.id).subscribe({next:s=>{this.session.set(s);this.message.set('Voice preference confirmed and recorded.');this.loadAudit();},error:e=>this.fail(e)});}protected reject(){const x=this.session();if(!x)return;this.api.rejectVoice(x.id).subscribe({next:s=>{this.session.set(s);this.message.set('Voice proposal rejected; no preference write was created.');this.loadAudit();},error:e=>this.fail(e)});}
 protected loadAudit(){const storeId=this.setting()?.storeId??this.storeForm.getRawValue().storeId??undefined;this.api.audit(undefined,storeId).subscribe({next:x=>this.audit.set(x),error:e=>this.fail(e)});}protected statusLabel(v:number){return['','Listening','Pending confirmation','Confirmed','Rejected','Expired'][v]??'Unknown';}
 private clear(){this.error.set('');this.message.set('');}private fail(e:any){this.saving.set(false);this.error.set(e?.error?.message??e?.message??'Voice request failed.');}
}
