using CustSearch.Application.Authentication;
using CustSearch.Application.CamerasTracking;
using CustSearch.Application.TenantOperations;
using CustSearch.Domain.Entities;
using CustSearch.Domain.Enums;
using CustSearch.Infrastructure.CamerasTracking;
using CustSearch.Infrastructure.Persistence;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;

namespace CustSearch.IntegrationTests;

public sealed class CameraMotionRuleServiceTests:IAsyncLifetime
{
    private static readonly DateTime Now=new(2026,8,28,12,0,0,DateTimeKind.Utc);private readonly string path=Path.Combine(Path.GetTempPath(),$"motion-rules-{Guid.NewGuid():N}.db");private readonly User user=new();private Tenant tenant=null!;private Store store=null!;private Camera camera=null!;private CameraZoneConfiguration entry=null!;private long actorId;
    public async Task InitializeAsync(){await using var db=Db();await db.Database.EnsureCreatedAsync();tenant=Tenant.Create("MOTION","Motion Tenant","Motion","Owner","owner@motion.test","9000000301","IN","India Standard Time","INR",5,10,5,Now);db.Tenants.Add(tenant);await db.SaveChangesAsync();var actor=UserAccount.CreateTenant(tenant.Id,"motion-admin","motion@tenant.test","Motion Admin","hash",Now);db.UserAccounts.Add(actor);await db.SaveChangesAsync();actorId=actor.Id;store=Store.Create(tenant.Id,"MAIN","Main","Road",null,null,"Surat",null,"Gujarat","395001","IN",null,null,null,null,StoreLocationSource.Manual,"India Standard Time",null,null,Now);db.Stores.Add(store);await db.SaveChangesAsync();camera=Camera.Create(tenant.Id,store.Id,"ENTRY","Entry","env:CUSTSEARCH_CAMERA_ENTRY_RTSP",null,CameraDirection.Entry,true,Now);db.Cameras.Add(camera);await db.SaveChangesAsync();entry=CameraZoneConfiguration.Create(tenant.Id,store.Id,camera.Id,"ENTRY","Entry",CameraZoneType.Entry,"{\"points\":[[0,0],[1,0],[1,1]]}",1,null,Now);db.CameraZoneConfigurations.Add(entry);await db.SaveChangesAsync();user.Tenant=tenant.Id;user.UserIdValue=actorId;user.Stores=new HashSet<long>([store.Id]);}
    public Task DisposeAsync(){if(File.Exists(path))File.Delete(path);return Task.CompletedTask;}
    [Fact]public void CatalogExposesAllPlannedCodesButOnlyInitialSixAreAvailable(){using var db=Db();var catalog=Service(db).GetCatalog();Assert.Equal(26,catalog.Count);Assert.Equal(6,catalog.Count(x=>x.IsAvailable));Assert.Contains(catalog,x=>x.RuleCode=="SUSPECTED_UNPAID_EXIT"&&!x.IsAvailable);}
    [Fact]public async Task MasterAndFullFrameRuleAreSavedAndAdvancedRuleIsRejected(){await using var db=Db();var service=Service(db);Assert.False((await service.GetSettingsAsync(camera.Id)).MotionRulesEnabled);Assert.True((await service.SetSettingsAsync(camera.Id,true,Audit())).MotionRulesEnabled);var saved=await service.SaveAsync(camera.Id,null,Command("PERSON_DETECTED"),Audit());Assert.True(saved.IsEnabled);Assert.Null(saved.ZoneId);Assert.Equal("MON,TUE",saved.DaysOfWeek);var duplicate=await Assert.ThrowsAsync<CameraTrackingException>(()=>service.SaveAsync(camera.Id,null,Command("PERSON_DETECTED"),Audit()));Assert.Equal(CameraTrackingFailureKind.Conflict,duplicate.Kind);var advanced=await Assert.ThrowsAsync<CameraTrackingException>(()=>service.SaveAsync(camera.Id,null,Command("CAMERA_OCCLUDED"),Audit()));Assert.Equal(CameraTrackingFailureKind.Validation,advanced.Kind);}
    [Fact]public async Task ZoneRequiredRuleRejectsMissingOrOutOfScopeZone(){await using var db=Db();var service=Service(db);var missing=await Assert.ThrowsAsync<CameraTrackingException>(()=>service.SaveAsync(camera.Id,null,Command("ENTRY_CROSSED"),Audit()));Assert.Equal(CameraTrackingFailureKind.Validation,missing.Kind);var saved=await service.SaveAsync(camera.Id,null,Command("ENTRY_CROSSED") with{ZoneId=entry.Id},Audit());Assert.True(saved.ZoneRequired);Assert.Equal(entry.Id,saved.ZoneId);user.Stores=new HashSet<long>();var forbidden=await Assert.ThrowsAsync<CameraTrackingException>(()=>service.ListAsync(camera.Id));Assert.Equal(CameraTrackingFailureKind.Forbidden,forbidden.Kind);}
    private static SaveCameraMotionRuleCommand Command(string code)=>new(code,code,true,.75m,60,2,30,null,null,"mon,tue",true,false,5,10,AlertSeverity.Warning,true,true,null);private TenantAuditContext Audit()=>new(actorId,"127.0.0.1","tests","motion-rules");private CameraMotionRuleService Service(CustSearchDbContext db)=>new(db,user,new Clock());private CustSearchDbContext Db()=>new(new DbContextOptionsBuilder<CustSearchDbContext>().UseSqlite(new SqliteConnectionStringBuilder{DataSource=path,Cache=SqliteCacheMode.Shared,Mode=SqliteOpenMode.ReadWriteCreate,Pooling=false}.ToString()).Options);private sealed class Clock:TimeProvider{public override DateTimeOffset GetUtcNow()=>new(Now);}private sealed class User:ICurrentUserContext{public long Tenant{get;set;}public long UserIdValue{get;set;}public IReadOnlySet<long>Stores{get;set;}=new HashSet<long>();public bool IsAuthenticated=>true;public long UserId=>UserIdValue;public long?TenantId=>Tenant;public bool IsPlatformAdmin=>false;public string SecurityStamp=>"motion";public IReadOnlySet<string>Roles=>new HashSet<string>(["Manager"]);public IReadOnlySet<string>Permissions=>new HashSet<string>();public IReadOnlySet<long>StoreIds=>Stores;}
}
