using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using CustSearch.Application.Authentication;
using CustSearch.Application.CamerasTracking;
using CustSearch.Application.Security;
using CustSearch.Application.TenantOperations;
using CustSearch.Domain.Entities;
using CustSearch.Domain.Enums;
using CustSearch.Infrastructure.CamerasTracking;
using CustSearch.Infrastructure.Persistence;
using CustSearch.Infrastructure.Security;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.Extensions.Options;

namespace CustSearch.IntegrationTests;

public sealed class CameraEvidenceStorageServiceTests:IAsyncLifetime
{
    private static readonly DateTime Now=new(2026,8,28,12,0,0,DateTimeKind.Utc);private static readonly JsonSerializerOptions JsonOptions=new(JsonSerializerDefaults.Web);private const string Secret="evidence-service-secret-that-is-at-least-32-bytes";private readonly string dbPath=Path.Combine(Path.GetTempPath(),$"evidence-{Guid.NewGuid():N}.db");private readonly string storagePath=Path.Combine(Path.GetTempPath(),$"evidence-files-{Guid.NewGuid():N}");private readonly User user=new();private Tenant tenant=null!;private Store store=null!;private Camera camera=null!;private long actorId;
    public async Task InitializeAsync(){await using var db=Db();await db.Database.EnsureCreatedAsync();tenant=Tenant.Create("EVIDENCE","Evidence Tenant","Evidence","Owner","owner@evidence.test","9000000401","IN","India Standard Time","INR",5,10,5,Now);db.Tenants.Add(tenant);await db.SaveChangesAsync();var actor=UserAccount.CreateTenant(tenant.Id,"evidence-admin","evidence@tenant.test","Evidence Admin","hash",Now);db.UserAccounts.Add(actor);await db.SaveChangesAsync();actorId=actor.Id;store=Store.Create(tenant.Id,"MAIN","Main","Road",null,null,"Surat",null,"Gujarat","395001","IN",null,null,null,null,StoreLocationSource.Manual,"India Standard Time",null,null,Now);db.Stores.Add(store);await db.SaveChangesAsync();camera=Camera.Create(tenant.Id,store.Id,"ENTRY","Entry","env:CUSTSEARCH_CAMERA_ENTRY_RTSP",null,CameraDirection.Entry,true,Now);db.Cameras.Add(camera);await db.SaveChangesAsync();user.Tenant=tenant.Id;user.UserIdValue=actorId;user.Stores=new HashSet<long>([store.Id]);}
    public Task DisposeAsync(){if(File.Exists(dbPath))File.Delete(dbPath);if(Directory.Exists(storagePath))Directory.Delete(storagePath,true);return Task.CompletedTask;}
    [Fact]public async Task SignedEvidenceUsesEncryptedTenantNamespaceAndIsIdempotent(){await using var db=Db();var service=Service(db);var defaults=await service.GetTenantStorageAsync();Assert.Equal(2L*1024*1024*1024,defaults.Policy.StorageQuotaBytes);var body=Encoding.UTF8.GetBytes("jpeg-test-content");var envelope=Envelope("ev-1","idem-1",body);var saved=await service.IngestAsync(envelope);Assert.False(saved.Duplicate);Assert.Equal(body.Length,saved.UsedBytes);var duplicate=await service.IngestAsync(envelope);Assert.True(duplicate.Duplicate);var conflict=await Assert.ThrowsAsync<CameraTrackingException>(()=>service.IngestAsync(Envelope("ev-2","idem-1",Encoding.UTF8.GetBytes("different-content"))));Assert.Equal(CameraTrackingFailureKind.Conflict,conflict.Kind);var record=await db.CameraEvidence.SingleAsync();Assert.StartsWith($"tenants/{tenant.Id:D12}/stores/{store.Id:D12}/cameras/{camera.Id:D12}/",record.StorageObjectKey);Assert.DoesNotContain("evidence@tenant.test",record.StorageObjectKey,StringComparison.OrdinalIgnoreCase);var encrypted=await File.ReadAllBytesAsync(Path.Combine(storagePath,record.StorageObjectKey.Replace('/',Path.DirectorySeparatorChar)));Assert.DoesNotContain(Convert.ToHexString(body),Convert.ToHexString(encrypted),StringComparison.Ordinal);await using var plaintext=await EvidenceStore().OpenDecryptedAsync(record.StorageObjectKey);using var copy=new MemoryStream();await plaintext.CopyToAsync(copy);Assert.Equal(body,copy.ToArray());}
    [Fact]public async Task QuotaReservationRejectsOversizedEvidenceWithoutChangingUsage(){await using var db=Db();var service=Service(db);await service.GetTenantStorageAsync();var policy=await db.TenantStoragePolicies.SingleAsync();var usage=await db.TenantStorageUsage.SingleAsync();policy.Configure(true,1048576,15,15,15,3,15,30,80,90,true,true,true,QuotaPressurePolicy.StopNewClips,Now);usage.SetQuota(1048576,Now);await db.SaveChangesAsync();var rejected=await Assert.ThrowsAsync<CameraTrackingException>(()=>service.IngestAsync(Envelope("ev-large","idem-large",new byte[1048577])));Assert.Equal(CameraTrackingFailureKind.Conflict,rejected.Kind);Assert.Equal(0,(await db.TenantStorageUsage.SingleAsync()).UsedBytes);Assert.Empty(await db.CameraEvidence.ToListAsync());}
    [Fact]public async Task InvalidSignatureAndCredentialScopeAreRejectedBeforeStorage(){await using var db=Db();var service=Service(db);var envelope=Envelope("ev-auth","idem-auth",Encoding.UTF8.GetBytes("signed"));var invalid=envelope with{Signature=new string('0',64)};var unauthorized=await Assert.ThrowsAsync<CameraTrackingException>(()=>service.IngestAsync(invalid));Assert.Equal(CameraTrackingFailureKind.Unauthorized,unauthorized.Kind);var metadata=new CctvEvidenceMetadata(1,tenant.Id,store.Id+999,camera.CameraCode,CameraEvidenceType.MotionSnapshot,"image/jpeg",Now);var header=Convert.ToBase64String(JsonSerializer.SerializeToUtf8Bytes(metadata,JsonOptions));var timestamp=Now.ToString("O");var prefix=$"cctv-test\n{timestamp}\nev-scope\nidem-scope\n{header}\n";var body=Encoding.UTF8.GetBytes("scope");var canonical=Encoding.UTF8.GetBytes(prefix).Concat(body).ToArray();var signature=Convert.ToHexString(HMACSHA256.HashData(Encoding.UTF8.GetBytes(Secret),canonical));var forbidden=await Assert.ThrowsAsync<CameraTrackingException>(()=>service.IngestAsync(new("cctv-test",timestamp,signature,"ev-scope","idem-scope",header,body,"evidence-test")));Assert.Equal(CameraTrackingFailureKind.Forbidden,forbidden.Kind);Assert.Empty(await db.CameraEvidence.ToListAsync());}
    [Fact]public async Task RetentionDeletesExpiredUnpinnedObjectAndReleasesUsageWithAudit(){await using var db=Db();var service=Service(db);var body=Encoding.UTF8.GetBytes("expired-evidence");await service.IngestAsync(Envelope("ev-expired","idem-expired",body));var record=await db.CameraEvidence.AsNoTracking().SingleAsync();var path=Path.Combine(storagePath,record.StorageObjectKey.Replace('/',Path.DirectorySeparatorChar));Assert.True(File.Exists(path));db.ChangeTracker.Clear();var processor=Processor(db,Now.AddDays(16));var result=await processor.RunOnceAsync(100,10,TimeSpan.FromHours(24));Assert.Equal(1,result.ExpiredDeleted);Assert.Equal(body.Length,result.BytesReleased);Assert.False(File.Exists(path));var deleted=await db.CameraEvidence.AsNoTracking().SingleAsync();Assert.True(deleted.IsDeleted);Assert.Equal("RetentionExpired",deleted.DeleteReason);var usage=await db.TenantStorageUsage.AsNoTracking().SingleAsync();Assert.Equal(0,usage.UsedBytes);Assert.NotNull(usage.LastCleanupUtc);Assert.NotNull(usage.LastReconciledUtc);Assert.Contains(await db.AuditLogs.AsNoTracking().ToListAsync(),x=>x.Action=="EvidenceRetentionDeleted"&&x.ActorType=="Worker");}
    [Fact]public async Task RetentionKeepsPinnedExpiredEvidence(){await using var db=Db();var service=Service(db);var body=Encoding.UTF8.GetBytes("pinned-evidence");await service.IngestAsync(Envelope("ev-pinned","idem-pinned",body,pinned:true));db.ChangeTracker.Clear();var processor=Processor(db,Now.AddDays(16));var result=await processor.RunOnceAsync(100,10,TimeSpan.FromHours(24));Assert.Equal(0,result.ExpiredDeleted);Assert.False((await db.CameraEvidence.AsNoTracking().SingleAsync()).IsDeleted);Assert.Equal(body.Length,(await db.TenantStorageUsage.AsNoTracking().SingleAsync()).UsedBytes);}
    [Fact]public async Task ReconciliationMarksMissingObjectDeletedAndCorrectsCounters(){await using var db=Db();var service=Service(db);var body=Encoding.UTF8.GetBytes("missing-evidence");await service.IngestAsync(Envelope("ev-missing","idem-missing",body));var record=await db.CameraEvidence.AsNoTracking().SingleAsync();await EvidenceStore().DeleteAsync(record.StorageObjectKey);db.ChangeTracker.Clear();var processor=Processor(db,Now);var result=await processor.RunOnceAsync(100,10,TimeSpan.FromHours(24));Assert.Equal(0,result.ExpiredDeleted);Assert.Equal(1,result.MissingDeleted);Assert.Equal(1,result.TenantsReconciled);Assert.Equal(body.Length,result.BytesReleased);var missing=await db.CameraEvidence.AsNoTracking().SingleAsync();Assert.True(missing.IsDeleted);Assert.Equal("ObjectMissingDuringReconciliation",missing.DeleteReason);Assert.Equal(0,(await db.TenantStorageUsage.AsNoTracking().SingleAsync()).UsedBytes);Assert.Contains(await db.AuditLogs.AsNoTracking().ToListAsync(),x=>x.Action=="EvidenceReconciliationMissingObject");}
    [Fact]public async Task PlatformPolicyCannotBeReducedBelowUsageAndTenantListIsStoreScoped(){await using var db=Db();var service=Service(db);await service.GetTenantStorageAsync();user.Platform=true;var saved=await service.SavePlatformPolicyAsync(tenant.Id,new(true,3L*1024*1024*1024,15,15,15,3,15,30,75,90,true,true,true,QuotaPressurePolicy.StopNewClips),new(actorId,"127.0.0.1","tests","storage-policy"));Assert.Equal(3L*1024*1024*1024,saved.Usage.QuotaBytes);user.Platform=false;user.RolesValue=new HashSet<string>();user.Stores=new HashSet<long>();var denied=await Assert.ThrowsAsync<CameraTrackingException>(()=>service.ListEvidenceAsync(store.Id,null));Assert.Equal(CameraTrackingFailureKind.Forbidden,denied.Kind);}
    private CctvEvidenceEnvelope Envelope(string eventId,string idempotency,byte[]body,bool pinned=false){var metadata=new CctvEvidenceMetadata(1,tenant.Id,store.Id,camera.CameraCode,CameraEvidenceType.MotionSnapshot,"image/jpeg",Now,IsPinned:pinned);var header=Convert.ToBase64String(JsonSerializer.SerializeToUtf8Bytes(metadata,JsonOptions));var timestamp=Now.ToString("O");var prefix=$"cctv-test\n{timestamp}\n{eventId}\n{idempotency}\n{header}\n";var canonical=Encoding.UTF8.GetBytes(prefix).Concat(body).ToArray();var signature=Convert.ToHexString(HMACSHA256.HashData(Encoding.UTF8.GetBytes(Secret),canonical));return new("cctv-test",timestamp,signature,eventId,idempotency,header,body,"evidence-test");}
    private CameraEvidenceStorageService Service(CustSearchDbContext db)=>new(db,user,new Resolver(new(Secret,tenant.Id,new HashSet<long>([store.Id]))),EvidenceStore(),new FixedClock(Now),Options.Create(new CctvSecurityOptions()),EvidenceOptions());private CameraEvidenceMaintenanceProcessor Processor(CustSearchDbContext db,DateTime now)=>new(db,EvidenceStore(),new FixedClock(now),NullLogger<CameraEvidenceMaintenanceProcessor>.Instance);private LocalEncryptedSecurityEvidenceStore EvidenceStore()=>new(EvidenceOptions());private IOptions<SecurityEvidenceOptions>EvidenceOptions()=>Options.Create(new SecurityEvidenceOptions{StoragePath=storagePath,DownloadSigningKey=new string('x',32),EncryptionKeyBase64=Convert.ToBase64String(Encoding.UTF8.GetBytes("01234567890123456789012345678901"))});private CustSearchDbContext Db()=>new(new DbContextOptionsBuilder<CustSearchDbContext>().UseSqlite(new SqliteConnectionStringBuilder{DataSource=dbPath,Cache=SqliteCacheMode.Shared,Mode=SqliteOpenMode.ReadWriteCreate,Pooling=false}.ToString()).Options);private sealed class FixedClock(DateTime value):TimeProvider{public override DateTimeOffset GetUtcNow()=>new(value);}private sealed class Resolver(CctvServiceCredential credential):ICctvServiceSecretResolver{public ValueTask<CctvServiceCredential?>ResolveAsync(string serviceId,CancellationToken cancellationToken=default)=>ValueTask.FromResult<CctvServiceCredential?>(serviceId=="cctv-test"?credential:null);}private sealed class User:ICurrentUserContext{public long Tenant{get;set;}public long UserIdValue{get;set;}public bool Platform{get;set;}public IReadOnlySet<long>Stores{get;set;}=new HashSet<long>();public IReadOnlySet<string>RolesValue{get;set;}=new HashSet<string>(["TenantAdmin"]);public bool IsAuthenticated=>true;public long UserId=>UserIdValue;public long?TenantId=>Platform?null:Tenant;public bool IsPlatformAdmin=>Platform;public string SecurityStamp=>"evidence";public IReadOnlySet<string>Roles=>RolesValue;public IReadOnlySet<string>Permissions=>new HashSet<string>();public IReadOnlySet<long>StoreIds=>Stores;}
}
