using CustSearch.Application.Authentication;
using CustSearch.Application.Authorization;
using CustSearch.Application.Recognition;
using CustSearch.Application.TenantOperations;
using CustSearch.Domain.Entities;
using CustSearch.Domain.Enums;
using CustSearch.Infrastructure.Persistence;
using CustSearch.Infrastructure.Recognition;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;

namespace CustSearch.IntegrationTests;

public sealed class PhaseFourteenRecognitionServiceTests:IAsyncLifetime
{
    private static readonly DateTime Now=new(2026,8,25,12,0,0,DateTimeKind.Utc);private readonly string databasePath=Path.Combine(Path.GetTempPath(),$"custsearch-p14-{Guid.NewGuid():N}.db");private readonly FakeCurrentUser user=new();private Tenant tenant=null!;private UserAccount actor=null!;private Store store1=null!;private Store store2=null!;private Customer customer=null!;private PersonTrackSession track=null!;
    public async Task InitializeAsync(){await using var db=CreateDb();await db.Database.EnsureCreatedAsync();tenant=Tenant.Create("P14","Phase Fourteen Private Limited","Phase Fourteen","Owner","owner@p14.test","9000000014","IN","India Standard Time","INR",10,30,10,Now);db.Tenants.Add(tenant);await db.SaveChangesAsync();actor=UserAccount.CreateTenant(tenant.Id,"recognition-reviewer","reviewer@p14.test","Recognition Reviewer","hash",Now);db.UserAccounts.Add(actor);await db.SaveChangesAsync();store1=NewStore(tenant.Id,"S1","Store One");store2=NewStore(tenant.Id,"S2","Store Two");db.Stores.AddRange(store1,store2);await db.SaveChangesAsync();customer=Customer.Create(tenant.Id,"C-14","Eligible","Customer",null,null,null,Now);db.Customers.Add(customer);await db.SaveChangesAsync();db.CustomerStoreAssignments.Add(CustomerStoreAssignment.Assign(tenant.Id,customer.Id,store1.Id,true,Now,actor.Id));var camera=Camera.Create(tenant.Id,store1.Id,"ENTRY","Entry","vault:entry",null,CameraDirection.Entry,true,Now);db.Cameras.Add(camera);await db.SaveChangesAsync();track=PersonTrackSession.Start(tenant.Id,store1.Id,camera.Id,"anonymous-p14",Now,.9m);db.PersonTrackSessions.Add(track);await db.SaveChangesAsync();user.UserIdValue=actor.Id;user.TenantIdValue=tenant.Id;user.StoreIdsValue=new HashSet<long>{store1.Id};user.PermissionsValue=new HashSet<string>{PermissionCatalog.Operations.RecognitionView,PermissionCatalog.Operations.RecognitionEnroll,PermissionCatalog.Operations.RecognitionReview,PermissionCatalog.Operations.RecognitionSettingsManage,PermissionCatalog.Operations.RecognitionConsentManage};}
    public Task DisposeAsync(){if(File.Exists(databasePath))File.Delete(databasePath);return Task.CompletedTask;}
    [Fact]public async Task EnrollmentWithoutConsentAndExpiredConsentAreRejected(){await using var db=CreateDb();var service=Service(db);var command=Enrollment(999);Assert.Equal(RecognitionFailureKind.NotFound,(await Assert.ThrowsAsync<RecognitionException>(()=>service.EnrollAsync(customer.Id,command,Audit()))).Kind);var expired=await service.GrantConsentAsync(customer.Id,new(RecognitionConsentType.BiometricRecognition,"Store welcome",Now.AddDays(-2),Now.AddDays(-1),"v1",null),Audit());Assert.Equal(RecognitionFailureKind.Forbidden,(await Assert.ThrowsAsync<RecognitionException>(()=>service.EnrollAsync(customer.Id,Enrollment(expired.Id),Audit()))).Kind);}
    [Fact]public async Task ActiveConsentEncryptsDerivedTemplateAndCrossStoreIsRejected(){await using var db=CreateDb();var service=Service(db);var consent=await Grant(service);var original=Enumerable.Range(0,64).Select(x=>(byte)x).ToArray();var enrolled=await service.EnrollAsync(customer.Id,new(store1.Id,consent.Id,"Store welcome",Convert.ToBase64String(original),"onnx-v1"),Audit());var stored=await db.BiometricTemplates.SingleAsync(x=>x.Id==enrolled.Id);Assert.NotEqual(original,stored.EncryptedTemplate);Assert.Equal(12,stored.Nonce.Length);Assert.Equal(16,stored.AuthenticationTag.Length);Assert.Equal(RecognitionFailureKind.Forbidden,(await Assert.ThrowsAsync<RecognitionException>(()=>service.EnrollAsync(customer.Id,new(store2.Id,consent.Id,"Store welcome",Convert.ToBase64String(original),"onnx-v1"),Audit()))).Kind);}
    [Fact]public async Task AmbiguousCandidateNeverAutoMergesAnonymousTrack(){await using var db=CreateDb();var service=Service(db);var template=await Enroll(service);var candidate=await service.CreateCandidateAsync(new(store1.Id,track.Id,template.Id,"request-ambiguous","Store welcome",.92m,.9m,.90m),Audit());Assert.Equal(RecognitionCandidateStatus.Ambiguous,candidate.Status);var reviewed=await service.ReviewAsync(candidate.Id,true,"Operator reviewed context",Audit());Assert.Equal(RecognitionCandidateStatus.Accepted,reviewed.Status);db.ChangeTracker.Clear();var persistedTrack=await db.PersonTrackSessions.SingleAsync(x=>x.Id==track.Id);Assert.Equal(TrackingSubjectKind.Anonymous,persistedTrack.SubjectKind);Assert.Null(persistedTrack.CustomerId);}
    [Fact]public async Task WithdrawalErasesTemplateBlocksReviewAndCreatesAudit(){await using var db=CreateDb();var service=Service(db);var template=await Enroll(service);var candidate=await service.CreateCandidateAsync(new(store1.Id,track.Id,template.Id,"request-withdraw","Store welcome",.95m,.9m,null),Audit());var consent=await db.CustomerRecognitionConsents.SingleAsync(x=>x.Id==template.ConsentId);await service.WithdrawConsentAsync(consent.Id,"Customer withdrew",Audit());db.ChangeTracker.Clear();var erased=await db.BiometricTemplates.SingleAsync(x=>x.Id==template.Id);Assert.Equal(BiometricTemplateStatus.Deleted,erased.Status);Assert.Empty(erased.EncryptedTemplate);Assert.Equal(RecognitionFailureKind.Forbidden,(await Assert.ThrowsAsync<RecognitionException>(()=>service.ReviewAsync(candidate.Id,true,"Too late",Audit()))).Kind);Assert.True(await db.AuditLogs.AnyAsync(x=>x.Action=="RecognitionConsentWithdrawn"));}
    [Fact]public async Task CrossTenantCustomerAndTemplateMetadataAccessAreRejected(){await using var db=CreateDb();var service=Service(db);await Enroll(service);user.TenantIdValue=tenant.Id+999;Assert.Equal(RecognitionFailureKind.NotFound,(await Assert.ThrowsAsync<RecognitionException>(()=>service.ListTemplatesAsync(customer.Id,Audit()))).Kind);}
    private RecognitionService Service(CustSearchDbContext db)=>new(db,user,new FakeProtector(),new FixedClock(),Options.Create(new RecognitionSecurityOptions{Enabled=true,EncryptionKeyReference="vault:key",EncryptionKeyBase64=Convert.ToBase64String(new byte[32]),MinimumConfidence=.85m,MinimumQuality=.7m,AmbiguityDelta=.05m,RetentionDaysAfterWithdrawal=30}));
    private async Task<RecognitionConsentView>Grant(RecognitionService service)=>await service.GrantConsentAsync(customer.Id,new(RecognitionConsentType.BiometricRecognition,"Store welcome",Now,null,"v1","consent:evidence"),Audit());
    private async Task<BiometricTemplateView>Enroll(RecognitionService service){var consent=await Grant(service);return await service.EnrollAsync(customer.Id,Enrollment(consent.Id),Audit());}
    private EnrollBiometricTemplateCommand Enrollment(long consentId)=>new(store1.Id,consentId,"Store welcome",Convert.ToBase64String(new byte[64]),"onnx-v1");private TenantAuditContext Audit()=>new(actor.Id,null,"tests","phase14-correlation");
    private static Store NewStore(long tenantId,string code,string name)=>Store.Create(tenantId,code,name,"1 Main Road",null,null,"Ahmedabad",null,"Gujarat","380001","IN",null,null,null,null,StoreLocationSource.Manual,"India Standard Time",null,null,Now);
    private CustSearchDbContext CreateDb()=>new(new DbContextOptionsBuilder<CustSearchDbContext>().UseSqlite(new SqliteConnectionStringBuilder{DataSource=databasePath,Cache=SqliteCacheMode.Shared,Mode=SqliteOpenMode.ReadWriteCreate,Pooling=false}.ToString()).Options);
    private sealed class FixedClock:TimeProvider{public override DateTimeOffset GetUtcNow()=>new(Now);}
    private sealed class FakeProtector:IRecognitionTemplateProtector{public ProtectedRecognitionTemplate Protect(ReadOnlySpan<byte>derivedTemplate){var bytes=derivedTemplate.ToArray();Array.Reverse(bytes);return new(bytes,new byte[12],new byte[16],"vault:key","AES-256-GCM");}}
    private sealed class FakeCurrentUser:ICurrentUserContext{public long UserIdValue{get;set;}public long TenantIdValue{get;set;}public IReadOnlySet<long>StoreIdsValue{get;set;}=new HashSet<long>();public IReadOnlySet<string>PermissionsValue{get;set;}=new HashSet<string>();public bool IsAuthenticated=>true;public long UserId=>UserIdValue;public long?TenantId=>TenantIdValue;public bool IsPlatformAdmin=>false;public string SecurityStamp=>"p14";public IReadOnlySet<string>Roles=>new HashSet<string>();public IReadOnlySet<string>Permissions=>PermissionsValue;public IReadOnlySet<long>StoreIds=>StoreIdsValue;}
}
