using CustSearch.Application.Authentication;
using CustSearch.Application.Authorization;
using CustSearch.Application.ReportsExports;
using CustSearch.Application.TenantOperations;
using CustSearch.Domain.Entities;
using CustSearch.Domain.Enums;
using CustSearch.Infrastructure.Persistence;
using CustSearch.Infrastructure.ReportsExports;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;

namespace CustSearch.IntegrationTests;

public sealed class PhaseFifteenReportsExportsServiceTests:IAsyncLifetime
{
    private static readonly DateTime Now=new(2026,8,25,12,0,0,DateTimeKind.Utc);private readonly string databasePath=Path.Combine(Path.GetTempPath(),$"custsearch-p15-{Guid.NewGuid():N}.db");private readonly FakeCurrentUser user=new();private readonly FakeReports queries=new();private Tenant tenant=null!;private UserAccount actor=null!;private Store store1=null!;private Store store2=null!;
    public async Task InitializeAsync(){await using var db=CreateDb();await db.Database.EnsureCreatedAsync();tenant=Tenant.Create("P15","Phase Fifteen Private Limited","Phase Fifteen","Owner","owner@p15.test","9000000015","IN","India Standard Time","INR",10,30,10,Now);db.Tenants.Add(tenant);await db.SaveChangesAsync();actor=UserAccount.CreateTenant(tenant.Id,"reporter","reporter@p15.test","Reporter","hash",Now);db.UserAccounts.Add(actor);await db.SaveChangesAsync();store1=Store.Create(tenant.Id,"S1","Store One","1 Main Road",null,null,"Ahmedabad",null,"Gujarat","380001","IN",null,null,null,null,StoreLocationSource.Manual,"India Standard Time",null,null,Now);store2=Store.Create(tenant.Id,"S2","Store Two","2 Main Road",null,null,"Ahmedabad",null,"Gujarat","380002","IN",null,null,null,null,StoreLocationSource.Manual,"India Standard Time",null,null,Now);db.Stores.AddRange(store1,store2);await db.SaveChangesAsync();user.UserIdValue=actor.Id;user.TenantIdValue=tenant.Id;user.StoreIdsValue=new HashSet<long>{store1.Id};user.PermissionsValue=new HashSet<string>{PermissionCatalog.Operations.ReportsView,PermissionCatalog.Operations.ReportsExport};}
    public Task DisposeAsync(){if(File.Exists(databasePath))File.Delete(databasePath);return Task.CompletedTask;}
    [Fact]public async Task TenantAndStoreScopeAreServerDerivedBeforeQuery(){await using var db=CreateDb();var service=Service(db);var filter=new ReportFilter(Now.AddDays(-1),Now,[store1.Id],1,100);await service.RunAsync(ReportType.Customers,filter);Assert.Equal(tenant.Id,queries.TenantId);Assert.Equal(new long[]{store1.Id},queries.StoreIds);await Assert.ThrowsAsync<ReportExportException>(()=>service.RunAsync(ReportType.Customers,filter with{StoreIds=[store2.Id]}));}
    [Fact]public async Task LargeExportIsQueuedWithoutRunningReportInBrowserTransaction(){await using var db=CreateDb();var service=Service(db);var job=await service.QueueAsync(new(ReportType.OperationalSummary,ExportFormat.Excel,new(Now.AddDays(-30),Now,[],1,100)),Audit());Assert.Equal(ExportJobStatus.Queued,job.Status);Assert.Equal(0,queries.QueryCount);Assert.True(await db.NotificationOutbox.AnyAsync(x=>x.EventType=="export.created"));Assert.True(await db.AuditLogs.AnyAsync(x=>x.Action=="ExportQueued"));}
    [Fact]public async Task AnotherUserCannotDiscoverOrDownloadExportByGuessingId(){await using var db=CreateDb();var service=Service(db);var job=await service.QueueAsync(new(ReportType.Customers,ExportFormat.Csv,new(Now.AddDays(-1),Now,[],1,100)),Audit());user.UserIdValue=actor.Id+999;Assert.Equal(ReportExportFailureKind.NotFound,(await Assert.ThrowsAsync<ReportExportException>(()=>service.GetJobAsync(job.Id))).Kind);Assert.Empty(await service.ListJobsAsync());}
    private ReportsExportsService Service(CustSearchDbContext db)=>new(db,user,queries,new FakeFiles(),new FakeTokens(),new FixedClock(),Options.Create(new ReportsExportsOptions{RetentionHours=24,DownloadTicketMinutes=5,MaximumExportRows=50000,LeaseSeconds=120,StoragePath="safe"}));
    private TenantAuditContext Audit()=>new(actor.Id,null,"tests","phase15-correlation");private CustSearchDbContext CreateDb()=>new(new DbContextOptionsBuilder<CustSearchDbContext>().UseSqlite(new SqliteConnectionStringBuilder{DataSource=databasePath,Cache=SqliteCacheMode.Shared,Mode=SqliteOpenMode.ReadWriteCreate}.ToString()).Options);
    private sealed class FixedClock:TimeProvider{public override DateTimeOffset GetUtcNow()=>new(Now);}
    private sealed class FakeReports:IReportQueryRepository{public long TenantId{get;private set;}public long[]StoreIds{get;private set;}=[];public int QueryCount{get;private set;}public Task<ReportResultView>QueryTenantAsync(long tenantId,ReportType type,long[]stores,ReportFilter filter,CancellationToken ct=default){TenantId=tenantId;StoreIds=stores;QueryCount++;return Task.FromResult(new ReportResultView(type,filter.FromUtc,filter.ToUtc,filter.Page,filter.PageSize,1,[new("Customers",stores.FirstOrDefault(),"Count",1,null,null)]));}public Task<ReportResultView>QueryPlatformAsync(ReportType type,ReportFilter filter,CancellationToken ct=default){QueryCount++;return Task.FromResult(new ReportResultView(type,filter.FromUtc,filter.ToUtc,filter.Page,filter.PageSize,0,[]));}}
    private sealed class FakeFiles:IExportFileStore{public Task<StoredExportFile>SaveAsync(long jobId,ExportFormat format,ReportResultView report,CancellationToken ct=default)=>Task.FromResult(new StoredExportFile("safe","safe","text/csv"));public Task<Stream>OpenReadAsync(string path,CancellationToken ct=default)=>Task.FromResult<Stream>(new MemoryStream());public Task DeleteAsync(string path,CancellationToken ct=default)=>Task.CompletedTask;}
    private sealed class FakeTokens:IExportDownloadTokenService{public ExportDownloadTicketView Create(long jobId,long userId,long?tenantId,DateTime expiresUtc)=>new("token",expiresUtc);public void Validate(string token,long jobId,long userId,long?tenantId,DateTime utcNow){}}
    private sealed class FakeCurrentUser:ICurrentUserContext{public long UserIdValue{get;set;}public long TenantIdValue{get;set;}public IReadOnlySet<long>StoreIdsValue{get;set;}=new HashSet<long>();public IReadOnlySet<string>PermissionsValue{get;set;}=new HashSet<string>();public bool IsAuthenticated=>true;public long UserId=>UserIdValue;public long?TenantId=>TenantIdValue;public bool IsPlatformAdmin=>false;public string SecurityStamp=>"p15";public IReadOnlySet<string>Roles=>new HashSet<string>{"Reporter"};public IReadOnlySet<string>Permissions=>PermissionsValue;public IReadOnlySet<long>StoreIds=>StoreIdsValue;}
}
