using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using CustSearch.Application.Authentication;
using CustSearch.Application.CamerasTracking;
using CustSearch.Application.TenantOperations;
using CustSearch.Domain.Entities;
using CustSearch.Domain.Enums;
using CustSearch.Infrastructure.CamerasTracking;
using CustSearch.Infrastructure.Persistence;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;

namespace CustSearch.IntegrationTests;

public sealed class PhaseThirteenCameraTrackingServiceTests:IAsyncLifetime
{
    private static readonly DateTime Now=new(2026,8,25,9,0,0,DateTimeKind.Utc);private static readonly JsonSerializerOptions WebJson=new(JsonSerializerDefaults.Web);private readonly string databasePath=Path.Combine(Path.GetTempPath(),$"custsearch-p13-{Guid.NewGuid():N}.db");private Tenant tenant=null!;private Store store1=null!;private Store store2=null!;private Camera camera1=null!;private Camera camera2=null!;private readonly FakeCurrentUser user=new();private readonly FakeSecret secrets=new();
    public async Task InitializeAsync(){await using var db=CreateDb();await db.Database.EnsureCreatedAsync();tenant=Tenant.Create("P13","Phase Thirteen Private Limited","Phase Thirteen","Owner","owner@p13.test","9000000013","IN","India Standard Time","INR",10,30,5,Now);db.Tenants.Add(tenant);await db.SaveChangesAsync();var actor=UserAccount.CreateTenant(tenant.Id,"camera-manager","camera-manager@p13.test","Camera Manager","hash",Now);db.UserAccounts.Add(actor);await db.SaveChangesAsync();store1=NewStore(tenant.Id,"S1","Store One");store2=NewStore(tenant.Id,"S2","Store Two");db.Stores.AddRange(store1,store2);await db.SaveChangesAsync();camera1=Camera.Create(tenant.Id,store1.Id,"ENTRY","Entry","vault:entry",null,CameraDirection.Entry,true,Now);camera2=Camera.Create(tenant.Id,store1.Id,"AISLE","Aisle","vault:aisle",null,CameraDirection.Internal,true,Now);db.Cameras.AddRange(camera1,camera2);await db.SaveChangesAsync();user.UserIdValue=actor.Id;user.TenantIdValue=tenant.Id;user.StoreIdsValue=new HashSet<long>{store1.Id};secrets.Credential=new("phase13-secret",tenant.Id,new HashSet<long>{store1.Id});}
    public Task DisposeAsync(){if(File.Exists(databasePath))File.Delete(databasePath);return Task.CompletedTask;}

    [Fact]public async Task StoreScopedCameraListCannotSeeAnotherStore(){await using(var setup=CreateDb()){setup.Cameras.Add(Camera.Create(tenant.Id,store2.Id,"PRIVATE","Private","vault:private",null,CameraDirection.Internal,true,Now));await setup.SaveChangesAsync();}await using var db=CreateDb();var result=await Service(db).ListCamerasAsync(null);Assert.Equal(2,result.Count);Assert.All(result,x=>Assert.Equal(store1.Id,x.StoreId));}
    [Fact]public async Task QuotaSummaryIsTenantWideEvenForStoreScopedUser(){await using(var setup=CreateDb()){setup.Cameras.Add(Camera.Create(tenant.Id,store2.Id,"PRIVATE","Private","vault:private",null,CameraDirection.Internal,true,Now));await setup.SaveChangesAsync();}await using var db=CreateDb();var quota=await Service(db).GetCameraQuotaAsync();Assert.Equal(5,quota.MaxCameras);Assert.Equal(3,quota.ConfiguredCameras);Assert.Equal(3,quota.ActiveCameras);Assert.Equal(2,quota.AvailableCameras);Assert.True(quota.CanAddActiveCamera);}
    [Fact]public async Task ActiveCameraQuotaAllowsFiveRejectsSixAndReusesDisabledSlot(){await using var db=CreateDb();var service=Service(db);var audit=new TenantAuditContext(user.UserId,"127.0.0.1","tests","camera-quota");for(var number=3;number<=5;number++){var code=$"CAM-{number}";await service.SaveCameraAsync(null,new(store1.Id,code,code,$"vault:{code}",null,CameraDirection.Internal,true),audit);}var full=await service.GetCameraQuotaAsync();Assert.Equal(5,full.ActiveCameras);Assert.Equal(0,full.AvailableCameras);Assert.False(full.CanAddActiveCamera);var sixth=await Assert.ThrowsAsync<CameraTrackingException>(()=>service.SaveCameraAsync(null,new(store1.Id,"CAM-6","Camera 6","vault:cam-6",null,CameraDirection.Internal,true),audit));Assert.Equal(CameraTrackingFailureKind.Conflict,sixth.Kind);Assert.Contains("maximum 5 active cameras",sixth.Message);var inactive=await service.SaveCameraAsync(null,new(store1.Id,"SPARE","Spare","vault:spare",null,CameraDirection.Internal,false),audit);var withSpare=await service.GetCameraQuotaAsync();Assert.Equal(6,withSpare.ConfiguredCameras);Assert.Equal(5,withSpare.ActiveCameras);var reactivation=await Assert.ThrowsAsync<CameraTrackingException>(()=>service.SaveCameraAsync(inactive.Id,new(store1.Id,inactive.CameraCode,inactive.Name,null,null,inactive.Direction,true),audit));Assert.Equal(CameraTrackingFailureKind.Conflict,reactivation.Kind);await service.SaveCameraAsync(camera1.Id,new(store1.Id,camera1.CameraCode,camera1.Name,null,null,camera1.Direction,false),audit);var activated=await service.SaveCameraAsync(inactive.Id,new(store1.Id,inactive.CameraCode,inactive.Name,null,null,inactive.Direction,true),audit);Assert.True(activated.IsActive);Assert.Equal(5,(await service.GetCameraQuotaAsync()).ActiveCameras);}
    [Fact]public async Task ValidEventsCreateAnonymousLifecycleAndHandoff(){await using var db=CreateDb();var service=Service(db);var entered=await service.ReceiveAsync(Envelope("evt-1","idem-1",Payload("person.entered","ENTRY",Now,.81m)));var handoff=await service.ReceiveAsync(Envelope("evt-2","idem-2",Payload("person.handoff","AISLE",Now.AddSeconds(5),.91m,"ENTRY",700)));var exited=await service.ReceiveAsync(Envelope("evt-3","idem-3",Payload("person.exited","AISLE",Now.AddSeconds(10),.92m)));Assert.False(entered.Duplicate);Assert.False(handoff.Duplicate);Assert.False(exited.Duplicate);var track=await db.PersonTrackSessions.SingleAsync();Assert.Equal(TrackingSubjectKind.Anonymous,track.SubjectKind);Assert.Equal(PersonTrackingState.Ended,track.TrackingState);Assert.Equal(camera2.Id,track.CameraId);Assert.Null(track.CustomerId);Assert.Null(track.StaffProfileId);Assert.Equal(1,await db.CameraTrackHandoffs.CountAsync());}
    [Fact]public async Task DuplicateIsAcknowledgedOnceAndChangedPayloadConflicts(){await using var db=CreateDb();var service=Service(db);var envelope=Envelope("evt-dup","idem-dup",Payload("person.entered","ENTRY",Now,.8m));var first=await service.ReceiveAsync(envelope);var duplicate=await service.ReceiveAsync(envelope);Assert.False(first.Duplicate);Assert.True(duplicate.Duplicate);Assert.Equal(1,await db.CameraOperationalEvents.CountAsync());var changed=Envelope("evt-dup","idem-dup",Payload("person.entered","ENTRY",Now,.9m));Assert.Equal(CameraTrackingFailureKind.Conflict,(await Assert.ThrowsAsync<CameraTrackingException>(()=>service.ReceiveAsync(changed))).Kind);}
    [Fact]public async Task InvalidAuthWrongTenantStoreAndIdentityFieldsAreRejected(){await using var db=CreateDb();var service=Service(db);var invalid=Envelope("evt-auth","idem-auth",Payload("person.entered","ENTRY",Now,.8m),"wrong");Assert.Equal(CameraTrackingFailureKind.Unauthorized,(await Assert.ThrowsAsync<CameraTrackingException>(()=>service.ReceiveAsync(invalid))).Kind);var wrongTenant=Payload("person.entered","ENTRY",Now,.8m,tenantId:tenant.Id+1);Assert.Equal(CameraTrackingFailureKind.Forbidden,(await Assert.ThrowsAsync<CameraTrackingException>(()=>service.ReceiveAsync(Envelope("evt-tenant","idem-tenant",wrongTenant)))).Kind);var wrongStore=Payload("person.entered","ENTRY",Now,.8m,storeId:store2.Id);Assert.Equal(CameraTrackingFailureKind.Forbidden,(await Assert.ThrowsAsync<CameraTrackingException>(()=>service.ReceiveAsync(Envelope("evt-store","idem-store",wrongStore)))).Kind);var identity=Encoding.UTF8.GetBytes($"{{\"contractVersion\":1,\"eventType\":\"person.entered\",\"tenantId\":{tenant.Id},\"storeId\":{store1.Id},\"cameraCode\":\"ENTRY\",\"personTrackId\":\"track-1\",\"occurredUtc\":\"{Now:O}\",\"confidence\":0.8,\"customerId\":99}}");Assert.Equal(CameraTrackingFailureKind.Validation,(await Assert.ThrowsAsync<CameraTrackingException>(()=>service.ReceiveAsync(Envelope("evt-identity","idem-identity",identity)))).Kind);}

    private CameraTrackingService Service(CustSearchDbContext db)=>new(db,user,secrets,new FixedClock(),Options.Create(new CctvSecurityOptions{AllowedClockSkewSeconds=300,MaximumBodyBytes=131072}));
    private static CctvInboundEnvelope Envelope(string eventId,string idempotency,byte[]body,string secret="phase13-secret"){var timestamp=new DateTimeOffset(Now).ToUnixTimeSeconds().ToString(CultureInfo.InvariantCulture);var serviceId="python-store-1";var canonical=Encoding.UTF8.GetBytes($"{serviceId}\n{timestamp}\n{eventId}\n{idempotency}\n").Concat(body).ToArray();var signature=Convert.ToHexString(HMACSHA256.HashData(Encoding.UTF8.GetBytes(secret),canonical)).ToLowerInvariant();return new(serviceId,timestamp,$"sha256={signature}",eventId,idempotency,body,"p13-correlation");}
    private byte[]Payload(string eventType,string cameraCode,DateTime occurred,decimal confidence,string?from=null,int?gap=null,long?tenantId=null,long?storeId=null)=>JsonSerializer.SerializeToUtf8Bytes(new{contractVersion=1,eventType,tenantId=tenantId??tenant.Id,storeId=storeId??store1.Id,cameraCode,personTrackId="track-1",occurredUtc=occurred,confidence,zoneCode=(string?)null,fromCameraCode=from,gapMilliseconds=gap,cameraStatus=(int?)null},WebJson);
    private static Store NewStore(long tenantId,string code,string name)=>Store.Create(tenantId,code,name,"1 Main Road",null,null,"Ahmedabad",null,"Gujarat","380001","IN",null,null,null,null,StoreLocationSource.Manual,"India Standard Time",null,null,Now);
    private CustSearchDbContext CreateDb()=>new(new DbContextOptionsBuilder<CustSearchDbContext>().UseSqlite(new SqliteConnectionStringBuilder{DataSource=databasePath,Cache=SqliteCacheMode.Shared,Mode=SqliteOpenMode.ReadWriteCreate,Pooling=false}.ToString()).Options);
    private sealed class FixedClock:TimeProvider{public override DateTimeOffset GetUtcNow()=>new(Now);}
    private sealed class FakeSecret:ICctvServiceSecretResolver{public CctvServiceCredential?Credential{get;set;}public ValueTask<CctvServiceCredential?>ResolveAsync(string serviceId,CancellationToken cancellationToken=default)=>ValueTask.FromResult(Credential);}
    private sealed class FakeCurrentUser:ICurrentUserContext{public long UserIdValue{get;set;}public long TenantIdValue{get;set;}public IReadOnlySet<long>StoreIdsValue{get;set;}=new HashSet<long>();public bool IsAuthenticated=>true;public long UserId=>UserIdValue;public long?TenantId=>TenantIdValue;public bool IsPlatformAdmin=>false;public string SecurityStamp=>"p13";public IReadOnlySet<string>Roles=>new HashSet<string>(["Manager"]);public IReadOnlySet<string>Permissions=>new HashSet<string>();public IReadOnlySet<long>StoreIds=>StoreIdsValue;}
}
