using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using CustSearch.Application.Authentication;
using CustSearch.Application.Integrations;
using CustSearch.Application.TenantOperations;
using CustSearch.Domain.Entities;
using CustSearch.Domain.Enums;
using CustSearch.Infrastructure.Integrations;
using CustSearch.Infrastructure.Persistence;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;

namespace CustSearch.IntegrationTests;

public sealed class PhaseTwelveIntegrationServiceTests:IAsyncLifetime
{
    private static readonly DateTime Now=new(2026,8,24,18,0,0,DateTimeKind.Utc);private readonly string databasePath=Path.Combine(Path.GetTempPath(),$"custsearch-p12-{Guid.NewGuid():N}.db");private Tenant tenant=null!;private IntegrationConfiguration configuration=null!;private readonly FakeSecrets secrets=new();
    public async Task InitializeAsync(){await using var db=CreateDb();await db.Database.EnsureCreatedAsync();tenant=Tenant.Create("P12","Phase Twelve Private Limited","Phase Twelve","Owner","owner@p12.test","9000000012","IN","India Standard Time","INR",10,30,10,Now);db.Tenants.Add(tenant);await db.SaveChangesAsync();configuration=IntegrationConfiguration.Create(tenant.Id,"Demo POS",IntegrationType.Bidirectional,true,"https://pos.example.test/hooks","credential-v1","signing-v1",10,3,5,Now);db.IntegrationConfigurations.Add(configuration);await db.SaveChangesAsync();secrets.Values["signing-v1"]="old-signing-secret";secrets.Values["credential-v1"]="credential-secret";}
    public Task DisposeAsync(){if(File.Exists(databasePath))File.Delete(databasePath);return Task.CompletedTask;}

    [Fact]public async Task ValidHmacCommitsOneReceiptAndDuplicateAcknowledgesWithoutMutation(){await using var db=CreateDb();var service=Inbound(db);var first=await service.ReceiveAsync(Request("evt-1","idem-1",Payload(),"old-signing-secret"));var duplicate=await service.ReceiveAsync(Request("evt-1","idem-1",Payload(),"old-signing-secret"));Assert.False(first.Duplicate);Assert.True(duplicate.Duplicate);Assert.Equal(first.InboundEventId,duplicate.InboundEventId);Assert.Equal(1,await db.IntegrationInboundEvents.CountAsync());Assert.Equal(1,await db.IntegrationDeliveryLogs.CountAsync());Assert.Equal(IntegrationInboundEventStatus.Processed,(await db.IntegrationInboundEvents.SingleAsync()).Status);}
    [Fact]public async Task InvalidHmacExpiredTimestampWrongTenantAndInvalidJsonAreRejected(){await using var db=CreateDb();var service=Inbound(db);var bad=Request("evt-bad","idem-bad",Payload(),"wrong");Assert.Equal(IntegrationFailureKind.Unauthorized,(await Assert.ThrowsAsync<IntegrationException>(()=>service.ReceiveAsync(bad))).Kind);var expired=Request("evt-old","idem-old",Payload(),"old-signing-secret",Now.AddMinutes(-6));Assert.Equal(IntegrationFailureKind.Unauthorized,(await Assert.ThrowsAsync<IntegrationException>(()=>service.ReceiveAsync(expired))).Kind);var wrongTenant=Request("evt-tenant","idem-tenant",Payload(),"old-signing-secret",tenantId:tenant.Id+1);Assert.Equal(IntegrationFailureKind.Forbidden,(await Assert.ThrowsAsync<IntegrationException>(()=>service.ReceiveAsync(wrongTenant))).Kind);var invalid=Request("evt-json","idem-json",Encoding.UTF8.GetBytes("{bad"),"old-signing-secret");Assert.Equal(IntegrationFailureKind.Validation,(await Assert.ThrowsAsync<IntegrationException>(()=>service.ReceiveAsync(invalid))).Kind);Assert.Equal(0,await db.IntegrationInboundEvents.CountAsync());}
    [Fact]public async Task OversizedBodyAndIdempotencyPayloadMismatchAreRejected(){await using var db=CreateDb();var service=Inbound(db,64);var oversized=new byte[65];Assert.Equal(IntegrationFailureKind.Validation,(await Assert.ThrowsAsync<IntegrationException>(()=>service.ReceiveAsync(Request("evt-size","idem-size",oversized,"old-signing-secret")))).Kind);var normal=Inbound(db);await normal.ReceiveAsync(Request("evt-same","idem-same",Payload(),"old-signing-secret"));var changed=Encoding.UTF8.GetBytes("{\"eventType\":\"invoice.updated\",\"contractVersion\":1,\"data\":{}}");Assert.Equal(IntegrationFailureKind.Conflict,(await Assert.ThrowsAsync<IntegrationException>(()=>normal.ReceiveAsync(Request("evt-same","idem-same",changed,"old-signing-secret")))).Kind);}
    [Fact]public async Task PreviousSigningReferenceWorksOnlyDuringRotationGrace(){await using(var db=CreateDb()){var tracked=await db.IntegrationConfigurations.SingleAsync();tracked.RotateReferences(null,"signing-v2",10,Now);await db.SaveChangesAsync();}secrets.Values["signing-v2"]="new-signing-secret";await using var verify=CreateDb();var service=Inbound(verify);var accepted=await service.ReceiveAsync(Request("evt-grace","idem-grace",Payload(),"old-signing-secret",Now.AddMinutes(1)));Assert.False(accepted.Duplicate);}
    [Fact]public async Task ManagementMasksReferencesAndRejectsSensitiveOutboundMetadata(){await using var db=CreateDb();var user=User();var service=new IntegrationManagementService(db,user,new MutableTimeProvider(Now));var view=await service.GetAsync(configuration.Id);Assert.True(view.HasCredentialReference);Assert.NotEqual("credential-v1",view.CredentialReferenceHint);Assert.DoesNotContain("credential-v1",view.CredentialReferenceHint!,StringComparison.Ordinal);var safe=await service.QueueOutboundAsync(new(configuration.Id,"invoice.created",1,"{\"invoiceId\":91}","queue:1","p12"));Assert.Equal(IntegrationOutboxStatus.Pending,safe.Status);var failure=await Assert.ThrowsAsync<IntegrationException>(()=>service.QueueOutboundAsync(new(configuration.Id,"invoice.created",1,"{\"accessToken\":\"forbidden\"}","queue:2","p12")));Assert.Equal(IntegrationFailureKind.Validation,failure.Kind);}
    [Fact]public async Task OutboxRetriesTransientFailureDeliversAndPermanentFailureCanBeRetriedManually(){await using var db=CreateDb();var clock=new MutableTimeProvider(Now);var management=new IntegrationManagementService(db,User(),clock);var transient=await management.QueueOutboundAsync(new(configuration.Id,"customer.created",1,"{\"customerId\":2}","out:transient","p12"));var transport=new FakeTransport(new(false,500,3,"server","Remote failed."),new(true,200,2,null,null));var processor=new IntegrationOutboxProcessor(db,transport,clock);var first=await processor.ProcessDueAsync();Assert.Equal(1,first.Failed);clock.Advance(TimeSpan.FromSeconds(5));var second=await processor.ProcessDueAsync();Assert.Equal(1,second.Delivered);Assert.Equal(2,(await db.IntegrationOutbox.SingleAsync(x=>x.Id==transient.Id)).AttemptCount);var permanent=await management.QueueOutboundAsync(new(configuration.Id,"customer.updated",1,"{\"customerId\":3}","out:permanent","p12"));transport.Results.Enqueue(new(false,400,1,"client","Rejected."));var third=await processor.ProcessDueAsync();Assert.Equal(1,third.DeadLettered);var retried=await management.RetryDeliveryAsync(permanent.Id,Audit());Assert.Equal(IntegrationOutboxStatus.Retrying,retried.Status);Assert.Equal(3,await db.IntegrationDeliveryLogs.CountAsync());}

    private CustSearchDbContext CreateDb()=>new(new DbContextOptionsBuilder<CustSearchDbContext>().UseSqlite(new SqliteConnectionStringBuilder{DataSource=databasePath,Cache=SqliteCacheMode.Shared,Mode=SqliteOpenMode.ReadWriteCreate}.ToString()).Options);
    private InboundIntegrationService Inbound(CustSearchDbContext db,int maximum=262144)=>new(db,secrets,new MutableTimeProvider(Now),Options.Create(new IntegrationSecurityOptions{AllowedClockSkewSeconds=300,MaximumInboundBodyBytes=maximum}));
    private InboundIntegrationRequest Request(string eventId,string idempotency,byte[]body,string secret,DateTime?timestamp=null,long?tenantId=null){var instant=new DateTimeOffset(timestamp??Now);var unix=instant.ToUnixTimeSeconds().ToString(CultureInfo.InvariantCulture);var signedTenant=(tenantId??tenant.Id).ToString(CultureInfo.InvariantCulture);var canonical=Encoding.UTF8.GetBytes($"{unix}\n{eventId}\n{idempotency}\n{signedTenant}\n").Concat(body).ToArray();var signature=Convert.ToHexString(HMACSHA256.HashData(Encoding.UTF8.GetBytes(secret),canonical)).ToLowerInvariant();return new(configuration.Id,signedTenant,unix,$"sha256={signature}",eventId,idempotency,body,"p12-correlation");}
    private static byte[]Payload()=>Encoding.UTF8.GetBytes("{\"eventType\":\"invoice.created\",\"contractVersion\":1,\"data\":{\"invoiceId\":91}}");
    private MutableCurrentUser User()=>new(){UserIdValue=1,TenantIdValue=tenant.Id};private static TenantAuditContext Audit()=>new(1,"127.0.0.1","Phase12Test","p12-correlation");
    private sealed class FakeSecrets:IIntegrationSecretResolver{public Dictionary<string,string>Values{get;}=new(StringComparer.Ordinal);public ValueTask<string?>ResolveAsync(string reference,CancellationToken cancellationToken=default)=>ValueTask.FromResult(Values.TryGetValue(reference,out var value)?value:null);}
    private sealed class MutableTimeProvider(DateTime utc):TimeProvider{private DateTimeOffset now=new(utc);public override DateTimeOffset GetUtcNow()=>now;public void Advance(TimeSpan value)=>now=now.Add(value);}
    private sealed class FakeTransport(params IntegrationTransportResult[]results):IIntegrationTransport{public Queue<IntegrationTransportResult>Results{get;}=new(results);public Task<IntegrationTransportResult>SendAsync(IntegrationTransportRequest request,CancellationToken cancellationToken=default)=>Task.FromResult(Results.Dequeue());}
    private sealed class MutableCurrentUser:ICurrentUserContext{public long UserIdValue{get;set;}public long?TenantIdValue{get;set;}public bool IsAuthenticated=>true;public long UserId=>UserIdValue;public long?TenantId=>TenantIdValue;public bool IsPlatformAdmin=>false;public string SecurityStamp=>"p12";public IReadOnlySet<string>Roles=>new HashSet<string>(["IntegrationAdmin"]);public IReadOnlySet<string>Permissions=>new HashSet<string>();public IReadOnlySet<long>StoreIds=>new HashSet<long>();}
}
