import { ChangeDetectionStrategy, Component, OnInit, inject, signal } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { AdminShell } from '../../shared/admin-shell/admin-shell';
import { SecurityApiService, SecurityIncidentDetail, SecurityIncidentSummary, SecurityReport, SecurityRule, SecuritySettings, SecurityStatus } from './security-api.service';

@Component({selector:'app-security-page',imports:[AdminShell,RouterLink],changeDetection:ChangeDetectionStrategy.OnPush,template:`
<app-admin-shell pageTitle="Retail security" eyebrow="Suspected Unpaid Exit review">
 <nav class="tabs"><a routerLink="/admin/security/dashboard">Dashboard</a><a routerLink="/admin/security/incidents">Incidents</a><a routerLink="/admin/security/settings">Settings</a><a routerLink="/admin/security/rules">Rules</a><a routerLink="/admin/security/reports">Reports</a></nav>
 <p class="notice"><b>AI suspicion is not proof.</b> Candidates are observations and risk signals. Only an authorized human may confirm a loss.</p>
 @if(error()){<p class="error" role="alert">{{error()}}</p>}
 @if(mode()==='dashboard'||mode()==='incidents'){
  <section class="cards"><article><b>{{incidents().length}}</b><span>Loaded candidates</span></article><article><b>{{highRisk()}}</b><span>High / critical risk</span></article><article><b>Shadow first</b><span>External escalation stays configured off during tuning</span></article></section>
  <section class="panel"><h2>Authorized store incidents</h2><table><thead><tr><th>Incident</th><th>Store</th><th>Risk</th><th>Severity</th><th>Status</th><th>Reviewer</th></tr></thead><tbody>@for(item of incidents();track item.id){<tr><td><a [routerLink]="['/admin/security/incidents',item.id]">{{item.incidentNumber}}</a></td><td>{{item.storeId}}</td><td>{{item.riskScore}}</td><td>{{severity(item.severity)}}</td><td>{{status(item.status)}}</td><td>{{item.assignedUserId??'Unassigned'}}</td></tr>}</tbody></table>@if(!incidents().length){<p>No security candidates in your authorized store scope.</p>}</section>
 }
 @if(mode()==='detail'&&detail();as value){<section class="detail-grid"><article class="panel"><h2>{{value.incident.incidentNumber}}</h2><dl><dt>Risk / severity</dt><dd>{{value.incident.riskScore}} / {{severity(value.incident.severity)}}</dd><dt>Status</dt><dd>{{status(value.incident.status)}}</dd><dt>Reviewer</dt><dd>{{value.incident.assignedUserId??'Unassigned'}}</dd><dt>Rule version</dt><dd>{{value.incident.ruleVersion}}</dd><dt>Resolution</dt><dd>{{value.incident.resolutionCode??'Pending human review'}}</dd></dl><div class="actions"><button (click)="act('review')">Start review</button><button (click)="act('confirm-loss')">Confirm loss</button><button (click)="act('false-positive')">False positive</button><button (click)="act('resolve')">Resolve</button></div></article><article class="panel"><h2>Payment correlation</h2>@for(payment of value.paymentCorrelations;track payment.id){<p>Invoice {{payment.invoiceId}} · score {{payment.matchScore}} · {{payment.notes}}</p>}@if(!value.paymentCorrelations.length){<p>No compatible paid invoice correlation.</p>}<h2>Product confidence</h2>@for(item of value.items;track item.id){<p>{{item.description}} · {{item.productConfidence??'unknown'}} · {{item.unitValue??'value unavailable'}}</p>}<h2>Evidence availability</h2>@for(evidence of value.evidence;track evidence.id){<p>Evidence {{evidence.id}} · {{evidence.available?'Available':'Expired'}} · retained to {{evidence.retentionUntilUtc}}</p>}@if(!value.evidence.length){<p>No evidence metadata available.</p>}</article></section><section class="panel"><h2>Audited timeline</h2>@for(action of value.timeline;track action.id){<p>{{action.occurredUtc}} · {{action.actorType}} · {{action.actionType}} · {{action.reasonCode??''}}</p>}</section>}
 @if(mode()==='settings'&&settings();as value){<section class="panel"><h2>Store security settings · version {{value.ruleVersion}}</h2><dl><dt>Security</dt><dd>{{value.securityEnabled?'Enabled':'Disabled'}}</dd><dt>Unpaid exit detection</dt><dd>{{value.unpaidExitDetectionEnabled?'Enabled':'Disabled'}}</dd><dt>Realtime alerts</dt><dd>{{value.realtimeAlertsEnabled?'Enabled':'Disabled'}}</dd><dt>Shadow Mode</dt><dd>{{value.shadowMode?'Enabled (recommended rollout)':'Disabled'}}</dd><dt>Risk threshold</dt><dd>{{value.riskThreshold}}</dd><dt>High value threshold</dt><dd>{{value.highValueThreshold}}</dd><dt>Checkout correlation</dt><dd>{{value.checkoutCorrelationWindowMinutes}} minutes</dd><dt>Exit grace</dt><dd>{{value.exitGracePeriodSeconds}} seconds</dd><dt>Evidence window</dt><dd>{{value.evidenceBeforeSeconds}}s before / {{value.evidenceAfterSeconds}}s after</dd><dt>Retention</dt><dd>{{value.evidenceRetentionDays}} days</dd><dt>Channels</dt><dd>{{value.notificationChannels.join(', ')||'In-app only when enabled'}}</dd><dt>Escalation</dt><dd>{{value.escalationPolicy}}</dd></dl></section>}
 @if(mode()==='rules'){<section class="panel"><h2>Effective versioned rules</h2>@for(rule of rules();track rule.id){<article><b>{{rule.ruleCode}} v{{rule.version}}</b><p>{{rule.name}} · {{rule.enabled?'Enabled':'Disabled'}} · severity {{severity(rule.severity)}}</p><code>{{rule.configurationJson}}</code></article>}</section>}
 @if(mode()==='reports'&&report();as value){<section class="cards"><article><b>{{value.candidateCount}}</b><span>Candidates</span></article><article><b>{{value.confirmedLossCount}}</b><span>Human-confirmed loss</span></article><article><b>{{value.falsePositiveCount}}</b><span>False positives</span></article><article><b>{{value.precision??'Not measured'}}</b><span>Measured precision</span></article></section>}
</app-admin-shell>`,styles:[`:host{display:block}.tabs{display:flex;flex-wrap:wrap;gap:.5rem;margin-bottom:1rem}.tabs a{background:var(--color-surface);border:1px solid var(--color-border);border-radius:var(--radius-sm);color:var(--color-text);padding:.6rem .8rem;text-decoration:none}.notice{background:#fff6d8;border-left:4px solid #d78b16;padding:1rem}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(12rem,1fr));gap:1rem;margin:1rem 0}.cards article,.panel{background:var(--color-surface);border:1px solid var(--color-border);border-radius:var(--radius-sm);padding:1rem}.cards article{display:grid;gap:.35rem}.cards b{font-size:1.3rem}.detail-grid{display:grid;grid-template-columns:1fr 1fr;gap:1rem}.panel{margin-bottom:1rem;overflow:auto}table{border-collapse:collapse;width:100%}th,td{border-bottom:1px solid var(--color-border);padding:.7rem;text-align:left}dl{display:grid;grid-template-columns:minmax(10rem,.5fr) 1fr;gap:.6rem}dd{margin:0}.actions{display:flex;flex-wrap:wrap;gap:.5rem}.actions button{background:var(--color-accent);border:0;border-radius:var(--radius-sm);color:var(--color-on-accent);padding:.65rem}.error{color:var(--color-danger)}code{overflow-wrap:anywhere}@media(max-width:800px){.detail-grid{grid-template-columns:1fr}}`],})
export class SecurityPage implements OnInit{
 private readonly route=inject(ActivatedRoute);private readonly api=inject(SecurityApiService);protected readonly mode=signal(String(this.route.snapshot.data['mode']??'dashboard'));protected readonly incidents=signal<SecurityIncidentSummary[]>([]);protected readonly detail=signal<SecurityIncidentDetail|null>(null);protected readonly settings=signal<SecuritySettings|null>(null);protected readonly rules=signal<SecurityRule[]>([]);protected readonly report=signal<SecurityReport|null>(null);protected readonly error=signal('');protected highRisk=()=>this.incidents().filter(x=>x.severity>=4).length;
 ngOnInit():void{const mode=this.mode();if(mode==='dashboard'||mode==='incidents')this.api.list().subscribe({next:x=>this.incidents.set(x),error:()=>this.fail()});else if(mode==='detail'){const id=Number(this.route.snapshot.paramMap.get('id'));this.api.detail(id).subscribe({next:x=>this.detail.set(x),error:()=>this.fail()});}else if(mode==='settings')this.api.settings().subscribe({next:x=>this.settings.set(x),error:()=>this.fail()});else if(mode==='rules')this.api.rules().subscribe({next:x=>this.rules.set(x),error:()=>this.fail()});else{const to=new Date();const from=new Date(to.getTime()-30*86400000);this.api.report(from.toISOString(),to.toISOString()).subscribe({next:x=>this.report.set(x),error:()=>this.fail()});}}
 protected act(action:'review'|'confirm-loss'|'false-positive'|'resolve'):void{const value=this.detail();if(!value)return;const reason=action==='confirm-loss'||action==='false-positive'?window.prompt('Authorized human review reason is required:','')??'':'';if((action==='confirm-loss'||action==='false-positive')&&!reason)return;this.api.transition(value.incident.id,action,reason).subscribe({next:x=>this.detail.set(x),error:()=>this.error.set('The state transition was rejected by the authoritative server.')});}
 protected status(value:SecurityStatus):string{return({1:'Observed',2:'Candidate',3:'Alerted',4:'Acknowledged',5:'Under review',6:'Confirmed loss',7:'False positive',8:'Resolved',9:'Archived'} as const)[value];}
 protected severity(value:number):string{return['','Info','Low','Medium','High','Critical'][value]??'Unknown';}
 private fail():void{this.error.set('Unable to load the authorized retail security view.');}
}
