using System.Globalization;
using System.Text.Json;
using CustSearch.Application.Authentication;
using CustSearch.Application.RetailBilling;
using CustSearch.Application.ShopperCustomers;
using CustSearch.Application.TenantOperations;
using CustSearch.Domain.Entities;
using CustSearch.Domain.Enums;
using CustSearch.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;

namespace CustSearch.Infrastructure.RetailBilling;

/// <summary>Phase 8 write/business service. TenantId and authorized StoreIds only come from authenticated server context.</summary>
public sealed class RetailBillingService(CustSearchDbContext db,IRetailBillingRepository repository,ICurrentUserContext currentUser,TimeProvider timeProvider):IRetailBillingService
{
    public async Task<PagedResult<ProductListItem>> SearchProductsAsync(ProductSearchQuery query,CancellationToken cancellationToken=default)
    {
        ArgumentNullException.ThrowIfNull(query);var tenantWide=IsTenantWide();EnsureStoreFilterAllowed(query.StoreId,tenantWide);var paging=PhaseSixAccessRules.NormalizePaging(query.PageNumber,query.PageSize);var q=query with{PageNumber=paging.PageNumber,PageSize=paging.PageSize};var rows=await repository.SearchProductsAsync(RequireTenantId(),currentUser.StoreIds,tenantWide,q,cancellationToken).ConfigureAwait(false);if(rows.Count==0)return PhaseEightPaging.Empty<ProductListItem>(q.PageNumber,q.PageSize);return new(rows.Select(x=>new ProductListItem(x.Id,x.ProductCode,x.Barcode,x.Name,x.CategoryId,x.CategoryName,x.Brand,x.UnitName,x.SalePrice,x.TaxPercent,x.IsActive)).ToArray(),q.PageNumber,q.PageSize,rows[0].TotalCount);
    }

    public async Task<ProductDetail> GetProductAsync(long productId,CancellationToken cancellationToken=default)=>await MapProductAsync(await RequireVisibleProductAsync(productId,false,cancellationToken).ConfigureAwait(false),cancellationToken).ConfigureAwait(false);

    public async Task<ProductDetail> CreateProductAsync(CreateProductCommand command,TenantAuditContext audit,CancellationToken cancellationToken=default)
    {
        ArgumentNullException.ThrowIfNull(command);ValidateAudit(audit);var tenantId=RequireTenantId();var stores=NormalizeIds(command.StoreIds);await ValidateCategoryAsync(command.CategoryId,cancellationToken).ConfigureAwait(false);await ValidateRequestedStoresAsync(stores,cancellationToken).ConfigureAwait(false);if(!IsTenantWide()&&stores.Length==0)throw new TenantBusinessRuleException("Store-scoped users must assign a new product to at least one authorized store.");
        var sku=command.ProductCode.Trim().ToUpperInvariant();if(await db.Products.AnyAsync(x=>x.TenantId==tenantId&&x.ProductCode==sku,cancellationToken).ConfigureAwait(false))throw new TenantBusinessRuleException("Product SKU already exists in this tenant.");if(!string.IsNullOrWhiteSpace(command.Barcode)&&await db.Products.AnyAsync(x=>x.TenantId==tenantId&&x.Barcode==command.Barcode.Trim(),cancellationToken).ConfigureAwait(false))throw new TenantBusinessRuleException("Product barcode already exists in this tenant.");
        Product product;try{product=Product.Create(tenantId,sku,command.Barcode,command.Name,command.Description,command.CategoryId,command.Brand,command.UnitName,command.SalePrice,command.CostPrice,command.TaxPercent,UtcNow());}catch(ArgumentException ex){throw new TenantBusinessRuleException(ex.Message);}
        await using var tx=await db.Database.BeginTransactionAsync(cancellationToken).ConfigureAwait(false);db.Products.Add(product);await db.SaveChangesAsync(cancellationToken).ConfigureAwait(false);foreach(var storeId in stores)db.ProductStoreAvailabilities.Add(ProductStoreAvailability.Create(tenantId,product.Id,storeId,true,UtcNow()));RecordAudit(tenantId,stores.FirstOrDefaultOrNull(),audit,"ProductCreated","Product",product.Id,null,new{product.ProductCode,product.Name,product.CategoryId,StoreIds=stores},UtcNow());await db.SaveChangesAsync(cancellationToken).ConfigureAwait(false);await tx.CommitAsync(cancellationToken).ConfigureAwait(false);return await MapProductAsync(product,cancellationToken).ConfigureAwait(false);
    }

    public async Task<ProductDetail> UpdateProductAsync(long productId,UpdateProductCommand command,TenantAuditContext audit,CancellationToken cancellationToken=default)
    {
        ArgumentNullException.ThrowIfNull(command);ValidateAudit(audit);var product=await RequireVisibleProductAsync(productId,true,cancellationToken).ConfigureAwait(false);await ValidateCategoryAsync(command.CategoryId,cancellationToken).ConfigureAwait(false);if(!string.IsNullOrWhiteSpace(command.Barcode)&&await db.Products.AnyAsync(x=>x.TenantId==RequireTenantId()&&x.Id!=productId&&x.Barcode==command.Barcode.Trim(),cancellationToken).ConfigureAwait(false))throw new TenantBusinessRuleException("Product barcode already exists in this tenant.");var before=new{product.Barcode,product.Name,product.CategoryId,product.SalePrice,product.CostPrice,product.TaxPercent,product.IsActive};try{product.Update(command.Barcode,command.Name,command.Description,command.CategoryId,command.Brand,command.UnitName,command.SalePrice,command.CostPrice,command.TaxPercent,command.IsActive,UtcNow());}catch(ArgumentException ex){throw new TenantBusinessRuleException(ex.Message);}RecordAudit(RequireTenantId(),null,audit,"ProductUpdated","Product",product.Id,before,new{product.Barcode,product.Name,product.CategoryId,product.SalePrice,product.CostPrice,product.TaxPercent,product.IsActive},UtcNow());await db.SaveChangesAsync(cancellationToken).ConfigureAwait(false);return await MapProductAsync(product,cancellationToken).ConfigureAwait(false);
    }

    public async Task<ProductDetail> SetProductStoresAsync(long productId,SetProductStoresCommand command,TenantAuditContext audit,CancellationToken cancellationToken=default)
    {
        ArgumentNullException.ThrowIfNull(command);ValidateAudit(audit);var tenantId=RequireTenantId();var product=await RequireVisibleProductAsync(productId,false,cancellationToken).ConfigureAwait(false);var requested=NormalizeIds(command.StoreIds);await ValidateRequestedStoresAsync(requested,cancellationToken).ConfigureAwait(false);if(!IsTenantWide()&&requested.Length==0)throw new TenantBusinessRuleException("Store-scoped users must keep at least one authorized product-store assignment.");var existing=await db.ProductStoreAvailabilities.Where(x=>x.TenantId==tenantId&&x.ProductId==productId).ToListAsync(cancellationToken).ConfigureAwait(false);var before=existing.Select(x=>new{x.StoreId,x.IsActive}).ToArray();
        if(IsTenantWide()){db.ProductStoreAvailabilities.RemoveRange(existing);foreach(var id in requested)db.ProductStoreAvailabilities.Add(ProductStoreAvailability.Create(tenantId,productId,id,true,UtcNow()));}
        else{var inScope=existing.Where(x=>currentUser.StoreIds.Contains(x.StoreId)).ToArray();db.ProductStoreAvailabilities.RemoveRange(inScope);foreach(var id in requested)db.ProductStoreAvailabilities.Add(ProductStoreAvailability.Create(tenantId,productId,id,true,UtcNow()));}
        RecordAudit(tenantId,requested.FirstOrDefaultOrNull(),audit,"ProductStoresChanged","Product",productId,before,new{StoreIds=requested},UtcNow());await db.SaveChangesAsync(cancellationToken).ConfigureAwait(false);return await MapProductAsync(product,cancellationToken).ConfigureAwait(false);
    }

    public async Task<PagedResult<RetailInvoiceListItem>> SearchInvoicesAsync(RetailInvoiceSearchQuery query,CancellationToken cancellationToken=default)
    {
        ArgumentNullException.ThrowIfNull(query);var tenantWide=IsTenantWide();EnsureStoreFilterAllowed(query.StoreId,tenantWide);var p=PhaseSixAccessRules.NormalizePaging(query.PageNumber,query.PageSize);var q=query with{PageNumber=p.PageNumber,PageSize=p.PageSize};var rows=await repository.SearchInvoicesAsync(RequireTenantId(),currentUser.StoreIds,tenantWide,q,cancellationToken).ConfigureAwait(false);if(rows.Count==0)return PhaseEightPaging.Empty<RetailInvoiceListItem>(q.PageNumber,q.PageSize);return new(rows.Select(x=>new RetailInvoiceListItem(x.Id,x.InvoiceNumber,x.StoreId,x.CustomerId,x.CustomerCode,x.CustomerName,x.InvoiceUtc,x.GrandTotal,x.PaidAmount,x.BalanceAmount,x.Status)).ToArray(),q.PageNumber,q.PageSize,rows[0].TotalCount);
    }

    public async Task<RetailInvoiceDetail> GetInvoiceAsync(long invoiceId,CancellationToken cancellationToken=default)=>await MapInvoiceAsync(await RequireVisibleInvoiceAsync(invoiceId,false,cancellationToken).ConfigureAwait(false),cancellationToken).ConfigureAwait(false);

    public async Task<RetailInvoiceDetail> CreateInvoiceAsync(CreateRetailInvoiceCommand command,TenantAuditContext audit,CancellationToken cancellationToken=default)
    {
        ArgumentNullException.ThrowIfNull(command);ValidateAudit(audit);if(command.Items is null||command.Items.Count==0)throw new TenantBusinessRuleException("Invoice requires at least one item.");var tenantId=RequireTenantId();await RequireAuthorizedStoreAsync(command.StoreId,cancellationToken).ConfigureAwait(false);await ValidateInvoiceLinksAsync(command.StoreId,command.CustomerId,command.HouseholdId,command.CustomerVisitId,command.VisitPartyId,cancellationToken).ConfigureAwait(false);var now=UtcNow();var invoice=RetailInvoice.Create(tenantId,command.StoreId,NewInvoiceNumber(now),command.CustomerId,command.HouseholdId,command.CustomerVisitId,command.VisitPartyId,audit.ActorUserId,now,command.Notes);
        await using var tx=await db.Database.BeginTransactionAsync(cancellationToken).ConfigureAwait(false);db.RetailInvoices.Add(invoice);await db.SaveChangesAsync(cancellationToken).ConfigureAwait(false);var items=await BuildItemsAsync(invoice.Id,command.StoreId,command.Items,cancellationToken).ConfigureAwait(false);db.RetailInvoiceItems.AddRange(items);ApplyTotals(invoice,items,now);RecordAudit(tenantId,command.StoreId,audit,"RetailInvoiceCreated","RetailInvoice",invoice.Id,null,new{invoice.InvoiceNumber,invoice.CustomerId,invoice.HouseholdId,ItemCount=items.Count,invoice.GrandTotal},now);await db.SaveChangesAsync(cancellationToken).ConfigureAwait(false);await tx.CommitAsync(cancellationToken).ConfigureAwait(false);return await MapInvoiceAsync(invoice,cancellationToken).ConfigureAwait(false);
    }

    public async Task<RetailInvoiceDetail> UpdateInvoiceAsync(long invoiceId,UpdateRetailInvoiceCommand command,TenantAuditContext audit,CancellationToken cancellationToken=default)
    {
        ArgumentNullException.ThrowIfNull(command);ValidateAudit(audit);if(command.Items is null||command.Items.Count==0)throw new TenantBusinessRuleException("Invoice requires at least one item.");var invoice=await RequireVisibleInvoiceAsync(invoiceId,true,cancellationToken).ConfigureAwait(false);if(invoice.Status!=RetailInvoiceStatus.Draft)throw new TenantBusinessRuleException("Only draft invoices can be edited.");await ValidateInvoiceLinksAsync(invoice.StoreId,command.CustomerId,command.HouseholdId,command.CustomerVisitId,command.VisitPartyId,cancellationToken).ConfigureAwait(false);var oldItems=await db.RetailInvoiceItems.Where(x=>x.TenantId==RequireTenantId()&&x.InvoiceId==invoiceId).ToListAsync(cancellationToken).ConfigureAwait(false);var oldIds=oldItems.Select(x=>x.Id).ToArray();var attrs=await db.RetailInvoiceItemAttributions.Where(x=>x.TenantId==RequireTenantId()&&x.InvoiceId==invoiceId&&oldIds.Contains(x.InvoiceItemId)).ToListAsync(cancellationToken).ConfigureAwait(false);
        await using var tx=await db.Database.BeginTransactionAsync(cancellationToken).ConfigureAwait(false);db.RetailInvoiceItemAttributions.RemoveRange(attrs);db.RetailInvoiceItems.RemoveRange(oldItems);invoice.UpdateDraftLinks(command.CustomerId,command.HouseholdId,command.CustomerVisitId,command.VisitPartyId,command.Notes,UtcNow());await db.SaveChangesAsync(cancellationToken).ConfigureAwait(false);var items=await BuildItemsAsync(invoice.Id,invoice.StoreId,command.Items,cancellationToken).ConfigureAwait(false);db.RetailInvoiceItems.AddRange(items);ApplyTotals(invoice,items,UtcNow());RecordAudit(RequireTenantId(),invoice.StoreId,audit,"RetailInvoiceUpdated","RetailInvoice",invoice.Id,new{ItemCount=oldItems.Count},new{ItemCount=items.Count,invoice.GrandTotal},UtcNow());await db.SaveChangesAsync(cancellationToken).ConfigureAwait(false);await tx.CommitAsync(cancellationToken).ConfigureAwait(false);return await MapInvoiceAsync(invoice,cancellationToken).ConfigureAwait(false);
    }

    public async Task<RetailInvoiceDetail> FinalizeInvoiceAsync(long invoiceId,TenantAuditContext audit,CancellationToken cancellationToken=default)
    {
        ValidateAudit(audit);var invoice=await RequireVisibleInvoiceAsync(invoiceId,true,cancellationToken).ConfigureAwait(false);if(!await db.RetailInvoiceItems.AnyAsync(x=>x.TenantId==RequireTenantId()&&x.InvoiceId==invoiceId,cancellationToken).ConfigureAwait(false))throw new TenantBusinessRuleException("Invoice has no items.");try{invoice.FinalizeInvoice(UtcNow());}catch(InvalidOperationException ex){throw new TenantBusinessRuleException(ex.Message);}RecordAudit(RequireTenantId(),invoice.StoreId,audit,"RetailInvoiceFinalized","RetailInvoice",invoice.Id,null,new{invoice.GrandTotal,invoice.Status},UtcNow());await db.SaveChangesAsync(cancellationToken).ConfigureAwait(false);return await MapInvoiceAsync(invoice,cancellationToken).ConfigureAwait(false);
    }

    public async Task<RetailInvoiceDetail> CancelInvoiceAsync(long invoiceId,string reason,TenantAuditContext audit,CancellationToken cancellationToken=default)
    {
        ValidateAudit(audit);var invoice=await RequireVisibleInvoiceAsync(invoiceId,true,cancellationToken).ConfigureAwait(false);try{invoice.Cancel(audit.ActorUserId,reason,UtcNow());}catch(InvalidOperationException ex){throw new TenantBusinessRuleException(ex.Message);}RecordAudit(RequireTenantId(),invoice.StoreId,audit,"RetailInvoiceCancelled","RetailInvoice",invoice.Id,null,new{invoice.Status,invoice.CancellationReason},UtcNow());await db.SaveChangesAsync(cancellationToken).ConfigureAwait(false);return await MapInvoiceAsync(invoice,cancellationToken).ConfigureAwait(false);
    }

    public async Task<RetailInvoiceDetail> AddPaymentAsync(long invoiceId,AddRetailPaymentCommand command,TenantAuditContext audit,CancellationToken cancellationToken=default)
    {
        ArgumentNullException.ThrowIfNull(command);ValidateAudit(audit);var invoice=await RequireVisibleInvoiceAsync(invoiceId,true,cancellationToken).ConfigureAwait(false);if(invoice.Status is RetailInvoiceStatus.Draft or RetailInvoiceStatus.Cancelled)throw new TenantBusinessRuleException("Payments require a finalized non-cancelled invoice.");if(command.Amount<=0||command.Amount>invoice.BalanceAmount)throw new TenantBusinessRuleException("Payment must be positive and cannot exceed invoice balance.");var reference=string.IsNullOrWhiteSpace(command.PaymentReference)?NewPaymentReference():command.PaymentReference.Trim();if(await db.RetailInvoicePayments.AnyAsync(x=>x.TenantId==RequireTenantId()&&x.PaymentReference==reference,cancellationToken).ConfigureAwait(false))throw new TenantBusinessRuleException("Payment reference already exists.");var payment=RetailInvoicePayment.Create(RequireTenantId(),invoice.StoreId,invoice.Id,reference,command.PaymentMethod,command.Amount,NormalizeUtc(command.PaymentUtc??UtcNow()),RetailPaymentStatus.Successful,command.ExternalTransactionId,command.Notes,audit.ActorUserId);
        await using var tx=await db.Database.BeginTransactionAsync(cancellationToken).ConfigureAwait(false);db.RetailInvoicePayments.Add(payment);await db.SaveChangesAsync(cancellationToken).ConfigureAwait(false);var paid=await db.RetailInvoicePayments.Where(x=>x.TenantId==RequireTenantId()&&x.InvoiceId==invoiceId&&x.Status==RetailPaymentStatus.Successful).SumAsync(x=>(decimal?)x.Amount,cancellationToken).ConfigureAwait(false)??0m;invoice.ApplyPaidAmount(paid,UtcNow());RecordAudit(RequireTenantId(),invoice.StoreId,audit,"RetailPaymentRecorded","RetailInvoicePayment",payment.Id,null,new{invoice.Id,payment.PaymentReference,payment.Amount,payment.PaymentMethod,invoice.PaidAmount,invoice.BalanceAmount},UtcNow());await db.SaveChangesAsync(cancellationToken).ConfigureAwait(false);await tx.CommitAsync(cancellationToken).ConfigureAwait(false);return await MapInvoiceAsync(invoice,cancellationToken).ConfigureAwait(false);
    }

    public async Task<RetailInvoiceDetail> SaveParticipantAsync(long invoiceId,SaveRetailParticipantCommand command,TenantAuditContext audit,CancellationToken cancellationToken=default)
    {
        ArgumentNullException.ThrowIfNull(command);ValidateAudit(audit);var invoice=await RequireVisibleInvoiceAsync(invoiceId,true,cancellationToken).ConfigureAwait(false);if(invoice.Status==RetailInvoiceStatus.Cancelled)throw new TenantBusinessRuleException("Cancelled invoice cannot be changed.");await RequireCustomerAtStoreAsync(command.CustomerId,invoice.StoreId,cancellationToken).ConfigureAwait(false);if(command.IsPayer&&await db.RetailInvoiceParticipants.AnyAsync(x=>x.TenantId==RequireTenantId()&&x.InvoiceId==invoiceId&&x.IsPayer&&x.CustomerId!=command.CustomerId,cancellationToken).ConfigureAwait(false))throw new TenantBusinessRuleException("Invoice can have only one explicit payer participant.");var existing=await db.RetailInvoiceParticipants.SingleOrDefaultAsync(x=>x.TenantId==RequireTenantId()&&x.InvoiceId==invoiceId&&x.CustomerId==command.CustomerId,cancellationToken).ConfigureAwait(false);if(existing is not null)db.RetailInvoiceParticipants.Remove(existing);db.RetailInvoiceParticipants.Add(RetailInvoiceParticipant.Create(RequireTenantId(),invoiceId,command.CustomerId,command.ParticipationType,command.IsPayer,UtcNow()));RecordAudit(RequireTenantId(),invoice.StoreId,audit,"RetailParticipantSaved","RetailInvoice",invoiceId,null,new{command.CustomerId,command.ParticipationType,command.IsPayer},UtcNow());await db.SaveChangesAsync(cancellationToken).ConfigureAwait(false);return await MapInvoiceAsync(invoice,cancellationToken).ConfigureAwait(false);
    }

    public async Task<RetailInvoiceDetail> SaveAttributionAsync(long invoiceId,SaveRetailAttributionCommand command,TenantAuditContext audit,CancellationToken cancellationToken=default)
    {
        ArgumentNullException.ThrowIfNull(command);ValidateAudit(audit);var invoice=await RequireVisibleInvoiceAsync(invoiceId,true,cancellationToken).ConfigureAwait(false);if(invoice.Status==RetailInvoiceStatus.Cancelled)throw new TenantBusinessRuleException("Cancelled invoice cannot be attributed.");var item=await db.RetailInvoiceItems.AsNoTracking().SingleOrDefaultAsync(x=>x.TenantId==RequireTenantId()&&x.InvoiceId==invoiceId&&x.Id==command.InvoiceItemId,cancellationToken).ConfigureAwait(false)??throw new TenantResourceNotFoundException("Invoice item");await RequireCustomerAtStoreAsync(command.CustomerId,invoice.StoreId,cancellationToken).ConfigureAwait(false);var existing=await db.RetailInvoiceItemAttributions.SingleOrDefaultAsync(x=>x.TenantId==RequireTenantId()&&x.InvoiceItemId==command.InvoiceItemId&&x.CustomerId==command.CustomerId,cancellationToken).ConfigureAwait(false);var otherTotal=await db.RetailInvoiceItemAttributions.Where(x=>x.TenantId==RequireTenantId()&&x.InvoiceItemId==command.InvoiceItemId&&x.CustomerId!=command.CustomerId).SumAsync(x=>(decimal?)x.AmountAttributed,cancellationToken).ConfigureAwait(false)??0m;if(otherTotal+command.AmountAttributed>item.LineTotal)throw new TenantBusinessRuleException("Attributed amount cannot exceed the invoice item total.");if(command.QuantityAttributed.HasValue&&command.QuantityAttributed.Value>item.Quantity)throw new TenantBusinessRuleException("Attributed quantity cannot exceed item quantity.");if(existing is not null)db.RetailInvoiceItemAttributions.Remove(existing);db.RetailInvoiceItemAttributions.Add(RetailInvoiceItemAttribution.Create(RequireTenantId(),invoiceId,command.InvoiceItemId,command.CustomerId,command.AttributionType,command.QuantityAttributed,command.AmountAttributed,command.Source,audit.ActorUserId,UtcNow()));RecordAudit(RequireTenantId(),invoice.StoreId,audit,"RetailSpendAttributed","RetailInvoiceItem",command.InvoiceItemId,null,new{command.CustomerId,command.AmountAttributed,command.QuantityAttributed,command.Source},UtcNow());await db.SaveChangesAsync(cancellationToken).ConfigureAwait(false);return await MapInvoiceAsync(invoice,cancellationToken).ConfigureAwait(false);
    }

    public async Task<CustomerPurchaseHistory> GetCustomerPurchaseHistoryAsync(long customerId,int recentCount=10,CancellationToken cancellationToken=default){await RequireVisibleCustomerAsync(customerId,cancellationToken).ConfigureAwait(false);return await repository.GetCustomerPurchaseHistoryAsync(RequireTenantId(),currentUser.StoreIds,IsTenantWide(),customerId,recentCount,cancellationToken).ConfigureAwait(false);}
    public async Task<HouseholdPurchaseSummary> GetHouseholdPurchaseSummaryAsync(long householdId,CancellationToken cancellationToken=default){await RequireVisibleHouseholdAsync(householdId,cancellationToken).ConfigureAwait(false);return await repository.GetHouseholdPurchaseSummaryAsync(RequireTenantId(),currentUser.StoreIds,IsTenantWide(),householdId,cancellationToken).ConfigureAwait(false);}
    public async Task<RetailSalesSummary> GetSalesSummaryAsync(long? storeId,DateTime? fromUtc,DateTime? toUtc,CancellationToken cancellationToken=default){EnsureStoreFilterAllowed(storeId,IsTenantWide());return await repository.GetSalesSummaryAsync(RequireTenantId(),currentUser.StoreIds,IsTenantWide(),storeId,fromUtc,toUtc,cancellationToken).ConfigureAwait(false);}
    public async Task<IReadOnlyList<RetailBreakdownItem>> GetSalesByProductAsync(long? storeId,DateTime? fromUtc,DateTime? toUtc,int top=20,CancellationToken cancellationToken=default){EnsureStoreFilterAllowed(storeId,IsTenantWide());return await repository.GetSalesByProductAsync(RequireTenantId(),currentUser.StoreIds,IsTenantWide(),storeId,fromUtc,toUtc,top,cancellationToken).ConfigureAwait(false);}
    public async Task<IReadOnlyList<RetailBreakdownItem>> GetSalesByCategoryAsync(long? storeId,DateTime? fromUtc,DateTime? toUtc,int top=20,CancellationToken cancellationToken=default){EnsureStoreFilterAllowed(storeId,IsTenantWide());return await repository.GetSalesByCategoryAsync(RequireTenantId(),currentUser.StoreIds,IsTenantWide(),storeId,fromUtc,toUtc,top,cancellationToken).ConfigureAwait(false);}
    public async Task<IReadOnlyList<RetailPaymentSummaryItem>> GetPaymentSummaryAsync(long? storeId,DateTime? fromUtc,DateTime? toUtc,CancellationToken cancellationToken=default){EnsureStoreFilterAllowed(storeId,IsTenantWide());return await repository.GetPaymentSummaryAsync(RequireTenantId(),currentUser.StoreIds,IsTenantWide(),storeId,fromUtc,toUtc,cancellationToken).ConfigureAwait(false);}

    private async Task<Product> RequireVisibleProductAsync(long id,bool tracked,CancellationToken ct)
    {
        var tenantId=RequireTenantId();var q=db.Products.Where(x=>x.TenantId==tenantId&&x.Id==id);var product=await(tracked?q:q.AsNoTracking()).SingleOrDefaultAsync(ct).ConfigureAwait(false)??throw new TenantResourceNotFoundException("Product");if(!IsTenantWide()){var anyAssignments=await db.ProductStoreAvailabilities.AsNoTracking().AnyAsync(x=>x.TenantId==tenantId&&x.ProductId==id&&x.IsActive,ct).ConfigureAwait(false);if(anyAssignments&&!await db.ProductStoreAvailabilities.AsNoTracking().AnyAsync(x=>x.TenantId==tenantId&&x.ProductId==id&&x.IsActive&&currentUser.StoreIds.Contains(x.StoreId),ct).ConfigureAwait(false))throw new TenantResourceNotFoundException("Product");}return product;
    }
    private async Task<RetailInvoice> RequireVisibleInvoiceAsync(long id,bool tracked,CancellationToken ct){var q=db.RetailInvoices.Where(x=>x.TenantId==RequireTenantId()&&x.Id==id);var invoice=await(tracked?q:q.AsNoTracking()).SingleOrDefaultAsync(ct).ConfigureAwait(false)??throw new TenantResourceNotFoundException("Retail invoice");if(!PhaseSixAccessRules.CanAccessStore(invoice.StoreId,currentUser.StoreIds,IsTenantWide()))throw new TenantResourceNotFoundException("Retail invoice");return invoice;}
    private async Task RequireAuthorizedStoreAsync(long storeId,CancellationToken ct){if(!PhaseSixAccessRules.CanAccessStore(storeId,currentUser.StoreIds,IsTenantWide()))throw new TenantResourceNotFoundException("Store");if(!await db.Stores.AsNoTracking().AnyAsync(x=>x.TenantId==RequireTenantId()&&x.Id==storeId&&x.IsActive,ct).ConfigureAwait(false))throw new TenantResourceNotFoundException("Store");}
    private async Task ValidateRequestedStoresAsync(long[] ids,CancellationToken ct){foreach(var id in ids)await RequireAuthorizedStoreAsync(id,ct).ConfigureAwait(false);}
    private async Task ValidateCategoryAsync(long categoryId,CancellationToken ct){var c=await db.ProductCategories.AsNoTracking().SingleOrDefaultAsync(x=>x.TenantId==RequireTenantId()&&x.Id==categoryId&&x.IsActive,ct).ConfigureAwait(false)??throw new TenantResourceNotFoundException("Product category");if(c.StoreId.HasValue&&!PhaseSixAccessRules.CanAccessStore(c.StoreId.Value,currentUser.StoreIds,IsTenantWide()))throw new TenantResourceNotFoundException("Product category");}
    private async Task RequireCustomerAtStoreAsync(long customerId,long storeId,CancellationToken ct){if(!await db.Customers.AsNoTracking().AnyAsync(x=>x.TenantId==RequireTenantId()&&x.Id==customerId&&x.IsActive,ct).ConfigureAwait(false))throw new TenantResourceNotFoundException("Customer");if(!await db.CustomerStoreAssignments.AsNoTracking().AnyAsync(x=>x.TenantId==RequireTenantId()&&x.CustomerId==customerId&&x.StoreId==storeId,ct).ConfigureAwait(false))throw new TenantBusinessRuleException("Customer is not assigned to the invoice store.");}
    private async Task RequireVisibleCustomerAsync(long customerId,CancellationToken ct){var exists=await db.Customers.AsNoTracking().AnyAsync(x=>x.TenantId==RequireTenantId()&&x.Id==customerId,ct).ConfigureAwait(false);if(!exists)throw new TenantResourceNotFoundException("Customer");if(!IsTenantWide()&&!await db.CustomerStoreAssignments.AsNoTracking().AnyAsync(x=>x.TenantId==RequireTenantId()&&x.CustomerId==customerId&&currentUser.StoreIds.Contains(x.StoreId),ct).ConfigureAwait(false))throw new TenantResourceNotFoundException("Customer");}
    private async Task RequireVisibleHouseholdAsync(long householdId,CancellationToken ct){if(!await db.Households.AsNoTracking().AnyAsync(x=>x.TenantId==RequireTenantId()&&x.Id==householdId,ct).ConfigureAwait(false))throw new TenantResourceNotFoundException("Household");if(!IsTenantWide()&&!await db.HouseholdMembers.AsNoTracking().AnyAsync(m=>m.TenantId==RequireTenantId()&&m.HouseholdId==householdId&&m.IsActive&&db.CustomerStoreAssignments.Any(cs=>cs.TenantId==RequireTenantId()&&cs.CustomerId==m.CustomerId&&currentUser.StoreIds.Contains(cs.StoreId)),ct).ConfigureAwait(false))throw new TenantResourceNotFoundException("Household");}

    private async Task ValidateInvoiceLinksAsync(long storeId,long? customerId,long? householdId,long? visitId,long? partyId,CancellationToken ct)
    {
        if(customerId.HasValue)await RequireCustomerAtStoreAsync(customerId.Value,storeId,ct).ConfigureAwait(false);if(householdId.HasValue){await RequireVisibleHouseholdAsync(householdId.Value,ct).ConfigureAwait(false);if(customerId.HasValue&&!await db.HouseholdMembers.AsNoTracking().AnyAsync(x=>x.TenantId==RequireTenantId()&&x.HouseholdId==householdId&&x.CustomerId==customerId&&x.IsActive&&x.IsVerified,ct).ConfigureAwait(false))throw new TenantBusinessRuleException("Customer is not an active verified member of the selected household.");}
        if(visitId.HasValue){var v=await db.CustomerVisits.AsNoTracking().SingleOrDefaultAsync(x=>x.TenantId==RequireTenantId()&&x.Id==visitId&&x.StoreId==storeId,ct).ConfigureAwait(false)??throw new TenantBusinessRuleException("Customer visit is invalid or belongs to another store/tenant.");if(customerId.HasValue&&v.CustomerId!=customerId.Value)throw new TenantBusinessRuleException("Customer visit belongs to a different customer.");}
        if(partyId.HasValue&&!await db.VisitParties.AsNoTracking().AnyAsync(x=>x.TenantId==RequireTenantId()&&x.Id==partyId&&x.StoreId==storeId,ct).ConfigureAwait(false))throw new TenantBusinessRuleException("Visit party is invalid or belongs to another store/tenant.");
    }

    private async Task<List<RetailInvoiceItem>> BuildItemsAsync(long invoiceId,long storeId,IReadOnlyList<RetailInvoiceItemInput> inputs,CancellationToken ct)
    {
        var tenantId=RequireTenantId();var ids=inputs.Select(x=>x.ProductId).Distinct().ToArray();var products=await db.Products.AsNoTracking().Where(x=>x.TenantId==tenantId&&ids.Contains(x.Id)&&x.IsActive).Select(x=>new{x.Id,x.ProductCode,x.Name,x.CategoryId,CategoryName=x.Category.Name,x.SalePrice,x.TaxPercent}).ToListAsync(ct).ConfigureAwait(false);if(products.Count!=ids.Length)throw new TenantBusinessRuleException("One or more products are unavailable.");var restricted=await db.ProductStoreAvailabilities.AsNoTracking().Where(x=>x.TenantId==tenantId&&ids.Contains(x.ProductId)&&x.IsActive).GroupBy(x=>x.ProductId).Select(g=>new{ProductId=g.Key,Allowed=g.Any(x=>x.StoreId==storeId)}).ToListAsync(ct).ConfigureAwait(false);if(restricted.Any(x=>!x.Allowed))throw new TenantBusinessRuleException("One or more products are not available in the invoice store.");var byId=products.ToDictionary(x=>x.Id);var result=new List<RetailInvoiceItem>();foreach(var input in inputs){if(input.Quantity<=0)throw new TenantBusinessRuleException("Invoice item quantity must be positive.");var p=byId[input.ProductId];try{result.Add(RetailInvoiceItem.Create(tenantId,invoiceId,p.Id,p.CategoryId,p.ProductCode,p.Name,p.CategoryName,input.Quantity,p.SalePrice,input.DiscountAmount,p.TaxPercent??0m,UtcNow()));}catch(ArgumentException ex){throw new TenantBusinessRuleException(ex.Message);}}return result;
    }
    private static void ApplyTotals(RetailInvoice invoice,IReadOnlyCollection<RetailInvoiceItem> items,DateTime now){var subtotal=items.Sum(x=>x.LineSubtotal);var discount=items.Sum(x=>x.DiscountAmount);var tax=items.Sum(x=>x.TaxAmount);var total=items.Sum(x=>x.LineTotal);invoice.SetCalculatedTotals(subtotal,discount,tax,total,now);}

    private async Task<ProductDetail> MapProductAsync(Product p,CancellationToken ct){var category=await db.ProductCategories.AsNoTracking().Where(x=>x.TenantId==p.TenantId&&x.Id==p.CategoryId).Select(x=>x.Name).SingleAsync(ct).ConfigureAwait(false);var stores=await db.ProductStoreAvailabilities.AsNoTracking().Where(x=>x.TenantId==p.TenantId&&x.ProductId==p.Id&&(IsTenantWide()||currentUser.StoreIds.Contains(x.StoreId))).OrderBy(x=>x.StoreId).Select(x=>new ProductStoreView(x.StoreId,x.IsActive)).ToArrayAsync(ct).ConfigureAwait(false);return new(p.Id,p.ProductCode,p.Barcode,p.Name,p.Description,p.CategoryId,category,p.Brand,p.UnitName,p.SalePrice,p.CostPrice,p.TaxPercent,p.IsActive,stores,p.CreatedUtc,p.UpdatedUtc);}
    private async Task<RetailInvoiceDetail> MapInvoiceAsync(RetailInvoice i,CancellationToken ct)
    {
        var tenantId=RequireTenantId();var items=await db.RetailInvoiceItems.AsNoTracking().Where(x=>x.TenantId==tenantId&&x.InvoiceId==i.Id).OrderBy(x=>x.Id).Select(x=>new RetailInvoiceItemView(x.Id,x.ProductId,x.ProductCodeSnapshot,x.ProductNameSnapshot,x.CategoryId,x.CategoryNameSnapshot,x.Quantity,x.UnitPrice,x.DiscountAmount,x.TaxPercent,x.TaxAmount,x.LineSubtotal,x.LineTotal)).ToArrayAsync(ct).ConfigureAwait(false);var payments=await db.RetailInvoicePayments.AsNoTracking().Where(x=>x.TenantId==tenantId&&x.InvoiceId==i.Id).OrderBy(x=>x.PaymentUtc).Select(x=>new RetailPaymentView(x.Id,x.PaymentReference,x.PaymentMethod,x.Amount,x.PaymentUtc,x.Status,x.ExternalTransactionId,x.Notes,x.ReceivedByUserId)).ToArrayAsync(ct).ConfigureAwait(false);var participants=await db.RetailInvoiceParticipants.AsNoTracking().Where(x=>x.TenantId==tenantId&&x.InvoiceId==i.Id).OrderByDescending(x=>x.IsPayer).Select(x=>new RetailParticipantView(x.CustomerId,x.Customer.CustomerCode,FullName(x.Customer.FirstName,x.Customer.LastName),x.ParticipationType,x.IsPayer)).ToArrayAsync(ct).ConfigureAwait(false);var attrs=await db.RetailInvoiceItemAttributions.AsNoTracking().Where(x=>x.TenantId==tenantId&&x.InvoiceId==i.Id).OrderBy(x=>x.Id).Select(x=>new RetailAttributionView(x.Id,x.InvoiceItemId,x.CustomerId,x.Customer.CustomerCode,FullName(x.Customer.FirstName,x.Customer.LastName),x.AttributionType,x.QuantityAttributed,x.AmountAttributed,x.Source,x.CreatedByUserId,x.CreatedUtc)).ToArrayAsync(ct).ConfigureAwait(false);var attributed=attrs.Sum(x=>x.AmountAttributed);return new(i.Id,i.InvoiceNumber,i.StoreId,i.CustomerId,i.HouseholdId,i.CustomerVisitId,i.VisitPartyId,i.InvoiceUtc,i.Subtotal,i.DiscountAmount,i.TaxAmount,i.GrandTotal,i.PaidAmount,i.BalanceAmount,i.Status,i.Notes,items,payments,participants,attrs,attributed,Math.Max(0,i.GrandTotal-attributed),i.CreatedUtc,i.UpdatedUtc,i.CancelledUtc,i.CancellationReason);
    }

    private void RecordAudit(long tenantId,long? storeId,TenantAuditContext audit,string action,string entityType,long entityId,object? before,object? after,DateTime now)=>db.AuditLogs.Add(AuditLog.Record(tenantId,storeId,audit.ActorUserId,"TenantUser",action,entityType,entityId.ToString(CultureInfo.InvariantCulture),before is null?null:JsonSerializer.Serialize(before),after is null?null:JsonSerializer.Serialize(after),audit.IpAddress,audit.UserAgent,audit.CorrelationId,now));
    private static void ValidateAudit(TenantAuditContext audit){ArgumentNullException.ThrowIfNull(audit);ArgumentOutOfRangeException.ThrowIfNegativeOrZero(audit.ActorUserId);ArgumentException.ThrowIfNullOrWhiteSpace(audit.CorrelationId);}
    private void EnsureStoreFilterAllowed(long? storeId,bool tenantWide){if(storeId.HasValue&&!PhaseSixAccessRules.CanAccessStore(storeId.Value,currentUser.StoreIds,tenantWide))throw new TenantResourceNotFoundException("Store");}
    private bool IsTenantWide()=>PhaseSixAccessRules.IsTenantWide(currentUser.Roles);private long RequireTenantId()=>currentUser.TenantId is>0 and var id?id:throw new UnauthorizedAccessException("Tenant context is required.");private DateTime UtcNow()=>timeProvider.GetUtcNow().UtcDateTime;
    private static long[] NormalizeIds(IReadOnlyList<long>? ids)=>(ids??[]).Where(x=>x>0).Distinct().OrderBy(x=>x).ToArray();private static DateTime NormalizeUtc(DateTime value)=>value.Kind switch{DateTimeKind.Utc=>value,DateTimeKind.Local=>value.ToUniversalTime(),_=>DateTime.SpecifyKind(value,DateTimeKind.Utc)};
    private static string NewInvoiceNumber(DateTime now)=>$"INV-{now:yyyyMMdd}-{Guid.NewGuid():N}"[..27].ToUpperInvariant();private static string NewPaymentReference()=>$"PAY-{Guid.NewGuid():N}"[..24].ToUpperInvariant();private static string FullName(string first,string? last)=>string.IsNullOrWhiteSpace(last)?first:$"{first} {last}";
}

internal static class PhaseEightCollectionExtensions
{
    public static long? FirstOrDefaultOrNull(this IReadOnlyCollection<long> source)=>source.Count==0?null:source.First();
}
