import { CommonModule } from '@angular/common';
import { HttpErrorResponse } from '@angular/common/http';
import { ChangeDetectionStrategy, Component, OnInit, computed, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { AdminShell } from '../../shared/admin-shell/admin-shell';
import { AuthSessionService } from '../../core/auth/auth-session.service';
import { PERMISSIONS } from '../../core/auth/permission-catalog';
import { AuditLogPage, OperationsApiService, SystemHealth, SystemSetting } from './operations-api.service';

@Component({selector:'app-operations-page',standalone:true,imports:[CommonModule,FormsModule,AdminShell],changeDetection:ChangeDetectionStrategy.OnPush,
styles:[`:host{display:block}.wrap{padding:1.5rem}.panel{background:var(--color-surface);border:1px solid var(--color-border);border-radius:var(--radius-sm);padding:1rem;margin-top:1rem}.filters,.actions,.health{display:flex;gap:.7rem;flex-wrap:wrap}.health>div{border:1px solid var(--color-border);border-radius:var(--radius-sm);padding:1rem;min-width:10rem}input,select,button{min-height:2.5rem;border:1px solid var(--color-border);border-radius:var(--radius-sm);padding:.5rem;background:var(--color-background);color:var(--color-text)}button{background:var(--color-accent);color:var(--color-on-accent);font-weight:700}.table{overflow:auto}table{border-collapse:collapse;min-width:100%}th,td{padding:.55rem;border-bottom:1px solid var(--color-border);text-align:left}.error{color:var(--color-danger)}.muted{color:var(--color-muted)}@media(max-width:700px){.filters>*{width:100%}}`],
template:`<app-admin-shell><main class="wrap"><h1>{{title()}}</h1><p class="muted">Operational data is server-authorized; tenant identity is never accepted from this page.</p>@if(error()){<p class="error" role="alert">{{error()}}</p>}@if(message()){<p role="status">{{message()}}</p>}
@if(mode==='settings'){<section class="panel"><div class="filters">@if(!platform){<input type="number" min="1" [(ngModel)]="storeId" placeholder="Store override ID (optional)"><button (click)="loadSettings()">Load scope</button>}</div><div class="table"><table><thead><tr><th>Setting</th><th>Source</th><th>Value</th><th>Description</th><th></th></tr></thead><tbody>@for(item of settings();track item.settingKey){<tr><td>{{item.settingKey}}</td><td>{{item.sourceScope}}</td><td>@if(item.valueType===1){<select [(ngModel)]="item.settingValue" [disabled]="!canSave(item)"><option value="true">true</option><option value="false">false</option></select>}@else{<input [(ngModel)]="item.settingValue" [disabled]="!canSave(item)" [type]="item.valueType===4?'text':'number'">}</td><td>{{item.description}}</td><td><button [disabled]="!canSave(item)" (click)="save(item)">Save {{platform?'platform':storeId?'store':'tenant'}} override</button></td></tr>}@empty{<tr><td colspan="5">No settings available.</td></tr>}</tbody></table></div></section>}
@if(mode==='audit'){<section class="panel"><div class="filters">@if(!platform){<input type="number" min="1" [(ngModel)]="storeId" placeholder="Store ID (optional)">}<input [(ngModel)]="action" placeholder="Exact action"><input [(ngModel)]="entityType" placeholder="Exact entity type"><button (click)="loadAudit(1)">Search</button></div><div class="table"><table><thead><tr><th>UTC</th><th>Scope</th><th>Actor</th><th>Action</th><th>Entity</th><th>Correlation</th></tr></thead><tbody>@for(item of audit()?.items??[];track item.id){<tr><td>{{item.createdUtc|date:'medium'}}</td><td>{{item.tenantId??'Platform'}} / {{item.storeId??'All'}}</td><td>{{item.userId??item.actorType}}</td><td>{{item.action}}</td><td>{{item.entityType}} {{item.entityId??''}}</td><td>{{item.correlationId}}</td></tr>}@empty{<tr><td colspan="6">No audit entries.</td></tr>}</tbody></table></div>@if(audit();as page){<div class="actions"><button [disabled]="page.pageNumber<=1" (click)="loadAudit(page.pageNumber-1)">Previous</button><span>Page {{page.pageNumber}} · {{page.totalCount}} total</span><button [disabled]="page.pageNumber*page.pageSize>=page.totalCount" (click)="loadAudit(page.pageNumber+1)">Next</button></div>}</section>}
@if(mode==='health'){@if(health();as h){<section class="panel health"><div><b>API</b><p>{{h.apiStatus}}</p></div><div><b>SQL Server</b><p>{{h.core.database.status}}</p><small>{{h.core.database.productVersion}}</small></div><div><b>Worker</b><p>{{workerStatus(h)}}</p></div><div><b>Redis</b><p>{{h.redisStatus}}</p></div><div><b>SignalR</b><p>{{h.signalRStatus}}</p><small>{{h.activeWebSocketConnections}} active</small></div><div><b>Redis backplane</b><p>{{h.redisBackplaneStatus}}</p></div><div><b>Python AI</b><p>{{h.pythonAiStatus}}</p></div><div><b>Cameras</b><p>{{h.core.cameras.onlineCameras}} / {{h.core.cameras.totalCameras}} online</p></div></section><section class="panel"><h2>Queues</h2><p>Reports {{h.core.queues.reportQueueDepth}} · Webhooks {{h.core.queues.webhookQueueDepth}} · Notifications {{h.core.queues.notificationQueueDepth}} · Realtime events {{h.core.queues.reportEventBacklog}}</p></section>}<button (click)="loadHealth()">Refresh health</button>}</main></app-admin-shell>`})
export class OperationsPage implements OnInit{
  private readonly api=inject(OperationsApiService);private readonly route=inject(ActivatedRoute);private readonly session=inject(AuthSessionService);protected readonly platform=this.route.snapshot.data['platform']===true;protected readonly mode=this.route.snapshot.data['mode'] as 'settings'|'audit'|'health';protected readonly settings=signal<SystemSetting[]>([]);protected readonly audit=signal<AuditLogPage|null>(null);protected readonly health=signal<SystemHealth|null>(null);protected readonly error=signal('');protected readonly message=signal('');protected readonly canManage=computed(()=>this.session.hasPermission(this.platform?PERMISSIONS.platformSettingsManage:PERMISSIONS.settingsManage));protected storeId:number|undefined;protected action='';protected entityType='';
  ngOnInit():void{if(this.mode==='settings')this.loadSettings();else if(this.mode==='audit')this.loadAudit(1);else this.loadHealth();}
  protected title():string{return this.mode==='health'?'System health':this.mode==='audit'?'Audit logs':'Operational settings';}
  protected loadSettings():void{this.clear();this.api.settings(this.platform,this.storeId).subscribe({next:x=>this.settings.set(x),error:e=>this.fail(e)});}
  protected save(item:SystemSetting):void{this.clear();this.api.save(this.platform,item,this.storeId).subscribe({next:x=>{this.settings.update(items=>items.map(i=>i.settingKey===x.settingKey?x:i));this.message.set('Setting saved and audited.');},error:e=>this.fail(e)});}
  protected loadAudit(pageNumber:number):void{this.clear();this.api.audit(this.platform,{storeId:this.storeId,action:this.action.trim()||undefined,entityType:this.entityType.trim()||undefined,pageNumber,pageSize:50}).subscribe({next:x=>this.audit.set(x),error:e=>this.fail(e)});}
  protected loadHealth():void{this.clear();this.api.health().subscribe({next:x=>this.health.set(x),error:e=>this.fail(e)});}
  protected workerStatus(h:SystemHealth):string{return h.core.workers.length===0?'Offline':h.core.workers.some(x=>x.healthStatus==='Offline')?'Offline':h.core.workers.some(x=>x.healthStatus==='Warning')?'Warning':'Healthy';}
  protected canSave(item:SystemSetting):boolean{return this.canManage()&&(this.platform||item.settingKey!=='AutoLinkHouseholdFromFaceSimilarity');}
  private clear(){this.error.set('');this.message.set('');}private fail(error:unknown){this.error.set(error instanceof HttpErrorResponse?(error.error?.detail??error.message):'Operational request failed.');}
}
