using System.Globalization;
using System.IO.Compression;
using System.Text;
using CustSearch.Application.ReportsExports;
using CustSearch.Domain.Enums;
using Microsoft.Extensions.Options;

namespace CustSearch.Infrastructure.ReportsExports;

/// <summary>Local private export store. Only opaque server paths are persisted; API callers never provide paths.</summary>
public sealed class LocalExportFileStore:IExportFileStore
{
    private readonly string root;
    public LocalExportFileStore(IOptions<ReportsExportsOptions>options){root=Path.GetFullPath(options.Value.StoragePath);Directory.CreateDirectory(root);}
    public async Task<StoredExportFile>SaveAsync(long jobId,ExportFormat format,ReportResultView report,CancellationToken ct=default){ArgumentOutOfRangeException.ThrowIfNegativeOrZero(jobId);var extension=format switch{ExportFormat.Csv=>"csv",ExportFormat.Excel=>"xlsx",ExportFormat.Pdf=>"pdf",_=>throw new ReportExportException("Export format is invalid.",ReportExportFailureKind.Validation)};var fileName=$"report-{jobId}.{extension}";var path=Resolve($"{jobId}-{Guid.NewGuid():N}.{extension}");var bytes=format switch{ExportFormat.Csv=>Csv(report),ExportFormat.Excel=>Excel(report),ExportFormat.Pdf=>Pdf(report),_=>[]};await File.WriteAllBytesAsync(path,bytes,ct).ConfigureAwait(false);var contentType=format switch{ExportFormat.Csv=>"text/csv",ExportFormat.Excel=>"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",ExportFormat.Pdf=>"application/pdf",_=>"application/octet-stream"};return new(path,fileName,contentType);}
    public Task<Stream>OpenReadAsync(string path,CancellationToken ct=default){ct.ThrowIfCancellationRequested();var resolved=ResolveExisting(path);Stream stream=new FileStream(resolved,FileMode.Open,FileAccess.Read,FileShare.Read,4096,FileOptions.Asynchronous|FileOptions.SequentialScan);return Task.FromResult(stream);}
    public Task DeleteAsync(string path,CancellationToken ct=default){ct.ThrowIfCancellationRequested();var resolved=ResolveExisting(path);File.Delete(resolved);return Task.CompletedTask;}
    private string Resolve(string name){var value=Path.GetFullPath(Path.Combine(root,name));if(!value.StartsWith(root+Path.DirectorySeparatorChar,StringComparison.Ordinal))throw new ReportExportException("Export path is invalid.",ReportExportFailureKind.Forbidden);return value;}
    private string ResolveExisting(string path){var value=Path.GetFullPath(path);if(!value.StartsWith(root+Path.DirectorySeparatorChar,StringComparison.Ordinal)||!File.Exists(value))throw new ReportExportException("Export file was not found.",ReportExportFailureKind.NotFound);return value;}
    private static byte[]Csv(ReportResultView report){var builder=new StringBuilder("Domain,StoreId,Metric,Value,Label,OccurredUtc\r\n");foreach(var row in report.Rows)builder.Append(Escape(row.Domain)).Append(',').Append(row.StoreId?.ToString(CultureInfo.InvariantCulture)).Append(',').Append(Escape(row.Metric)).Append(',').Append(row.Value.ToString(CultureInfo.InvariantCulture)).Append(',').Append(Escape(row.Label)).Append(',').Append(row.OccurredUtc?.ToString("O",CultureInfo.InvariantCulture)).Append("\r\n");return new UTF8Encoding(true).GetBytes(builder.ToString());}
    private static byte[]Excel(ReportResultView report){using var output=new MemoryStream();using(var zip=new ZipArchive(output,ZipArchiveMode.Create,true)){Write(zip,"[Content_Types].xml","<?xml version=\"1.0\" encoding=\"UTF-8\"?><Types xmlns=\"http://schemas.openxmlformats.org/package/2006/content-types\"><Default Extension=\"rels\" ContentType=\"application/vnd.openxmlformats-package.relationships+xml\"/><Default Extension=\"xml\" ContentType=\"application/xml\"/><Override PartName=\"/xl/workbook.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml\"/><Override PartName=\"/xl/worksheets/sheet1.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml\"/></Types>");Write(zip,"_rels/.rels","<?xml version=\"1.0\" encoding=\"UTF-8\"?><Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument\" Target=\"xl/workbook.xml\"/></Relationships>");Write(zip,"xl/workbook.xml","<?xml version=\"1.0\" encoding=\"UTF-8\"?><workbook xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\" xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\"><sheets><sheet name=\"Report\" sheetId=\"1\" r:id=\"rId1\"/></sheets></workbook>");Write(zip,"xl/_rels/workbook.xml.rels","<?xml version=\"1.0\" encoding=\"UTF-8\"?><Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet\" Target=\"worksheets/sheet1.xml\"/></Relationships>");var sheet=new StringBuilder("<?xml version=\"1.0\" encoding=\"UTF-8\"?><worksheet xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\"><sheetData>");sheet.Append(Row(["Domain","StoreId","Metric","Value","Label","OccurredUtc"]));foreach(var row in report.Rows)sheet.Append(Row([row.Domain,row.StoreId?.ToString(CultureInfo.InvariantCulture)??string.Empty,row.Metric,row.Value.ToString(CultureInfo.InvariantCulture),row.Label??string.Empty,row.OccurredUtc?.ToString("O",CultureInfo.InvariantCulture)??string.Empty]));sheet.Append("</sheetData></worksheet>");Write(zip,"xl/worksheets/sheet1.xml",sheet.ToString());}return output.ToArray();}
    private static byte[]Pdf(ReportResultView report){var lines=new List<string>{$"CustSearch report: {report.ReportType}",$"UTC range: {report.FromUtc:O} - {report.ToUtc:O}","Domain | Store | Metric | Value | Label"};lines.AddRange(report.Rows.Select(x=>$"{x.Domain} | {x.StoreId} | {x.Metric} | {x.Value.ToString(CultureInfo.InvariantCulture)} | {x.Label}"));var pages=lines.Chunk(45).ToArray();var fontId=3+pages.Length*2;var objects=new List<string>{$"<< /Type /Catalog /Pages 2 0 R >>",$"<< /Type /Pages /Kids [{string.Join(' ',Enumerable.Range(0,pages.Length).Select(i=>$"{3+i*2} 0 R"))}] /Count {pages.Length} >>"};for(var i=0;i<pages.Length;i++){var pageId=3+i*2;var contentId=pageId+1;objects.Add($"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 {fontId} 0 R >> >> /Contents {contentId} 0 R >>");var commands=new StringBuilder("BT /F1 9 Tf 40 760 Td 12 TL ");foreach(var line in pages[i])commands.Append('(').Append(PdfText(line)).Append(") Tj T* ");commands.Append("ET");var command=commands.ToString();objects.Add($"<< /Length {Encoding.ASCII.GetByteCount(command)} >>\nstream\n{command}\nendstream");}objects.Add("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>");using var stream=new MemoryStream();WriteAscii(stream,"%PDF-1.4\n");var offsets=new List<long>{0};for(var i=0;i<objects.Count;i++){offsets.Add(stream.Position);WriteAscii(stream,$"{i+1} 0 obj\n{objects[i]}\nendobj\n");}var xref=stream.Position;WriteAscii(stream,$"xref\n0 {objects.Count+1}\n0000000000 65535 f \n");foreach(var offset in offsets.Skip(1))WriteAscii(stream,$"{offset:0000000000} 00000 n \n");WriteAscii(stream,$"trailer << /Size {objects.Count+1} /Root 1 0 R >>\nstartxref\n{xref}\n%%EOF");return stream.ToArray();}
    private static string Escape(string?value){var v=value??string.Empty;return v.IndexOfAny([',','"','\r','\n'])>=0?$"\"{v.Replace("\"","\"\"",StringComparison.Ordinal)}\"":v;}
    private static string Row(IEnumerable<string>values)=>$"<row>{string.Concat(values.Select(x=>$"<c t=\"inlineStr\"><is><t>{Xml(x)}</t></is></c>"))}</row>";
    private static string Xml(string value)=>System.Security.SecurityElement.Escape(value)??string.Empty;
    private static string PdfText(string value)=>new string(value.Select(x=>x is>=' ' and<='~'?x:'?').ToArray()).Replace("\\","\\\\",StringComparison.Ordinal).Replace("(","\\(",StringComparison.Ordinal).Replace(")","\\)",StringComparison.Ordinal);
    private static void Write(ZipArchive zip,string path,string content){var entry=zip.CreateEntry(path,CompressionLevel.Fastest);using var writer=new StreamWriter(entry.Open(),new UTF8Encoding(false));writer.Write(content);}
    private static void WriteAscii(Stream stream,string value){var bytes=Encoding.ASCII.GetBytes(value);stream.Write(bytes);}
}
