using System.Globalization;
using System.IO.Compression;
using System.Security.Cryptography;
using System.Text;
using System.Xml;
using CustSearch.Application.ReportsExports;
using Microsoft.Extensions.Options;

namespace CustSearch.Infrastructure.ReportsExports;

public sealed class ReportExportOptions
{
    public const string SectionName="ReportExports";
    public string StorageRoot{get;set;}="report-exports";
    public int RetentionHours{get;set;}=24;
    public int PollIntervalSeconds{get;set;}=2;
    public int LeaseSeconds{get;set;}=300;
    public int CleanupIntervalSeconds{get;set;}=60;
    public int CleanupBatchSize{get;set;}=100;
}

/// <summary>Writes private opaque report artifacts. Browser file names and paths never control storage.</summary>
public sealed class ReportArtifactStore(IOptions<ReportExportOptions>options):IReportArtifactStore
{
    private readonly string root=ResolveRoot(options.Value.StorageRoot);
    public async Task<ReportArtifactMetadata>WriteAsync(long jobId,ReportExportFormat format,ReportDataView data,CancellationToken ct=default)
    {
        ArgumentOutOfRangeException.ThrowIfNegativeOrZero(jobId);ArgumentNullException.ThrowIfNull(data);Directory.CreateDirectory(root);var token=Convert.ToHexString(RandomNumberGenerator.GetBytes(24)).ToLowerInvariant();var extension=format switch{ReportExportFormat.Csv=>"csv",ReportExportFormat.Excel=>"xlsx",ReportExportFormat.Pdf=>"pdf",_=>throw new ReportExportBusinessRuleException("Export format is invalid.")};var key=$"{jobId}-{token}.{extension}";var path=ResolveKey(key);await using(var stream=new FileStream(path,FileMode.CreateNew,FileAccess.Write,FileShare.None,65536,FileOptions.Asynchronous|FileOptions.SequentialScan)){switch(format){case ReportExportFormat.Csv:await WriteCsvAsync(stream,data,ct).ConfigureAwait(false);break;case ReportExportFormat.Excel:await WriteXlsxAsync(stream,data,ct).ConfigureAwait(false);break;case ReportExportFormat.Pdf:await WritePdfAsync(stream,data,ct).ConfigureAwait(false);break;}}await using var read=new FileStream(path,FileMode.Open,FileAccess.Read,FileShare.Read,65536,FileOptions.Asynchronous|FileOptions.SequentialScan);var hash=Convert.ToHexString(await SHA256.HashDataAsync(read,ct).ConfigureAwait(false)).ToLowerInvariant();var contentType=format switch{ReportExportFormat.Csv=>"text/csv; charset=utf-8",ReportExportFormat.Excel=>"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",_=>"application/pdf"};return new(key,$"report-{jobId}.{extension}",contentType,read.Length,hash);
    }
    public Task<Stream>OpenReadAsync(string storageReference,CancellationToken ct=default){ct.ThrowIfCancellationRequested();var path=ResolveKey(storageReference);if(!File.Exists(path))throw new ReportExportNotFoundException("Report artifact was not found.");return Task.FromResult<Stream>(new FileStream(path,FileMode.Open,FileAccess.Read,FileShare.Read,65536,FileOptions.Asynchronous|FileOptions.SequentialScan));}
    public Task DeleteAsync(string storageReference,CancellationToken ct=default){ct.ThrowIfCancellationRequested();var path=ResolveKey(storageReference);if(File.Exists(path))File.Delete(path);return Task.CompletedTask;}
    private static async Task WriteCsvAsync(Stream stream,ReportDataView data,CancellationToken ct){await using var writer=new StreamWriter(stream,new UTF8Encoding(true),65536,true);await writer.WriteLineAsync(string.Join(',',data.Columns.Select(Csv))).ConfigureAwait(false);foreach(var row in data.Rows){ct.ThrowIfCancellationRequested();await writer.WriteLineAsync(string.Join(',',data.Columns.Select(c=>Csv(Value(row.TryGetValue(c,out var value)?value:null))))).ConfigureAwait(false);}await writer.FlushAsync(ct).ConfigureAwait(false);}
    private static string Csv(string value){var safe=NeutralizeFormula(value);return $"\"{safe.Replace("\"","\"\"",StringComparison.Ordinal)}\"";}
    private static async Task WriteXlsxAsync(Stream stream,ReportDataView data,CancellationToken ct){using var zip=new ZipArchive(stream,ZipArchiveMode.Create,true);await Entry(zip,"[Content_Types].xml","<?xml version=\"1.0\" encoding=\"UTF-8\"?><Types xmlns=\"http://schemas.openxmlformats.org/package/2006/content-types\"><Default Extension=\"rels\" ContentType=\"application/vnd.openxmlformats-package.relationships+xml\"/><Default Extension=\"xml\" ContentType=\"application/xml\"/><Override PartName=\"/xl/workbook.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml\"/><Override PartName=\"/xl/worksheets/sheet1.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml\"/></Types>",ct);await Entry(zip,"_rels/.rels","<?xml version=\"1.0\"?><Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument\" Target=\"xl/workbook.xml\"/></Relationships>",ct);await Entry(zip,"xl/workbook.xml","<?xml version=\"1.0\"?><workbook xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\" xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\"><sheets><sheet name=\"Report\" sheetId=\"1\" r:id=\"rId1\"/></sheets></workbook>",ct);await Entry(zip,"xl/_rels/workbook.xml.rels","<?xml version=\"1.0\"?><Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet\" Target=\"worksheets/sheet1.xml\"/></Relationships>",ct);var sheet=zip.CreateEntry("xl/worksheets/sheet1.xml",CompressionLevel.Optimal);await using var output=sheet.Open();await using var writer=XmlWriter.Create(output,new XmlWriterSettings{Async=true,Encoding=new UTF8Encoding(false),CloseOutput=false});await writer.WriteStartDocumentAsync();await writer.WriteStartElementAsync(null,"worksheet","http://schemas.openxmlformats.org/spreadsheetml/2006/main");await writer.WriteStartElementAsync(null,"sheetData",null);await XlsxRow(writer,data.Columns.Cast<object?>());foreach(var row in data.Rows){ct.ThrowIfCancellationRequested();await XlsxRow(writer,data.Columns.Select(c=>row.TryGetValue(c,out var v)?v:null));}await writer.WriteEndElementAsync();await writer.WriteEndElementAsync();await writer.WriteEndDocumentAsync();await writer.FlushAsync();}
    private static async Task XlsxRow(XmlWriter writer,IEnumerable<object?>values){await writer.WriteStartElementAsync(null,"row",null);foreach(var value in values){await writer.WriteStartElementAsync(null,"c",null);await writer.WriteAttributeStringAsync(null,"t",null,"inlineStr");await writer.WriteStartElementAsync(null,"is",null);await writer.WriteElementStringAsync(null,"t",null,NeutralizeFormula(Value(value)));await writer.WriteEndElementAsync();await writer.WriteEndElementAsync();}await writer.WriteEndElementAsync();}
    private static async Task Entry(ZipArchive zip,string name,string content,CancellationToken ct){var entry=zip.CreateEntry(name,CompressionLevel.Optimal);await using var output=entry.Open();await using var writer=new StreamWriter(output,new UTF8Encoding(false),4096,true);await writer.WriteAsync(content.AsMemory(),ct).ConfigureAwait(false);}
    private static async Task WritePdfAsync(Stream stream,ReportDataView data,CancellationToken ct){var lines=new List<string>{string.Join(" | ",data.Columns)};lines.AddRange(data.Rows.Select(row=>string.Join(" | ",data.Columns.Select(c=>Value(row.TryGetValue(c,out var v)?v:null)))));const int perPage=45;var pages=lines.Chunk(perPage).ToArray();if(pages.Length==0)pages=[Array.Empty<string>()];var objects=new List<byte[]>();var fontId=3+pages.Length*2;objects.Add(Ascii("<< /Type /Catalog /Pages 2 0 R >>"));objects.Add(Ascii($"<< /Type /Pages /Count {pages.Length} /Kids [{string.Join(' ',Enumerable.Range(0,pages.Length).Select(i=>$"{3+i*2} 0 R"))}] >>"));for(var i=0;i<pages.Length;i++){var pageId=3+i*2;var contentId=pageId+1;objects.Add(Ascii($"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 842 595] /Resources << /Font << /F1 {fontId} 0 R >> >> /Contents {contentId} 0 R >>"));var body=new StringBuilder("BT /F1 7 Tf 28 565 Td 0 -12 Td ");foreach(var line in pages[i])body.Append('(').Append(Pdf(line.Length>160?line[..160]:line)).Append(") Tj 0 -12 Td ");body.Append("ET");var bytes=Ascii(body.ToString());objects.Add(Ascii($"<< /Length {bytes.Length} >>\nstream\n{Encoding.ASCII.GetString(bytes)}\nendstream"));}objects.Add(Ascii("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>"));using var buffer=new MemoryStream();await buffer.WriteAsync(Ascii("%PDF-1.4\n"),ct);var offsets=new List<long>{0};for(var i=0;i<objects.Count;i++){offsets.Add(buffer.Position);await buffer.WriteAsync(Ascii($"{i+1} 0 obj\n"),ct);await buffer.WriteAsync(objects[i],ct);await buffer.WriteAsync(Ascii("\nendobj\n"),ct);}var xref=buffer.Position;await buffer.WriteAsync(Ascii($"xref\n0 {objects.Count+1}\n0000000000 65535 f \n"),ct);for(var i=1;i<offsets.Count;i++)await buffer.WriteAsync(Ascii($"{offsets[i]:0000000000} 00000 n \n"),ct);await buffer.WriteAsync(Ascii($"trailer << /Size {objects.Count+1} /Root 1 0 R >>\nstartxref\n{xref}\n%%EOF"),ct);buffer.Position=0;await buffer.CopyToAsync(stream,ct).ConfigureAwait(false);}
    private static byte[]Ascii(string value)=>Encoding.ASCII.GetBytes(value);
    private static string Pdf(string value)=>new string(value.Select(ch=>ch is>=(' ') and<=('~')?ch:'?').ToArray()).Replace("\\","\\\\",StringComparison.Ordinal).Replace("(","\\(",StringComparison.Ordinal).Replace(")","\\)",StringComparison.Ordinal);
    private static string Value(object?value)=>value switch{null=>string.Empty,DateTime date=>date.ToUniversalTime().ToString("O",CultureInfo.InvariantCulture),DateTimeOffset date=>date.ToUniversalTime().ToString("O",CultureInfo.InvariantCulture),IFormattable f=>f.ToString(null,CultureInfo.InvariantCulture)??string.Empty,_=>value.ToString()??string.Empty};
    private static string NeutralizeFormula(string value)=>value.Length>0&&value[0] is '=' or '+' or '-' or '@'?"'"+value:value;
    private static string ResolveRoot(string configured){var root=Path.IsPathRooted(configured)?configured:Path.Combine(Directory.GetCurrentDirectory(),configured);return Path.GetFullPath(root);}
    private string ResolveKey(string key){if(string.IsNullOrWhiteSpace(key)||key.IndexOfAny([Path.DirectorySeparatorChar,Path.AltDirectorySeparatorChar])>=0||key.Contains("..",StringComparison.Ordinal))throw new ReportExportNotFoundException("Report artifact was not found.");var path=Path.GetFullPath(Path.Combine(root,key));if(!path.StartsWith(root+Path.DirectorySeparatorChar,StringComparison.OrdinalIgnoreCase))throw new ReportExportNotFoundException("Report artifact was not found.");return path;}
}
