using System.Globalization;
using System.Text.Json;
using CustSearch.Application.AlertsRealtime;
using CustSearch.Application.Authentication;
using CustSearch.Application.Authorization;
using CustSearch.Application.ReportsExports;
using CustSearch.Application.TenantOperations;
using CustSearch.Domain.Entities;
using CustSearch.Domain.Enums;
using CustSearch.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;

namespace CustSearch.Infrastructure.ReportsExports;

/// <summary>
/// Orchestrates bounded tenant/platform reports and asynchronous exports. Tenant/store filters come
/// from the authenticated context and generated downloads remain requester-bound and short-lived.
/// </summary>
public sealed class ReportsExportsService(CustSearchDbContext db,ICurrentUserContext currentUser,IReportQueryRepository queries,IExportFileStore files,IExportDownloadTokenService tokens,TimeProvider clock,IOptions<ReportsExportsOptions>options):IReportsExportsService
{
    private static readonly JsonSerializerOptions JsonOptions=new(JsonSerializerDefaults.Web);private readonly ReportsExportsOptions settings=options.Value;
    private static readonly ReportCatalogItem[]Items=[new(ReportType.OperationalSummary,"operational-summary","Operational summary",ReportScope.Tenant,PermissionCatalog.Operations.ReportsView,true),new(ReportType.Customers,"customers","Customers",ReportScope.Tenant,PermissionCatalog.Operations.ReportsView,true),new(ReportType.Households,"households","Households",ReportScope.Tenant,PermissionCatalog.Operations.ReportsView,true),new(ReportType.Visits,"visits","Visits",ReportScope.Tenant,PermissionCatalog.Operations.ReportsView,true),new(ReportType.RetailBilling,"retail-billing","Retail billing",ReportScope.Tenant,PermissionCatalog.Operations.ReportsView,true),new(ReportType.Preferences,"preferences","Preferences",ReportScope.Tenant,PermissionCatalog.Operations.ReportsView,true),new(ReportType.Alerts,"alerts","Alerts",ReportScope.Tenant,PermissionCatalog.Operations.ReportsView,true),new(ReportType.Integrations,"integrations","Integrations",ReportScope.Tenant,PermissionCatalog.Operations.ReportsView,true),new(ReportType.Cameras,"cameras","Cameras",ReportScope.Tenant,PermissionCatalog.Operations.ReportsView,true),new(ReportType.StaffOperations,"staff-operations","Staff operational analytics",ReportScope.Tenant,PermissionCatalog.Operations.ReportsView,true),new(ReportType.PlatformTenants,"platform-tenants","Platform tenant operations",ReportScope.Platform,PermissionCatalog.Platform.ReportsView,true)];
    public IReadOnlyList<ReportCatalogItem>Catalog()=>Items.Where(x=>currentUser.Permissions.Contains(x.RequiredPermission)&&(currentUser.IsPlatformAdmin)==(x.Scope==ReportScope.Platform)).ToArray();
    public Task<ReportResultView>RunAsync(ReportType reportType,ReportFilter filter,CancellationToken ct=default){var item=RequireCatalog(reportType,false);var normalized=filter.Normalize();return item.Scope==ReportScope.Platform?queries.QueryPlatformAsync(reportType,normalized,ct):queries.QueryTenantAsync(RequireTenant(),reportType,AuthorizedStores(normalized.StoreIds),normalized,ct);}
    public async Task<ExportJobView>QueueAsync(QueueExportCommand command,TenantAuditContext audit,CancellationToken ct=default){ArgumentNullException.ThrowIfNull(command);ArgumentNullException.ThrowIfNull(audit);var item=RequireCatalog(command.ReportType,true);var filter=command.Filter.Normalize();var tenant=item.Scope==ReportScope.Tenant?RequireTenant():(long?)null;var stores=item.Scope==ReportScope.Tenant?AuthorizedStores(filter.StoreIds):[];var now=clock.GetUtcNow().UtcDateTime;var safeFilter=filter with{StoreIds=stores};var job=ExportJob.Queue(currentUser.UserId,tenant,command.ReportType,command.Format,JsonSerializer.Serialize(safeFilter,JsonOptions),JsonSerializer.Serialize(stores,JsonOptions),now,now.AddHours(settings.RetentionHours));await using var transaction=await db.Database.BeginTransactionAsync(ct).ConfigureAwait(false);db.ExportJobs.Add(job);await db.SaveChangesAsync(ct).ConfigureAwait(false);if(tenant.HasValue){var alert=Alert.Create(tenant.Value,null,"Export",AlertSeverity.Info,$"Export {job.Id} queued","Your export is queued for asynchronous processing.","ExportJob",job.Id.ToString(CultureInfo.InvariantCulture),audit.CorrelationId,$"export:{job.Id}",now);db.Alerts.Add(alert);await db.SaveChangesAsync(ct).ConfigureAwait(false);job.LinkAlert(alert.Id);await QueueEventAsync(alert,"export.created",audit.CorrelationId,now,ct).ConfigureAwait(false);}Audit(audit,tenant,null,"ExportQueued","ExportJob",job.Id,new{job.Id,job.ReportType,job.Format,StoreCount=stores.Length,job.ExpiresUtc},now);await db.SaveChangesAsync(ct).ConfigureAwait(false);await transaction.CommitAsync(ct).ConfigureAwait(false);return Map(job,now);}
    public async Task<IReadOnlyList<ExportJobView>>ListJobsAsync(CancellationToken ct=default){RequireView();var now=clock.GetUtcNow().UtcDateTime;return await VisibleJobs().OrderByDescending(x=>x.CreatedUtc).Take(200).Select(x=>new ExportJobView(x.Id,x.TenantId,x.RequestedByUserId,x.ReportType,x.Format,x.Status,x.Progress,x.CreatedUtc,x.StartedUtc,x.CompletedUtc,x.ExpiresUtc,x.Error,x.AttemptCount,x.Status==ExportJobStatus.Completed&&x.ExpiresUtc>now&&x.FilePath!=null)).ToListAsync(ct).ConfigureAwait(false);}
    public async Task<ExportJobView>GetJobAsync(long jobId,CancellationToken ct=default){var job=await RequireJob(jobId,ct).ConfigureAwait(false);return Map(job,clock.GetUtcNow().UtcDateTime);}
    public async Task<ExportJobView>RetryAsync(long jobId,TenantAuditContext audit,CancellationToken ct=default){RequireExport();var job=await RequireJob(jobId,ct).ConfigureAwait(false);try{job.Retry(clock.GetUtcNow().UtcDateTime);}catch(InvalidOperationException ex){throw new ReportExportException(ex.Message,ReportExportFailureKind.Conflict);}Audit(audit,job.TenantId,null,"ExportRetried","ExportJob",job.Id,new{job.Id,job.AttemptCount},clock.GetUtcNow().UtcDateTime);await db.SaveChangesAsync(ct).ConfigureAwait(false);return Map(job,clock.GetUtcNow().UtcDateTime);}
    public async Task<ExportDownloadTicketView>CreateDownloadTicketAsync(long jobId,TenantAuditContext audit,CancellationToken ct=default){RequireExport();var job=await RequireJob(jobId,ct).ConfigureAwait(false);var now=clock.GetUtcNow().UtcDateTime;if(job.Status!=ExportJobStatus.Completed||job.ExpiresUtc<=now||job.FilePath is null)throw new ReportExportException("Export is unavailable or expired.",ReportExportFailureKind.Conflict);var ticket=tokens.Create(job.Id,currentUser.UserId,job.TenantId,now.AddMinutes(settings.DownloadTicketMinutes));Audit(audit,job.TenantId,null,"ExportDownloadTicketCreated","ExportJob",job.Id,new{job.Id,ticket.ExpiresUtc},now);await db.SaveChangesAsync(ct).ConfigureAwait(false);return ticket;}
    public async Task<ExportDownloadFile>OpenDownloadAsync(long jobId,string token,TenantAuditContext audit,CancellationToken ct=default){RequireExport();var job=await RequireJob(jobId,ct).ConfigureAwait(false);var now=clock.GetUtcNow().UtcDateTime;tokens.Validate(token,job.Id,currentUser.UserId,job.TenantId,now);if(job.Status!=ExportJobStatus.Completed||job.ExpiresUtc<=now||job.FilePath is null||job.FileName is null||job.ContentType is null)throw new ReportExportException("Export is unavailable or expired.",ReportExportFailureKind.Conflict);var stream=await files.OpenReadAsync(job.FilePath,ct).ConfigureAwait(false);Audit(audit,job.TenantId,null,"ExportDownloaded","ExportJob",job.Id,new{job.Id,job.Format,job.FileName},now);await db.SaveChangesAsync(ct).ConfigureAwait(false);return new(stream,job.ContentType,job.FileName);}
    private ReportCatalogItem RequireCatalog(ReportType type,bool export){var item=Items.SingleOrDefault(x=>x.ReportType==type)??throw new ReportExportException("Report type is invalid.",ReportExportFailureKind.Validation);var permission=export?(item.Scope==ReportScope.Platform?PermissionCatalog.Platform.ReportsExport:PermissionCatalog.Operations.ReportsExport):item.RequiredPermission;if(!currentUser.Permissions.Contains(permission)||(currentUser.IsPlatformAdmin)!=(item.Scope==ReportScope.Platform))throw new ReportExportException("Report permission is required.",ReportExportFailureKind.Forbidden);return item;}
    private void RequireView(){var permission=currentUser.IsPlatformAdmin?PermissionCatalog.Platform.ReportsView:PermissionCatalog.Operations.ReportsView;if(!currentUser.Permissions.Contains(permission))throw new ReportExportException("Report permission is required.",ReportExportFailureKind.Forbidden);}
    private void RequireExport(){var permission=currentUser.IsPlatformAdmin?PermissionCatalog.Platform.ReportsExport:PermissionCatalog.Operations.ReportsExport;if(!currentUser.Permissions.Contains(permission))throw new ReportExportException("Export permission is required.",ReportExportFailureKind.Forbidden);}
    private long RequireTenant()=>currentUser.IsAuthenticated&&!currentUser.IsPlatformAdmin&&currentUser.TenantId is>0?currentUser.TenantId.Value:throw new ReportExportException("Tenant scope is required.",ReportExportFailureKind.Forbidden);
    private long[]AuthorizedStores(long[]requested){var granted=currentUser.StoreIds.Where(x=>x>0).Distinct().OrderBy(x=>x).ToArray();if(requested.Length==0)return granted;if(requested.Any(x=>!granted.Contains(x)))throw new ReportExportException("Store access is forbidden.",ReportExportFailureKind.Forbidden);return requested;}
    private IQueryable<ExportJob>VisibleJobs()=>currentUser.IsPlatformAdmin?db.ExportJobs.Where(x=>x.TenantId==null&&x.RequestedByUserId==currentUser.UserId):db.ExportJobs.Where(x=>x.TenantId==RequireTenant()&&x.RequestedByUserId==currentUser.UserId);
    private async Task<ExportJob>RequireJob(long id,CancellationToken ct){ArgumentOutOfRangeException.ThrowIfNegativeOrZero(id);return await VisibleJobs().SingleOrDefaultAsync(x=>x.Id==id,ct).ConfigureAwait(false)??throw new ReportExportException("Export job was not found.",ReportExportFailureKind.NotFound);}
    private static ExportJobView Map(ExportJob x,DateTime now)=>new(x.Id,x.TenantId,x.RequestedByUserId,x.ReportType,x.Format,x.Status,x.Progress,x.CreatedUtc,x.StartedUtc,x.CompletedUtc,x.ExpiresUtc,x.Error,x.AttemptCount,x.Status==ExportJobStatus.Completed&&x.ExpiresUtc>now&&x.FilePath!=null);
    private void Audit(TenantAuditContext audit,long?tenant,long?store,string action,string entity,long id,object metadata,DateTime now)=>db.AuditLogs.Add(AuditLog.Record(tenant,store,audit.ActorUserId,"User",action,entity,id.ToString(CultureInfo.InvariantCulture),null,JsonSerializer.Serialize(metadata,JsonOptions),audit.IpAddress,audit.UserAgent,audit.CorrelationId,now));
    private async Task QueueEventAsync(Alert alert,string eventName,string correlationId,DateTime now,CancellationToken ct){var realtime=RealtimeEvent.Create(alert.TenantId,alert.StoreId,alert.Id,eventName,1,correlationId,$"{eventName}:{alert.Id}:{now.Ticks}",now);db.RealtimeEvents.Add(realtime);await db.SaveChangesAsync(ct).ConfigureAwait(false);var view=new AlertView(alert.Id,alert.AlertType,alert.StoreId,alert.Severity,alert.Title,alert.Message,alert.EntityType,alert.EntityId,alert.CreatedUtc,alert.AcknowledgedUtc,alert.AcknowledgedByUserId,alert.ResolvedUtc,alert.Status,alert.CorrelationId,alert.DeduplicationKey);var payload=JsonSerializer.Serialize(new AlertRealtimeEventV1(realtime.Id,eventName,1,now,alert.TenantId,alert.StoreId,correlationId,view),JsonOptions);realtime.SetPayload(payload);db.NotificationOutbox.Add(NotificationOutboxMessage.Queue(alert.TenantId,alert.StoreId,alert.Id,realtime.Id,"SignalR",eventName,1,payload,correlationId,$"signalr:{realtime.Id}",now));}
}
