import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component, OnInit, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { AdminShell } from '../../shared/admin-shell/admin-shell';
import { PlatformBillingApiService, PlatformInvoice, PlatformPayment, PlatformPlan, PlatformSubscription } from './platform-billing-api.service';

type Mode='plans'|'subscriptions'|'invoices'|'payments';

@Component({selector:'app-platform-billing-page',standalone:true,imports:[CommonModule,ReactiveFormsModule,AdminShell],changeDetection:ChangeDetectionStrategy.OnPush,
styles:[`:host{display:block}.wrap{padding:24px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:14px}.card{border:1px solid #ddd;border-radius:12px;padding:14px;margin:12px 0}.form{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:8px}input,select,textarea,button{min-height:40px;padding:8px;border:1px solid #bbb;border-radius:8px}table{width:100%;border-collapse:collapse}th,td{padding:8px;border-bottom:1px solid #eee;text-align:left}.ok{color:#147d32}.error{color:#b3261e}.muted{opacity:.7}`],
template:`<app-admin-shell><main class="wrap"><h1>Platform Billing</h1><p class="muted">CustSearch subscription billing only — this screen never shows shop-customer retail invoices or payments.</p>@if(message()){<p class="ok">{{message()}}</p>}@if(error()){<p class="error">{{error()}}</p>}
@if(mode==='plans'){<section class="card"><h2>Subscription Plans</h2><form class="form" [formGroup]="planForm" (ngSubmit)="createPlan()"><input formControlName="planCode" placeholder="Plan code"><input formControlName="name" placeholder="Plan name"><input formControlName="description" placeholder="Description"><input type="number" formControlName="monthlyPrice" placeholder="Monthly price"><input type="number" formControlName="annualPrice" placeholder="Annual price"><input formControlName="currency" placeholder="Currency"><input type="number" formControlName="trialDays" placeholder="Trial days"><input type="number" formControlName="maxStores" placeholder="Max stores"><input type="number" formControlName="maxUsers" placeholder="Max users"><input type="number" formControlName="maxStaff" placeholder="Max staff"><input type="number" formControlName="maxCameras" placeholder="Max cameras"><input type="number" formControlName="displayOrder" placeholder="Display order"><button [disabled]="planForm.invalid">Create plan</button></form></section><table><thead><tr><th>Plan</th><th>Price</th><th>Trial</th><th>Limits</th><th>Status</th></tr></thead><tbody>@for(x of plans();track x.id){<tr><td>{{x.planCode}} — {{x.name}}</td><td>{{x.currency}} {{x.monthlyPrice}} / month</td><td>{{x.trialDays}} days</td><td>{{x.maxStores}} stores · {{x.maxUsers}} users · {{x.maxStaff}} staff · {{x.maxCameras}} cameras</td><td>{{x.isActive?'Active':'Inactive'}}</td></tr>}</tbody></table>}
@if(mode==='subscriptions'){<section class="card"><h2>Create / trial subscription</h2><form class="form" [formGroup]="subscriptionForm" (ngSubmit)="createSubscription()"><input type="number" formControlName="tenantId" placeholder="Tenant ID"><input type="number" formControlName="planId" placeholder="Plan ID"><select formControlName="billingCycle"><option>Monthly</option><option>Annual</option></select><label><input type="checkbox" formControlName="useTrial"> Use plan trial</label><button>Create subscription</button></form></section><table><thead><tr><th>Tenant</th><th>Plan</th><th>Status</th><th>Period</th><th>Limits</th></tr></thead><tbody>@for(x of subscriptions();track x.id){<tr><td>{{x.tenantId}}</td><td>{{x.planCode}} / {{x.billingCycle}}</td><td>{{x.status}}{{x.cancelAtPeriodEnd?' · cancels at period end':''}}</td><td>{{x.startUtc|date:'mediumDate'}} → {{x.currentPeriodEndUtc|date:'mediumDate'}}</td><td>{{x.maxStores}} / {{x.maxUsers}} / {{x.maxStaff}} / {{x.maxCameras}}</td></tr>}</tbody></table>}
@if(mode==='invoices'){<section class="card"><h2>Generate platform invoice</h2><form class="form" [formGroup]="invoiceForm" (ngSubmit)="generateInvoice()"><input type="number" formControlName="tenantId" placeholder="Tenant ID"><input type="number" formControlName="discountAmount" placeholder="Discount"><input type="number" formControlName="taxAmount" placeholder="Tax"><button>Generate invoice</button></form></section><table><thead><tr><th>Invoice</th><th>Tenant</th><th>Status</th><th>Total</th><th>Snapshot</th></tr></thead><tbody>@for(x of invoices();track x.id){<tr><td>{{x.invoiceNumber}}</td><td>{{x.tenantId}}</td><td>{{x.status}}</td><td>{{x.currency}} {{x.total}} (paid {{x.paidAmount}})</td><td>{{x.items[0]?.planName||'-'}}</td></tr>}</tbody></table>}
@if(mode==='payments'){<section class="card"><h2>Record provider-neutral payment callback</h2><form class="form" [formGroup]="paymentForm" (ngSubmit)="recordPayment()"><input type="number" formControlName="platformInvoiceId" placeholder="Platform invoice ID"><input formControlName="paymentMethod" placeholder="Payment method"><input type="number" formControlName="amount" placeholder="Amount"><input formControlName="currency" placeholder="Currency"><input formControlName="transactionReference" placeholder="Transaction reference"><select formControlName="status"><option>Pending</option><option>Successful</option><option>Failed</option><option>Refunded</option></select><button>Record payment</button></form></section><table><thead><tr><th>Reference</th><th>Invoice</th><th>Status</th><th>Amount</th></tr></thead><tbody>@for(x of payments();track x.id){<tr><td>{{x.transactionReference}}</td><td>{{x.platformInvoiceId}}</td><td>{{x.status}}</td><td>{{x.currency}} {{x.amount}}</td></tr>}</tbody></table>}</main></app-admin-shell>`})
export class PlatformBillingPage implements OnInit{
 private readonly api=inject(PlatformBillingApiService);private readonly route=inject(ActivatedRoute);private readonly fb=inject(FormBuilder);protected readonly mode=this.route.snapshot.data['mode'] as Mode;protected readonly plans=signal<PlatformPlan[]>([]);protected readonly subscriptions=signal<PlatformSubscription[]>([]);protected readonly invoices=signal<PlatformInvoice[]>([]);protected readonly payments=signal<PlatformPayment[]>([]);protected readonly message=signal('');protected readonly error=signal('');
 protected readonly planForm=this.fb.nonNullable.group({planCode:['',Validators.required],name:['',Validators.required],description:'',monthlyPrice:[0,Validators.min(0)],annualPrice:[0,Validators.min(0)],currency:['INR',Validators.required],trialDays:[0,Validators.min(0)],maxStores:[1,Validators.min(1)],maxUsers:[1,Validators.min(1)],maxStaff:[1,Validators.min(1)],maxCameras:[1,Validators.min(1)],displayOrder:[0,Validators.min(0)]});
 protected readonly subscriptionForm=this.fb.nonNullable.group({tenantId:[0,Validators.min(1)],planId:[0,Validators.min(1)],billingCycle:'Monthly',useTrial:true});protected readonly invoiceForm=this.fb.nonNullable.group({tenantId:[0,Validators.min(1)],discountAmount:[0,Validators.min(0)],taxAmount:[0,Validators.min(0)]});protected readonly paymentForm=this.fb.nonNullable.group({platformInvoiceId:[0,Validators.min(1)],paymentMethod:['Manual',Validators.required],amount:[0,Validators.min(.01)],currency:['INR',Validators.required],transactionReference:['',Validators.required],status:'Successful'});
 ngOnInit(){this.load();}
 protected createPlan(){if(this.planForm.invalid)return;const v=this.planForm.getRawValue();this.api.createPlan({...v,description:v.description.trim()||null,annualPrice:v.annualPrice||null,maxMonthlyRecognitions:null,maxMonthlyApiCalls:null,featureLimitsJson:null,isActive:true}).subscribe({next:()=>this.success('Plan created.'),error:e=>this.fail(e)});}
 protected createSubscription(){if(this.subscriptionForm.invalid)return;const v=this.subscriptionForm.getRawValue();this.api.createSubscription(v.tenantId,{planId:v.planId,billingCycle:v.billingCycle,startUtc:new Date().toISOString(),useTrial:v.useTrial}).subscribe({next:()=>this.success('Subscription created.'),error:e=>this.fail(e)});}
 protected generateInvoice(){if(this.invoiceForm.invalid)return;const v=this.invoiceForm.getRawValue();this.api.generateInvoice(v.tenantId,{discountAmount:v.discountAmount,taxAmount:v.taxAmount,dueUtc:null}).subscribe({next:()=>this.success('Platform invoice generated.'),error:e=>this.fail(e)});}
 protected recordPayment(){if(this.paymentForm.invalid)return;const v=this.paymentForm.getRawValue();this.api.recordPayment({...v,gatewayReference:null,paymentUtc:new Date().toISOString()}).subscribe({next:()=>this.success('Platform payment recorded.'),error:e=>this.fail(e)});}
 private load(){this.error.set('');if(this.mode==='plans')this.api.plans().subscribe({next:x=>this.plans.set(x),error:e=>this.fail(e)});if(this.mode==='subscriptions')this.api.subscriptions().subscribe({next:x=>this.subscriptions.set(x),error:e=>this.fail(e)});if(this.mode==='invoices')this.api.invoices().subscribe({next:x=>this.invoices.set(x),error:e=>this.fail(e)});if(this.mode==='payments')this.api.payments().subscribe({next:x=>this.payments.set(x),error:e=>this.fail(e)});}
 private success(text:string){this.message.set(text);this.load();}private fail(e:unknown){this.error.set(e instanceof Error?e.message:'Request failed.');}
}
