import { HttpClient } from '@angular/common/http';
import { Injectable, inject } from '@angular/core';

export interface PlatformPlan { id:number; planCode:string; name:string; description:string|null; monthlyPrice:number; annualPrice:number|null; currency:string; trialDays:number; maxStores:number; maxUsers:number; maxStaff:number; maxCameras:number; maxMonthlyRecognitions:number|null; maxMonthlyApiCalls:number|null; featureLimitsJson:string|null; isActive:boolean; displayOrder:number; createdUtc:string; updatedUtc:string; }
export interface PlatformSubscription { id:number; tenantId:number; planId:number; planCode:string; planName:string; billingCycle:string; status:string; startUtc:string; trialEndUtc:string|null; currentPeriodStartUtc:string|null; currentPeriodEndUtc:string|null; cancelAtPeriodEnd:boolean; cancelledUtc:string|null; maxStores:number; maxUsers:number; maxStaff:number; maxCameras:number; }
export interface PlatformInvoiceItem { id:number; planId:number|null; planName:string; description:string|null; quantity:number; rate:number; discount:number; tax:number; subtotal:number; total:number; }
export interface PlatformInvoice { id:number; tenantId:number; tenantSubscriptionId:number; invoiceNumber:string; currency:string; invoiceUtc:string; dueUtc:string; status:string; subtotal:number; discount:number; tax:number; total:number; paidAmount:number; items:PlatformInvoiceItem[]; }
export interface PlatformPayment { id:number; tenantId:number; platformInvoiceId:number; paymentMethod:string; amount:number; currency:string; gatewayReference:string|null; transactionReference:string; paymentUtc:string; status:string; }
export interface TenantBillingSummary { subscription:PlatformSubscription|null; currentPlan:string|null; maxStores:number; maxUsers:number; maxStaff:number; maxCameras:number; renewalUtc:string|null; latestPaymentStatus:string|null; invoiceCount:number; }
export interface SavePlatformPlan { planCode:string; name:string; description:string|null; monthlyPrice:number; annualPrice:number|null; currency:string; trialDays:number; maxStores:number; maxUsers:number; maxStaff:number; maxCameras:number; maxMonthlyRecognitions:number|null; maxMonthlyApiCalls:number|null; featureLimitsJson:string|null; isActive:boolean; displayOrder:number; }

@Injectable({providedIn:'root'})
export class PlatformBillingApiService {
  private readonly http=inject(HttpClient); private readonly platform='/api/platform/billing'; private readonly tenant='/api/tenant/platform-billing';
  plans(){return this.http.get<PlatformPlan[]>(`${this.platform}/plans`);} createPlan(body:SavePlatformPlan){return this.http.post<PlatformPlan>(`${this.platform}/plans`,body);} updatePlan(id:number,body:SavePlatformPlan){return this.http.put<PlatformPlan>(`${this.platform}/plans/${this.id(id)}`,body);}
  subscriptions(){return this.http.get<PlatformSubscription[]>(`${this.platform}/subscriptions`);} createSubscription(tenantId:number,body:{planId:number;billingCycle:string;startUtc:string;useTrial:boolean}){return this.http.post<PlatformSubscription>(`${this.platform}/subscriptions/${this.id(tenantId)}`,body);} renew(tenantId:number){return this.http.post<PlatformSubscription>(`${this.platform}/subscriptions/${this.id(tenantId)}/renew`,{});} changePlan(tenantId:number,body:{planId:number;billingCycle:string}){return this.http.put<PlatformSubscription>(`${this.platform}/subscriptions/${this.id(tenantId)}/plan`,body);} cancel(tenantId:number,atPeriodEnd:boolean){return this.http.post<PlatformSubscription>(`${this.platform}/subscriptions/${this.id(tenantId)}/cancel?atPeriodEnd=${atPeriodEnd}`,{});}
  invoices(){return this.http.get<PlatformInvoice[]>(`${this.platform}/invoices`);} generateInvoice(tenantId:number,body:{discountAmount:number;taxAmount:number;dueUtc:string|null}){return this.http.post<PlatformInvoice>(`${this.platform}/invoices/${this.id(tenantId)}`,body);} payments(){return this.http.get<PlatformPayment[]>(`${this.platform}/payments`);} recordPayment(body:{platformInvoiceId:number;paymentMethod:string;amount:number;currency:string;gatewayReference:string|null;transactionReference:string;paymentUtc:string;status:string}){return this.http.post<PlatformPayment>(`${this.platform}/payments`,body);}
  tenantSummary(){return this.http.get<TenantBillingSummary>(this.tenant);} tenantSubscription(){return this.http.get<PlatformSubscription|null>(`${this.tenant}/subscription`);} tenantInvoices(){return this.http.get<PlatformInvoice[]>(`${this.tenant}/invoices`);} tenantPayments(){return this.http.get<PlatformPayment[]>(`${this.tenant}/payments`);}
  private id(value:number){if(!Number.isSafeInteger(value)||value<=0)throw new Error('A valid identifier is required.');return value;}
}
