import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component, OnInit, inject, signal } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { AdminShell } from '../../shared/admin-shell/admin-shell';
import { PlatformBillingApiService, PlatformInvoice, PlatformPayment, PlatformSubscription, TenantBillingSummary } from './platform-billing-api.service';

type Mode='summary'|'subscription'|'invoices';

@Component({selector:'app-tenant-billing-page',standalone:true,imports:[CommonModule,RouterLink,AdminShell],changeDetection:ChangeDetectionStrategy.OnPush,
styles:[`:host{display:block}.wrap{padding:24px}.billing-nav{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0 20px}.billing-nav a{padding:8px 11px;border:1px solid #ddd;border-radius:8px;text-decoration:none;color:inherit}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:12px}.card{border:1px solid #ddd;border-radius:12px;padding:14px}.muted{opacity:.7}table{width:100%;border-collapse:collapse}th,td{padding:8px;border-bottom:1px solid #eee;text-align:left}.error{color:#b3261e}`],
template:`<app-admin-shell><main class="wrap"><h1>CustSearch Billing</h1><p class="muted">Your platform subscription only. Shop-customer retail purchases are not shown here.</p><nav class="billing-nav" aria-label="Platform billing"><a routerLink="/customer-admin/billing">Summary</a><a routerLink="/customer-admin/billing/subscription">Subscription</a><a routerLink="/customer-admin/billing/invoices">Invoice history</a></nav>@if(error()){<p class="error">{{error()}}</p>}
@if(mode==='summary'&&summary();as s){<section class="grid"><div class="card"><b>Current Plan</b><p>{{s.currentPlan||'No plan'}}</p></div><div class="card"><b>Subscription status</b><p>{{s.subscription?.status||'-'}}</p></div><div class="card"><b>Renewal date</b><p>{{s.renewalUtc?(s.renewalUtc|date:'mediumDate'):'-'}}</p></div><div class="card"><b>Latest payment</b><p>{{s.latestPaymentStatus||'-'}}</p></div><div class="card"><b>Plan limits</b><p>{{s.maxStores}} stores · {{s.maxUsers}} users · {{s.maxStaff}} staff · {{s.maxCameras}} cameras</p></div><div class="card"><b>Invoice history</b><p>{{s.invoiceCount}} platform invoices</p></div></section>}
@if(mode==='subscription'&&subscription();as s){<section class="card"><h2>{{s.planName}}</h2><p>Status: <strong>{{s.status}}</strong></p><p>Cycle: {{s.billingCycle}}</p><p>Period: {{s.currentPeriodStartUtc|date:'mediumDate'}} → {{s.currentPeriodEndUtc|date:'mediumDate'}}</p><p>Limits: {{s.maxStores}} stores · {{s.maxUsers}} users · {{s.maxStaff}} staff · {{s.maxCameras}} cameras</p><p>{{s.cancelAtPeriodEnd?'Cancellation scheduled for period end':'Automatic continuation enabled'}}</p></section>}
@if(mode==='invoices'){<h2>Platform invoice history</h2><table><thead><tr><th>Invoice</th><th>Date</th><th>Status</th><th>Total</th><th>Plan snapshot</th></tr></thead><tbody>@for(x of invoices();track x.id){<tr><td>{{x.invoiceNumber}}</td><td>{{x.invoiceUtc|date:'mediumDate'}}</td><td>{{x.status}}</td><td>{{x.currency}} {{x.total}}</td><td>{{x.items[0]?.planName||'-'}}</td></tr>}</tbody></table><h2>Payment status</h2><table><tbody>@for(p of payments();track p.id){<tr><td>{{p.transactionReference}}</td><td>{{p.status}}</td><td>{{p.currency}} {{p.amount}}</td></tr>}</tbody></table>}</main></app-admin-shell>`})
export class TenantBillingPage implements OnInit{
 private readonly api=inject(PlatformBillingApiService);private readonly route=inject(ActivatedRoute);protected readonly mode=this.route.snapshot.data['mode'] as Mode;protected readonly summary=signal<TenantBillingSummary|null>(null);protected readonly subscription=signal<PlatformSubscription|null>(null);protected readonly invoices=signal<PlatformInvoice[]>([]);protected readonly payments=signal<PlatformPayment[]>([]);protected readonly error=signal('');
 ngOnInit(){if(this.mode==='summary')this.api.tenantSummary().subscribe({next:x=>this.summary.set(x),error:e=>this.fail(e)});if(this.mode==='subscription')this.api.tenantSubscription().subscribe({next:x=>this.subscription.set(x),error:e=>this.fail(e)});if(this.mode==='invoices'){this.api.tenantInvoices().subscribe({next:x=>this.invoices.set(x),error:e=>this.fail(e)});this.api.tenantPayments().subscribe({next:x=>this.payments.set(x),error:e=>this.fail(e)});}}
 private fail(e:unknown){this.error.set(e instanceof Error?e.message:'Request failed.');}
}
