using CustSearch.Domain.Entities;
using CustSearch.Domain.Enums;

namespace CustSearch.UnitTests;

public sealed class PhaseTwelveIntegrationEntityTests
{
    private static readonly DateTime Now=new(2026,8,24,18,0,0,DateTimeKind.Utc);
    [Fact]public void ConfigurationStoresReferencesAndSupportsGracefulSigningRotation(){var item=IntegrationConfiguration.Create(1,"Demo POS",IntegrationType.Bidirectional,true,"https://pos.example.test/hooks","credential-v1","signing-v1",10,5,5,Now);item.RotateReferences("credential-v2","signing-v2",15,Now.AddMinutes(1));Assert.Equal("credential-v2",item.CredentialReference);Assert.Equal("signing-v2",item.WebhookSigningSecretReference);Assert.Equal("signing-v1",item.PreviousWebhookSigningSecretReference);Assert.Equal(Now.AddMinutes(16),item.PreviousSigningSecretValidUntilUtc);Assert.True(item.SupportsInbound);Assert.True(item.SupportsOutbound);}
    [Fact]public void ConfigurationRejectsNonHttpsAndUnboundedPolicy(){Assert.Throws<ArgumentException>(()=>IntegrationConfiguration.Create(1,"POS",IntegrationType.Api,true,"http://pos.example.test",null,null,10,5,5,Now));Assert.Throws<ArgumentOutOfRangeException>(()=>IntegrationConfiguration.Create(1,"POS",IntegrationType.Api,true,"https://pos.example.test",null,null,121,5,5,Now));}
    [Fact]public void OutboxUsesBoundedExponentialRetryThenDeadLetterAndManualRetry(){var item=IntegrationOutboxMessage.Queue(1,2,"POS","https://pos.example.test","invoice.created",1,"{}",new string('a',64),"p12","out:1",3,5,Now);item.StartAttempt(Now,TimeSpan.FromMinutes(1));item.MarkFailed(500,"remote failure",false,Now);Assert.Equal(IntegrationOutboxStatus.Failed,item.Status);Assert.Equal(Now.AddSeconds(5),item.NextAttemptUtc);item.StartAttempt(item.NextAttemptUtc,TimeSpan.FromMinutes(1));item.MarkFailed(500,"remote failure",false,item.NextAttemptUtc);Assert.Equal(IntegrationOutboxStatus.Retrying,item.Status);var third=item.NextAttemptUtc;item.StartAttempt(third,TimeSpan.FromMinutes(1));item.MarkFailed(500,"remote failure",false,third);Assert.Equal(IntegrationOutboxStatus.DeadLetter,item.Status);item.RetryManually(third.AddMinutes(1));Assert.Equal(IntegrationOutboxStatus.Retrying,item.Status);Assert.Equal(0,item.AttemptCount);}
    [Fact]public void PermanentFailureDeadLettersImmediately(){var item=IntegrationOutboxMessage.Queue(1,2,"POS","https://pos.example.test","invoice.created",1,"{}",new string('a',64),"p12","out:2",5,5,Now);item.StartAttempt(Now,TimeSpan.FromMinutes(1));item.MarkFailed(400,"permanent",true,Now);Assert.Equal(IntegrationOutboxStatus.DeadLetter,item.Status);Assert.Equal(1,item.AttemptCount);}
    [Fact]public void RetryingDeliveryCanBeManuallyRequeued(){var item=IntegrationOutboxMessage.Queue(1,2,"POS","https://pos.example.test","invoice.created",1,"{}",new string('a',64),"p12","out:3",5,5,Now);item.StartAttempt(Now,TimeSpan.FromMinutes(1));item.MarkFailed(500,"transient",false,Now);item.StartAttempt(item.NextAttemptUtc,TimeSpan.FromMinutes(1));item.MarkFailed(500,"transient",false,item.NextAttemptUtc);Assert.Equal(IntegrationOutboxStatus.Retrying,item.Status);item.RetryManually(Now.AddMinutes(2));Assert.Equal(0,item.AttemptCount);Assert.Equal(Now.AddMinutes(2),item.NextAttemptUtc);}
    [Fact]public void DeliveryLogRequiresExactlyOneSource(){Assert.Throws<ArgumentOutOfRangeException>(()=>IntegrationDeliveryLog.RecordOutbound(1,2,0,"p12","POS",IntegrationDeliveryStatus.Failed,4,500,"server",Now));var log=IntegrationDeliveryLog.RecordOutbound(1,2,3,"p12","POS",IntegrationDeliveryStatus.Delivered,4,200,null,Now);Assert.Null(log.InboundEventId);Assert.Equal(3,log.OutboxMessageId);}
}
