import { CommonModule } from '@angular/common';
import { HttpErrorResponse } from '@angular/common/http';
import { ChangeDetectionStrategy, Component, OnInit, computed, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { AuthSessionService } from '../../core/auth/auth-session.service';
import { PERMISSIONS } from '../../core/auth/permission-catalog';
import { AdminShell } from '../../shared/admin-shell/admin-shell';
import { AnonymousVisitorListItem, VisitorApiService } from './visitor-api.service';

/** Phase 6F anonymous visitor UI. Conversion is always an explicit operator action and never automatic identity inference. */
@Component({selector:'app-visitor-list-page',standalone:true,imports:[CommonModule,ReactiveFormsModule,RouterLink,AdminShell],changeDetection:ChangeDetectionStrategy.OnPush,
styles:[`:host{display:block}.wrap{padding:24px}.toolbar{display:flex;gap:12px;justify-content:space-between;align-items:end;flex-wrap:wrap}.filters{display:flex;gap:8px;flex-wrap:wrap}.grid{display:grid;grid-template-columns:minmax(0,1fr) 360px;gap:18px;margin-top:18px}.card{border:1px solid #ddd;border-radius:12px;padding:16px;background:var(--mat-sys-surface,#fff)}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:10px;border-bottom:1px solid #eee}input,button{min-height:40px;padding:8px;border:1px solid #ccc;border-radius:8px}form{display:grid;gap:9px}.pager{display:flex;gap:8px;align-items:center;margin-top:12px}.error{color:#b3261e}.ok{color:#147d32}.muted{opacity:.65}@media(max-width:900px){.grid{grid-template-columns:1fr}}`],
template:`<app-admin-shell><main class="wrap"><div class="toolbar"><div><a routerLink="/customer-admin/customers">Customers</a><h1>Anonymous Visitors</h1><p class="muted">Unknown people remain anonymous until an authorized conversion.</p></div><form class="filters" [formGroup]="searchForm" (ngSubmit)="search()"><input formControlName="search" placeholder="Visitor code"><input formControlName="storeId" placeholder="Store ID"><label><input type="checkbox" formControlName="activeOnly"> Active only</label><button>Search</button></form></div>@if(error()){<p class="error">{{error()}}</p>}@if(message()){<p class="ok">{{message()}}</p>}<div class="grid"><section class="card"><table><thead><tr><th>Visitor</th><th>Store</th><th>First seen</th><th>Last seen</th><th>Status</th><th></th></tr></thead><tbody>@for(x of visitors();track x.id){<tr><td>{{x.visitorCode}}</td><td>{{x.storeId}}</td><td>{{x.firstSeenUtc}}</td><td>{{x.lastSeenUtc}}</td><td>{{x.convertedCustomerId?'Converted':(x.isActive?'Active':'Inactive')}}</td><td>@if(canConvert()&&!x.convertedCustomerId){<button type="button" (click)="select(x)">Convert</button>}</td></tr>}@empty{<tr><td colspan="6">No anonymous visitors found.</td></tr>}</tbody></table><div class="pager"><button type="button" [disabled]="pageNumber()<=1" (click)="previous()">Previous</button><span>Page {{pageNumber()}} · {{totalCount()}} records</span><button type="button" [disabled]="pageNumber()*pageSize()>=totalCount()" (click)="next()">Next</button></div></section>@if(canConvert()&&selected();as v){<aside class="card"><h2>Convert {{v.visitorCode}}</h2><p class="muted">Use an existing customer ID, or leave it blank and create a new customer below. The API rechecks customer permissions and store scope.</p><form [formGroup]="convertForm" (ngSubmit)="convert()"><input formControlName="customerId" placeholder="Existing customer ID (optional)"><input formControlName="firstName" placeholder="New customer first name"><input formControlName="lastName" placeholder="Last name"><input formControlName="mobile" placeholder="Mobile"><input formControlName="email" placeholder="Email"><input formControlName="notes" placeholder="Notes"><button [disabled]="saving()">Convert visitor</button><button type="button" (click)="cancel()">Cancel</button></form></aside>}</div></main></app-admin-shell>`})
export class VisitorListPage implements OnInit{
 private readonly api=inject(VisitorApiService);private readonly session=inject(AuthSessionService);private readonly fb=inject(FormBuilder);
 protected readonly visitors=signal<AnonymousVisitorListItem[]>([]);protected readonly selected=signal<AnonymousVisitorListItem|null>(null);protected readonly pageNumber=signal(1);protected readonly pageSize=signal(25);protected readonly totalCount=signal(0);protected readonly saving=signal(false);protected readonly error=signal('');protected readonly message=signal('');protected readonly canConvert=computed(()=>this.session.hasPermission(PERMISSIONS.visitorsConvert));
 protected readonly searchForm=this.fb.nonNullable.group({search:'',storeId:'',activeOnly:true});protected readonly convertForm=this.fb.nonNullable.group({customerId:'',firstName:'',lastName:'',mobile:'',email:['',Validators.email],notes:''});
 ngOnInit(){this.load();}protected search(){this.pageNumber.set(1);this.load();}protected previous(){this.pageNumber.update(x=>Math.max(1,x-1));this.load();}protected next(){if(this.pageNumber()*this.pageSize()<this.totalCount()){this.pageNumber.update(x=>x+1);this.load();}}protected select(v:AnonymousVisitorListItem){this.selected.set(v);this.convertForm.reset({customerId:'',firstName:'',lastName:'',mobile:'',email:'',notes:''});this.clearStatus();}protected cancel(){this.selected.set(null);}
 protected convert(){const visitor=this.selected();if(!visitor)return;const v=this.convertForm.getRawValue();const customerId=this.numberOrNull(v.customerId);if(!customerId&&!v.firstName.trim()){this.error.set('First name is required when no existing customer ID is supplied.');return;}this.saving.set(true);this.clearStatus();this.api.convert(visitor.id,{customerId,firstName:customerId?null:v.firstName.trim(),lastName:customerId?null:(v.lastName.trim()||null),mobile:customerId?null:(v.mobile.trim()||null),email:customerId?null:(v.email.trim()||null),notes:customerId?null:(v.notes.trim()||null)}).subscribe({next:c=>{this.saving.set(false);this.message.set(`Visitor converted to ${c.customerCode}.`);this.selected.set(null);this.load(false);},error:e=>this.fail(e)});}
 private load(clear=true){if(clear)this.clearStatus();const v=this.searchForm.getRawValue();const filters:Record<string,string|number|boolean>={activeOnly:v.activeOnly};const storeId=this.numberOrNull(v.storeId);if(storeId)filters['storeId']=storeId;this.api.search({pageNumber:this.pageNumber(),pageSize:this.pageSize(),search:v.search.trim()||undefined,filters}).subscribe({next:r=>{this.visitors.set(r.data);this.totalCount.set(r.totalCount);},error:e=>this.fail(e)});}private numberOrNull(v:string){const n=Number(v);return Number.isInteger(n)&&n>0?n:null;}private clearStatus(){this.error.set('');this.message.set('');}private fail(e:unknown){this.saving.set(false);this.error.set(e instanceof HttpErrorResponse?(e.error?.message??e.message):'Request failed.');}
}
