using System.Data;
using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using CustSearch.Application.Abstractions.Data;
using CustSearch.Application.Authentication;
using CustSearch.Application.Authorization;
using CustSearch.Application.CamerasTracking;
using CustSearch.Application.Security;
using CustSearch.Application.TenantOperations;
using CustSearch.Domain.Entities;
using CustSearch.Domain.Enums;
using Dapper;
using Microsoft.Extensions.Options;

namespace CustSearch.Infrastructure.Security;

#pragma warning disable CA1822 // Helpers are instance members to keep the security workflow cohesive and mockable at the service boundary.

/// <summary>Server-authoritative Phase 18 ingestion, POS correlation, risk and tenant/store boundary.</summary>
public sealed class SecurityPlatformService(
    IDbConnectionFactory connections,ICurrentUserContext currentUser,ICctvServiceSecretResolver serviceSecrets,
    ISecurityRealtimePublisher realtime,ISecurityEvidenceTokenService evidenceTokens,ISecurityEvidenceStore evidenceStore,
    TimeProvider clock,IOptions<SecurityIngestionOptions> ingestionOptions):ISecurityPlatformService
{
    private const string SettingsCode="STORE_SECURITY_SETTINGS";
    private static readonly JsonSerializerOptions StrictJson=new(JsonSerializerDefaults.Web){UnmappedMemberHandling=JsonUnmappedMemberHandling.Disallow};
    private readonly SecurityIngestionOptions ingestion=ingestionOptions.Value;

    public async Task<SecurityIngestionResult>IngestAsync(SecurityIngestionEnvelope envelope,CancellationToken ct=default)
    {
        ArgumentNullException.ThrowIfNull(envelope);
        if(envelope.Body.Length is 0||envelope.Body.Length>ingestion.MaximumBodyBytes)throw Fail("Observation body size is invalid.",SecurityFailureKind.Validation);
        var signedUtc=ParseTimestamp(envelope.Timestamp);var now=clock.GetUtcNow().UtcDateTime;
        if(Math.Abs((now-signedUtc).TotalSeconds)>ingestion.AllowedClockSkewSeconds)throw Fail("Signed observation is expired.",SecurityFailureKind.Unauthorized);
        var credential=await serviceSecrets.ResolveAsync(envelope.ServiceKeyId,ct).ConfigureAwait(false)??throw Fail("AI service credential is not configured.",SecurityFailureKind.Unauthorized);
        ValidateSignature(credential.Secret,envelope);
        SecurityObservationRequest request;
        try{request=JsonSerializer.Deserialize<SecurityObservationRequest>(envelope.Body,StrictJson)??throw new JsonException();}
        catch(JsonException){throw Fail("Observation JSON does not match the normalized contract.",SecurityFailureKind.Validation);}
        ValidateObservation(request,now);
        if(request.TenantId!=credential.TenantId||(!credential.AllowAllStores&&!credential.StoreIds.Contains(request.StoreId)))throw Fail("Observation is outside the AI service tenant/store scope.",SecurityFailureKind.Forbidden);
        var bodyHash=SHA256.HashData(envelope.Body);var nonceHash=SHA256.HashData(Encoding.UTF8.GetBytes(envelope.Nonce));
        await using var db=await connections.OpenConnectionAsync(ct).ConfigureAwait(false);
        ObservationReceipt receipt;
        try
        {
            receipt=await db.QuerySingleAsync<ObservationReceipt>(new CommandDefinition("dbo.SecurityObservation_Ingest",new{
                request.TenantId,request.StoreId,request.CameraId,envelope.ServiceKeyId,envelope.IdempotencyKey,NonceHash=nonceHash,BodyHash=bodyHash,SignedUtc=signedUtc,
                request.VisitId,request.PersonTrackSessionId,request.PersonTrackId,ObservationType=(byte)request.ObservationType,request.OccurredUtc,request.ZoneId,request.ProductId,request.ProductCategoryId,request.Confidence,
                envelope.CorrelationId,request.ModelVersion,request.MetadataJson},commandType:CommandType.StoredProcedure,cancellationToken:ct)).ConfigureAwait(false);
        }
        catch(Exception ex)when(ex.Message.Contains("replay",StringComparison.OrdinalIgnoreCase)||ex.Message.Contains("nonce",StringComparison.OrdinalIgnoreCase)){throw Fail("Signed observation replay was rejected.",SecurityFailureKind.Replay);}
        catch(Exception ex)when(ex.Message.Contains("camera",StringComparison.OrdinalIgnoreCase)||ex.Message.Contains("scope",StringComparison.OrdinalIgnoreCase)){throw Fail("Camera is outside the signed tenant/store scope.",SecurityFailureKind.Forbidden);}
        if(receipt.WasDuplicate)return new(receipt.Id,true,null,null,false,"duplicate");
        if(request.ObservationType!=SecurityObservationType.PersonExit)return new(receipt.Id,false,null,null,false,"observed");
        var result=await EvaluateExitAsync(db,request,envelope.CorrelationId,ct).ConfigureAwait(false);
        return result with{ObservationId=receipt.Id};
    }

    private async Task<SecurityIngestionResult>EvaluateExitAsync(System.Data.Common.DbConnection db,SecurityObservationRequest exit,string correlationId,CancellationToken ct)
    {
        var settings=await LoadSettingsAsync(db,exit.TenantId,exit.StoreId,ct).ConfigureAwait(false);
        if(!settings.SecurityEnabled||!settings.UnpaidExitDetectionEnabled)return new(0,false,null,null,true,"shadow-disabled");
        var from=exit.OccurredUtc.AddMinutes(-settings.CheckoutCorrelationWindowMinutes);
        var observations=(await db.QueryAsync<SignalRow>(new CommandDefinition(@"SELECT ObservationType,OccurredUtc,Confidence,MetadataJson,ProductId,ProductCategoryId FROM dbo.SecurityObservations
WHERE TenantId=@TenantId AND StoreId=@StoreId AND OccurredUtc BETWEEN @FromUtc AND @OccurredUtc
AND ((@PersonTrackSessionId IS NOT NULL AND PersonTrackSessionId=@PersonTrackSessionId) OR (@PersonTrackId IS NOT NULL AND PersonTrackId=@PersonTrackId))",new{exit.TenantId,exit.StoreId,FromUtc=from,exit.OccurredUtc,exit.PersonTrackSessionId,exit.PersonTrackId},cancellationToken:ct)).ConfigureAwait(false)).AsList();
        var correlation=SecuritySignalCorrelationEngine.Correlate(observations.Select(x=>new SecurityObservedSignal((SecurityObservationType)x.ObservationType,x.OccurredUtc,x.Confidence,x.ProductId,x.ProductCategoryId)),exit.OccurredUtc);
        var pickup=correlation.Pickup;
        var meta=observations.Select(x=>ReadMetadata(x.MetadataJson)).ToArray();
        var evidenceMetadata=meta.LastOrDefault(x=>!string.IsNullOrWhiteSpace(x.EvidenceObjectKey)&&!string.IsNullOrWhiteSpace(x.EvidenceContentHashHex));
        var productId=exit.ProductId??pickup?.ProductId;var categoryId=exit.ProductCategoryId??pickup?.ProductCategoryId;
        var paid=await FindPaidMatchAsync(db,exit,productId,categoryId,settings.CheckoutCorrelationWindowMinutes,ct).ConfigureAwait(false);
        var rule=new SecurityRiskRule(settings.RuleVersion,settings.RiskThreshold,settings.HighValueThreshold,settings.CheckoutCorrelationWindowMinutes,settings.ExitGracePeriodSeconds);
        var signals=new SecurityRiskSignals(true,pickup is not null||correlation.ItemRemainsWithTrack,correlation.PutBackObserved,correlation.CheckoutVisited,paid is not null,meta.Any(x=>x.StaffHandling),meta.Any(x=>x.GroupHandoff),meta.Any(x=>x.CrowdedAisle),meta.Any(x=>x.ReEntry),meta.Any(x=>x.RfidEas),pickup?.Confidence??exit.Confidence,meta.Length==0?1m:meta.Min(x=>x.OcclusionQuality),meta.Max(x=>x.CameraGapSeconds),meta.Select(x=>x.ProductValue).FirstOrDefault(x=>x.HasValue));
        var evaluation=SecurityRiskEngine.Evaluate(rule,signals);
        if(!evaluation.Candidate)return new(0,false,null,evaluation.Score,evaluation.Suppressed,evaluation.Reason);
        var existing=await db.QuerySingleOrDefaultAsync<long?>(new CommandDefinition(@"SELECT TOP(1)Id FROM dbo.SecurityIncidents WHERE TenantId=@TenantId AND StoreId=@StoreId AND Status<6 AND UpdatedUtc>=DATEADD(SECOND,-120,SYSUTCDATETIME()) AND ((@PersonTrackId IS NOT NULL AND PersonTrackId=@PersonTrackId) OR (@PersonTrackSessionId IS NOT NULL AND PersonTrackSessionId=@PersonTrackSessionId)) ORDER BY Id DESC",exit,cancellationToken:ct)).ConfigureAwait(false);
        if(existing.HasValue)return new(0,false,existing,evaluation.Score,false,"candidate-deduplicated");
        await using var tx=await db.BeginTransactionAsync(ct).ConfigureAwait(false);
        var incidentNumber=$"SEC-{exit.OccurredUtc:yyyyMMdd}-{Guid.NewGuid():N}"[..30].ToUpperInvariant();
        var incidentId=await db.QuerySingleAsync<long>(new CommandDefinition(@"INSERT dbo.SecurityIncidents(IncidentNumber,TenantId,StoreId,VisitId,PersonTrackSessionId,PersonTrackId,IncidentType,Severity,RiskScore,RuleCode,RuleVersion,Status,FirstObservedUtc,ExitObservedUtc,EstimatedLossAmount,Currency)
VALUES(@IncidentNumber,@TenantId,@StoreId,@VisitId,@PersonTrackSessionId,@PersonTrackId,1,@Severity,@RiskScore,@RuleCode,@RuleVersion,2,@OccurredUtc,@OccurredUtc,@EstimatedLoss,N'INR');SELECT CONVERT(BIGINT,SCOPE_IDENTITY());",new{IncidentNumber=incidentNumber,exit.TenantId,exit.StoreId,exit.VisitId,exit.PersonTrackSessionId,exit.PersonTrackId,Severity=(byte)evaluation.Severity,RiskScore=evaluation.Score,RuleCode=SettingsCode,RuleVersion=settings.RuleVersion,exit.OccurredUtc,EstimatedLoss=signals.ProductValue},tx,cancellationToken:ct)).ConfigureAwait(false);
        await db.ExecuteAsync(new CommandDefinition(@"INSERT dbo.SecurityIncidentActions(TenantId,StoreId,SecurityIncidentId,ActionType,FromStatus,ToStatus,ActorType,ReasonCode,Notes,CorrelationId)
VALUES(@TenantId,@StoreId,@IncidentId,N'CandidateCreated',1,2,N'System',N'RISK_THRESHOLD',@Reason,@CorrelationId);
INSERT dbo.SecurityIncidentActions(TenantId,StoreId,SecurityIncidentId,ActionType,ActorType,ReasonCode,Notes,CorrelationId)
VALUES(@TenantId,@StoreId,@IncidentId,N'CheckoutCorrelationEvaluated',N'System',N'NO_PAID_MATCH',@CheckoutNotes,@CorrelationId)",new{exit.TenantId,exit.StoreId,IncidentId=incidentId,evaluation.Reason,CheckoutNotes=correlation.CheckoutVisited?"Checkout zone visited; no compatible paid invoice matched.":"No checkout-zone visit or compatible paid invoice matched.",CorrelationId=correlationId},tx,cancellationToken:ct)).ConfigureAwait(false);
        if(productId.HasValue||categoryId.HasValue)await db.ExecuteAsync(new CommandDefinition(@"INSERT dbo.SecurityIncidentItems(TenantId,StoreId,SecurityIncidentId,ProductId,ProductCategoryId,DisplayDescription,Quantity,UnitValue,ProductConfidence,PaymentMatchStatus)
VALUES(@TenantId,@StoreId,@IncidentId,@ProductId,@CategoryId,N'Probable product/category association',1,@UnitValue,@Confidence,@PaymentStatus)",new{exit.TenantId,exit.StoreId,IncidentId=incidentId,ProductId=productId,CategoryId=categoryId,UnitValue=signals.ProductValue,Confidence=pickup?.Confidence??exit.Confidence,PaymentStatus=(byte)SecurityPaymentMatchStatus.NoMatch},tx,cancellationToken:ct)).ConfigureAwait(false);
        if(evidenceMetadata is not null){var hash=ValidateEvidenceMetadata(evidenceMetadata,exit.OccurredUtc);await db.ExecuteAsync(new CommandDefinition(@"INSERT dbo.SecurityIncidentEvidence(TenantId,StoreId,SecurityIncidentId,EvidenceType,CameraId,CapturedUtc,StorageObjectKey,ContentHash,StartUtc,EndUtc,RetentionUntilUtc,IsRestricted)
VALUES(@TenantId,@StoreId,@IncidentId,@EvidenceType,@CameraId,@CapturedUtc,@ObjectKey,@ContentHash,@StartUtc,@EndUtc,@RetentionUntilUtc,1)",new{exit.TenantId,exit.StoreId,IncidentId=incidentId,EvidenceType=evidenceMetadata.EvidenceType,exit.CameraId,CapturedUtc=evidenceMetadata.EvidenceCapturedUtc??exit.OccurredUtc,ObjectKey=evidenceMetadata.EvidenceObjectKey,ContentHash=hash,StartUtc=exit.OccurredUtc.AddSeconds(-settings.EvidenceBeforeSeconds),EndUtc=exit.OccurredUtc.AddSeconds(settings.EvidenceAfterSeconds),RetentionUntilUtc=exit.OccurredUtc.AddDays(settings.EvidenceRetentionDays)},tx,cancellationToken:ct)).ConfigureAwait(false);}
        if(!settings.ShadowMode&&settings.RealtimeAlertsEnabled)await db.ExecuteAsync(new CommandDefinition(@"UPDATE dbo.SecurityIncidents SET Status=3,UpdatedUtc=SYSUTCDATETIME() WHERE TenantId=@TenantId AND StoreId=@StoreId AND Id=@IncidentId AND Status=2;
INSERT dbo.SecurityIncidentActions(TenantId,StoreId,SecurityIncidentId,ActionType,FromStatus,ToStatus,ActorType,ReasonCode,CorrelationId)VALUES(@TenantId,@StoreId,@IncidentId,N'Alerted',2,3,N'System',N'REALTIME_THRESHOLD',@CorrelationId)",new{exit.TenantId,exit.StoreId,IncidentId=incidentId,CorrelationId=correlationId},tx,cancellationToken:ct)).ConfigureAwait(false);
        if(!settings.ShadowMode&&settings.RealtimeAlertsEnabled)foreach(var channel in settings.NotificationChannels.Append("InApp").Distinct(StringComparer.OrdinalIgnoreCase))await db.ExecuteAsync(new CommandDefinition(@"INSERT dbo.SecurityNotificationDeliveries(TenantId,StoreId,SecurityIncidentId,Channel,DestinationReference,Status,AttemptCount,QueuedUtc,NextAttemptUtc,IdempotencyKey)
VALUES(@TenantId,@StoreId,@IncidentId,@Channel,@Link,1,0,SYSUTCDATETIME(),SYSUTCDATETIME(),@Key)",new{exit.TenantId,exit.StoreId,IncidentId=incidentId,Channel=channel,Link=$"/admin/security/incidents/{incidentId}",Key=$"security-created:{incidentId}:{channel.ToUpperInvariant()}"},tx,cancellationToken:ct)).ConfigureAwait(false);
        await tx.CommitAsync(ct).ConfigureAwait(false);
        if(!settings.ShadowMode&&settings.RealtimeAlertsEnabled){await realtime.PublishAsync(new(evaluation.Severity==SecuritySeverity.Critical?"security.incident.critical":"security.incident.created",exit.TenantId,exit.StoreId,incidentId,incidentNumber,SecurityIncidentStatus.Alerted,evaluation.Severity,evaluation.Score,clock.GetUtcNow().UtcDateTime,correlationId),ct).ConfigureAwait(false);}
        return new(0,false,incidentId,evaluation.Score,false,settings.ShadowMode?"shadow-candidate":"candidate");
    }

    public async Task<IReadOnlyList<SecurityIncidentSummary>>ListIncidentsAsync(long?storeId,SecurityIncidentStatus?status,int take=100,CancellationToken ct=default)
    {var tenant=RequireTenant();var stores=await StoresAsync(storeId,ct).ConfigureAwait(false);take=Math.Clamp(take,1,200);await using var db=await connections.OpenConnectionAsync(ct).ConfigureAwait(false);var rows=await db.QueryAsync<IncidentRow>(new CommandDefinition(@"SELECT TOP(@Take)Id,IncidentNumber,StoreId,PersonTrackId,Severity,RiskScore,RuleVersion,Status,EstimatedLossAmount,Currency,AssignedUserId,ResolutionCode,CreatedUtc,UpdatedUtc FROM dbo.SecurityIncidents WHERE TenantId=@TenantId AND StoreId IN @Stores AND (@Status IS NULL OR Status=@Status) ORDER BY CreatedUtc DESC,Id DESC",new{Take=take,TenantId=tenant,Stores=stores,Status=(byte?)status},cancellationToken:ct)).ConfigureAwait(false);return rows.Select(Map).ToArray();}

    public async Task<SecurityIncidentDetail>GetIncidentAsync(long id,CancellationToken ct=default)
    {var tenant=RequireTenant();var stores=await StoresAsync(null,ct).ConfigureAwait(false);await using var db=await connections.OpenConnectionAsync(ct).ConfigureAwait(false);var incident=await db.QuerySingleOrDefaultAsync<IncidentRow>(new CommandDefinition(@"SELECT Id,IncidentNumber,StoreId,PersonTrackId,Severity,RiskScore,RuleVersion,Status,EstimatedLossAmount,Currency,AssignedUserId,ResolutionCode,CreatedUtc,UpdatedUtc FROM dbo.SecurityIncidents WHERE TenantId=@TenantId AND StoreId IN @Stores AND Id=@Id",new{TenantId=tenant,Stores=stores,Id=id},cancellationToken:ct)).ConfigureAwait(false)??throw Fail("Security incident was not found.",SecurityFailureKind.NotFound);var items=(await db.QueryAsync<SecurityIncidentItemView>(new CommandDefinition(@"SELECT Id,ProductId,ProductCategoryId,DisplayDescription Description,Quantity,UnitValue,ProductConfidence,PaymentMatchStatus FROM dbo.SecurityIncidentItems WHERE TenantId=@TenantId AND StoreId=@StoreId AND SecurityIncidentId=@Id ORDER BY Id",new{TenantId=tenant,incident.StoreId,Id=id},cancellationToken:ct)).ConfigureAwait(false)).AsList();var payments=(await db.QueryAsync<SecurityPaymentCorrelationView>(new CommandDefinition(@"SELECT Id,InvoiceId,TransactionReference,MatchType,MatchScore,MatchedUtc,Notes FROM dbo.SecurityPaymentCorrelations WHERE TenantId=@TenantId AND StoreId=@StoreId AND SecurityIncidentId=@Id ORDER BY MatchedUtc DESC",new{TenantId=tenant,incident.StoreId,Id=id},cancellationToken:ct)).ConfigureAwait(false)).AsList();IReadOnlyList<SecurityEvidenceView>evidence=currentUser.Permissions.Contains(PermissionCatalog.Security.EvidenceView)?await EvidenceRowsAsync(db,tenant,incident.StoreId,id,ct).ConfigureAwait(false):[];var timeline=await TimelineRowsAsync(db,tenant,incident.StoreId,id,ct).ConfigureAwait(false);return new(Map(incident),items,payments,evidence,timeline);}

    public async Task<SecurityIncidentDetail>AssignAsync(long id,long userId,TenantAuditContext audit,CancellationToken ct=default)
    {var detail=await GetIncidentAsync(id,ct).ConfigureAwait(false);var tenant=RequireTenant();await using var db=await connections.OpenConnectionAsync(ct).ConfigureAwait(false);var eligible=await db.ExecuteScalarAsync<int>(new CommandDefinition(@"SELECT COUNT(1) FROM dbo.Users u JOIN dbo.UserStoreAssignments a ON a.TenantId=u.TenantId AND a.UserId=u.Id WHERE u.TenantId=@TenantId AND u.Id=@UserId AND u.IsActive=1 AND a.StoreId=@StoreId",new{TenantId=tenant,UserId=userId,detail.Incident.StoreId},cancellationToken:ct)).ConfigureAwait(false)>0;if(!eligible)throw Fail("Reviewer is not assigned to the incident store.",SecurityFailureKind.Validation);await db.ExecuteAsync(new CommandDefinition(@"UPDATE dbo.SecurityIncidents SET AssignedUserId=@UserId,UpdatedUtc=SYSUTCDATETIME() WHERE TenantId=@TenantId AND StoreId=@StoreId AND Id=@Id;INSERT dbo.SecurityIncidentActions(TenantId,StoreId,SecurityIncidentId,ActionType,UserId,ActorType,Notes,CorrelationId)VALUES(@TenantId,@StoreId,@Id,N'Assigned',@Actor,N'Human',CONVERT(NVARCHAR(50),@UserId),@CorrelationId)",new{TenantId=tenant,StoreId=detail.Incident.StoreId,Id=id,UserId=userId,Actor=audit.ActorUserId,audit.CorrelationId},cancellationToken:ct)).ConfigureAwait(false);return await GetIncidentAsync(id,ct).ConfigureAwait(false);}

    public async Task<SecurityIncidentDetail>TransitionAsync(long id,SecurityIncidentStatus target,string?reason,string?notes,TenantAuditContext audit,CancellationToken ct=default)
    {var detail=await GetIncidentAsync(id,ct).ConfigureAwait(false);try{SecurityIncidentStateMachine.RequireTransition(detail.Incident.Status,target,target==SecurityIncidentStatus.ConfirmedLoss,reason);}catch(InvalidOperationException ex){throw Fail(ex.Message,SecurityFailureKind.Conflict);}var tenant=RequireTenant();await using var db=await connections.OpenConnectionAsync(ct).ConfigureAwait(false);var rowVersion=await db.QuerySingleAsync<byte[]>(new CommandDefinition("SELECT RowVersion FROM dbo.SecurityIncidents WHERE TenantId=@TenantId AND StoreId=@StoreId AND Id=@Id",new{TenantId=tenant,detail.Incident.StoreId,Id=id},cancellationToken:ct)).ConfigureAwait(false);await db.ExecuteAsync(new CommandDefinition("dbo.SecurityIncident_Transition",new{TenantId=tenant,detail.Incident.StoreId,IncidentId=id,ToStatus=(byte)target,UserId=audit.ActorUserId,ReasonCode=reason,Notes=notes,ExpectedRowVersion=rowVersion,audit.CorrelationId},commandType:CommandType.StoredProcedure,cancellationToken:ct)).ConfigureAwait(false);if(target is SecurityIncidentStatus.FalsePositive or SecurityIncidentStatus.ConfirmedLoss)await UpdateEvidenceRetentionAsync(db,tenant,detail.Incident.StoreId,id,target,ct).ConfigureAwait(false);var updated=await GetIncidentAsync(id,ct).ConfigureAwait(false);var eventName=target switch{SecurityIncidentStatus.Acknowledged=>"security.incident.acknowledged",SecurityIncidentStatus.Resolved or SecurityIncidentStatus.FalsePositive=>"security.incident.resolved",_=>"security.incident.updated"};await realtime.PublishAsync(new(eventName,tenant,updated.Incident.StoreId,id,updated.Incident.IncidentNumber,target,updated.Incident.Severity,updated.Incident.RiskScore,clock.GetUtcNow().UtcDateTime,audit.CorrelationId),ct).ConfigureAwait(false);return updated;}

    public async Task<IReadOnlyList<SecurityActionView>>TimelineAsync(long id,CancellationToken ct=default)=>(await GetIncidentAsync(id,ct).ConfigureAwait(false)).Timeline;
    public async Task<IReadOnlyList<SecurityEvidenceView>>EvidenceAsync(long id,TenantAuditContext audit,CancellationToken ct=default){var detail=await GetIncidentAsync(id,ct).ConfigureAwait(false);await AuditEvidenceAsync(detail.Incident,id,null,"EvidenceListed",audit,ct).ConfigureAwait(false);return detail.Evidence;}
    public async Task<SecurityEvidenceTicket>EvidenceTicketAsync(long incidentId,long evidenceId,bool isExport,TenantAuditContext audit,CancellationToken ct=default){var detail=await GetIncidentAsync(incidentId,ct).ConfigureAwait(false);if(!detail.Evidence.Any(x=>x.Id==evidenceId&&x.Available))throw Fail("Evidence was not found or has expired.",SecurityFailureKind.NotFound);await AuditEvidenceAsync(detail.Incident,incidentId,evidenceId,isExport?"EvidenceExportAuthorized":"EvidenceViewAuthorized",audit,ct).ConfigureAwait(false);return evidenceTokens.Create(evidenceId,incidentId,audit.ActorUserId,RequireTenant(),isExport,clock.GetUtcNow().UtcDateTime.AddMinutes(5));}
    public async Task<SecurityEvidenceFile>OpenEvidenceAsync(long incidentId,long evidenceId,string token,bool isExport,TenantAuditContext audit,CancellationToken ct=default){var detail=await GetIncidentAsync(incidentId,ct).ConfigureAwait(false);evidenceTokens.Validate(token,evidenceId,incidentId,audit.ActorUserId,RequireTenant(),isExport,clock.GetUtcNow().UtcDateTime);await using var db=await connections.OpenConnectionAsync(ct).ConfigureAwait(false);var args=new{TenantId=RequireTenant(),detail.Incident.StoreId,IncidentId=incidentId,EvidenceId=evidenceId};var key=await db.QuerySingleOrDefaultAsync<string>(new CommandDefinition("SELECT StorageObjectKey FROM dbo.CameraEvidence WHERE TenantId=@TenantId AND StoreId=@StoreId AND SecurityIncidentId=@IncidentId AND Id=@EvidenceId AND EvidenceType IN(3,4) AND DeletedUtc IS NULL AND RetentionUntilUtc>SYSUTCDATETIME()",args,cancellationToken:ct)).ConfigureAwait(false);key??=await db.QuerySingleOrDefaultAsync<string>(new CommandDefinition("SELECT StorageObjectKey FROM dbo.SecurityIncidentEvidence WHERE TenantId=@TenantId AND StoreId=@StoreId AND SecurityIncidentId=@IncidentId AND Id=@EvidenceId AND DeletedUtc IS NULL AND RetentionUntilUtc>SYSUTCDATETIME()",args,cancellationToken:ct)).ConfigureAwait(false);if(key is null)throw Fail("Evidence was not found or has expired.",SecurityFailureKind.NotFound);var stream=await evidenceStore.OpenDecryptedAsync(key,ct).ConfigureAwait(false);await AuditEvidenceAsync(detail.Incident,incidentId,evidenceId,isExport?"EvidenceExported":"EvidenceViewed",audit,ct).ConfigureAwait(false);return new(stream,"application/octet-stream",$"security-evidence-{evidenceId}.bin");}

    public async Task<SecuritySettingsView>GetSettingsAsync(long?storeId,CancellationToken ct=default){var tenant=RequireTenant();if(storeId.HasValue)await StoresAsync(storeId,ct).ConfigureAwait(false);await using var db=await connections.OpenConnectionAsync(ct).ConfigureAwait(false);return await LoadSettingsAsync(db,tenant,storeId,ct).ConfigureAwait(false);}
    public async Task<SecuritySettingsView>SaveSettingsAsync(long?storeId,SaveSecuritySettingsCommand command,TenantAuditContext audit,CancellationToken ct=default){ValidateSettings(command);var json=JsonSerializer.Serialize(command);await SaveRuleAsync(storeId,new(SettingsCode,"Store security settings",true,SecuritySeverity.Medium,json),audit,ct).ConfigureAwait(false);return await GetSettingsAsync(storeId,ct).ConfigureAwait(false);}
    public async Task<IReadOnlyList<SecurityRuleView>>ListRulesAsync(long?storeId,CancellationToken ct=default){var tenant=RequireTenant();if(storeId.HasValue)await StoresAsync(storeId,ct).ConfigureAwait(false);await using var db=await connections.OpenConnectionAsync(ct).ConfigureAwait(false);return (await db.QueryAsync<SecurityRuleView>(new CommandDefinition("dbo.SecurityRule_List",new{TenantId=tenant,StoreId=storeId},commandType:CommandType.StoredProcedure,cancellationToken:ct)).ConfigureAwait(false)).AsList();}
    public async Task<SecurityRuleView>SaveRuleAsync(long?storeId,SaveSecurityRuleCommand command,TenantAuditContext audit,CancellationToken ct=default){var tenant=RequireTenant();if(storeId.HasValue)await StoresAsync(storeId,ct).ConfigureAwait(false);if(string.IsNullOrWhiteSpace(command.RuleCode)||command.RuleCode.Length>100||string.IsNullOrWhiteSpace(command.Name)||command.Name.Length>200)throw Fail("Rule code/name is invalid.",SecurityFailureKind.Validation);try{using var doc=JsonDocument.Parse(command.ConfigurationJson);if(doc.RootElement.ValueKind!=JsonValueKind.Object)throw new JsonException();}catch(JsonException){throw Fail("Rule configuration must be a JSON object.",SecurityFailureKind.Validation);}await using var db=await connections.OpenConnectionAsync(ct).ConfigureAwait(false);return await db.QuerySingleAsync<SecurityRuleView>(new CommandDefinition("dbo.SecurityRule_CreateVersion",new{TenantId=tenant,StoreId=storeId,command.RuleCode,command.Name,IsEnabled=command.Enabled,Severity=(byte)command.Severity,command.ConfigurationJson,UserId=audit.ActorUserId,audit.CorrelationId},commandType:CommandType.StoredProcedure,cancellationToken:ct)).ConfigureAwait(false);}
    public async Task<SecurityReportView>ReportAsync(long?storeId,DateTime fromUtc,DateTime toUtc,CancellationToken ct=default){if(toUtc<=fromUtc||toUtc-fromUtc>TimeSpan.FromDays(366))throw Fail("Report range is invalid.",SecurityFailureKind.Validation);var tenant=RequireTenant();var stores=await StoresAsync(storeId,ct).ConfigureAwait(false);await using var db=await connections.OpenConnectionAsync(ct).ConfigureAwait(false);var x=await db.QuerySingleAsync<ReportRow>(new CommandDefinition(@"SELECT COUNT_BIG(*) CandidateCount,SUM(CASE WHEN Status>=3 THEN 1 ELSE 0 END) AlertedCount,SUM(CASE WHEN Status=6 THEN 1 ELSE 0 END) ConfirmedLossCount,SUM(CASE WHEN Status=7 THEN 1 ELSE 0 END) FalsePositiveCount,SUM(CASE WHEN Status=8 THEN 1 ELSE 0 END) ResolvedCount,COALESCE(AVG(CONVERT(DECIMAL(18,3),RiskScore)),0) AverageRisk FROM dbo.SecurityIncidents WHERE TenantId=@TenantId AND StoreId IN @Stores AND CreatedUtc>=@FromUtc AND CreatedUtc<@ToUtc",new{TenantId=tenant,Stores=stores,FromUtc=fromUtc,ToUtc=toUtc},cancellationToken:ct)).ConfigureAwait(false);var reviewed=x.ConfirmedLossCount+x.FalsePositiveCount;return new(storeId,fromUtc,toUtc,x.CandidateCount,x.AlertedCount,x.ConfirmedLossCount,x.FalsePositiveCount,x.ResolvedCount,x.AverageRisk,reviewed==0?null:decimal.Round((decimal)x.ConfirmedLossCount/reviewed,4),reviewed==0?null:decimal.Round((decimal)x.FalsePositiveCount/reviewed,4));}

    private async Task<SecuritySettingsView>LoadSettingsAsync(System.Data.Common.DbConnection db,long tenant,long?store,CancellationToken ct){var row=await db.QuerySingleOrDefaultAsync<RuleRow>(new CommandDefinition(@"SELECT TOP(1)Id,StoreId,ConfigurationJson,Version FROM dbo.SecurityRules WHERE TenantId=@TenantId AND RuleCode=@Code AND IsEnabled=1 AND (StoreId=@StoreId OR StoreId IS NULL) ORDER BY CASE WHEN StoreId=@StoreId THEN 0 ELSE 1 END,Version DESC",new{TenantId=tenant,StoreId=store,Code=SettingsCode},cancellationToken:ct)).ConfigureAwait(false);if(row is null)return Defaults(store);try{var cmd=JsonSerializer.Deserialize<SaveSecuritySettingsCommand>(row.ConfigurationJson,StrictJson)??throw new JsonException();ValidateSettings(cmd);return MapSettings(store,cmd,row.Version);}catch(JsonException){throw Fail("Stored security settings are invalid.",SecurityFailureKind.Unavailable);}}
    private static SecuritySettingsView Defaults(long?store)=>new(store,false,false,false,true,70m,5000m,30,15,10,20,14,[],"None",0);
    private static SecuritySettingsView MapSettings(long?store,SaveSecuritySettingsCommand x,int version)=>new(store,x.SecurityEnabled,x.UnpaidExitDetectionEnabled,x.RealtimeAlertsEnabled,x.ShadowMode,x.RiskThreshold,x.HighValueThreshold,x.CheckoutCorrelationWindowMinutes,x.ExitGracePeriodSeconds,x.EvidenceBeforeSeconds,x.EvidenceAfterSeconds,x.EvidenceRetentionDays,x.NotificationChannels,x.EscalationPolicy,version);
    private static void ValidateSettings(SaveSecuritySettingsCommand x){if(x.RiskThreshold is<0 or>100||x.HighValueThreshold<0||x.CheckoutCorrelationWindowMinutes is<1 or>1440||x.ExitGracePeriodSeconds is<0 or>600||x.EvidenceBeforeSeconds is<0 or>300||x.EvidenceAfterSeconds is<0 or>300||x.EvidenceRetentionDays is<1 or>3650||x.NotificationChannels.Length>10)throw Fail("Security settings are outside allowed ranges.",SecurityFailureKind.Validation);if(x.NotificationChannels.Any(c=>c is not("InApp" or "Push" or "SMS" or "WhatsApp" or "Email")))throw Fail("Unsupported notification channel.",SecurityFailureKind.Validation);}
    private async Task UpdateEvidenceRetentionAsync(System.Data.Common.DbConnection db,long tenant,long store,long incident,SecurityIncidentStatus status,CancellationToken ct){var column=status==SecurityIncidentStatus.FalsePositive?"FalsePositiveRetentionDays":"ConfirmedIncidentRetentionDays";var fallback=status==SecurityIncidentStatus.FalsePositive?3:30;var days=await db.ExecuteScalarAsync<int?>(new CommandDefinition($"SELECT {column} FROM dbo.TenantStoragePolicies WHERE TenantId=@TenantId",new{TenantId=tenant},cancellationToken:ct)).ConfigureAwait(false)??fallback;var retention=clock.GetUtcNow().UtcDateTime.AddDays(days);var comparison=status==SecurityIncidentStatus.FalsePositive?">":"<";await db.ExecuteAsync(new CommandDefinition($"UPDATE dbo.CameraEvidence SET RetentionUntilUtc=@RetentionUntilUtc WHERE TenantId=@TenantId AND StoreId=@StoreId AND SecurityIncidentId=@IncidentId AND DeletedUtc IS NULL AND RetentionUntilUtc{comparison}@RetentionUntilUtc;UPDATE dbo.SecurityIncidentEvidence SET RetentionUntilUtc=@RetentionUntilUtc WHERE TenantId=@TenantId AND StoreId=@StoreId AND SecurityIncidentId=@IncidentId AND DeletedUtc IS NULL AND RetentionUntilUtc{comparison}@RetentionUntilUtc",new{RetentionUntilUtc=retention,TenantId=tenant,StoreId=store,IncidentId=incident},cancellationToken:ct)).ConfigureAwait(false);}
    private async Task<PaidRow?>FindPaidMatchAsync(System.Data.Common.DbConnection db,SecurityObservationRequest x,long?product,long?category,int minutes,CancellationToken ct){if(x.VisitId is null||(product is null&&category is null))return null;return await db.QuerySingleOrDefaultAsync<PaidRow>(new CommandDefinition(@"SELECT TOP(1)i.Id InvoiceId,i.InvoiceNumber TransactionReference FROM dbo.RetailInvoices i JOIN dbo.RetailInvoiceItems li ON li.TenantId=i.TenantId AND li.InvoiceId=i.Id WHERE i.TenantId=@TenantId AND i.StoreId=@StoreId AND i.CustomerVisitId=@VisitId AND i.Status=4 AND i.BalanceAmount=0 AND i.CancelledUtc IS NULL AND i.InvoiceUtc BETWEEN DATEADD(MINUTE,-@Minutes,@OccurredUtc) AND DATEADD(MINUTE,@Minutes,@OccurredUtc) AND ((@ProductId IS NOT NULL AND li.ProductId=@ProductId) OR (@CategoryId IS NOT NULL AND li.CategoryId=@CategoryId)) ORDER BY i.InvoiceUtc DESC",new{x.TenantId,x.StoreId,x.VisitId,Minutes=minutes,x.OccurredUtc,ProductId=product,CategoryId=category},cancellationToken:ct)).ConfigureAwait(false);}
    private async Task<long[]>StoresAsync(long?requested,CancellationToken ct){var tenant=RequireTenant();await using var db=await connections.OpenConnectionAsync(ct).ConfigureAwait(false);if(requested.HasValue){if(!TenantWide()&&!currentUser.StoreIds.Contains(requested.Value))throw Fail("Store is outside the authorized scope.",SecurityFailureKind.Forbidden);var exists=await db.ExecuteScalarAsync<int>(new CommandDefinition("SELECT COUNT(1) FROM dbo.Stores WHERE TenantId=@TenantId AND Id=@Id AND IsActive=1",new{TenantId=tenant,Id=requested},cancellationToken:ct)).ConfigureAwait(false)>0;if(!exists)throw Fail("Store was not found.",SecurityFailureKind.NotFound);return[requested.Value];}if(TenantWide())return(await db.QueryAsync<long>(new CommandDefinition("SELECT Id FROM dbo.Stores WHERE TenantId=@TenantId AND IsActive=1",new{TenantId=tenant},cancellationToken:ct)).ConfigureAwait(false)).ToArray();return currentUser.StoreIds.ToArray();}
    private long RequireTenant()=>currentUser.IsAuthenticated&&!currentUser.IsPlatformAdmin&&currentUser.TenantId is>0?currentUser.TenantId.Value:throw Fail("Tenant session is required.",SecurityFailureKind.Forbidden);
    private bool TenantWide()=>PhaseFiveAccessRules.ContainsTenantWideRole(currentUser.Roles);
    private static void ValidateObservation(SecurityObservationRequest x,DateTime now){if(x.TenantId<=0||x.StoreId<=0||x.CameraId<=0||!Enum.IsDefined(x.ObservationType)||x.Confidence is<0 or>1||x.OccurredUtc.Kind!=DateTimeKind.Utc||x.OccurredUtc>now.AddMinutes(1)||string.IsNullOrWhiteSpace(x.ModelVersion)||x.ModelVersion.Length>100||(x.PersonTrackId?.Length??0)>200||(x.MetadataJson?.Length??0)>4000)throw Fail("Normalized observation fields are invalid.",SecurityFailureKind.Validation);if(x.MetadataJson is not null){try{using var _=JsonDocument.Parse(x.MetadataJson);}catch(JsonException){throw Fail("Observation metadata is invalid JSON.",SecurityFailureKind.Validation);}}}
    private static void ValidateSignature(string secret,SecurityIngestionEnvelope x){var bodyHash=Convert.ToHexString(SHA256.HashData(x.Body)).ToLowerInvariant();var canonical=$"{x.Timestamp}\n{x.Nonce}\n{x.IdempotencyKey}\n{bodyHash}";var expected=HMACSHA256.HashData(Encoding.UTF8.GetBytes(secret),Encoding.UTF8.GetBytes(canonical));byte[] supplied;try{supplied=Convert.FromHexString(x.Signature.StartsWith("sha256=",StringComparison.OrdinalIgnoreCase)?x.Signature[7..]:x.Signature);}catch(FormatException){throw Fail("AI service signature is invalid.",SecurityFailureKind.Unauthorized);}if(supplied.Length!=expected.Length||!CryptographicOperations.FixedTimeEquals(supplied,expected))throw Fail("AI service signature is invalid.",SecurityFailureKind.Unauthorized);}
    private static DateTime ParseTimestamp(string value){if(!long.TryParse(value,NumberStyles.None,CultureInfo.InvariantCulture,out var seconds))throw Fail("Signed timestamp is invalid.",SecurityFailureKind.Unauthorized);try{return DateTimeOffset.FromUnixTimeSeconds(seconds).UtcDateTime;}catch(ArgumentOutOfRangeException){throw Fail("Signed timestamp is invalid.",SecurityFailureKind.Unauthorized);}}
    private static Metadata ReadMetadata(string?json){if(string.IsNullOrWhiteSpace(json))return new();try{return JsonSerializer.Deserialize<Metadata>(json,StrictJson)??new();}catch(JsonException){return new();}}
    private static byte[]ValidateEvidenceMetadata(Metadata value,DateTime occurredUtc){var objectKey=value.EvidenceObjectKey!;if(Path.IsPathRooted(objectKey)||objectKey.Contains("..",StringComparison.Ordinal)||objectKey.Contains(':')||objectKey.Length>500||value.EvidenceType is<1 or>2||Math.Abs(((value.EvidenceCapturedUtc??occurredUtc)-occurredUtc).TotalMinutes)>5)throw Fail("Evidence metadata is invalid.",SecurityFailureKind.Validation);try{var hash=Convert.FromHexString(value.EvidenceContentHashHex!);if(hash.Length!=32)throw new FormatException();return hash;}catch(FormatException){throw Fail("Evidence content hash is invalid.",SecurityFailureKind.Validation);}}
    private static SecurityIncidentSummary Map(IncidentRow x)=>new(x.Id,x.IncidentNumber,x.StoreId,x.PersonTrackId,(SecuritySeverity)x.Severity,x.RiskScore,x.RuleVersion,(SecurityIncidentStatus)x.Status,x.EstimatedLossAmount,x.Currency,x.AssignedUserId,x.ResolutionCode,x.CreatedUtc,x.UpdatedUtc);
    private static async Task<IReadOnlyList<SecurityEvidenceView>>EvidenceRowsAsync(System.Data.Common.DbConnection db,long tenant,long store,long incident,CancellationToken ct){var args=new{TenantId=tenant,StoreId=store,IncidentId=incident};var unified=(await db.QueryAsync<SecurityEvidenceView>(new CommandDefinition("SELECT Id,EvidenceType,CameraId,CapturedUtc,CONVERT(BIT,CASE WHEN DeletedUtc IS NULL AND RetentionUntilUtc>SYSUTCDATETIME() THEN 1 ELSE 0 END) Available,RetentionUntilUtc,IsRestricted Restricted FROM dbo.CameraEvidence WHERE TenantId=@TenantId AND StoreId=@StoreId AND SecurityIncidentId=@IncidentId AND EvidenceType IN(3,4) ORDER BY CapturedUtc",args,cancellationToken:ct)).ConfigureAwait(false)).AsList();if(unified.Count>0)return unified;return(await db.QueryAsync<SecurityEvidenceView>(new CommandDefinition("SELECT Id,EvidenceType,CameraId,CapturedUtc,CONVERT(BIT,CASE WHEN DeletedUtc IS NULL AND RetentionUntilUtc>SYSUTCDATETIME() THEN 1 ELSE 0 END) Available,RetentionUntilUtc,IsRestricted Restricted FROM dbo.SecurityIncidentEvidence WHERE TenantId=@TenantId AND StoreId=@StoreId AND SecurityIncidentId=@IncidentId ORDER BY CapturedUtc",args,cancellationToken:ct)).ConfigureAwait(false)).AsList();}
    private static async Task<IReadOnlyList<SecurityActionView>>TimelineRowsAsync(System.Data.Common.DbConnection db,long tenant,long store,long incident,CancellationToken ct)=>(await db.QueryAsync<SecurityActionView>(new CommandDefinition("SELECT Id,ActionType,FromStatus,ToStatus,UserId,ActorType,ReasonCode,Notes,OccurredUtc,CorrelationId FROM dbo.SecurityIncidentActions WHERE TenantId=@TenantId AND StoreId=@StoreId AND SecurityIncidentId=@IncidentId ORDER BY OccurredUtc,Id",new{TenantId=tenant,StoreId=store,IncidentId=incident},cancellationToken:ct)).ConfigureAwait(false)).AsList();
    private async Task AuditEvidenceAsync(SecurityIncidentSummary incident,long incidentId,long?evidenceId,string action,TenantAuditContext audit,CancellationToken ct){await using var db=await connections.OpenConnectionAsync(ct).ConfigureAwait(false);await db.ExecuteAsync(new CommandDefinition(@"INSERT dbo.SecurityIncidentActions(TenantId,StoreId,SecurityIncidentId,ActionType,UserId,ActorType,Notes,OccurredUtc,CorrelationId)VALUES(@TenantId,@StoreId,@IncidentId,@Action,@UserId,N'Human',@Notes,SYSUTCDATETIME(),@CorrelationId)",new{TenantId=RequireTenant(),incident.StoreId,IncidentId=incidentId,Action=action,UserId=audit.ActorUserId,Notes=evidenceId?.ToString(CultureInfo.InvariantCulture),audit.CorrelationId},cancellationToken:ct)).ConfigureAwait(false);}
    private static SecurityException Fail(string message,SecurityFailureKind kind)=>new(message,kind);
    private sealed class ObservationReceipt{public long Id{get;set;}public long IngestionRequestId{get;set;}public bool WasDuplicate{get;set;}}
    private sealed class SignalRow{public byte ObservationType{get;set;}public DateTime OccurredUtc{get;set;}public decimal Confidence{get;set;}public string?MetadataJson{get;set;}public long?ProductId{get;set;}public long?ProductCategoryId{get;set;}}
    private sealed class IncidentRow{public long Id{get;set;}public string IncidentNumber{get;set;}="";public long StoreId{get;set;}public string?PersonTrackId{get;set;}public byte Severity{get;set;}public decimal RiskScore{get;set;}public int RuleVersion{get;set;}public byte Status{get;set;}public decimal?EstimatedLossAmount{get;set;}public string Currency{get;set;}="INR";public long?AssignedUserId{get;set;}public string?ResolutionCode{get;set;}public DateTime CreatedUtc{get;set;}public DateTime UpdatedUtc{get;set;}}
    private sealed class RuleRow{public long Id{get;set;}public long?StoreId{get;set;}public string ConfigurationJson{get;set;}="{}";public int Version{get;set;}}
    private sealed class PaidRow{public long InvoiceId{get;set;}public string TransactionReference{get;set;}="";}
    private sealed class ReportRow{public long CandidateCount{get;set;}public long AlertedCount{get;set;}public long ConfirmedLossCount{get;set;}public long FalsePositiveCount{get;set;}public long ResolvedCount{get;set;}public decimal AverageRisk{get;set;}}
    private sealed class Metadata{public bool StaffHandling{get;set;}public bool GroupHandoff{get;set;}public bool CrowdedAisle{get;set;}public bool ReEntry{get;set;}public bool RfidEas{get;set;}public decimal OcclusionQuality{get;set;}=1;public int CameraGapSeconds{get;set;}public decimal?ProductValue{get;set;}public string?EvidenceObjectKey{get;set;}public string?EvidenceContentHashHex{get;set;}public byte EvidenceType{get;set;}=1;public DateTime?EvidenceCapturedUtc{get;set;}}
}
