import { ChangeDetectionStrategy, Component, OnInit, computed, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { AuthSessionService } from '../../core/auth/auth-session.service';
import { PERMISSIONS } from '../../core/auth/permission-catalog';
import { AdminShell } from '../../shared/admin-shell/admin-shell';
import { BiometricTemplateMetadata, RecognitionApiService, RecognitionCandidate, RecognitionConsent } from './recognition-api.service';

@Component({selector:'app-recognition-review-page',imports:[AdminShell,FormsModule],changeDetection:ChangeDetectionStrategy.OnPush,template:`
<app-admin-shell pageTitle="Consent-based recognition" eyebrow="Phase 14 · Human-reviewed candidates">
  <p class="boundary">Recognition is off unless a customer has active purpose-specific consent. Anonymous tracks remain anonymous; a candidate never auto-merges or overwrites customer identity.</p>
  @if(!enabled()){<p class="disabled" role="status">RECOGNITION DISABLED — encryption key and policy configuration must be explicitly enabled by an authorized administrator.</p>}
  @if(error()){<p class="error" role="alert">{{error()}}</p>}@if(message()){<p class="ok">{{message()}}</p>}
  <section class="grid"><article class="panel"><h2>Customer consent</h2><label>Customer ID<input type="number" min="1" [(ngModel)]="customerId"></label><button type="button" (click)="loadCustomer()">Load consent & templates</button>
    @for(consent of consents();track consent.id){<div class="item"><b>{{consent.purpose}}</b><span>{{consent.isActive?'Active':'Inactive'}} · {{consent.consentVersion}}</span><small>Granted {{consent.grantedUtc}} · expires {{consent.expiresUtc||'never'}}</small>@if(consent.isActive&&canConsent()){<button type="button" class="danger" (click)="withdraw(consent.id)">Withdraw & erase active template</button>}</div>}
    @if(canConsent()){<form (ngSubmit)="grant()"><h3>Record explicit consent</h3><label>Purpose<input required maxlength="200" name="purpose" [(ngModel)]="consentForm.purpose"></label><label>Consent version<input required maxlength="50" name="version" [(ngModel)]="consentForm.consentVersion"></label><label>Expires (optional)<input type="datetime-local" name="expires" [(ngModel)]="consentForm.expiresUtc"></label><label>Evidence reference<input maxlength="500" name="evidence" [(ngModel)]="consentForm.evidenceReference"></label><button type="submit">Grant consent</button></form>}
  </article><article class="panel"><h2>Encrypted template enrollment</h2><p class="muted">Only a derived template/embedding is accepted. Do not upload a raw frame or image.</p>@for(template of templates();track template.id){<div class="item"><b>Template {{template.id}} · Store {{template.storeId}}</b><span>{{template.algorithm}} / {{template.templateVersion}} · {{templateStatus(template.status)}}</span></div>}
    @if(canEnroll()){<form (ngSubmit)="enroll()"><label>Store ID<input type="number" min="1" required name="store" [(ngModel)]="enrollForm.storeId"></label><label>Active consent ID<input type="number" min="1" required name="consent" [(ngModel)]="enrollForm.consentId"></label><label>Exact consent purpose<input required maxlength="200" name="enrollPurpose" [(ngModel)]="enrollForm.purpose"></label><label>Derived template Base64<textarea required maxlength="32768" name="template" [(ngModel)]="enrollForm.derivedTemplateBase64"></textarea></label><label>Template/model version<input required maxlength="50" name="templateVersion" [(ngModel)]="enrollForm.templateVersion"></label><button type="submit" [disabled]="!enabled()">Enroll encrypted template</button></form>}
  </article></section>
  <section class="panel"><h2>Candidate review queue</h2><div class="actions"><label>Store filter<input type="number" min="1" [(ngModel)]="storeFilter"></label><button type="button" (click)="loadCandidates()">Refresh queue</button></div><div class="table"><b>Track</b><b>Candidate customer</b><b>Scores</b><b>Status</b><b>Review</b>@for(candidate of candidates();track candidate.id){<span>{{candidate.personTrackSessionId}} (anonymous)</span><span>{{candidate.customerId}}</span><span>{{candidate.confidence}} / {{candidate.quality}}</span><span>{{candidateStatus(candidate.status)}}<small>{{candidate.reviewReason}}</small></span><span>@if((candidate.status===1||candidate.status===2)&&canReview()){<button type="button" (click)="review(candidate,true)">Accept candidate</button><button type="button" class="danger" (click)="review(candidate,false)">Reject</button>}</span>}</div><p class="muted">Accepting records a human decision only. It does not associate the anonymous track with the customer.</p></section>
</app-admin-shell>`,styles:[`:host{display:block}.boundary{border-left:4px solid var(--color-accent);padding:.8rem 1rem}.disabled{background:#5b3b00;border:2px solid #ffb020;border-radius:.5rem;color:#fff0c2;font-weight:800;padding:.8rem}.grid{display:grid;grid-template-columns:1fr 1fr;gap:1rem}.panel{background:var(--color-surface);border:1px solid var(--color-border);border-radius:var(--radius-sm);margin-bottom:1rem;padding:1rem}.panel form,.panel label,.item{display:grid;gap:.4rem}.panel form{margin-top:1rem}.panel input,.panel textarea{background:var(--color-background);border:1px solid var(--color-border);border-radius:var(--radius-sm);color:var(--color-text);padding:.65rem}.panel button{background:var(--color-accent);border:0;border-radius:var(--radius-sm);color:var(--color-on-accent);font-weight:700;padding:.65rem}.danger{background:var(--color-danger)!important}.item{border-bottom:1px solid var(--color-border);padding:.7rem 0}.muted,small{color:var(--color-muted);font-size:.8rem}.actions{display:flex;gap:.7rem}.table{display:grid;grid-template-columns:1fr 1fr 1fr 1.3fr 1.2fr;gap:.5rem;overflow:auto}.table>*{border-bottom:1px solid var(--color-border);display:grid;gap:.3rem;padding:.5rem}.error{color:var(--color-danger)}.ok{color:var(--color-success)}@media(max-width:850px){.grid{grid-template-columns:1fr}.table{grid-template-columns:repeat(5,minmax(9rem,1fr))}}`],})
export class RecognitionReviewPage implements OnInit{
  private readonly api=inject(RecognitionApiService);private readonly session=inject(AuthSessionService);protected customerId=0;protected storeFilter=0;protected readonly enabled=signal(false);protected readonly consents=signal<RecognitionConsent[]>([]);protected readonly templates=signal<BiometricTemplateMetadata[]>([]);protected readonly candidates=signal<RecognitionCandidate[]>([]);protected readonly error=signal('');protected readonly message=signal('');protected readonly canConsent=computed(()=>this.session.hasPermission(PERMISSIONS.recognitionConsentManage));protected readonly canEnroll=computed(()=>this.session.hasPermission(PERMISSIONS.recognitionEnroll));protected readonly canReview=computed(()=>this.session.hasPermission(PERMISSIONS.recognitionReview));protected consentForm={purpose:'Store welcome',consentVersion:'2026-01',expiresUtc:'',evidenceReference:''};protected enrollForm={storeId:0,consentId:0,purpose:'Store welcome',derivedTemplateBase64:'',templateVersion:'onnx-v1'};
  ngOnInit():void{this.api.settings().subscribe({next:x=>this.enabled.set(x.enabled),error:()=>this.fail('Unable to load recognition policy.')});this.loadCandidates();}
  protected loadCustomer():void{if(this.customerId<1)return;this.api.consents(this.customerId).subscribe({next:x=>this.consents.set(x),error:()=>this.fail('Unable to load consent.')});this.api.templates(this.customerId).subscribe({next:x=>this.templates.set(x),error:()=>this.fail('Unable to load template metadata.')});}
  protected grant():void{if(this.customerId<1)return;const expires=this.consentForm.expiresUtc?new Date(this.consentForm.expiresUtc).toISOString():null;this.api.grantConsent(this.customerId,{consentType:1,purpose:this.consentForm.purpose.trim(),grantedUtc:new Date().toISOString(),expiresUtc:expires,consentVersion:this.consentForm.consentVersion.trim(),evidenceReference:this.consentForm.evidenceReference.trim()||null}).subscribe({next:()=>{this.message.set('Consent recorded.');this.loadCustomer();},error:()=>this.fail('Consent was rejected.')});}
  protected withdraw(id:number):void{this.api.withdrawConsent(id,'Customer withdrawal recorded by authorized operator').subscribe({next:()=>{this.message.set('Consent withdrawn and active template material erased.');this.loadCustomer();this.loadCandidates();},error:()=>this.fail('Consent withdrawal was rejected.')});}
  protected enroll():void{if(this.customerId<1)return;this.api.enroll(this.customerId,this.enrollForm).subscribe({next:()=>{this.message.set('Derived template encrypted and enrolled.');this.enrollForm.derivedTemplateBase64='';this.loadCustomer();},error:()=>this.fail('Enrollment requires active matching consent and store access.')});}
  protected loadCandidates():void{this.api.candidates(this.storeFilter||undefined).subscribe({next:x=>this.candidates.set(x),error:()=>this.fail('Unable to load recognition candidates.')});}
  protected review(candidate:RecognitionCandidate,accept:boolean):void{this.api.review(candidate.id,accept,accept?'Human reviewer accepted the candidate; no automatic merge':'Human reviewer rejected the candidate').subscribe({next:()=>this.loadCandidates(),error:()=>this.fail('Review was rejected; consent may no longer be active.')});}
  protected templateStatus(value:number):string{return({1:'Active',2:'Disabled',3:'Deleted / material erased'} as Record<number,string>)[value]??'Unknown';}protected candidateStatus(value:number):string{return({1:'Pending review',2:'Ambiguous',3:'Accepted candidate',4:'Rejected',5:'Expired'} as Record<number,string>)[value]??'Unknown';}private fail(message:string):void{this.error.set(message);this.message.set('');}
}
