using System.Data;
using System.Text.Json;
using CustSearch.Application.Abstractions.Data;
using CustSearch.Application.Authentication;
using CustSearch.Application.Operations;
using CustSearch.Domain.Entities;
using CustSearch.Domain.Enums;
using CustSearch.Infrastructure.Persistence;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;

namespace CustSearch.Infrastructure.Operations;

public sealed class OperationalPlatformOptions
{
    public const string SectionName="OperationalPlatform";public int LeaseSeconds{get;set;}=60;public int RetentionBatchSize{get;set;}=500;public int RetentionPollMinutes{get;set;}=60;public int HeartbeatSeconds{get;set;}=30;public bool RedisEnabled{get;set;}public string RedisEndpoint{get;set;}=string.Empty;public bool AiServiceEnabled{get;set;}public string AiServiceHealthUrl{get;set;}=string.Empty;
    public bool IsValid()=>LeaseSeconds is>=15 and<=600&&RetentionBatchSize is>=1 and<=5000&&RetentionPollMinutes is>=1 and<=1440&&HeartbeatSeconds is>=10 and<=300&&(!RedisEnabled||Uri.TryCreate(RedisEndpoint,UriKind.Absolute,out _))&&(!AiServiceEnabled||Uri.TryCreate(AiServiceHealthUrl,UriKind.Absolute,out var ai)&&ai.Scheme==Uri.UriSchemeHttps);
}

/// <summary>
/// Provides platform-admin-only health, settings, worker control, retry and retention operations.
/// Tenant/store scopes are validated against authoritative records and secret references are masked.
/// </summary>
public sealed class OperationalPlatformService(CustSearchDbContext db,ICurrentUserContext currentUser,TimeProvider clock,IOptions<OperationalPlatformOptions>options):IOperationalPlatformService
{
    private static readonly string[]WorkerTypes=["notifications","integrations","exports","retention","cctv-operations"];
    public async Task<OperationalHealthView>HealthAsync(CancellationToken ct=default){RequirePlatform(false);var notifications=await db.NotificationOutbox.CountAsync(x=>x.Status==NotificationOutboxStatus.Pending||x.Status==NotificationOutboxStatus.Failed||x.Status==NotificationOutboxStatus.Retrying,ct);var notificationDead=await db.NotificationOutbox.CountAsync(x=>x.Status==NotificationOutboxStatus.DeadLetter,ct);var integrations=await db.IntegrationOutbox.CountAsync(x=>x.Status==IntegrationOutboxStatus.Pending||x.Status==IntegrationOutboxStatus.Failed||x.Status==IntegrationOutboxStatus.Retrying,ct);var integrationDead=await db.IntegrationOutbox.CountAsync(x=>x.Status==IntegrationOutboxStatus.DeadLetter,ct);var exports=await db.ExportJobs.CountAsync(x=>x.Status==ExportJobStatus.Queued||x.Status==ExportJobStatus.Processing,ct);var exportFailures=await db.ExportJobs.CountAsync(x=>x.Status==ExportJobStatus.Failed,ct);var oldest=await db.NotificationOutbox.Where(x=>x.Status==NotificationOutboxStatus.Pending).Select(x=>(DateTime?)x.CreatedUtc).MinAsync(ct);var controls=await WorkerControlsAsync(ct);var configured=options.Value;var dependencies=new List<DependencyHealthView>{new("sql-server","Healthy","Authoritative operational state available."),new("redis",configured.RedisEnabled?"Configured":"Disabled",configured.RedisEnabled?"Optional scale-out endpoint configured; SQL remains authoritative.":"Single-node fallback; no Redis dependency."),new("signalr","Ready","Authenticated hub and SQL recovery cursor registered."),new("ai-service",configured.AiServiceEnabled?"Configured":"Disabled",configured.AiServiceEnabled?"Readiness probe enabled.":"Optional dependency disabled.")};return new(dependencies,controls,new(notifications,notificationDead,integrations,integrationDead,exports,exportFailures,oldest));}
    public async Task<IReadOnlyList<OperationalSettingView>>SettingsAsync(CancellationToken ct=default){RequirePlatform(false);return await db.OperationalSettings.AsNoTracking().OrderBy(x=>x.Scope).ThenBy(x=>x.TenantId).ThenBy(x=>x.StoreId).ThenBy(x=>x.Key).Select(x=>new OperationalSettingView(x.Id,x.Scope,x.TenantId,x.StoreId,x.Key,x.ValueJson,x.UpdatedUtc)).ToListAsync(ct);}
    public async Task<OperationalSettingView>SaveSettingAsync(SaveOperationalSettingCommand command,string correlationId,CancellationToken ct=default){RequirePlatform(true);await ValidateScopeAsync(command.Scope,command.TenantId,command.StoreId,ct);var now=Now();var entity=await db.OperationalSettings.SingleOrDefaultAsync(x=>x.Scope==command.Scope&&x.TenantId==command.TenantId&&x.StoreId==command.StoreId&&x.Key==command.Key,ct);if(entity is null){entity=OperationalSetting.Create(command.Scope,command.TenantId,command.StoreId,command.Key,command.ValueJson,now);db.OperationalSettings.Add(entity);}else entity.Update(command.ValueJson,now);Audit("OperationalSettingSaved","OperationalSetting",command.Key,command.TenantId,command.StoreId,correlationId,new{command.Scope,command.Key});await db.SaveChangesAsync(ct);return new(entity.Id,entity.Scope,entity.TenantId,entity.StoreId,entity.Key,entity.ValueJson,entity.UpdatedUtc);}
    public async Task<IReadOnlyList<OperationalSecretReferenceView>>SecretReferencesAsync(CancellationToken ct=default){RequirePlatform(false);var rows=await db.OperationalSecretReferences.AsNoTracking().OrderBy(x=>x.Scope).ThenBy(x=>x.Key).ToListAsync(ct);return rows.Select(x=>new OperationalSecretReferenceView(x.Id,x.Scope,x.TenantId,x.StoreId,x.Key,Mask(x.Reference),x.UpdatedUtc)).ToArray();}
    public async Task<OperationalSecretReferenceView>SaveSecretReferenceAsync(SaveSecretReferenceCommand command,string correlationId,CancellationToken ct=default){RequirePlatform(true);await ValidateScopeAsync(command.Scope,command.TenantId,command.StoreId,ct);var now=Now();var entity=await db.OperationalSecretReferences.SingleOrDefaultAsync(x=>x.Scope==command.Scope&&x.TenantId==command.TenantId&&x.StoreId==command.StoreId&&x.Key==command.Key,ct);if(entity is null){entity=OperationalSecretReference.Create(command.Scope,command.TenantId,command.StoreId,command.Key,command.Reference,now);db.OperationalSecretReferences.Add(entity);}else entity.Rotate(command.Reference,now);Audit("OperationalSecretReferenceRotated","OperationalSecretReference",command.Key,command.TenantId,command.StoreId,correlationId,new{command.Scope,command.Key,referenceMasked=true});await db.SaveChangesAsync(ct);return new(entity.Id,entity.Scope,entity.TenantId,entity.StoreId,entity.Key,Mask(entity.Reference),entity.UpdatedUtc);}
    public async Task<IReadOnlyList<WorkerControlView>>WorkerControlsAsync(CancellationToken ct=default){RequirePlatform(false);var controls=await db.WorkerControls.AsNoTracking().ToDictionaryAsync(x=>x.WorkerType,StringComparer.OrdinalIgnoreCase,ct);return WorkerTypes.Select(x=>controls.TryGetValue(x,out var c)?View(c):new WorkerControlView(x,false,null,null,DateTime.UnixEpoch)).ToArray();}
    public async Task<WorkerControlView>SetWorkerPausedAsync(string workerType,bool paused,string?reason,string correlationId,CancellationToken ct=default){RequirePlatform(true);workerType=NormalizeWorker(workerType);var now=Now();var control=await db.WorkerControls.SingleOrDefaultAsync(x=>x.WorkerType==workerType,ct);if(control is null){control=WorkerControl.Create(workerType,now);db.WorkerControls.Add(control);}control.SetPaused(paused,reason,currentUser.UserId,now);Audit(paused?"WorkerPaused":"WorkerResumed","WorkerControl",workerType,null,null,correlationId,new{workerType,paused,reason=paused?reason:null});await db.SaveChangesAsync(ct);return View(control);}
    public async Task RetryDeadLetterAsync(string queue,long id,string correlationId,CancellationToken ct=default){RequirePlatform(true);ArgumentOutOfRangeException.ThrowIfNegativeOrZero(id);var now=Now();switch(queue.Trim().ToLowerInvariant()){case "notifications":var notification=await db.NotificationOutbox.SingleOrDefaultAsync(x=>x.Id==id,ct)??throw NotFound();notification.RetryManually(now);break;case "integrations":var integration=await db.IntegrationOutbox.SingleOrDefaultAsync(x=>x.Id==id,ct)??throw NotFound();integration.RetryManually(now);break;default:throw new OperationalException("Queue is not eligible for manual retry.",OperationalFailureKind.Validation);}Audit("DeadLetterRetried","QueueMessage",$"{queue}:{id}",null,null,correlationId,new{queue,id});await db.SaveChangesAsync(ct);}
    public async Task<IReadOnlyList<RetentionPolicyView>>RetentionPoliciesAsync(CancellationToken ct=default){RequirePlatform(false);return await db.RetentionPolicies.AsNoTracking().OrderBy(x=>x.Domain).ThenBy(x=>x.TenantId).ThenBy(x=>x.StoreId).Select(x=>new RetentionPolicyView(x.Id,x.Domain,x.TenantId,x.StoreId,x.RetentionDays,x.Enabled,x.UpdatedUtc)).ToListAsync(ct);}
    public async Task<RetentionPolicyView>SaveRetentionPolicyAsync(SaveRetentionPolicyCommand command,string correlationId,CancellationToken ct=default){RequirePlatform(true);if(command.TenantId.HasValue)await ValidateScopeAsync(command.StoreId.HasValue?OperationalScope.Store:OperationalScope.Tenant,command.TenantId,command.StoreId,ct);var now=Now();var policy=await db.RetentionPolicies.SingleOrDefaultAsync(x=>x.Domain==command.Domain&&x.TenantId==command.TenantId&&x.StoreId==command.StoreId,ct);if(policy is null){policy=RetentionPolicy.Create(command.Domain,command.TenantId,command.StoreId,command.RetentionDays,command.Enabled,now);db.RetentionPolicies.Add(policy);}else policy.Update(command.RetentionDays,command.Enabled,now);Audit("RetentionPolicySaved","RetentionPolicy",command.Domain.ToString(),command.TenantId,command.StoreId,correlationId,new{command.Domain,command.RetentionDays,command.Enabled});await db.SaveChangesAsync(ct);return new(policy.Id,policy.Domain,policy.TenantId,policy.StoreId,policy.RetentionDays,policy.Enabled,policy.UpdatedUtc);}
    private void RequirePlatform(bool manage){if(!currentUser.IsAuthenticated||!currentUser.IsPlatformAdmin)throw new OperationalException("Platform operational scope is required.",OperationalFailureKind.Forbidden);var permission=manage?"PlatformOperations.Manage":"PlatformOperations.View";if(!currentUser.Permissions.Contains(permission))throw new OperationalException("Operational permission is required.",OperationalFailureKind.Forbidden);}
    private async Task ValidateScopeAsync(OperationalScope scope,long?tenantId,long?storeId,CancellationToken ct){OperationalSetting.ValidateScope(scope,tenantId,storeId);if(tenantId.HasValue&&!await db.Tenants.AnyAsync(x=>x.Id==tenantId,ct))throw NotFound();if(storeId.HasValue&&!await db.Stores.AnyAsync(x=>x.Id==storeId&&x.TenantId==tenantId,ct))throw NotFound();}
    private void Audit(string action,string entity,string?entityId,long?tenantId,long?storeId,string correlationId,object metadata)=>db.AuditLogs.Add(AuditLog.Record(tenantId,storeId,currentUser.UserId,"PlatformUser",action,entity,entityId,null,JsonSerializer.Serialize(metadata),null,null,correlationId,Now()));
    private static WorkerControlView View(WorkerControl x)=>new(x.WorkerType,x.IsPaused,x.Reason,x.UpdatedByUserId,x.UpdatedUtc);
    private static string Mask(string value)=>value.Length<=4?"****":$"****{value[^4..]}";
    private static string NormalizeWorker(string value){ArgumentException.ThrowIfNullOrWhiteSpace(value);var normalized=value.Trim().ToLowerInvariant();return WorkerTypes.Contains(normalized,StringComparer.Ordinal)?normalized:throw new OperationalException("Unknown worker type.",OperationalFailureKind.Validation);}
    private DateTime Now()=>clock.GetUtcNow().UtcDateTime;
    private static OperationalException NotFound()=>new("Operational resource was not found.",OperationalFailureKind.NotFound);
}

/// <summary>
/// Coordinates database-backed worker leases and heartbeats so multiple processes cannot claim the
/// same batch concurrently; a pause control is checked before a lease is granted.
/// </summary>
public sealed class WorkerRuntimeGate(CustSearchDbContext db,TimeProvider clock):IWorkerRuntimeGate
{
    public async Task<WorkerLeaseHandle?>TryAcquireAsync(string workerType,string ownerId,TimeSpan duration,CancellationToken ct=default){ArgumentException.ThrowIfNullOrWhiteSpace(workerType);ArgumentException.ThrowIfNullOrWhiteSpace(ownerId);if(duration<TimeSpan.FromSeconds(5)||duration>TimeSpan.FromMinutes(10))throw new ArgumentOutOfRangeException(nameof(duration));var now=clock.GetUtcNow().UtcDateTime;await using var transaction=await db.Database.BeginTransactionAsync(IsolationLevel.Serializable,ct);if(await db.WorkerControls.AsNoTracking().AnyAsync(x=>x.WorkerType==workerType&&x.IsPaused,ct)){await transaction.CommitAsync(ct);return null;}var lease=await db.WorkerLeases.SingleOrDefaultAsync(x=>x.WorkerType==workerType,ct);var id=Guid.NewGuid();if(lease is null){lease=WorkerLease.Acquire(workerType,id,ownerId,now,now+duration);db.WorkerLeases.Add(lease);}else{if(lease.ExpiresUtc>now){await transaction.CommitAsync(ct);return null;}lease.Reassign(id,ownerId,now,now+duration);}await db.SaveChangesAsync(ct);await transaction.CommitAsync(ct);return new(workerType,id,ownerId,now+duration);}
    public async Task ReleaseAsync(WorkerLeaseHandle lease,CancellationToken ct=default){var row=await db.WorkerLeases.SingleOrDefaultAsync(x=>x.WorkerType==lease.WorkerType&&x.LeaseId==lease.LeaseId,ct);if(row is null)return;row.Release(lease.LeaseId,clock.GetUtcNow().UtcDateTime);await db.SaveChangesAsync(ct);}
    public async Task HeartbeatAsync(string instanceId,string workerType,bool ready,string?errorMessage,CancellationToken ct=default){var now=clock.GetUtcNow().UtcDateTime;var heartbeat=await db.WorkerHeartbeats.SingleOrDefaultAsync(x=>x.InstanceId==instanceId&&x.WorkerType==workerType,ct);if(heartbeat is null){heartbeat=WorkerHeartbeat.Start(instanceId,workerType,now);db.WorkerHeartbeats.Add(heartbeat);}heartbeat.Beat(ready,errorMessage,now);await db.SaveChangesAsync(ct);}
}

/// <summary>
/// Executes bounded, audited retention batches through the versioned stored procedure. A failed
/// policy is recorded without hiding failures from the operational health surface.
/// </summary>
public sealed class OperationalRetentionProcessor(CustSearchDbContext db,IDbConnectionFactory connections,TimeProvider clock):IRetentionProcessor
{
    public async Task<RetentionBatchResult>RunDueAsync(int batchSize,CancellationToken ct=default){ArgumentOutOfRangeException.ThrowIfLessThan(batchSize,1);ArgumentOutOfRangeException.ThrowIfGreaterThan(batchSize,5000);var policies=await db.RetentionPolicies.Where(x=>x.Enabled).OrderBy(x=>x.Id).ToListAsync(ct);var deleted=0;var failed=0;foreach(var policy in policies){var now=clock.GetUtcNow().UtcDateTime;var run=RetentionRun.Start(policy.Id,Guid.NewGuid(),now);db.RetentionRuns.Add(run);await db.SaveChangesAsync(ct);try{await using var connection=await connections.OpenConnectionAsync(ct);var command=new CommandDefinition("dbo.OperationalRetention_Run",new{PolicyId=policy.Id,BatchSize=batchSize,UtcNow=now},commandType:CommandType.StoredProcedure,cancellationToken:ct);var count=await connection.ExecuteScalarAsync<int>(command);run.Complete(count,clock.GetUtcNow().UtcDateTime);deleted+=count;}catch(Exception exception)when(exception is not OperationCanceledException){run.Fail(exception.Message,clock.GetUtcNow().UtcDateTime);failed++;}await db.SaveChangesAsync(ct);}return new(policies.Count,deleted,failed);}
}
