using CustSearch.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace CustSearch.Infrastructure.Persistence.Configurations;

public sealed class OperationalSettingConfiguration:IEntityTypeConfiguration<OperationalSetting>{public void Configure(EntityTypeBuilder<OperationalSetting>builder){builder.ToTable("OperationalSettings","dbo",t=>t.HasCheckConstraint("CK_OperationalSettings_Scope","([Scope]=1 AND [TenantId] IS NULL AND [StoreId] IS NULL) OR ([Scope]=2 AND [TenantId] IS NOT NULL AND [StoreId] IS NULL) OR ([Scope]=3 AND [TenantId] IS NOT NULL AND [StoreId] IS NOT NULL)"));builder.HasKey(x=>x.Id);builder.Property(x=>x.Key).HasMaxLength(120).IsRequired();builder.Property(x=>x.ValueJson).HasMaxLength(4000).IsRequired();builder.Property(x=>x.CreatedUtc).HasPrecision(7);builder.Property(x=>x.UpdatedUtc).HasPrecision(7);builder.Property(x=>x.RowVersion).IsRowVersion();builder.HasIndex(x=>new{x.Scope,x.TenantId,x.StoreId,x.Key}).IsUnique();}}
public sealed class OperationalSecretReferenceConfiguration:IEntityTypeConfiguration<OperationalSecretReference>{public void Configure(EntityTypeBuilder<OperationalSecretReference>builder){builder.ToTable("OperationalSecretReferences","dbo",t=>t.HasCheckConstraint("CK_OperationalSecretReferences_Scope","([Scope]=1 AND [TenantId] IS NULL AND [StoreId] IS NULL) OR ([Scope]=2 AND [TenantId] IS NOT NULL AND [StoreId] IS NULL) OR ([Scope]=3 AND [TenantId] IS NOT NULL AND [StoreId] IS NOT NULL)"));builder.HasKey(x=>x.Id);builder.Property(x=>x.Key).HasMaxLength(120).IsRequired();builder.Property(x=>x.Reference).HasMaxLength(250).IsRequired();builder.Property(x=>x.CreatedUtc).HasPrecision(7);builder.Property(x=>x.UpdatedUtc).HasPrecision(7);builder.HasIndex(x=>new{x.Scope,x.TenantId,x.StoreId,x.Key}).IsUnique();}}
public sealed class WorkerControlConfiguration:IEntityTypeConfiguration<WorkerControl>{public void Configure(EntityTypeBuilder<WorkerControl>builder){builder.ToTable("WorkerControls","dbo");builder.HasKey(x=>x.WorkerType);builder.Property(x=>x.WorkerType).HasMaxLength(80);builder.Property(x=>x.Reason).HasMaxLength(500);builder.Property(x=>x.UpdatedUtc).HasPrecision(7);builder.Property(x=>x.RowVersion).IsRowVersion();}}
public sealed class WorkerLeaseConfiguration:IEntityTypeConfiguration<WorkerLease>{public void Configure(EntityTypeBuilder<WorkerLease>builder){builder.ToTable("WorkerLeases","dbo");builder.HasKey(x=>x.WorkerType);builder.Property(x=>x.WorkerType).HasMaxLength(80);builder.Property(x=>x.OwnerId).HasMaxLength(150).IsRequired();builder.Property(x=>x.AcquiredUtc).HasPrecision(7);builder.Property(x=>x.RenewedUtc).HasPrecision(7);builder.Property(x=>x.ExpiresUtc).HasPrecision(7);builder.Property(x=>x.RowVersion).IsRowVersion();builder.HasIndex(x=>x.ExpiresUtc);}}
public sealed class RetentionPolicyConfiguration:IEntityTypeConfiguration<RetentionPolicy>{public void Configure(EntityTypeBuilder<RetentionPolicy>builder){builder.ToTable("RetentionPolicies","dbo",t=>{t.HasCheckConstraint("CK_RetentionPolicies_Days","[RetentionDays] BETWEEN 1 AND 36500");t.HasCheckConstraint("CK_RetentionPolicies_Scope","[StoreId] IS NULL OR [TenantId] IS NOT NULL");});builder.HasKey(x=>x.Id);builder.Property(x=>x.CreatedUtc).HasPrecision(7);builder.Property(x=>x.UpdatedUtc).HasPrecision(7);builder.Property(x=>x.RowVersion).IsRowVersion();builder.HasIndex(x=>new{x.Domain,x.TenantId,x.StoreId}).IsUnique();}}
public sealed class RetentionRunConfiguration:IEntityTypeConfiguration<RetentionRun>{public void Configure(EntityTypeBuilder<RetentionRun>builder){builder.ToTable("RetentionRuns","dbo");builder.HasKey(x=>x.Id);builder.Property(x=>x.Status).HasMaxLength(30).IsRequired();builder.Property(x=>x.Error).HasMaxLength(2000);builder.Property(x=>x.StartedUtc).HasPrecision(7);builder.Property(x=>x.CompletedUtc).HasPrecision(7);builder.HasIndex(x=>new{x.PolicyId,x.StartedUtc});builder.HasIndex(x=>x.RunId).IsUnique();}}
public sealed class WorkerHeartbeatConfiguration:IEntityTypeConfiguration<WorkerHeartbeat>{public void Configure(EntityTypeBuilder<WorkerHeartbeat>builder){builder.ToTable("WorkerHeartbeats","dbo");builder.HasKey(x=>new{x.InstanceId,x.WorkerType});builder.Property(x=>x.InstanceId).HasMaxLength(150);builder.Property(x=>x.WorkerType).HasMaxLength(80);builder.Property(x=>x.LastError).HasMaxLength(1000);builder.Property(x=>x.StartedUtc).HasPrecision(7);builder.Property(x=>x.LastHeartbeatUtc).HasPrecision(7);builder.HasIndex(x=>x.LastHeartbeatUtc);}}
