using CustSearch.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace CustSearch.Infrastructure.Persistence.Configurations;

public sealed class OperationalSettingConfiguration:IEntityTypeConfiguration<OperationalSetting>{public void Configure(EntityTypeBuilder<OperationalSetting>b){b.ToTable("OperationalSettings","dbo",t=>t.HasCheckConstraint("CK_OperationalSettings_Scope","([Scope]=1 AND [TenantId] IS NULL AND [StoreId] IS NULL) OR ([Scope]=2 AND [TenantId] IS NOT NULL AND [StoreId] IS NULL) OR ([Scope]=3 AND [TenantId] IS NOT NULL AND [StoreId] IS NOT NULL)"));b.HasKey(x=>x.Id);b.Property(x=>x.Key).HasMaxLength(120).IsRequired();b.Property(x=>x.ValueJson).HasMaxLength(4000).IsRequired();b.Property(x=>x.CreatedUtc).HasPrecision(7);b.Property(x=>x.UpdatedUtc).HasPrecision(7);b.Property(x=>x.RowVersion).IsRowVersion();b.HasIndex(x=>new{x.Scope,x.TenantId,x.StoreId,x.Key}).IsUnique();}}
public sealed class OperationalSecretReferenceConfiguration:IEntityTypeConfiguration<OperationalSecretReference>{public void Configure(EntityTypeBuilder<OperationalSecretReference>b){b.ToTable("OperationalSecretReferences","dbo",t=>t.HasCheckConstraint("CK_OperationalSecretReferences_Scope","([Scope]=1 AND [TenantId] IS NULL AND [StoreId] IS NULL) OR ([Scope]=2 AND [TenantId] IS NOT NULL AND [StoreId] IS NULL) OR ([Scope]=3 AND [TenantId] IS NOT NULL AND [StoreId] IS NOT NULL)"));b.HasKey(x=>x.Id);b.Property(x=>x.Key).HasMaxLength(120).IsRequired();b.Property(x=>x.Reference).HasMaxLength(250).IsRequired();b.Property(x=>x.CreatedUtc).HasPrecision(7);b.Property(x=>x.UpdatedUtc).HasPrecision(7);b.HasIndex(x=>new{x.Scope,x.TenantId,x.StoreId,x.Key}).IsUnique();}}
public sealed class WorkerControlConfiguration:IEntityTypeConfiguration<WorkerControl>{public void Configure(EntityTypeBuilder<WorkerControl>b){b.ToTable("WorkerControls","dbo");b.HasKey(x=>x.WorkerType);b.Property(x=>x.WorkerType).HasMaxLength(80);b.Property(x=>x.Reason).HasMaxLength(500);b.Property(x=>x.UpdatedUtc).HasPrecision(7);b.Property(x=>x.RowVersion).IsRowVersion();}}
public sealed class WorkerLeaseConfiguration:IEntityTypeConfiguration<WorkerLease>{public void Configure(EntityTypeBuilder<WorkerLease>b){b.ToTable("WorkerLeases","dbo");b.HasKey(x=>x.WorkerType);b.Property(x=>x.WorkerType).HasMaxLength(80);b.Property(x=>x.OwnerId).HasMaxLength(150).IsRequired();b.Property(x=>x.AcquiredUtc).HasPrecision(7);b.Property(x=>x.RenewedUtc).HasPrecision(7);b.Property(x=>x.ExpiresUtc).HasPrecision(7);b.Property(x=>x.RowVersion).IsRowVersion();b.HasIndex(x=>x.ExpiresUtc);}}
public sealed class RetentionPolicyConfiguration:IEntityTypeConfiguration<RetentionPolicy>{public void Configure(EntityTypeBuilder<RetentionPolicy>b){b.ToTable("RetentionPolicies","dbo",t=>{t.HasCheckConstraint("CK_RetentionPolicies_Days","[RetentionDays] BETWEEN 1 AND 36500");t.HasCheckConstraint("CK_RetentionPolicies_Scope","[StoreId] IS NULL OR [TenantId] IS NOT NULL");});b.HasKey(x=>x.Id);b.Property(x=>x.CreatedUtc).HasPrecision(7);b.Property(x=>x.UpdatedUtc).HasPrecision(7);b.Property(x=>x.RowVersion).IsRowVersion();b.HasIndex(x=>new{x.Domain,x.TenantId,x.StoreId}).IsUnique();}}
public sealed class RetentionRunConfiguration:IEntityTypeConfiguration<RetentionRun>{public void Configure(EntityTypeBuilder<RetentionRun>b){b.ToTable("RetentionRuns","dbo");b.HasKey(x=>x.Id);b.Property(x=>x.Status).HasMaxLength(30).IsRequired();b.Property(x=>x.Error).HasMaxLength(2000);b.Property(x=>x.StartedUtc).HasPrecision(7);b.Property(x=>x.CompletedUtc).HasPrecision(7);b.HasIndex(x=>new{x.PolicyId,x.StartedUtc});b.HasIndex(x=>x.RunId).IsUnique();}}
public sealed class WorkerHeartbeatConfiguration:IEntityTypeConfiguration<WorkerHeartbeat>{public void Configure(EntityTypeBuilder<WorkerHeartbeat>b){b.ToTable("WorkerHeartbeats","dbo");b.HasKey(x=>new{x.InstanceId,x.WorkerType});b.Property(x=>x.InstanceId).HasMaxLength(150);b.Property(x=>x.WorkerType).HasMaxLength(80);b.Property(x=>x.LastError).HasMaxLength(1000);b.Property(x=>x.StartedUtc).HasPrecision(7);b.Property(x=>x.LastHeartbeatUtc).HasPrecision(7);b.HasIndex(x=>x.LastHeartbeatUtc);}}
