import { ChangeDetectionStrategy, Component, DestroyRef, OnInit, computed, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { timer } from 'rxjs';
import { AuthSessionService } from '../../core/auth/auth-session.service';
import { PERMISSIONS } from '../../core/auth/permission-catalog';
import { AdminShell } from '../../shared/admin-shell/admin-shell';
import { CameraView, CameraZoneType, CameraZoneView, CamerasApiService, PersonTrackView, SaveCameraRequest } from './cameras-api.service';

@Component({selector:'app-camera-operations-page',imports:[AdminShell,FormsModule],changeDetection:ChangeDetectionStrategy.OnPush,template:`
<app-admin-shell pageTitle="Camera operations" eyebrow="Phase 13 · Anonymous operational tracking">
  @if(demoMode()){<p class="demo" role="status">DEMO MODE — deterministic fixtures; no physical RTSP camera is connected.</p>}
  <p class="boundary">Tracking is anonymous by default. Phase 13 does not perform biometric or identity recognition, and staff observations are never payroll, attendance or disciplinary truth.</p>
  @if(error()){<p class="error" role="alert">{{error()}}</p>}
  <section class="summary"><div><b>{{cameras().length}}</b><span>Cameras</span></div><div><b>{{onlineCount()}}</b><span>Online</span></div><div><b>{{activeTracks()}}</b><span>Active tracks</span></div><button type="button" (click)="load()">Refresh</button></section>
  <section class="layout"><div class="panel"><h2>Cameras</h2>@for(camera of cameras();track camera.id){<button type="button" class="item" [class.selected]="selected()?.id===camera.id" (click)="select(camera)"><b>{{camera.cameraCode}} · {{camera.name}}</b><span>Store {{camera.storeId}} · {{status(camera.status)}} · {{camera.rtspConfigurationHint}}</span><small>{{camera.location||'Location not set'}} · heartbeat {{camera.lastHeartbeatUtc||'never'}}</small></button>}@if(cameras().length===0){<p>No cameras configured.</p>}</div>
  <form class="panel form" (ngSubmit)="saveCamera()"><h2>{{selected()?'Edit camera':'New camera'}}</h2><label>Store ID<input name="storeId" type="number" min="1" [(ngModel)]="cameraForm.storeId" required [readonly]="!!selected()"></label><label>Camera code<input name="cameraCode" [(ngModel)]="cameraForm.cameraCode" required maxlength="50" [readonly]="!!selected()"></label><label>Name<input name="name" [(ngModel)]="cameraForm.name" required maxlength="150"></label><label>RTSP configuration reference<input name="rtsp" [(ngModel)]="cameraForm.rtspConfigurationReference" type="password" autocomplete="new-password" [required]="!selected()"><small>Opaque vault/config reference only; credentials are never displayed.</small></label><label>Location<input name="location" [(ngModel)]="cameraForm.location" maxlength="250"></label><label>Direction<select name="direction" [(ngModel)]="cameraForm.direction"><option [ngValue]="1">Entry</option><option [ngValue]="2">Exit</option><option [ngValue]="3">Bidirectional</option><option [ngValue]="4">Internal</option></select></label><label class="check"><input name="active" type="checkbox" [(ngModel)]="cameraForm.isActive"> Active</label>@if(canManage()){<button type="submit">Save camera</button>}<button type="button" class="secondary" (click)="newCamera()">New</button></form></section>
  @if(selected();as camera){<section class="panel"><h2>Zone editor · {{camera.cameraCode}}</h2><div class="zone-layout"><div>@for(zone of zones();track zone.id){<p><b>{{zone.zoneCode}} v{{zone.version}}</b> · {{zoneType(zone.zoneType)}} · {{zone.isActive?'Current':'Superseded'}}</p>}</div><form class="form" (ngSubmit)="saveZone(camera.id)"><label>Zone code<input name="zoneCode" [(ngModel)]="zoneForm.zoneCode" required></label><label>Name<input name="zoneName" [(ngModel)]="zoneForm.name" required></label><label>Type<select name="zoneType" [(ngModel)]="zoneForm.zoneType"><option [ngValue]="1">Entry</option><option [ngValue]="2">Exit</option><option [ngValue]="3">Checkout</option><option [ngValue]="4">Shelf</option><option [ngValue]="5">Category</option><option [ngValue]="6">Restricted</option><option [ngValue]="7">Staff area</option></select></label><label>Normalized polygon JSON<textarea name="geometry" [(ngModel)]="zoneForm.geometryJson" rows="4"></textarea></label>@if(canManage()){<button type="submit">Create zone version</button>}</form></div></section>}
  <section class="panel"><h2>Operational tracking sessions</h2><p class="muted">Auto-recovers authoritative track state every 5 seconds.</p><div class="tracks"><b>Track</b><b>Store / camera</b><b>State</b><b>Subject</b><b>Confidence</b><b>Updated</b>@for(track of tracks();track track.id){<span>{{track.personTrackId}}</span><span>{{track.storeId}} / {{track.cameraId}}</span><span>{{trackState(track.trackingState)}}</span><span>{{subject(track)}}</span><span>{{track.confidence}}</span><span>{{track.updatedUtc}}</span>}</div></section>
</app-admin-shell>`,styles:[`:host{display:block}.demo{background:#5b3b00;border:2px solid #ffb020;border-radius:.5rem;color:#fff0c2;font-weight:800;padding:.8rem}.boundary{border-left:4px solid var(--color-accent);padding:.7rem 1rem}.summary{display:grid;grid-template-columns:repeat(3,minmax(0,1fr)) auto;gap:.75rem;margin-bottom:1rem}.summary div,.panel{background:var(--color-surface);border:1px solid var(--color-border);border-radius:var(--radius-sm)}.summary div{display:grid;padding:1rem}.summary span,small,.muted{color:var(--color-muted);font-size:.8rem}.layout,.zone-layout{display:grid;grid-template-columns:1fr 1fr;gap:1rem}.panel{padding:1rem;margin-bottom:1rem}.item{background:transparent;border:0;border-bottom:1px solid var(--color-border);color:var(--color-text);display:grid;gap:.25rem;padding:.8rem;text-align:left;width:100%}.item.selected{background:var(--color-nav-active)}.form,.form label{display:grid;gap:.35rem}.form{gap:.7rem}.check{display:flex!important}.panel input,.panel select,.panel textarea{background:var(--color-background);border:1px solid var(--color-border);border-radius:var(--radius-sm);color:var(--color-text);padding:.65rem}.panel button,.summary button{background:var(--color-accent);border:0;border-radius:var(--radius-sm);color:var(--color-on-accent);font-weight:700;padding:.7rem 1rem}.secondary{background:var(--color-nav-active)!important;color:var(--color-text)!important;margin-left:.5rem}.tracks{display:grid;grid-template-columns:1.2fr .8fr .7fr .8fr .6fr 1.2fr;gap:.5rem;overflow:auto}.tracks>*{border-bottom:1px solid var(--color-border);padding:.5rem}.error{color:var(--color-danger)}@media(max-width:850px){.summary,.layout,.zone-layout{grid-template-columns:1fr}.tracks{grid-template-columns:repeat(6,minmax(8rem,1fr))}}`],})
export class CameraOperationsPage implements OnInit{
  private readonly api=inject(CamerasApiService);private readonly session=inject(AuthSessionService);private readonly destroyRef=inject(DestroyRef);protected readonly cameras=signal<CameraView[]>([]);protected readonly zones=signal<CameraZoneView[]>([]);protected readonly tracks=signal<PersonTrackView[]>([]);protected readonly selected=signal<CameraView|null>(null);protected readonly demoMode=signal(false);protected readonly error=signal('');protected readonly canManage=computed(()=>this.session.hasPermission(PERMISSIONS.camerasManage));protected readonly onlineCount=computed(()=>this.cameras().filter(x=>x.status===2).length);protected readonly activeTracks=computed(()=>this.tracks().filter(x=>x.trackingState<=2).length);protected cameraForm:SaveCameraRequest=this.blankCamera();protected zoneForm={zoneCode:'',name:'',zoneType:1 as CameraZoneType,geometryJson:'{"points":[[0.1,0.1],[0.9,0.1],[0.9,0.9],[0.1,0.9]]}',categoryId:null as number|null};
  ngOnInit():void{this.load();timer(5000,5000).pipe(takeUntilDestroyed(this.destroyRef)).subscribe(()=>this.loadTracks());}
  protected load():void{this.error.set('');this.api.cameras().subscribe({next:items=>this.cameras.set(items),error:()=>this.error.set('Unable to load cameras.')});this.api.capabilities().subscribe({next:value=>this.demoMode.set(value.demoMode),error:()=>this.error.set('Unable to load CCTV capabilities.')});this.loadTracks();}
  protected loadTracks():void{this.api.tracks(undefined,undefined,200).subscribe({next:items=>this.tracks.set(items),error:()=>this.error.set('Unable to recover tracking sessions.')});}
  protected select(camera:CameraView):void{this.selected.set(camera);this.cameraForm={storeId:camera.storeId,cameraCode:camera.cameraCode,name:camera.name,rtspConfigurationReference:null,location:camera.location,direction:camera.direction,isActive:camera.isActive};this.api.zones(camera.id).subscribe({next:items=>this.zones.set(items),error:()=>this.error.set('Unable to load camera zones.')});}
  protected newCamera():void{this.selected.set(null);this.zones.set([]);this.cameraForm=this.blankCamera();}
  protected saveCamera():void{const selected=this.selected();const result=selected?this.api.update(selected.id,{...this.cameraForm,rtspConfigurationReference:this.cameraForm.rtspConfigurationReference||null}):this.api.create(this.cameraForm);result.subscribe({next:item=>{this.cameras.update(items=>[item,...items.filter(x=>x.id!==item.id)]);this.select(item);},error:()=>this.error.set('Camera configuration was rejected.')});}
  protected saveZone(cameraId:number):void{this.api.addZone(cameraId,this.zoneForm).subscribe({next:()=>{this.api.zones(cameraId).subscribe(items=>this.zones.set(items));},error:()=>this.error.set('Zone geometry or scope was rejected.')});}
  protected status(value:number):string{return({1:'Offline',2:'Online',3:'Degraded',4:'Maintenance'} as Record<number,string>)[value]??'Unknown';}protected zoneType(value:number):string{return({1:'Entry',2:'Exit',3:'Checkout',4:'Shelf',5:'Category',6:'Restricted',7:'Staff area'} as Record<number,string>)[value]??'Unknown';}protected trackState(value:number):string{return({1:'Active',2:'Handoff',3:'Ended',4:'Lost'} as Record<number,string>)[value]??'Unknown';}protected subject(track:PersonTrackView):string{return track.subjectKind===2?`Customer ${track.customerId}`:track.subjectKind===3?`Staff ${track.staffProfileId} · operational only`:'Anonymous';}
  private blankCamera():SaveCameraRequest{return{storeId:0,cameraCode:'',name:'',rtspConfigurationReference:'',location:'',direction:3,isActive:true};}
}
