import { ChangeDetectionStrategy, Component, DestroyRef, OnInit, computed, inject, signal } from '@angular/core';
import { HttpErrorResponse } from '@angular/common/http';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { Subscription, switchMap, timer } from 'rxjs';
import { AuthSessionService } from '../../core/auth/auth-session.service';
import { PERMISSIONS } from '../../core/auth/permission-catalog';
import { AdminShell } from '../../shared/admin-shell/admin-shell';
import { CameraPreviewGrantView, CameraPreviewSessionView, CameraQuotaView, CameraView, CameraZoneType, CameraZoneView, CamerasApiService, PersonTrackView, SaveCameraRequest } from './cameras-api.service';

@Component({selector:'app-camera-operations-page',imports:[AdminShell,FormsModule,RouterLink],changeDetection:ChangeDetectionStrategy.OnPush,template:`
<app-admin-shell pageTitle="Camera operations" eyebrow="Phase 13 · Anonymous operational tracking">
  @if(demoMode()){<p class="demo" role="status">DEMO MODE — deterministic fixtures; no physical RTSP camera is connected.</p>}
  <p class="boundary">Tracking is anonymous by default. The browser never receives camera IPs, RTSP URLs or credentials.</p>
  @if(error()){<p class="error" role="alert">{{error()}}</p>}
  <section class="summary"><div><b>{{quota()?.activeCameras??'—'}} / {{quota()?.maxCameras??'—'}}</b><span>Active camera quota</span></div><div><b>{{quota()?.configuredCameras??'—'}}</b><span>Total configured</span></div><div><b>{{quota()?.availableCameras??'—'}}</b><span>Available slots</span></div><div><b>{{onlineCount()}}</b><span>Online</span></div><div><b>{{activeTracks()}}</b><span>Active tracks</span></div><button type="button" (click)="load()">Refresh</button></section>
  <section class="layout"><div class="panel"><h2>Cameras</h2>@for(camera of cameras();track camera.id){<button type="button" class="item" [class.selected]="selected()?.id===camera.id" (click)="select(camera)"><b>{{camera.cameraCode}} · {{camera.name}}</b><span>Store {{camera.storeId}} · {{status(camera.status)}} · {{camera.rtspConfigurationHint}}</span><small>{{camera.location||'Location not set'}} · heartbeat {{camera.lastHeartbeatUtc||'never'}}</small></button>}@if(cameras().length===0){<p>No cameras configured.</p>}</div>
  <form class="panel form" (ngSubmit)="saveCamera()"><h2>{{selected()?'Edit camera':'New camera'}}</h2><label>Store ID<input name="storeId" type="number" min="1" [(ngModel)]="cameraForm.storeId" required [readonly]="!!selected()"></label><label>Camera code<input name="cameraCode" [(ngModel)]="cameraForm.cameraCode" required maxlength="50" [readonly]="!!selected()"></label><label>Name<input name="name" [(ngModel)]="cameraForm.name" required maxlength="150"></label><label>RTSP configuration reference<input name="rtsp" [(ngModel)]="cameraForm.rtspConfigurationReference" type="password" autocomplete="new-password" [required]="!selected()"><small>Opaque env/vault reference only.</small></label><label>Location<input name="location" [(ngModel)]="cameraForm.location" maxlength="250"></label><label>Direction<select name="direction" [(ngModel)]="cameraForm.direction"><option [ngValue]="1">Entry</option><option [ngValue]="2">Exit</option><option [ngValue]="3">Bidirectional</option><option [ngValue]="4">Internal</option></select></label><label class="check"><input name="active" type="checkbox" [(ngModel)]="cameraForm.isActive"> Active</label>@if(cameraActivationBlocked()){<small class="error">Camera limit reached. Disable another camera or save this camera as inactive.</small>}@if(canManage()){<button type="submit" [disabled]="cameraActivationBlocked()">Save camera</button>}<button type="button" class="secondary" [disabled]="quota()?.canAddActiveCamera===false" (click)="newCamera()">New active camera</button></form></section>
  @if(selected();as camera){
    <section class="panel preview-panel"><h2>Secure live preview · {{camera.cameraCode}}</h2><p><a [routerLink]="['/customer-admin/cameras',camera.id,'motion-rules']">Configure motion rules</a></p><p class="muted">Authenticated server-mediated preview; RTSP secrets remain on the camera host.</p>@if(!previewEnabled()){<p class="error">Preview runtime is disabled on the API server.</p>}@if(previewState()){<p role="status">{{previewState()}}</p>}@if(previewObjectUrl()){<img class="preview" [src]="previewObjectUrl()" [alt]="camera.name+' live preview'"><small>Session expires {{previewSession()?.expiresUtc}}</small>}<div><button type="button" [disabled]="!previewEnabled()||!canPreview()||!!previewSession()" (click)="startPreview(camera.id)">Start preview</button><button type="button" class="secondary" [disabled]="!previewSession()" (click)="stopPreview()">Stop preview</button></div></section>
    @if(canManage()){<section class="panel"><h2>User-wise preview access</h2><form class="grant-form" (ngSubmit)="savePreviewGrant(camera.id)"><label>User ID<input name="previewUserId" type="number" min="1" [(ngModel)]="previewGrantForm.userId" required></label><label class="check"><input name="canViewLive" type="checkbox" [(ngModel)]="previewGrantForm.canViewLive"> Live</label><label class="check"><input name="canViewTracking" type="checkbox" [(ngModel)]="previewGrantForm.canViewTracking"> Tracking</label><label class="check"><input name="canControl" type="checkbox" [(ngModel)]="previewGrantForm.canControl"> Control</label><label class="check"><input name="grantActive" type="checkbox" [(ngModel)]="previewGrantForm.isActive"> Active</label><button type="submit">Save user grant</button></form><div class="grants">@for(grant of previewGrants();track grant.userId){<span><b>{{grant.displayName}}</b> ({{grant.userName}} / {{grant.userId}}) · live {{grant.canViewLive?'yes':'no'}} · tracking {{grant.canViewTracking?'yes':'no'}} · {{grant.isActive?'active':'inactive'}}</span><button type="button" class="secondary" (click)="removePreviewGrant(camera.id,grant.userId)">Remove</button>}@if(previewGrants().length===0){<p>No users assigned to this camera preview.</p>}</div></section>}
    <section class="panel"><h2>Zone editor · {{camera.cameraCode}}</h2><div class="zone-layout"><div>@for(zone of zones();track zone.id){<p><b>{{zone.zoneCode}} v{{zone.version}}</b> · {{zoneType(zone.zoneType)}} · {{zone.isActive?'Current':'Superseded'}}</p>}</div><form class="form" (ngSubmit)="saveZone(camera.id)"><label>Zone code<input name="zoneCode" [(ngModel)]="zoneForm.zoneCode" required></label><label>Name<input name="zoneName" [(ngModel)]="zoneForm.name" required></label><label>Type<select name="zoneType" [(ngModel)]="zoneForm.zoneType"><option [ngValue]="1">Entry</option><option [ngValue]="2">Exit</option><option [ngValue]="3">Checkout</option><option [ngValue]="4">Shelf</option><option [ngValue]="5">Category</option><option [ngValue]="6">Restricted</option><option [ngValue]="7">Staff area</option></select></label><label>Normalized polygon JSON<textarea name="geometry" [(ngModel)]="zoneForm.geometryJson" rows="4"></textarea></label>@if(canManage()){<button type="submit">Create zone version</button>}</form></div></section>
  }
  <section class="panel"><h2>Operational tracking sessions</h2><p class="muted">Auto-recovers authoritative track state every 5 seconds.</p><div class="tracks"><b>Track</b><b>Store / camera</b><b>State</b><b>Subject</b><b>Confidence</b><b>Updated</b>@for(track of tracks();track track.id){<span>{{track.personTrackId}}</span><span>{{track.storeId}} / {{track.cameraId}}</span><span>{{trackState(track.trackingState)}}</span><span>{{subject(track)}}</span><span>{{track.confidence}}</span><span>{{track.updatedUtc}}</span>}</div></section>
</app-admin-shell>`,styles:[`:host{display:block}.demo{background:#5b3b00;border:2px solid #ffb020;border-radius:.5rem;color:#fff0c2;font-weight:800;padding:.8rem}.boundary{border-left:4px solid var(--color-accent);padding:.7rem 1rem}.summary{display:grid;grid-template-columns:repeat(5,minmax(0,1fr)) auto;gap:.75rem;margin-bottom:1rem}.summary div,.panel{background:var(--color-surface);border:1px solid var(--color-border);border-radius:var(--radius-sm)}.summary div{display:grid;padding:1rem}.summary span,small,.muted{color:var(--color-muted);font-size:.8rem}.layout,.zone-layout{display:grid;grid-template-columns:1fr 1fr;gap:1rem}.panel{padding:1rem;margin-bottom:1rem}.item{background:transparent;border:0;border-bottom:1px solid var(--color-border);color:var(--color-text);display:grid;gap:.25rem;padding:.8rem;text-align:left;width:100%}.item.selected{background:var(--color-nav-active)}.form,.form label{display:grid;gap:.35rem}.form{gap:.7rem}.check{display:flex!important;gap:.35rem}.panel input,.panel select,.panel textarea{background:var(--color-background);border:1px solid var(--color-border);border-radius:var(--radius-sm);color:var(--color-text);padding:.65rem}.panel button,.summary button{background:var(--color-accent);border:0;border-radius:var(--radius-sm);color:var(--color-on-accent);font-weight:700;padding:.7rem 1rem}.secondary{background:var(--color-nav-active)!important;color:var(--color-text)!important;margin-left:.5rem}.tracks{display:grid;grid-template-columns:1.2fr .8fr .7fr .8fr .6fr 1.2fr;gap:.5rem;overflow:auto}.tracks>*{border-bottom:1px solid var(--color-border);padding:.5rem}.preview{background:#000;display:block;max-height:34rem;object-fit:contain;width:100%}.preview-panel>div{margin-top:.75rem}.grants{display:grid;grid-template-columns:1fr auto;gap:.5rem;margin-top:1rem}.grant-form{display:grid;grid-template-columns:repeat(5,minmax(0,1fr)) auto;align-items:end;gap:.7rem}.error{color:var(--color-danger)}@media(max-width:1100px){.summary{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:850px){.summary,.layout,.zone-layout,.grant-form{grid-template-columns:1fr}.tracks{grid-template-columns:repeat(6,minmax(8rem,1fr))}}`],})
export class CameraOperationsPage implements OnInit{
  private readonly api=inject(CamerasApiService);private readonly session=inject(AuthSessionService);private readonly destroyRef=inject(DestroyRef);private previewFrames?:Subscription;
  protected readonly cameras=signal<CameraView[]>([]);protected readonly quota=signal<CameraQuotaView|null>(null);protected readonly zones=signal<CameraZoneView[]>([]);protected readonly tracks=signal<PersonTrackView[]>([]);protected readonly previewGrants=signal<CameraPreviewGrantView[]>([]);protected readonly selected=signal<CameraView|null>(null);protected readonly demoMode=signal(false);protected readonly previewEnabled=signal(false);protected readonly previewSession=signal<CameraPreviewSessionView|null>(null);protected readonly previewObjectUrl=signal<string|null>(null);protected readonly previewState=signal('');protected readonly error=signal('');
  protected readonly canManage=computed(()=>this.session.hasPermission(PERMISSIONS.camerasManage));protected readonly canPreview=computed(()=>this.session.hasPermission(PERMISSIONS.camerasPreview));protected readonly onlineCount=computed(()=>this.cameras().filter(x=>x.status===2).length);protected readonly activeTracks=computed(()=>this.tracks().filter(x=>x.trackingState<=2).length);
  protected cameraForm:SaveCameraRequest=this.blankCamera();protected zoneForm={zoneCode:'',name:'',zoneType:1 as CameraZoneType,geometryJson:'{"points":[[0.1,0.1],[0.9,0.1],[0.9,0.9],[0.1,0.9]]}',categoryId:null as number|null};protected previewGrantForm={userId:0,canViewLive:true,canViewTracking:true,canControl:false,isActive:true};
  ngOnInit():void{this.destroyRef.onDestroy(()=>this.releasePreview());this.load();timer(5000,5000).pipe(takeUntilDestroyed(this.destroyRef)).subscribe(()=>this.loadTracks());}
  protected load():void{this.error.set('');this.api.cameras().subscribe({next:items=>this.cameras.set(items),error:()=>this.error.set('Unable to load cameras.')});this.loadQuota();this.api.capabilities().subscribe({next:value=>{this.demoMode.set(value.demoMode);this.previewEnabled.set(value.previewEnabled);},error:()=>this.error.set('Unable to load CCTV capabilities.')});this.loadTracks();}
  private loadQuota():void{this.api.quota().subscribe({next:value=>this.quota.set(value),error:()=>this.error.set('Unable to load camera quota.')});}
  protected loadTracks():void{this.api.tracks(undefined,undefined,200).subscribe({next:items=>this.tracks.set(items),error:()=>this.error.set('Unable to recover tracking sessions.')});}
  protected select(camera:CameraView):void{this.stopPreview();this.selected.set(camera);this.cameraForm={storeId:camera.storeId,cameraCode:camera.cameraCode,name:camera.name,rtspConfigurationReference:null,location:camera.location,direction:camera.direction,isActive:camera.isActive};this.api.zones(camera.id).subscribe({next:items=>this.zones.set(items),error:()=>this.error.set('Unable to load camera zones.')});if(this.canManage())this.loadPreviewGrants(camera.id);}
  protected newCamera():void{this.stopPreview();this.selected.set(null);this.zones.set([]);this.previewGrants.set([]);this.cameraForm=this.blankCamera();}
  protected saveCamera():void{if(this.cameraActivationBlocked())return;const selected=this.selected();const result=selected?this.api.update(selected.id,{...this.cameraForm,rtspConfigurationReference:this.cameraForm.rtspConfigurationReference||null}):this.api.create(this.cameraForm);result.subscribe({next:item=>{this.cameras.update(items=>[item,...items.filter(x=>x.id!==item.id)]);this.loadQuota();this.select(item);},error:(failure:HttpErrorResponse)=>this.error.set(failure.status===409?(failure.error?.message||'Camera limit reached. Disable another camera before activating this one.'):'Camera configuration was rejected.')});}
  protected cameraActivationBlocked():boolean{return this.cameraForm.isActive&&!this.selected()?.isActive&&this.quota()?.canAddActiveCamera===false;}
  protected saveZone(cameraId:number):void{this.api.addZone(cameraId,this.zoneForm).subscribe({next:()=>this.api.zones(cameraId).subscribe(items=>this.zones.set(items)),error:()=>this.error.set('Zone geometry or scope was rejected.')});}
  protected loadPreviewGrants(cameraId:number):void{this.api.previewGrants(cameraId).subscribe({next:items=>this.previewGrants.set(items),error:()=>this.error.set('Unable to load preview grants.')});}
  protected savePreviewGrant(cameraId:number):void{if(this.previewGrantForm.userId<=0)return;this.api.savePreviewGrant(cameraId,this.previewGrantForm.userId,{canViewLive:this.previewGrantForm.canViewLive,canViewTracking:this.previewGrantForm.canViewTracking,canControl:this.previewGrantForm.canControl,validUntilUtc:null,isActive:this.previewGrantForm.isActive}).subscribe({next:()=>this.loadPreviewGrants(cameraId),error:()=>this.error.set('Preview grant was rejected.')});}
  protected removePreviewGrant(cameraId:number,userId:number):void{this.api.removePreviewGrant(cameraId,userId).subscribe({next:()=>this.loadPreviewGrants(cameraId),error:()=>this.error.set('Preview grant could not be removed.')});}
  protected startPreview(cameraId:number):void{this.previewState.set('Connecting to authorized camera...');this.api.startPreview(cameraId).subscribe({next:value=>{this.previewSession.set(value);this.previewState.set('Live');this.previewFrames=timer(0,value.refreshMilliseconds).pipe(switchMap(()=>this.api.previewFrame(cameraId,value.sessionId))).subscribe({next:blob=>this.showFrame(blob),error:()=>{this.previewState.set('Camera frame unavailable; start a new session to reconnect.');this.releasePreview();}});},error:()=>this.previewState.set('Live preview is unavailable or not assigned to this user.')});}
  protected stopPreview():void{const active=this.previewSession();if(active)this.api.endPreview(active.cameraId,active.sessionId).subscribe({error:()=>undefined});this.releasePreview();this.previewState.set('');}
  private showFrame(blob:Blob):void{const old=this.previewObjectUrl();const next=URL.createObjectURL(blob);this.previewObjectUrl.set(next);if(old)URL.revokeObjectURL(old);}
  private releasePreview():void{this.previewFrames?.unsubscribe();this.previewFrames=undefined;const old=this.previewObjectUrl();if(old)URL.revokeObjectURL(old);this.previewObjectUrl.set(null);this.previewSession.set(null);}
  protected status(value:number):string{return({1:'Offline',2:'Online',3:'Degraded',4:'Maintenance'} as Record<number,string>)[value]??'Unknown';}protected zoneType(value:number):string{return({1:'Entry',2:'Exit',3:'Checkout',4:'Shelf',5:'Category',6:'Restricted',7:'Staff area'} as Record<number,string>)[value]??'Unknown';}protected trackState(value:number):string{return({1:'Active',2:'Handoff',3:'Ended',4:'Lost'} as Record<number,string>)[value]??'Unknown';}protected subject(track:PersonTrackView):string{return track.subjectKind===2?`Customer ${track.customerId}`:track.subjectKind===3?`Staff ${track.staffProfileId} · operational only`:'Anonymous';}
  private blankCamera():SaveCameraRequest{return{storeId:0,cameraCode:'',name:'',rtspConfigurationReference:'',location:'',direction:3,isActive:true};}
}
