using System.Diagnostics;
using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using CustSearch.Application.Integrations;
using CustSearch.Domain.Entities;
using CustSearch.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;

namespace CustSearch.Infrastructure.Integrations;

/// <summary>Authenticates exact raw webhook bytes and persists one idempotent receipt per provider event.</summary>
/// <summary>
/// Validates signed inbound integration requests, timestamps, payload limits and idempotency keys
/// before persisting tenant-owned receipts; credentials and raw secrets are never written to logs.
/// </summary>
public sealed class InboundIntegrationService(CustSearchDbContext db,IIntegrationSecretResolver secrets,TimeProvider clock,IOptions<IntegrationSecurityOptions> options):IInboundIntegrationService
{
    public async Task<InboundIntegrationAcknowledgement>ReceiveAsync(InboundIntegrationRequest request,CancellationToken cancellationToken=default)
    {
        ArgumentNullException.ThrowIfNull(request);ArgumentOutOfRangeException.ThrowIfNegativeOrZero(request.IntegrationConfigurationId);var settings=options.Value;if(request.Body.Length<2||request.Body.Length>settings.MaximumInboundBodyBytes)throw new IntegrationException("Inbound request body size is invalid.",IntegrationFailureKind.Validation);var configuration=await db.IntegrationConfigurations.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==request.IntegrationConfigurationId,cancellationToken).ConfigureAwait(false)??throw new IntegrationException("Integration endpoint was not found.",IntegrationFailureKind.NotFound);if(!configuration.Enabled||!configuration.SupportsInbound)throw new IntegrationException("Integration endpoint is not enabled for inbound traffic.",IntegrationFailureKind.Forbidden);if(!long.TryParse(request.TenantId,NumberStyles.None,CultureInfo.InvariantCulture,out var signedTenantId)||signedTenantId!=configuration.TenantId)throw new IntegrationException("Signed tenant scope does not match the integration.",IntegrationFailureKind.Forbidden);
        var providerEventId=Required(request.ProviderEventId,"Provider event id",200);var idempotencyKey=Required(request.IdempotencyKey,"Idempotency key",200);if(!long.TryParse(request.Timestamp,NumberStyles.None,CultureInfo.InvariantCulture,out var timestampSeconds))throw new IntegrationException("Webhook timestamp is invalid.",IntegrationFailureKind.Unauthorized);DateTimeOffset providerTimestamp;try{providerTimestamp=DateTimeOffset.FromUnixTimeSeconds(timestampSeconds);}catch(ArgumentOutOfRangeException){throw new IntegrationException("Webhook timestamp is invalid.",IntegrationFailureKind.Unauthorized);}var now=clock.GetUtcNow();if(Math.Abs((now-providerTimestamp).TotalSeconds)>settings.AllowedClockSkewSeconds)throw new IntegrationException("Webhook timestamp is outside the allowed clock skew.",IntegrationFailureKind.Unauthorized);
        var signature=ParseSignature(request.Signature);var current=configuration.WebhookSigningSecretReference;var previous=configuration.PreviousSigningSecretValidUntilUtc>=now.UtcDateTime?configuration.PreviousWebhookSigningSecretReference:null;if(current is null)throw new IntegrationException("Webhook signing is not configured.",IntegrationFailureKind.Unavailable);var currentSecret=await secrets.ResolveAsync(current,cancellationToken).ConfigureAwait(false);var previousSecret=previous is null?null:await secrets.ResolveAsync(previous,cancellationToken).ConfigureAwait(false);if(string.IsNullOrWhiteSpace(currentSecret))throw new IntegrationException("Webhook signing secret is unavailable.",IntegrationFailureKind.Unavailable);var canonical=Canonical(request.Timestamp,providerEventId,idempotencyKey,request.TenantId,request.Body.Span);if(!Verify(signature,currentSecret,canonical)&&!(previousSecret is not null&&Verify(signature,previousSecret,canonical)))throw new IntegrationException("Webhook signature is invalid.",IntegrationFailureKind.Unauthorized);
        var envelope=ValidateEnvelope(request.Body);var payloadHash=IntegrationSecurity.Hash(request.Body.Span);var existing=await db.IntegrationInboundEvents.AsNoTracking().FirstOrDefaultAsync(x=>x.TenantId==configuration.TenantId&&x.IntegrationConfigurationId==configuration.Id&&(x.ProviderEventId==providerEventId||x.IdempotencyKey==idempotencyKey),cancellationToken).ConfigureAwait(false);if(existing is not null){if(!string.Equals(existing.PayloadHash,payloadHash,StringComparison.Ordinal))throw new IntegrationException("Webhook idempotency key was reused with a different payload.",IntegrationFailureKind.Conflict);return new(existing.Id,true,"accepted",existing.CorrelationId);}
        var stopwatch=Stopwatch.StartNew();await using var transaction=await db.Database.BeginTransactionAsync(cancellationToken).ConfigureAwait(false);var inbound=IntegrationInboundEvent.Accept(configuration.TenantId,configuration.Id,providerEventId,idempotencyKey,envelope.EventType,envelope.ContractVersion,payloadHash,request.CorrelationId,providerTimestamp.UtcDateTime,now.UtcDateTime);db.IntegrationInboundEvents.Add(inbound);
        try{await db.SaveChangesAsync(cancellationToken).ConfigureAwait(false);}catch(DbUpdateException){await transaction.RollbackAsync(cancellationToken).ConfigureAwait(false);db.ChangeTracker.Clear();var duplicate=await db.IntegrationInboundEvents.AsNoTracking().FirstOrDefaultAsync(x=>x.TenantId==configuration.TenantId&&x.IntegrationConfigurationId==configuration.Id&&(x.ProviderEventId==providerEventId||x.IdempotencyKey==idempotencyKey),cancellationToken).ConfigureAwait(false);if(duplicate is not null&&string.Equals(duplicate.PayloadHash,payloadHash,StringComparison.Ordinal))return new(duplicate.Id,true,"accepted",duplicate.CorrelationId);throw;}
        inbound.MarkProcessed(clock.GetUtcNow().UtcDateTime);stopwatch.Stop();db.IntegrationDeliveryLogs.Add(IntegrationDeliveryLog.RecordInbound(configuration.TenantId,configuration.Id,inbound.Id,request.CorrelationId,configuration.Provider,stopwatch.ElapsedMilliseconds,clock.GetUtcNow().UtcDateTime));await db.SaveChangesAsync(cancellationToken).ConfigureAwait(false);await transaction.CommitAsync(cancellationToken).ConfigureAwait(false);return new(inbound.Id,false,"accepted",request.CorrelationId);
    }
    private static (string EventType,int ContractVersion)ValidateEnvelope(ReadOnlyMemory<byte>body)
    {try{using var document=JsonDocument.Parse(body);var root=document.RootElement;if(root.ValueKind!=JsonValueKind.Object||root.TryGetProperty("tenantId",out _))throw new IntegrationException("Inbound JSON schema is invalid.",IntegrationFailureKind.Validation);if(!root.TryGetProperty("eventType",out var eventTypeElement)||eventTypeElement.ValueKind!=JsonValueKind.String||string.IsNullOrWhiteSpace(eventTypeElement.GetString())||!root.TryGetProperty("contractVersion",out var versionElement)||!versionElement.TryGetInt32(out var version)||version<1||!root.TryGetProperty("data",out var data)||data.ValueKind!=JsonValueKind.Object)throw new IntegrationException("Inbound JSON schema is invalid.",IntegrationFailureKind.Validation);return(Required(eventTypeElement.GetString()!,"Event type",100),version);}catch(JsonException){throw new IntegrationException("Inbound body is invalid JSON.",IntegrationFailureKind.Validation);}}
    private static byte[]Canonical(string timestamp,string eventId,string idempotencyKey,string tenantId,ReadOnlySpan<byte>body){var prefix=Encoding.UTF8.GetBytes($"{timestamp}\n{eventId}\n{idempotencyKey}\n{tenantId}\n");var result=new byte[prefix.Length+body.Length];prefix.CopyTo(result,0);body.CopyTo(result.AsSpan(prefix.Length));return result;}
    private static bool Verify(ReadOnlySpan<byte>signature,string secret,ReadOnlySpan<byte>canonical){var expected=HMACSHA256.HashData(Encoding.UTF8.GetBytes(secret),canonical);return signature.Length==expected.Length&&CryptographicOperations.FixedTimeEquals(signature,expected);}
    private static byte[]ParseSignature(string value){if(string.IsNullOrWhiteSpace(value))throw new IntegrationException("Webhook signature is required.",IntegrationFailureKind.Unauthorized);var normalized=value.StartsWith("sha256=",StringComparison.OrdinalIgnoreCase)?value[7..]:value;try{var bytes=Convert.FromHexString(normalized);if(bytes.Length!=32)throw new FormatException();return bytes;}catch(FormatException){throw new IntegrationException("Webhook signature is invalid.",IntegrationFailureKind.Unauthorized);}}
    private static string Required(string value,string name,int max){if(string.IsNullOrWhiteSpace(value))throw new IntegrationException($"{name} is required.",IntegrationFailureKind.Validation);var result=value.Trim();return result.Length<=max?result:throw new IntegrationException($"{name} exceeds the allowed length.",IntegrationFailureKind.Validation);}
}
