using System.Globalization;
using System.Text;
using System.Text.Json;
using CustSearch.Application.Authentication;
using CustSearch.Application.Integrations;
using CustSearch.Application.TenantOperations;
using CustSearch.Domain.Entities;
using CustSearch.Domain.Enums;
using CustSearch.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;

namespace CustSearch.Infrastructure.Integrations;

/// <summary>Tenant-safe management boundary that returns only masked secret-reference metadata.</summary>
public sealed class IntegrationManagementService(CustSearchDbContext db,ICurrentUserContext currentUser,TimeProvider clock):IIntegrationManagementService
{
    private static readonly JsonSerializerOptions JsonOptions=new(JsonSerializerDefaults.Web);
    public async Task<IReadOnlyList<IntegrationConfigurationView>>ListAsync(CancellationToken cancellationToken=default)
    {var tenantId=RequireTenant();var configurations=await db.IntegrationConfigurations.AsNoTracking().Where(x=>x.TenantId==tenantId).OrderBy(x=>x.Provider).ThenBy(x=>x.IntegrationType).ToListAsync(cancellationToken).ConfigureAwait(false);var latest=await LatestStatusesAsync(tenantId,cancellationToken).ConfigureAwait(false);return configurations.Select(x=>Map(x,latest)).ToList();}
    public async Task<IntegrationConfigurationView>GetAsync(long integrationId,CancellationToken cancellationToken=default){var tenantId=RequireTenant();var configuration=await RequireAsync(tenantId,integrationId,false,cancellationToken).ConfigureAwait(false);var latest=await LatestStatusesAsync(tenantId,cancellationToken).ConfigureAwait(false);return Map(configuration,latest);}
    public async Task<IntegrationConfigurationView>SaveAsync(long?integrationId,SaveIntegrationConfigurationCommand command,TenantAuditContext audit,CancellationToken cancellationToken=default)
    {
        ArgumentNullException.ThrowIfNull(command);ArgumentNullException.ThrowIfNull(audit);var tenantId=RequireTenant();var now=clock.GetUtcNow().UtcDateTime;await using var transaction=await db.Database.BeginTransactionAsync(cancellationToken).ConfigureAwait(false);IntegrationConfiguration configuration;string action;
        if(integrationId.HasValue){configuration=await RequireAsync(tenantId,integrationId.Value,true,cancellationToken).ConfigureAwait(false);configuration.Update(command.Provider,command.IntegrationType,command.Enabled,command.EndpointBaseUrl,command.TimeoutSeconds,command.RetryMaxAttempts,command.RetryBaseDelaySeconds,now);if(command.CredentialReference is not null||command.WebhookSigningSecretReference is not null)configuration.RotateReferences(command.CredentialReference,command.WebhookSigningSecretReference,0,now);action="IntegrationUpdated";}
        else{configuration=IntegrationConfiguration.Create(tenantId,command.Provider,command.IntegrationType,command.Enabled,command.EndpointBaseUrl,command.CredentialReference,command.WebhookSigningSecretReference,command.TimeoutSeconds,command.RetryMaxAttempts,command.RetryBaseDelaySeconds,now);db.IntegrationConfigurations.Add(configuration);action="IntegrationCreated";}
        try{await db.SaveChangesAsync(cancellationToken).ConfigureAwait(false);}catch(DbUpdateException exception){throw new IntegrationException($"Integration provider/type configuration already exists: {exception.GetType().Name}.",IntegrationFailureKind.Conflict);}
        var view=Map(configuration,new());db.AuditLogs.Add(AuditLog.Record(tenantId,null,audit.ActorUserId,"User",action,"IntegrationConfiguration",configuration.Id.ToString(CultureInfo.InvariantCulture),null,JsonSerializer.Serialize(view,JsonOptions),audit.IpAddress,audit.UserAgent,audit.CorrelationId,now));await db.SaveChangesAsync(cancellationToken).ConfigureAwait(false);await transaction.CommitAsync(cancellationToken).ConfigureAwait(false);return view;
    }
    public async Task<IntegrationConfigurationView>RotateReferencesAsync(long integrationId,RotateIntegrationReferencesCommand command,TenantAuditContext audit,CancellationToken cancellationToken=default)
    {ArgumentNullException.ThrowIfNull(command);ArgumentNullException.ThrowIfNull(audit);if(string.IsNullOrWhiteSpace(command.CredentialReference)&&string.IsNullOrWhiteSpace(command.WebhookSigningSecretReference))throw new IntegrationException("At least one new secret reference is required.",IntegrationFailureKind.Validation);var tenantId=RequireTenant();var configuration=await RequireAsync(tenantId,integrationId,true,cancellationToken).ConfigureAwait(false);var now=clock.GetUtcNow().UtcDateTime;configuration.RotateReferences(command.CredentialReference,command.WebhookSigningSecretReference,command.SigningGraceMinutes,now);var view=Map(configuration,new());db.AuditLogs.Add(AuditLog.Record(tenantId,null,audit.ActorUserId,"User","IntegrationCredentialReferencesRotated","IntegrationConfiguration",configuration.Id.ToString(CultureInfo.InvariantCulture),null,JsonSerializer.Serialize(new{configuration.Id,view.HasCredentialReference,view.HasWebhookSigningSecret,command.SigningGraceMinutes},JsonOptions),audit.IpAddress,audit.UserAgent,audit.CorrelationId,now));await db.SaveChangesAsync(cancellationToken).ConfigureAwait(false);return view;}
    public async Task<IReadOnlyList<IntegrationDeliveryLogView>>DeliveryHistoryAsync(long?integrationId,int take=100,CancellationToken cancellationToken=default)
    {var tenantId=RequireTenant();take=Math.Clamp(take,1,500);var query=db.IntegrationDeliveryLogs.AsNoTracking().Where(x=>x.TenantId==tenantId);if(integrationId.HasValue){await RequireAsync(tenantId,integrationId.Value,false,cancellationToken).ConfigureAwait(false);query=query.Where(x=>x.IntegrationConfigurationId==integrationId.Value);}return await query.OrderByDescending(x=>x.CreatedUtc).ThenByDescending(x=>x.Id).Take(take).Select(x=>new IntegrationDeliveryLogView(x.Id,x.IntegrationConfigurationId,x.InboundEventId,x.OutboxMessageId,x.CorrelationId,x.Provider,x.Direction,x.Status,x.DurationMilliseconds,x.HttpStatusCode,x.ErrorCategory,x.CreatedUtc)).ToListAsync(cancellationToken).ConfigureAwait(false);}
    public async Task<IntegrationOutboxView>RetryDeliveryAsync(long deliveryId,TenantAuditContext audit,CancellationToken cancellationToken=default)
    {ArgumentNullException.ThrowIfNull(audit);ArgumentOutOfRangeException.ThrowIfNegativeOrZero(deliveryId);var tenantId=RequireTenant();var item=await db.IntegrationOutbox.SingleOrDefaultAsync(x=>x.Id==deliveryId&&x.TenantId==tenantId,cancellationToken).ConfigureAwait(false)??throw new IntegrationException("Integration delivery was not found.",IntegrationFailureKind.NotFound);var now=clock.GetUtcNow().UtcDateTime;try{item.RetryManually(now);}catch(InvalidOperationException exception){throw new IntegrationException(exception.Message,IntegrationFailureKind.Validation);}db.AuditLogs.Add(AuditLog.Record(tenantId,null,audit.ActorUserId,"User","IntegrationDeliveryManualRetry","IntegrationOutbox",item.Id.ToString(CultureInfo.InvariantCulture),null,JsonSerializer.Serialize(new{item.Id,item.IntegrationConfigurationId},JsonOptions),audit.IpAddress,audit.UserAgent,audit.CorrelationId,now));await db.SaveChangesAsync(cancellationToken).ConfigureAwait(false);return Map(item);}
    public async Task<IntegrationOutboxView>QueueOutboundAsync(QueueIntegrationOutboundCommand command,CancellationToken cancellationToken=default)
    {ArgumentNullException.ThrowIfNull(command);var tenantId=RequireTenant();var configuration=await RequireAsync(tenantId,command.IntegrationConfigurationId,false,cancellationToken).ConfigureAwait(false);if(!configuration.Enabled||!configuration.SupportsOutbound)throw new IntegrationException("Integration is not enabled for outbound delivery.",IntegrationFailureKind.Validation);var payload=IntegrationSecurity.ValidateSafePayload(command.PayloadMetadataJson);var hash=IntegrationSecurity.Hash(Encoding.UTF8.GetBytes(payload));var existing=await db.IntegrationOutbox.AsNoTracking().SingleOrDefaultAsync(x=>x.TenantId==tenantId&&x.IdempotencyKey==command.IdempotencyKey,cancellationToken).ConfigureAwait(false);if(existing is not null)return Map(existing);var item=IntegrationOutboxMessage.Queue(tenantId,configuration.Id,configuration.Provider,configuration.EndpointBaseUrl,command.EventType,command.ContractVersion,payload,hash,command.CorrelationId,command.IdempotencyKey,configuration.RetryMaxAttempts,configuration.RetryBaseDelaySeconds,clock.GetUtcNow().UtcDateTime);db.IntegrationOutbox.Add(item);try{await db.SaveChangesAsync(cancellationToken).ConfigureAwait(false);}catch(DbUpdateException){db.ChangeTracker.Clear();var duplicate=await db.IntegrationOutbox.AsNoTracking().SingleOrDefaultAsync(x=>x.TenantId==tenantId&&x.IdempotencyKey==command.IdempotencyKey,cancellationToken).ConfigureAwait(false);if(duplicate is not null)return Map(duplicate);throw;}return Map(item);}
    private async Task<Dictionary<long,(IntegrationDeliveryStatus Status,IntegrationDirection Direction)>>LatestStatusesAsync(long tenantId,CancellationToken cancellationToken){var rows=await db.IntegrationDeliveryLogs.AsNoTracking().Where(x=>x.TenantId==tenantId).OrderByDescending(x=>x.CreatedUtc).ThenByDescending(x=>x.Id).Select(x=>new{x.IntegrationConfigurationId,x.Status,x.Direction}).ToListAsync(cancellationToken).ConfigureAwait(false);return rows.GroupBy(x=>x.IntegrationConfigurationId).ToDictionary(x=>x.Key,x=>(x.First().Status,x.First().Direction));}
    private async Task<IntegrationConfiguration>RequireAsync(long tenantId,long integrationId,bool tracked,CancellationToken cancellationToken){ArgumentOutOfRangeException.ThrowIfNegativeOrZero(integrationId);var query=tracked?db.IntegrationConfigurations:db.IntegrationConfigurations.AsNoTracking();return await query.SingleOrDefaultAsync(x=>x.Id==integrationId&&x.TenantId==tenantId,cancellationToken).ConfigureAwait(false)??throw new IntegrationException("Integration configuration was not found.",IntegrationFailureKind.NotFound);}
    private long RequireTenant()=>currentUser.IsAuthenticated&&!currentUser.IsPlatformAdmin&&currentUser.TenantId is>0?currentUser.TenantId.Value:throw new IntegrationException("A tenant-scoped authenticated session is required.",IntegrationFailureKind.Forbidden);
    private static IntegrationConfigurationView Map(IntegrationConfiguration x,IReadOnlyDictionary<long,(IntegrationDeliveryStatus Status,IntegrationDirection Direction)>latest){var status=latest.TryGetValue(x.Id,out var value)?value.Status.ToString():(x.Enabled?"Configured":"Disabled");var webhook=x.SupportsInbound?(x.HasSigningSecret()?"Signing configured":"Signing missing"):"Not applicable";return new(x.Id,x.Provider,x.IntegrationType,x.Enabled,x.EndpointBaseUrl,x.CredentialReference is not null,x.CredentialReference is null?null:IntegrationSecurity.Hint(x.CredentialReference),x.WebhookSigningSecretReference is not null,x.WebhookSigningSecretReference is null?null:IntegrationSecurity.Hint(x.WebhookSigningSecretReference),x.TimeoutSeconds,x.RetryMaxAttempts,x.RetryBaseDelaySeconds,x.CreatedUtc,x.UpdatedUtc,status,webhook);}
    private static IntegrationOutboxView Map(IntegrationOutboxMessage x)=>new(x.Id,x.IntegrationConfigurationId,x.Provider,x.Destination,x.EventType,x.ContractVersion,x.Status,x.AttemptCount,x.MaxAttempts,x.NextAttemptUtc,x.LastResponseCode,x.LastError,x.CorrelationId,x.IdempotencyKey,x.CreatedUtc,x.DeliveredUtc);
}

internal static class IntegrationConfigurationExtensions{public static bool HasSigningSecret(this IntegrationConfiguration configuration)=>configuration.WebhookSigningSecretReference is not null;}
