/** Keeps Angular permission names identical to the backend's stable authorization catalog. */
export const PERMISSIONS = {
  camerasPreview:'Cameras.Preview', camerasTrackingView:'Cameras.TrackingView',
  tenantsView:'Tenants.View', tenantsCreate:'Tenants.Create', tenantsEdit:'Tenants.Edit', tenantsActivate:'Tenants.Activate', tenantsSuspend:'Tenants.Suspend', tenantsViewUsage:'Tenants.ViewUsage', tenantsOperationalSummary:'Tenants.ViewOperationalSummary',
  platformBillingView:'PlatformBilling.View', subscriptionPlansView:'SubscriptionPlans.View', subscriptionPlansManage:'SubscriptionPlans.Manage', platformReportsView:'PlatformReports.View', platformOperationsView:'PlatformOperations.View', platformOperationsManage:'PlatformOperations.Manage', platformAuditView:'PlatformAudit.View',
  platformBillingPlansView:'PlatformBilling.Plans.View', platformBillingPlansManage:'PlatformBilling.Plans.Manage', platformBillingSubscriptionsView:'PlatformBilling.Subscriptions.View', platformBillingSubscriptionsManage:'PlatformBilling.Subscriptions.Manage', platformBillingInvoicesView:'PlatformBilling.Invoices.View', platformBillingPaymentsView:'PlatformBilling.Payments.View',
  tenantPlatformBillingSubscriptionsView:'TenantPlatformBilling.Subscriptions.View', tenantPlatformBillingInvoicesView:'TenantPlatformBilling.Invoices.View', tenantPlatformBillingPaymentsView:'TenantPlatformBilling.Payments.View',
  tenantDashboardView:'TenantDashboard.View', tenantUsersView:'TenantUsers.View', tenantUsersCreate:'TenantUsers.Create', tenantUsersEdit:'TenantUsers.Edit', tenantUsersDeactivate:'TenantUsers.Deactivate', tenantUsersAssignRoles:'TenantUsers.AssignRoles', tenantStoresView:'TenantStores.View', tenantStoresCreate:'TenantStores.Create', tenantStoresEdit:'TenantStores.Edit', tenantBillingView:'TenantBilling.View', tenantReportsView:'TenantReports.View', tenantAuditView:'TenantAudit.View',
  staffView:'Staff.View', staffManage:'Staff.Manage', staffTrackingView:'StaffTracking.View', storeCategoriesView:'StoreCategories.View', storeCategoriesManage:'StoreCategories.Manage', voiceCommandsUse:'VoiceCommands.Use', voiceCommandsView:'VoiceCommands.View', voiceCommandsConfigure:'VoiceCommands.Configure', voiceCommandsAudit:'VoiceCommands.Audit', preferencesView:'Preferences.View', preferencesManage:'Preferences.Manage',
  customersView:'Customers.View', customersCreate:'Customers.Create', customersEdit:'Customers.Edit', visitorsView:'Visitors.View', visitorsConvert:'Visitors.Convert', householdsView:'Households.View', householdsCreate:'Households.Create', householdsEdit:'Households.Edit', householdsManageMembers:'Households.ManageMembers', visitsView:'Visits.View', visitsEdit:'Visits.Edit', visitPartiesView:'VisitParties.View',
  invoicesView:'Invoices.View', reportsView:'Reports.View', reportsExport:'Reports.Export', camerasView:'Cameras.View', camerasManage:'Cameras.Manage', camerasManageRules:'Cameras.ManageRules', camerasControl:'Cameras.Control', recognitionView:'Recognition.View', recognitionEnroll:'Recognition.Enroll', recognitionReview:'Recognition.Review', recognitionSettingsManage:'Recognition.Settings.Manage', recognitionConsentManage:'Recognition.Consent.Manage', alertsView:'Alerts.View', alertsAcknowledge:'Alerts.Acknowledge', alertsConfigure:'Alerts.Configure', integrationsView:'Integrations.View', integrationsManage:'Integrations.Manage', webhooksView:'Webhooks.View', webhooksManage:'Webhooks.Manage',
  productsView:'Products.View', productsCreate:'Products.Create', productsEdit:'Products.Edit', productsManageStores:'Products.ManageStores',
  retailInvoicesView:'RetailInvoices.View', retailInvoicesCreate:'RetailInvoices.Create', retailInvoicesEdit:'RetailInvoices.Edit', retailInvoicesFinalize:'RetailInvoices.Finalize', retailInvoicesCancel:'RetailInvoices.Cancel',
  retailPaymentsView:'RetailPayments.View', retailPaymentsCreate:'RetailPayments.Create', retailSpendAttributionView:'RetailSpendAttribution.View', retailSpendAttributionManage:'RetailSpendAttribution.Manage', retailReportsView:'RetailReports.View',
  securityIncidentsView:'Security.Incidents.View', securityIncidentsAcknowledge:'Security.Incidents.Acknowledge', securityIncidentsAssign:'Security.Incidents.Assign', securityIncidentsReview:'Security.Incidents.Review', securityIncidentsConfirmLoss:'Security.Incidents.ConfirmLoss', securityIncidentsResolve:'Security.Incidents.Resolve', securityEvidenceView:'Security.Evidence.View', securityEvidenceExport:'Security.Evidence.Export', securitySettingsView:'Security.Settings.View', securitySettingsManage:'Security.Settings.Manage', securityRulesView:'Security.Rules.View', securityRulesManage:'Security.Rules.Manage', securityReportsView:'Security.Reports.View',
} as const;
