/** Keeps Angular permission names identical to the backend's stable authorization catalog. */
export const PERMISSIONS = {
  tenantsView: 'Tenants.View',
  tenantsCreate: 'Tenants.Create',
  tenantsEdit: 'Tenants.Edit',
  tenantsActivate: 'Tenants.Activate',
  tenantsSuspend: 'Tenants.Suspend',
  tenantsViewUsage: 'Tenants.ViewUsage',
  tenantsOperationalSummary: 'Tenants.ViewOperationalSummary',
  platformBillingView: 'PlatformBilling.View',
  subscriptionPlansView: 'SubscriptionPlans.View',
  subscriptionPlansManage: 'SubscriptionPlans.Manage',
  platformReportsView: 'PlatformReports.View',
  platformAuditView: 'PlatformAudit.View',
  tenantDashboardView: 'TenantDashboard.View',
  tenantUsersView: 'TenantUsers.View',
  tenantStoresView: 'TenantStores.View',
  tenantBillingView: 'TenantBilling.View',
  tenantReportsView: 'TenantReports.View',
  tenantAuditView: 'TenantAudit.View',
  customersView: 'Customers.View',
  householdsView: 'Households.View',
  invoicesView: 'Invoices.View',
  reportsView: 'Reports.View',
  camerasView: 'Cameras.View',
  alertsView: 'Alerts.View',
  integrationsView: 'Integrations.View',
} as const;
