import { expect, Page, Route, test } from '@playwright/test';

function jwtWithFutureExpiry():string{const h=Buffer.from(JSON.stringify({alg:'none',typ:'JWT'})).toString('base64url');const p=Buffer.from(JSON.stringify({exp:Math.floor(Date.now()/1000)+3600})).toString('base64url');return `${h}.${p}.signature`;}
const json=(route:Route,body:unknown,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(body)});
const phase9Views=['TenantPlatformBilling.Subscriptions.View','TenantPlatformBilling.Invoices.View','TenantPlatformBilling.Payments.View'];
function tenantIdentity(overrides:Record<string,unknown>={}){return{userId:501,tenantId:25,tenantCode:'DEMO-STORE',userName:'owner',displayName:'Demo Shop Owner',email:'owner@example.test',isPlatformAdmin:false,roles:['TenantAdmin'],permissions:['TenantDashboard.View',...phase9Views],storeIds:[101],...overrides};}
function platformIdentity(overrides:Record<string,unknown>={}){return{userId:1,tenantId:null,tenantCode:null,userName:'billing-admin',displayName:'Platform Billing Admin',email:'billing@example.test',isPlatformAdmin:true,roles:['PlatformBillingAdmin'],permissions:['Tenants.ViewOperationalSummary','PlatformBilling.Plans.View','PlatformBilling.Plans.Manage','PlatformBilling.Subscriptions.View','PlatformBilling.Subscriptions.Manage','PlatformBilling.Invoices.View','PlatformBilling.Payments.View'],storeIds:[],...overrides};}
interface State{calls:string[];bodies:unknown[];plans:any[];subscriptions:any[];invoices:any[];payments:any[];}
async function mockAuth(page:Page,user:any){const expires=new Date(Date.now()+3600000).toISOString();const auth=()=>({accessToken:jwtWithFutureExpiry(),accessTokenExpiresUtc:expires,user});await page.route('**/api/auth/login',r=>json(r,auth()));await page.route('**/api/auth/refresh',r=>json(r,auth()));await page.route('**/api/auth/me',r=>json(r,{user,accessTokenExpiresUtc:expires}));}
async function mockTenantBilling(page:Page,user=tenantIdentity()):Promise<State>{await mockAuth(page,user);const state:State={calls:[],bodies:[],plans:[],subscriptions:[],invoices:[],payments:[]};const subscription={id:41,tenantId:25,planId:3,planCode:'PRO',planName:'Pro',billingCycle:'Monthly',status:'Active',startUtc:'2026-08-01T00:00:00Z',trialEndUtc:null,currentPeriodStartUtc:'2026-08-01T00:00:00Z',currentPeriodEndUtc:'2026-09-01T00:00:00Z',cancelAtPeriodEnd:false,cancelledUtc:null,maxStores:5,maxUsers:20,maxStaff:10,maxCameras:8};const invoice={id:71,tenantId:25,tenantSubscriptionId:41,invoiceNumber:'PLAT-25-202608',currency:'INR',invoiceUtc:'2026-08-01T00:00:00Z',dueUtc:'2026-08-08T00:00:00Z',status:'Paid',subtotal:999,discount:0,tax:0,total:999,paidAmount:999,items:[{id:711,planId:3,planName:'Pro',description:'Pro plan',quantity:1,rate:999,discount:0,tax:0,subtotal:999,total:999}]};const payment={id:81,tenantId:25,platformInvoiceId:71,paymentMethod:'UPI',amount:999,currency:'INR',gatewayReference:'gw-81',transactionReference:'txn-81',paymentUtc:'2026-08-02T00:00:00Z',status:'Successful'};
 await page.route('**/api/tenant/**',route=>{const req=route.request();const url=new URL(req.url());const path=url.pathname.replace('/api/tenant/','');state.calls.push(`${req.method()} ${path}${url.search}`);if(req.method()!=='GET')state.bodies.push(req.postDataJSON());if(path==='dashboard/summary')return json(route,{activeUsers:2,activeStores:1,activeStaff:1,activeCategories:2,openShifts:0,activePresenceSessions:0});if(path==='platform-billing')return json(route,{subscription,currentPlan:'Pro',maxStores:5,maxUsers:20,maxStaff:10,maxCameras:8,renewalUtc:'2026-09-01T00:00:00Z',latestPaymentStatus:'Successful',invoiceCount:1});if(path==='platform-billing/subscription')return json(route,subscription);if(path==='platform-billing/invoices')return json(route,[invoice]);if(path==='platform-billing/payments')return json(route,[payment]);return json(route,{message:`Unhandled Phase9 tenant route ${path}`},501);});return state;}
async function mockPlatformBilling(page:Page,user=platformIdentity()):Promise<State>{await mockAuth(page,user);const state:State={calls:[],bodies:[],plans:[{id:3,planCode:'PRO',name:'Pro',description:'Pro plan',monthlyPrice:999,annualPrice:9999,currency:'INR',trialDays:14,maxStores:5,maxUsers:20,maxStaff:10,maxCameras:8,maxMonthlyRecognitions:null,maxMonthlyApiCalls:null,featureLimitsJson:null,isActive:true,displayOrder:1,createdUtc:'2026-08-01T00:00:00Z',updatedUtc:'2026-08-01T00:00:00Z'}],subscriptions:[],invoices:[],payments:[]};
 await page.route('**/api/platform/**',route=>{const req=route.request();const url=new URL(req.url());const path=url.pathname.replace('/api/platform/','');state.calls.push(`${req.method()} ${path}${url.search}`);if(req.method()!=='GET')state.bodies.push(req.postDataJSON());if(path==='dashboard')return json(route,{totalTenants:2,activeTenants:2,trialTenants:0,suspendedTenants:0,inactiveTenants:0,monthlyRecurringRevenue:1998,totalTenantUsers:4,totalCameras:2});if(path==='billing/plans'&&req.method()==='GET')return json(route,state.plans);if(path==='billing/plans'&&req.method()==='POST'){const b=req.postDataJSON() as any;const created={id:4,...b,createdUtc:'2026-08-23T18:00:00Z',updatedUtc:'2026-08-23T18:00:00Z'};state.plans.push(created);return json(route,created,201);}if(path==='billing/subscriptions'&&req.method()==='GET')return json(route,state.subscriptions);if(path==='billing/invoices'&&req.method()==='GET')return json(route,state.invoices);if(path==='billing/payments'&&req.method()==='GET')return json(route,state.payments);return json(route,{message:`Unhandled Phase9 platform route ${req.method()} ${path}`},501);});return state;}
async function signInTenant(page:Page){await page.goto('/login');await page.getByLabel('Tenant code').fill('DEMO-STORE');await page.getByLabel('Email or username').fill('owner');await page.getByLabel('Password').fill('safe-e2e-password');await page.getByRole('button',{name:'Sign in'}).click();await expect(page).toHaveURL(/\/customer-admin\/dashboard$/);}
async function signInPlatform(page:Page){await page.goto('/login');await page.getByLabel('Email or username').fill('billing-admin');await page.getByLabel('Password').fill('safe-e2e-password');await page.getByRole('button',{name:'Sign in'}).click();await expect(page).toHaveURL(/\/admin\/dashboard$/);}

test('tenant platform billing summary is factual, read-only and never sends TenantId',async({page})=>{const state=await mockTenantBilling(page);await signInTenant(page);await page.goto('/customer-admin/billing');await expect(page.getByRole('heading',{name:'CustSearch Billing'})).toBeVisible();await expect(page.getByText('Pro',{exact:true}).first()).toBeVisible();await expect(page.getByText(/5 stores · 20 users · 10 staff · 8 cameras/)).toBeVisible();expect(state.calls.some(x=>/tenantId/i.test(x))).toBe(false);expect(state.bodies).toHaveLength(0);expect(state.calls.some(x=>/retail/i.test(x))).toBe(false);});

test('tenant platform invoice history stays separate from retail invoices and payments',async({page})=>{const state=await mockTenantBilling(page);await signInTenant(page);await page.goto('/customer-admin/billing/invoices');await expect(page.getByText('PLAT-25-202608',{exact:true})).toBeVisible();await expect(page.getByText('txn-81',{exact:true})).toBeVisible();await expect(page.getByText(/Shop-customer retail purchases are not shown here/)).toBeVisible();expect(state.calls.some(x=>x.includes('retail/invoices'))).toBe(false);});

test('tenant billing permission guard denies missing Phase 9 permission',async({page})=>{await mockTenantBilling(page,tenantIdentity({roles:['StoreManager'],permissions:['TenantDashboard.View'],storeIds:[101]}));await signInTenant(page);await page.goto('/customer-admin/billing');await expect(page).toHaveURL(/\/access-denied$/);});

test('platform billing admin creates platform plan without touching retail domain',async({page})=>{const state=await mockPlatformBilling(page);await signInPlatform(page);await page.goto('/platform-admin/billing/plans');await expect(page.getByText(/never shows shop-customer retail invoices or payments/)).toBeVisible();await page.getByPlaceholder('Plan code').fill('ENTERPRISE');await page.getByPlaceholder('Plan name').fill('Enterprise');await page.getByPlaceholder('Monthly price').fill('4999');await page.getByPlaceholder('Annual price').fill('49999');await page.getByPlaceholder('Trial days').fill('30');await page.getByPlaceholder('Max stores').fill('20');await page.getByPlaceholder('Max users').fill('100');await page.getByPlaceholder('Max staff').fill('75');await page.getByPlaceholder('Max cameras').fill('50');await page.getByRole('button',{name:'Create plan'}).click();await expect(page.getByText('Plan created.',{exact:true})).toBeVisible();expect(JSON.stringify(state.bodies)).not.toMatch(/customerId|storeId|retailInvoice|retailPayment/i);expect(state.calls.some(x=>/retail/i.test(x))).toBe(false);});
