import {expect,Page,Route,test} from '@playwright/test';

const permissions=['TenantDashboard.View','Recognition.View','Recognition.Enroll','Recognition.Review','Recognition.Consent.Manage'];
function jwt(){const header=Buffer.from(JSON.stringify({alg:'none',typ:'JWT'})).toString('base64url');const payload=Buffer.from(JSON.stringify({exp:Math.floor(Date.now()/1000)+3600})).toString('base64url');return `${header}.${payload}.signature`;}
const json=(route:Route,body:unknown,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(body)});
function identity(grants=permissions){return{userId:914,tenantId:42,tenantCode:'RECOGNITION-DEMO',userName:'reviewer',displayName:'Recognition Reviewer',email:'reviewer@example.test',isPlatformAdmin:false,roles:['CRMStaff'],permissions:grants,storeIds:[7]};}
async function mock(page:Page,grants=permissions){const user=identity(grants);const expires=new Date(Date.now()+3600000).toISOString();const auth=()=>({accessToken:jwt(),accessTokenExpiresUtc:expires,user});const bodies:unknown[]=[];await page.route('**/api/auth/login',route=>json(route,auth()));await page.route('**/api/auth/refresh',route=>json(route,auth()));await page.route('**/api/auth/me',route=>json(route,{user,accessTokenExpiresUtc:expires}));await page.route('**/api/tenant/**',route=>{const request=route.request();const path=new URL(request.url()).pathname.replace('/api/tenant/','');if(request.method()!=='GET')bodies.push(request.postDataJSON());if(path==='dashboard/summary')return json(route,{activeUsers:2,activeStores:1,activeStaff:1,activeCategories:2,openShifts:0,activePresenceSessions:0});if(path==='recognition/settings')return json(route,{enabled:true,minimumConfidence:.85,minimumQuality:.7,ambiguityDelta:.05,retentionDaysAfterWithdrawal:30,storesRawImages:false,automaticIdentityMerge:false,externalIdentityDatabases:false});if(path==='recognition/candidates')return json(route,[{id:21,storeId:7,personTrackSessionId:41,biometricTemplateId:51,customerId:61,requestId:'demo-21',purpose:'Store welcome',confidence:.91,quality:.88,secondBestConfidence:.89,status:2,createdUtc:'2026-08-25T12:00:00Z',reviewedUtc:null,reviewedByUserId:null,reviewReason:'Ambiguous candidates require human review.'}]);if(path==='recognition/candidates/21/review')return json(route,{id:21,status:3});return json(route,[]);});return bodies;}
async function signIn(page:Page){await page.goto('/login');await page.getByLabel('Tenant code').fill('RECOGNITION-DEMO');await page.getByLabel('Email or username').fill('reviewer');await page.getByLabel('Password').fill('safe-e2e-password');await page.getByRole('button',{name:'Sign in'}).click();await expect(page).toHaveURL(/\/customer-admin\/dashboard$/);}

test('recognition queue remains consent-gated and human-reviewed without auto merge',async({page})=>{const bodies=await mock(page);await signIn(page);await page.goto('/customer-admin/recognition');await expect(page.getByRole('heading',{name:'Consent-based recognition'})).toBeVisible();await expect(page.getByText(/Anonymous tracks remain anonymous/)).toBeVisible();await expect(page.getByText(/Ambiguous candidates require human review/)).toBeVisible();await page.getByRole('button',{name:'Accept candidate'}).click();await expect.poll(()=>bodies.length).toBeGreaterThan(0);const serialized=JSON.stringify(bodies);expect(serialized).not.toMatch(/tenantId/i);expect(serialized).not.toMatch(/customerMerge|associateCustomer/i);expect(serialized).not.toMatch(/rawImage|faceImage|aadhaar|pan/i);});
test('recognition route rejects users without Recognition.View',async({page})=>{await mock(page,permissions.filter(x=>x!=='Recognition.View'));await signIn(page);await page.goto('/customer-admin/recognition');await expect(page).toHaveURL(/\/access-denied$/);});
