import { expect, Page, Route, test } from '@playwright/test';

function jwtWithFutureExpiry():string{const h=Buffer.from(JSON.stringify({alg:'none',typ:'JWT'})).toString('base64url');const p=Buffer.from(JSON.stringify({exp:Math.floor(Date.now()/1000)+3600})).toString('base64url');return `${h}.${p}.signature`;}
const permissions=['TenantDashboard.View','Products.View','Products.Create','Products.Edit','Products.ManageStores','RetailInvoices.View','RetailInvoices.Create','RetailInvoices.Edit','RetailInvoices.Finalize','RetailInvoices.Cancel','RetailPayments.View','RetailPayments.Create','RetailSpendAttribution.View','RetailSpendAttribution.Manage','RetailReports.View'];
const json=(route:Route,body:unknown,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(body)});
function identity(overrides:Record<string,unknown>={}){return{userId:501,tenantId:25,tenantCode:'DEMO-STORE',userName:'owner',displayName:'Demo Shop Owner',email:'owner@example.test',isPlatformAdmin:false,roles:['TenantAdmin'],permissions,storeIds:[101],...overrides};}
interface State{calls:string[];bodies:unknown[];products:any[];invoice:any|null;}
async function mockApi(page:Page,user=identity()):Promise<State>{
 const now='2026-08-23T15:30:00Z';const state:State={calls:[],bodies:[],products:[{id:20,productCode:'SKU-001',barcode:'890123',name:'Silk Saree',categoryId:40,categoryName:'Sarees',brand:'Brand A',unitName:'Each',salePrice:1000,taxPercent:5,isActive:true}],invoice:null};
 const expires=new Date(Date.now()+3600000).toISOString();const auth=()=>({accessToken:jwtWithFutureExpiry(),accessTokenExpiresUtc:expires,user});
 await page.route('**/api/auth/login',r=>json(r,auth()));await page.route('**/api/auth/refresh',r=>json(r,auth()));await page.route('**/api/auth/me',r=>json(r,{user,accessTokenExpiresUtc:expires}));
 await page.route('**/api/tenant/**',async route=>{const req=route.request();const url=new URL(req.url());const path=url.pathname.replace('/api/tenant/','');const method=req.method();state.calls.push(`${method} ${path}${url.search}`);if(method!=='GET')state.bodies.push(req.postDataJSON());
  if(path==='dashboard/summary'&&method==='GET')return json(route,{activeUsers:2,activeStores:1,activeStaff:1,activeCategories:2,openShifts:0,activePresenceSessions:0});
  if(path==='products'&&method==='GET')return json(route,{data:state.products,pageNumber:1,pageSize:50,totalCount:state.products.length,totalPages:1});
  if(path==='products'&&method==='POST'){const b=req.postDataJSON() as any;const p={id:21,productCode:b.productCode,barcode:b.barcode,name:b.name,categoryId:b.categoryId,categoryName:'Sarees',brand:b.brand,unitName:b.unitName,salePrice:b.salePrice,taxPercent:b.taxPercent,isActive:true,description:null,costPrice:b.costPrice,stores:(b.storeIds||[]).map((storeId:number)=>({storeId,isActive:true})),createdUtc:now,updatedUtc:now};state.products.push(p);return json(route,p,201);}
  if(path==='retail/invoices'&&method==='GET')return json(route,{data:state.invoice?[state.invoice]:[],pageNumber:1,pageSize:25,totalCount:state.invoice?1:0,totalPages:state.invoice?1:0});
  if(path==='retail/invoices'&&method==='POST'){const b=req.postDataJSON() as any;state.invoice={id:77,invoiceNumber:'INV-20260823-0001',storeId:b.storeId,customerId:b.customerId,customerCode:'CUST-001',customerName:'Priya Shah',householdId:b.householdId,customerVisitId:b.customerVisitId,visitPartyId:b.visitPartyId,invoiceUtc:now,subtotal:2000,discountAmount:100,taxAmount:95,grandTotal:1995,paidAmount:0,balanceAmount:1995,status:1,notes:b.notes,items:[{id:701,productId:20,productCode:'SKU-001',productName:'Silk Saree',categoryId:40,categoryName:'Sarees',quantity:2,unitPrice:1000,discountAmount:100,taxPercent:5,taxAmount:95,lineSubtotal:2000,lineTotal:1995}],payments:[],participants:[],attributions:[],attributedTotal:0,unattributedTotal:1995,createdUtc:now,updatedUtc:now,cancelledUtc:null,cancellationReason:null};return json(route,state.invoice,201);}
  if(path==='retail/invoices/77'&&method==='GET')return json(route,state.invoice);
  if(path==='retail/invoices/77/finalize'&&method==='POST'){state.invoice.status=2;return json(route,state.invoice);}
  if(path==='retail/invoices/77/payments'&&method==='POST'){const b=req.postDataJSON() as any;state.invoice.payments.push({id:801,paymentReference:b.paymentReference||'PAY-1',paymentMethod:b.paymentMethod,amount:b.amount,paymentUtc:now,status:2,externalTransactionId:null,notes:null,receivedByUserId:501});state.invoice.paidAmount=b.amount;state.invoice.balanceAmount=state.invoice.grandTotal-b.amount;state.invoice.status=state.invoice.balanceAmount===0?4:3;return json(route,state.invoice);}
  return json(route,{message:`Unhandled Phase8 route ${method} ${path}`},501);
 });return state;
}
async function signIn(page:Page){await page.goto('/login');await page.getByLabel('Tenant code').fill('DEMO-STORE');await page.getByLabel('Email or username').fill('owner');await page.getByLabel('Password').fill('safe-e2e-password');await page.getByRole('button',{name:'Sign in'}).click();await expect(page).toHaveURL(/\/customer-admin\/dashboard$/);}

test('product search and create never send browser TenantId',async({page})=>{const state=await mockApi(page);await signIn(page);await page.goto('/customer-admin/products');await expect(page.getByText('SKU-001',{exact:true})).toBeVisible();await page.getByPlaceholder('SKU',{exact:true}).fill('SKU-002');await page.getByPlaceholder('Product name').fill('Cotton Saree');await page.getByPlaceholder('Category ID').last().fill('40');await page.getByPlaceholder('Sale price').fill('1200');await page.getByRole('button',{name:'Create',exact:true}).click();await expect(page.getByText('Product created.',{exact:true})).toBeVisible();expect(JSON.stringify(state.bodies)).not.toMatch(/tenantId/i);expect(state.calls.some(x=>/tenantId/i.test(x))).toBe(false);});

test('invoice creation uses server totals then finalize and payment update factual balance',async({page})=>{const state=await mockApi(page);await signIn(page);await page.goto('/customer-admin/retail/invoices/new');await page.getByPlaceholder('Store ID').fill('101');await page.getByPlaceholder('Customer ID optional').fill('901');await page.getByPlaceholder('Product ID').fill('20');await page.getByPlaceholder('Qty').fill('2');await page.getByPlaceholder('Discount').fill('100');await page.getByRole('button',{name:'Create invoice'}).click();await expect(page).toHaveURL(/\/customer-admin\/retail\/invoices\/77$/);await expect(page.getByText('₹1995',{exact:true}).first()).toBeVisible();await page.getByRole('button',{name:'Finalize'}).click();await expect(page.getByText('Invoice finalized.',{exact:true})).toBeVisible();const payment=page.locator('section.card').filter({has:page.getByRole('heading',{name:'Add payment'})});await payment.getByPlaceholder('Amount').fill('1000');await payment.getByRole('button',{name:'Record payment'}).click();await expect(page.getByText('Payment recorded.',{exact:true})).toBeVisible();await expect(page.getByText('₹995',{exact:true})).toBeVisible();expect(JSON.stringify(state.bodies)).not.toMatch(/tenantId/i);});

test('retail route permission guard denies user without retail invoice permission',async({page})=>{await mockApi(page,identity({roles:['StoreManager'],permissions:['TenantDashboard.View','Products.View'],storeIds:[101]}));await signIn(page);await page.goto('/customer-admin/retail/invoices');await expect(page).toHaveURL(/\/access-denied$/);});
