import { expect, Page, Route, test } from '@playwright/test';

function jwtWithFutureExpiry():string{const h=Buffer.from(JSON.stringify({alg:'none',typ:'JWT'})).toString('base64url');const p=Buffer.from(JSON.stringify({exp:Math.floor(Date.now()/1000)+3600})).toString('base64url');return `${h}.${p}.signature`;}
const json=(route:Route,body:unknown,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(body)});
const permissions=['TenantDashboard.View','Customers.View','Households.View','Preferences.View','Preferences.Manage','StoreCategories.View','StoreCategories.Manage','VoiceCommands.Use','VoiceCommands.View','VoiceCommands.Configure','VoiceCommands.Audit','RetailInvoices.View'];
function tenantIdentity(overrides:Record<string,unknown>={}){return{userId:701,tenantId:31,tenantCode:'VOICE-DEMO',userName:'manager',displayName:'Voice Manager',email:'voice@example.test',isPlatformAdmin:false,roles:['StoreManager'],permissions,storeIds:[101],...overrides};}
async function mockAuth(page:Page,user=tenantIdentity()){const expires=new Date(Date.now()+3600000).toISOString();const auth=()=>({accessToken:jwtWithFutureExpiry(),accessTokenExpiresUtc:expires,user});await page.route('**/api/auth/login',r=>json(r,auth()));await page.route('**/api/auth/refresh',r=>json(r,auth()));await page.route('**/api/auth/me',r=>json(r,{user,accessTokenExpiresUtc:expires}));}
async function signIn(page:Page){await page.goto('/login');await page.getByLabel('Tenant code').fill('VOICE-DEMO');await page.getByLabel('Email or username').fill('manager');await page.getByLabel('Password').fill('safe-e2e-password');await page.getByRole('button',{name:'Sign in'}).click();await expect(page).toHaveURL(/\/customer-admin\/dashboard$/);}

interface VoiceState{calls:string[];bodies:unknown[];signals:number;confirmed:boolean;}
async function mockVoice(page:Page,user=tenantIdentity()):Promise<VoiceState>{await mockAuth(page,user);const state:VoiceState={calls:[],bodies:[],signals:0,confirmed:false};let session={id:501,storeId:101,customerId:9001,matchedTrigger:'Magic Add',recognizedText:null as string|null,recognitionConfidence:null as number|null,proposedPreferenceType:null as number|null,proposedReferenceId:null as number|null,proposedValue:null as string|null,confirmationRequired:true,status:1,expiresUtc:'2026-08-24T04:00:30Z',resolvedUtc:null as string|null};
 await page.route('**/api/tenant/**',route=>{const req=route.request();const url=new URL(req.url());const path=url.pathname.replace('/api/tenant/','');state.calls.push(`${req.method()} ${path}${url.search}`);if(req.method()!=='GET'){const body=req.postDataJSON();state.bodies.push(body);}
  if(path==='dashboard/summary')return json(route,{activeUsers:2,activeStores:1,activeStaff:1,activeCategories:2,openShifts:0,activePresenceSessions:0});
  if(path==='stores/101/voice-command-runtime'&&req.method()==='GET')return json(route,{storeId:101,triggerKeyword:'Magic Add',responseMode:'InAppAndVoice',isEnabled:true,requireConfirmationForAmbiguousCategory:true,aliases:['Apna Add'],languageCode:'gu-IN',requireConfirmation:true,listeningTimeoutSeconds:30,minimumRecognitionConfidence:70});
  if(path==='stores/101/voice-command-runtime'&&req.method()==='PUT')return json(route,{storeId:101,...req.postDataJSON()});
  if(path==='voice/commands/start'&&req.method()==='POST'){const b=req.postDataJSON() as Record<string,unknown>;if(b['triggerText']!=='Magic Add'&&b['triggerText']!=='Apna Add')return json(route,{message:'Voice trigger does not match this store configuration.'},400);session={...session,matchedTrigger:String(b['triggerText'])};return json(route,session);}
  if(path==='voice/commands/501/interpret'&&req.method()==='POST'){const b=req.postDataJSON() as Record<string,unknown>;const text=String(b['recognizedText']??'');if(text==='Unknown Random Category')return json(route,{message:'Category not found. Add an authorized category/alias instead of creating one from voice text.'},400);if(!b['selectedCategoryId'])return json(route,{session,needsCategorySelection:true,candidates:[{categoryId:11,categoryCode:'BAN',categoryName:'Banarasi Saree',matchSource:'Alias'},{categoryId:12,categoryCode:'PARTY',categoryName:'Party Wear Saree',matchSource:'Alias'}],resolutionMessage:'Multiple categories matched. Select one of the server-resolved categories before any CRM write.'});session={...session,recognizedText:text,recognitionConfidence:Number(b['recognitionConfidence']),proposedPreferenceType:1,proposedReferenceId:Number(b['selectedCategoryId']),proposedValue:Number(b['selectedCategoryId'])===11?'Banarasi Saree':'Party Wear Saree',status:2};return json(route,{session,needsCategorySelection:false,candidates:[{categoryId:Number(b['selectedCategoryId']),categoryCode:'BAN',categoryName:session.proposedValue,matchSource:'Alias'}],resolutionMessage:'Category resolved. CRM write requires confirmation.'});}
  if(path==='voice/commands/501/confirm'&&req.method()==='POST'){state.confirmed=true;state.signals++;session={...session,status:3,resolvedUtc:'2026-08-24T04:00:05Z'};return json(route,session);}
  if(path==='voice/commands/501/reject'&&req.method()==='POST'){session={...session,status:4,resolvedUtc:'2026-08-24T04:00:05Z'};return json(route,session);}
  if(path.startsWith('store-categories/11/aliases')&&req.method()==='POST')return json(route,{id:1,storeId:101,productCategoryId:11,aliasText:'Banarasi Sadi',normalizedAliasText:'banarasi sadi',languageCode:'gu-IN',isActive:true,createdUtc:'2026-08-24T04:00:00Z'},201);
  if(path.startsWith('preferences/audit'))return json(route,[{id:1,storeId:101,userId:701,action:'VoiceCommandConfirmed',entityType:'VoiceCommandSession',entityId:'501',beforeJson:null,afterJson:null,correlationId:'p10-e2e',createdUtc:'2026-08-24T04:00:05Z'}]);
  return json(route,{message:`Unhandled Phase10 route ${req.method()} ${path}`},501);
 });return state;}

test('dynamic store trigger and ambiguity require server category selection plus confirmation',async({page})=>{const state=await mockVoice(page);await signIn(page);await page.goto('/customer-admin/voice-commands');await page.getByPlaceholder('Store ID').fill('101');await page.getByRole('button',{name:'Load voice settings'}).click();await expect(page.locator('input[formcontrolname="triggerKeyword"]')).toHaveValue('Magic Add');await expect(page.getByPlaceholder('Trigger aliases comma separated')).toHaveValue(/Apna Add/);await page.getByPlaceholder('Customer ID').fill('9001');await page.getByPlaceholder('Configured trigger phrase').fill('Apna Add');await page.getByRole('button',{name:'Start listening'}).click();await expect(page.getByText(/Listening session started/)).toBeVisible();await page.getByPlaceholder(/Recognized category text/).fill('Party Saree');await page.getByPlaceholder('Recognition confidence').fill('94');await page.getByRole('button',{name:'Resolve category'}).click();await expect(page.getByText(/Multiple categories matched/)).toBeVisible();expect(state.signals).toBe(0);await page.getByLabel('Resolved candidates').selectOption({label:'Banarasi Saree (BAN)'});await page.getByRole('button',{name:'Resolve category'}).click();await expect(page.getByText(/CRM write requires confirmation/)).toBeVisible();expect(state.signals).toBe(0);await page.getByRole('button',{name:'Confirm CRM write'}).click();await expect(page.getByText(/confirmed and recorded/)).toBeVisible();expect(state.signals).toBe(1);expect(state.confirmed).toBe(true);expect(JSON.stringify(state.bodies)).not.toMatch(/tenantId|preferenceType|referenceId|"value"/i);});

test('unknown category is rejected without creating a signal or random category',async({page})=>{const state=await mockVoice(page);await signIn(page);await page.goto('/customer-admin/voice-commands');await page.getByPlaceholder('Store ID').fill('101');await page.getByRole('button',{name:'Load voice settings'}).click();await page.getByPlaceholder('Customer ID').fill('9001');await page.getByPlaceholder('Configured trigger phrase').fill('Magic Add');await page.getByRole('button',{name:'Start listening'}).click();await page.getByPlaceholder(/Recognized category text/).fill('Unknown Random Category');await page.getByPlaceholder('Recognition confidence').fill('95');await page.getByRole('button',{name:'Resolve category'}).click();await expect(page.getByText(/Category not found/)).toBeVisible();expect(state.signals).toBe(0);expect(state.calls.some(x=>/create-category/i.test(x))).toBe(false);});

test('category alias creation targets an existing category and remains tenant/store scoped',async({page})=>{const state=await mockVoice(page);await signIn(page);await page.goto('/customer-admin/voice-commands');await page.getByPlaceholder('Store ID').fill('101');await page.getByRole('button',{name:'Load voice settings'}).click();await page.getByPlaceholder('Existing category ID').fill('11');await page.getByPlaceholder(/Alias, e.g./).fill('Banarasi Sadi');await page.getByPlaceholder('Language code').last().fill('gu-IN');await page.getByRole('button',{name:'Add category alias'}).click();await expect(page.getByText('Category alias added.')).toBeVisible();const aliasBody=state.bodies.find(x=>JSON.stringify(x).includes('Banarasi Sadi'));expect(aliasBody).toMatchObject({storeId:101,aliasText:'Banarasi Sadi',languageCode:'gu-IN'});expect(JSON.stringify(aliasBody)).not.toMatch(/tenantId|autoCreate/i);});

test('voice audit route is permission guarded and displays auditable actions',async({page})=>{await mockVoice(page);await signIn(page);await page.goto('/customer-admin/voice-command-audit');await page.getByPlaceholder('Store ID').fill('101');await page.getByRole('button',{name:'Load voice settings'}).click();await expect(page.getByRole('heading',{name:'Preference & voice audit'})).toBeVisible();await expect(page.getByText('VoiceCommandConfirmed')).toBeVisible();});

test('voice audit route denies a user without audit permission',async({page})=>{await mockVoice(page,tenantIdentity({permissions:permissions.filter(x=>x!=='VoiceCommands.Audit')}));await signIn(page);await page.goto('/customer-admin/voice-command-audit');await expect(page).toHaveURL(/\/access-denied$/);});
