import {expect,Page,Route,test} from '@playwright/test';

const permissions=['TenantDashboard.View','Alerts.View','Alerts.Acknowledge','Alerts.Configure'];
function jwt(){const h=Buffer.from(JSON.stringify({alg:'none',typ:'JWT'})).toString('base64url');const p=Buffer.from(JSON.stringify({exp:Math.floor(Date.now()/1000)+3600})).toString('base64url');return `${h}.${p}.signature`;}
const json=(route:Route,body:unknown,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(body)});
function identity(grants=permissions){return{userId:711,tenantId:31,tenantCode:'ALERT-DEMO',userName:'manager',displayName:'Alert Manager',email:'alerts@example.test',isPlatformAdmin:false,roles:['StoreManager'],permissions:grants,storeIds:[101]};}
async function mock(page:Page,grants=permissions,initialAlert=true){const user=identity(grants);const expires=new Date(Date.now()+3600000).toISOString();const auth=()=>({accessToken:jwt(),accessTokenExpiresUtc:expires,user});const state={bodies:[] as unknown[],recoveryCalls:0,alert:{id:51,alertType:'returning.customer',storeId:101,severity:2,title:'Returning customer detected',message:'A returning customer entered Surat store.',entityType:'Customer',entityId:'9001',createdUtc:'2026-08-24T15:00:00Z',acknowledgedUtc:null as string|null,acknowledgedByUserId:null as number|null,resolvedUtc:null as string|null,status:2,correlationId:'p11-e2e',deduplicationKey:'returning:9001:visit:77'}};
 await page.route('**/api/auth/login',r=>json(r,auth()));await page.route('**/api/auth/refresh',r=>json(r,auth()));await page.route('**/api/auth/me',r=>json(r,{user,accessTokenExpiresUtc:expires}));
 await page.route('**/api/tenant/**',route=>{const req=route.request();const url=new URL(req.url());const path=url.pathname.replace('/api/tenant/','');if(req.method()!=='GET')state.bodies.push(req.postDataJSON());if(path==='dashboard/summary')return json(route,{activeUsers:2,activeStores:1,activeStaff:1,activeCategories:2,openShifts:0,activePresenceSessions:0});if(path==='alerts')return json(route,{items:initialAlert?[state.alert]:[],unreadCount:initialAlert&&state.alert.status<=2?1:0,lastEventId:80});if(path.startsWith('alerts/recovery')){state.recoveryCalls++;const recovered={eventId:81,eventType:'alert.created',contractVersion:1,occurredUtc:'2026-08-24T15:03:00Z',tenantId:31,storeId:101,correlationId:'p17-reconnect',alert:{...state.alert,id:52,title:'Recovered after reconnect',correlationId:'p17-reconnect',deduplicationKey:'recovered:52'}};return json(route,{requestedAfterEventId:0,nextCursor:state.recoveryCalls>=2?81:80,events:!initialAlert&&state.recoveryCalls>=2?[recovered]:[]});}if(path==='alerts/51/acknowledge'&&req.method()==='POST'){state.alert={...state.alert,status:3,acknowledgedUtc:'2026-08-24T15:01:00Z',acknowledgedByUserId:711};return json(route,state.alert);}if(path==='alerts/51/resolve'&&req.method()==='POST'){state.alert={...state.alert,status:4,resolvedUtc:'2026-08-24T15:02:00Z'};return json(route,state.alert);}return json(route,{message:`Unhandled ${req.method()} ${path}`},501);});return state;}
async function signIn(page:Page){await page.goto('/login');await page.getByLabel('Tenant code').fill('ALERT-DEMO');await page.getByLabel('Email or username').fill('manager');await page.getByLabel('Password').fill('safe-e2e-password');await page.getByRole('button',{name:'Sign in'}).click();await expect(page).toHaveURL(/\/customer-admin\/dashboard$/);}

test('notification center loads authoritative alerts and applies acknowledge plus resolve',async({page})=>{const state=await mock(page);await signIn(page);await page.goto('/customer-admin/alerts');await expect(page.getByRole('heading',{name:'Notification center'})).toBeVisible();await expect(page.getByText('Returning customer detected')).toBeVisible();await expect(page.getByLabel('Alert summary').locator('div').filter({hasText:'Unread'}).locator('b')).toHaveText('1');await page.getByText('Returning customer detected').click();await page.getByRole('button',{name:'Acknowledge'}).click();await expect(page.getByText('Acknowledged',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Resolve'}).click();await expect(page.getByText('Resolved',{exact:true})).toBeVisible();expect(JSON.stringify(state.bodies)).not.toMatch(/tenantId|acknowledgedByUserId/i);});

test('notification center route rejects a user without Alerts.View',async({page})=>{await mock(page,permissions.filter(x=>x!=='Alerts.View'));await signIn(page);await page.goto('/customer-admin/alerts');await expect(page).toHaveURL(/\/access-denied$/);});

test('SignalR reconnect reports cursor and recovers missed authoritative alert',async({page,request})=>{await request.post('http://127.0.0.1:4317/reset');const state=await mock(page,permissions,false);await signIn(page);await page.goto('/customer-admin/alerts');await expect(page.getByText('Connected',{exact:true})).toBeVisible();await expect.poll(()=>state.recoveryCalls).toBeGreaterThanOrEqual(1);await request.post('http://127.0.0.1:4317/trigger-reconnect');await expect(page.getByText('Recovered after reconnect',{exact:true})).toBeVisible({timeout:15000});const stats=await(await request.get('http://127.0.0.1:4317/stats')).json();expect(stats.connectionCount).toBeGreaterThanOrEqual(2);expect(stats.reconnectInvocations).toBeGreaterThanOrEqual(1);expect(state.recoveryCalls).toBeGreaterThanOrEqual(2);});
