import {expect,Page,Route,test} from '@playwright/test';

const permissions=['TenantDashboard.View','Integrations.View','Integrations.Manage','Webhooks.View','Webhooks.Manage'];
function jwt(){const h=Buffer.from(JSON.stringify({alg:'none',typ:'JWT'})).toString('base64url');const p=Buffer.from(JSON.stringify({exp:Math.floor(Date.now()/1000)+3600})).toString('base64url');return `${h}.${p}.signature`;}
const json=(route:Route,body:unknown,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(body)});
function identity(grants=permissions){return{userId:812,tenantId:42,tenantCode:'INTEGRATION-DEMO',userName:'integration-admin',displayName:'Integration Admin',email:'integration@example.test',isPlatformAdmin:false,roles:['IntegrationAdmin'],permissions:grants,storeIds:[]};}
async function mock(page:Page,grants=permissions){const user=identity(grants);const expires=new Date(Date.now()+3600000).toISOString();const auth=()=>({accessToken:jwt(),accessTokenExpiresUtc:expires,user});const state={bodies:[] as unknown[],configuration:{id:71,provider:'Demo POS',integrationType:3,enabled:true,endpointBaseUrl:'https://pos.example.test/hooks',hasCredentialReference:true,credentialReferenceHint:'••••d-v1',hasWebhookSigningSecret:true,webhookSigningSecretHint:'••••g-v1',timeoutSeconds:10,retryMaxAttempts:5,retryBaseDelaySeconds:5,createdUtc:'2026-08-24T18:00:00Z',updatedUtc:'2026-08-24T18:00:00Z',connectionStatus:'Retrying',webhookStatus:'Signing configured'},history:[{id:81,integrationConfigurationId:71,inboundEventId:null,outboxMessageId:91,correlationId:'p12-e2e',provider:'Demo POS',direction:2,status:5,durationMilliseconds:32,httpStatusCode:400,errorCategory:'client',createdUtc:'2026-08-24T18:01:00Z'}]};
 await page.route('**/api/auth/login',r=>json(r,auth()));await page.route('**/api/auth/refresh',r=>json(r,auth()));await page.route('**/api/auth/me',r=>json(r,{user,accessTokenExpiresUtc:expires}));
 await page.route('**/api/tenant/**',route=>{const req=route.request();const url=new URL(req.url());const path=url.pathname.replace('/api/tenant/','');if(req.method()!=='GET')state.bodies.push(req.postDataJSON());if(path==='dashboard/summary')return json(route,{activeUsers:2,activeStores:1,activeStaff:1,activeCategories:2,openShifts:0,activePresenceSessions:0});if(path==='integrations'&&req.method()==='GET')return json(route,[state.configuration]);if(path==='integrations/deliveries'&&req.method()==='GET')return json(route,state.history);if(path==='integrations/71/rotate-references'&&req.method()==='POST'){state.configuration={...state.configuration,credentialReferenceHint:'••••d-v2',webhookSigningSecretHint:'••••g-v2'};return json(route,state.configuration);}if(path==='integrations/deliveries/91/retry'&&req.method()==='POST'){state.history=[];return json(route,{id:91,status:5});}if(path==='integrations/71/test-delivery'&&req.method()==='POST')return json(route,{id:92,status:1});return json(route,{message:`Unhandled ${req.method()} ${path}`},501);});return state;}
async function signIn(page:Page){await page.goto('/login');await page.getByLabel('Tenant code').fill('INTEGRATION-DEMO');await page.getByLabel('Email or username').fill('integration-admin');await page.getByLabel('Password').fill('safe-e2e-password');await page.getByRole('button',{name:'Sign in'}).click();await expect(page).toHaveURL(/\/customer-admin\/dashboard$/);}

test('integration settings mask references, rotate credentials and retry dead letters',async({page})=>{const state=await mock(page);await signIn(page);await page.goto('/customer-admin/integrations');await expect(page.getByRole('heading',{name:'Integration Settings'})).toBeVisible();await expect(page.getByText('Demo POS',{exact:true})).toBeVisible();await page.getByText('Demo POS',{exact:true}).click();await expect(page.getByText(/credential ••••d-v1/)).toBeVisible();await expect(page.getByText('credential-v1')).toHaveCount(0);await page.getByLabel('New credential reference').fill('credential-ref-v2');await page.getByLabel('New signing reference').fill('signing-ref-v2');await page.getByRole('button',{name:'Rotate references'}).click();await expect(page.getByText(/credential ••••d-v2/)).toBeVisible();await page.getByRole('button',{name:'Retry'}).click();await expect(page.getByRole('button',{name:'Retry'})).toHaveCount(0);expect(JSON.stringify(state.bodies)).not.toMatch(/tenantId|actual-secret|password/i);});
test('integration route rejects users without Integrations.View',async({page})=>{await mock(page,permissions.filter(x=>x!=='Integrations.View'));await signIn(page);await page.goto('/customer-admin/integrations');await expect(page).toHaveURL(/\/access-denied$/);});
