import { expect, Page, Route, test } from '@playwright/test';

function jwtWithFutureExpiry():string{const h=Buffer.from(JSON.stringify({alg:'none',typ:'JWT'})).toString('base64url');const p=Buffer.from(JSON.stringify({exp:Math.floor(Date.now()/1000)+3600})).toString('base64url');return `${h}.${p}.signature`;}
const permissions=['TenantDashboard.View','Customers.View','Households.View','Households.Create','Households.Edit','Households.ManageMembers','Visits.View','Visits.Edit','VisitParties.View'];
interface Member{customerId:number;customerCode:string;firstName:string;lastName:string|null;relationshipType:string;relationshipSource:number;isVerified:boolean;verifiedByUserId:number;verifiedUtc:string;isActive:boolean;}
interface Household{id:number;householdCode:string;name:string;notes:string|null;isActive:boolean;members:Member[];createdUtc:string;updatedUtc:string;}
interface Visit{id:number;visitCode:string;customerId:number;customerCode:string;customerName:string;storeId:number;visitPartyId:number|null;enteredUtc:string;exitedUtc:string|null;source:number;status:number;createdUtc:string;updatedUtc:string;}
interface Party{id:number;partyCode:string;storeId:number;startedUtc:string;endedUtc:string|null;source:number;status:number;memberCount:number;members:{id:number;identityType:number;customerId:number|null;customerCode:string|null;anonymousVisitorId:number|null;visitorCode:string|null;joinedUtc:string}[];createdUtc:string;updatedUtc:string;}
interface State{households:Household[];visits:Visit[];parties:Party[];calls:string[];bodies:unknown[];}
const json=(route:Route,body:unknown,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(body)});
function identity(overrides:Record<string,unknown>={}){return{userId:501,tenantId:25,tenantCode:'DEMO-STORE',userName:'owner',displayName:'Demo Shop Owner',email:'owner@example.test',isPlatformAdmin:false,roles:['TenantAdmin'],permissions,storeIds:[101],...overrides};}
async function mockApi(page:Page,user=identity()):Promise<State>{
 const now='2026-08-23T14:00:00Z';const state:State={households:[{id:10,householdCode:'HH-001',name:'Shah Family',notes:'Verified household',isActive:true,members:[{customerId:901,customerCode:'CUST-001',firstName:'Priya',lastName:'Shah',relationshipType:'Parent',relationshipSource:1,isVerified:true,verifiedByUserId:501,verifiedUtc:now,isActive:true}],createdUtc:now,updatedUtc:now}],visits:[{id:30,visitCode:'VST-001',customerId:901,customerCode:'CUST-001',customerName:'Priya Shah',storeId:101,visitPartyId:20,enteredUtc:now,exitedUtc:null,source:1,status:1,createdUtc:now,updatedUtc:now}],parties:[{id:20,partyCode:'PARTY-001',storeId:101,startedUtc:now,endedUtc:null,source:2,status:1,memberCount:2,members:[{id:1,identityType:1,customerId:901,customerCode:'CUST-001',anonymousVisitorId:null,visitorCode:null,joinedUtc:now},{id:2,identityType:2,customerId:null,customerCode:null,anonymousVisitorId:1001,visitorCode:'VIS-001',joinedUtc:now}],createdUtc:now,updatedUtc:now}],calls:[],bodies:[]};
 const expires=new Date(Date.now()+3600000).toISOString();
 const authResponse=()=>({accessToken:jwtWithFutureExpiry(),accessTokenExpiresUtc:expires,user});
 await page.route('**/api/auth/login',r=>json(r,authResponse()));
 await page.route('**/api/auth/refresh',r=>json(r,authResponse()));
 await page.route('**/api/auth/me',r=>json(r,{user,accessTokenExpiresUtc:expires}));
 await page.route('**/api/tenant/**',async route=>{const req=route.request();const url=new URL(req.url());const path=url.pathname.replace('/api/tenant/','');const method=req.method();state.calls.push(`${method} ${path}${url.search}`);if(method!=='GET')state.bodies.push(req.postDataJSON());
  if(path==='dashboard/summary'&&method==='GET')return json(route,{activeUsers:2,activeStores:1,activeStaff:1,activeCategories:2,openShifts:0,activePresenceSessions:0});
  if(path==='households'&&method==='GET')return json(route,{data:state.households.map(h=>({id:h.id,householdCode:h.householdCode,name:h.name,visibleMemberCount:h.members.filter(m=>m.isActive).length,isActive:h.isActive,updatedUtc:h.updatedUtc})),pageNumber:1,pageSize:25,totalCount:state.households.length,totalPages:1});
  if(path==='households'&&method==='POST'){const b=req.postDataJSON() as {householdCode:string|null;name:string;notes:string|null};const h:Household={id:11,householdCode:b.householdCode||'HH-AUTO-002',name:b.name,notes:b.notes,isActive:true,members:[],createdUtc:now,updatedUtc:now};state.households.push(h);return json(route,h,201);}
  const household=path.match(/^households\/(\d+)$/);if(household&&method==='GET')return json(route,state.households.find(x=>x.id===Number(household[1]))!);if(household&&method==='PUT'){const h=state.households.find(x=>x.id===Number(household[1]))!;Object.assign(h,req.postDataJSON(),{updatedUtc:now});return json(route,h);}
  const members=path.match(/^households\/(\d+)\/members$/);if(members&&method==='POST'){const h=state.households.find(x=>x.id===Number(members[1]))!;const b=req.postDataJSON() as {customerId:number;relationshipType:string;relationshipSource:number};h.members.push({customerId:b.customerId,customerCode:'CUST-002',firstName:'Ravi',lastName:'Shah',relationshipType:b.relationshipType,relationshipSource:b.relationshipSource,isVerified:true,verifiedByUserId:501,verifiedUtc:now,isActive:true});return json(route,h);}
  const member=path.match(/^households\/(\d+)\/members\/(\d+)$/);if(member&&method==='PUT'){const h=state.households.find(x=>x.id===Number(member[1]))!;const m=h.members.find(x=>x.customerId===Number(member[2]))!;Object.assign(m,req.postDataJSON(),{verifiedUtc:now});return json(route,h);}if(member&&method==='DELETE'){const h=state.households.find(x=>x.id===Number(member[1]))!;const m=h.members.find(x=>x.customerId===Number(member[2]))!;m.isActive=false;return route.fulfill({status:204});}
  if(path==='visits'&&method==='GET')return json(route,{data:state.visits,pageNumber:1,pageSize:25,totalCount:state.visits.length,totalPages:1});if(path==='visits'&&method==='POST'){const b=req.postDataJSON() as {storeId:number;customerId:number;visitPartyId:number|null;enteredUtc:string|null};const v:Visit={id:31,visitCode:'VST-002',customerId:b.customerId,customerCode:'CUST-001',customerName:'Priya Shah',storeId:b.storeId,visitPartyId:b.visitPartyId,enteredUtc:now,exitedUtc:null,source:1,status:1,createdUtc:now,updatedUtc:now};state.visits.push(v);return json(route,v,201);}
  if(path==='visit-parties'&&method==='GET')return json(route,{data:state.parties.map(({members,...p})=>p),pageNumber:1,pageSize:50,totalCount:state.parties.length,totalPages:1});const party=path.match(/^visit-parties\/(\d+)$/);if(party&&method==='GET')return json(route,state.parties.find(x=>x.id===Number(party[1]))!);
  return json(route,{message:`Unhandled Phase7 route ${method} ${path}`},501);
 });return state;
}
async function signIn(page:Page){await page.goto('/login');await page.getByLabel('Tenant code').fill('DEMO-STORE');await page.getByLabel('Email or username').fill('owner');await page.getByLabel('Password').fill('safe-e2e-password');await page.getByRole('button',{name:'Sign in'}).click();await expect(page).toHaveURL(/\/customer-admin\/dashboard$/);}

test('household search and create never send TenantId',async({page})=>{const state=await mockApi(page);await signIn(page);await page.locator('app-phase-five-dashboard main nav.nav').getByRole('link',{name:'Households',exact:true}).click();await expect(page.getByText('HH-001',{exact:true})).toBeVisible();await page.getByPlaceholder('Household name').fill('Patel Family');await page.getByRole('button',{name:'Create household'}).click();await expect(page.getByText('Household created.',{exact:true})).toBeVisible();expect(JSON.stringify(state.bodies)).not.toMatch(/tenantId/i);expect(state.calls.some(x=>/tenantId/i.test(x))).toBe(false);});

test('verified household member can be linked removed and re-added without anonymous visitor identity',async({page})=>{const state=await mockApi(page);await signIn(page);await page.goto('/customer-admin/households/10');await expect(page.getByText('CUST-001 · Priya Shah',{exact:true})).toBeVisible();await page.getByPlaceholder('Customer ID').fill('902');await page.getByPlaceholder('Relationship (e.g. Parent, Spouse)').fill('Sibling');await page.getByRole('button',{name:'Save member'}).click();await expect(page.getByText('Verified household member saved.',{exact:true})).toBeVisible();await expect(page.getByText('CUST-002 · Ravi Shah',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Remove'}).last().click();await expect(page.getByText('Household member removed.',{exact:true})).toBeVisible();expect(JSON.stringify(state.bodies)).not.toMatch(/anonymousVisitorId|visitorId|tenantId/i);});

test('visits are factual and Visit Party is visibly labeled Co-Visit not family truth',async({page})=>{await mockApi(page);await signIn(page);await page.goto('/customer-admin/visits');await expect(page.getByText('VST-001',{exact:true})).toBeVisible();await page.goto('/customer-admin/visit-parties');await expect(page.getByRole('heading',{name:'Visit Party / Co-Visit'})).toBeVisible();await expect(page.getByText('PARTY-001',{exact:true})).toBeVisible();await page.getByRole('button',{name:'View'}).click();await expect(page.getByText('Anonymous visitor VIS-001 (#1001)',{exact:true})).toBeVisible();await expect(page.getByText(/Observed together ≠ family/i)).toBeVisible();});

test('household route permission guard denies tenant user without Households.View',async({page})=>{await mockApi(page,identity({roles:['StoreManager'],permissions:['TenantDashboard.View','Visits.View'],storeIds:[101]}));await signIn(page);await page.goto('/customer-admin/households');await expect(page).toHaveURL(/\/access-denied$/);});

test('store-scoped phase7 pages trust server authorized results and never request another tenant',async({page})=>{const state=await mockApi(page,identity({roles:['StoreManager'],permissions:['TenantDashboard.View','Households.View','Visits.View','VisitParties.View'],storeIds:[101]}));await signIn(page);await page.goto('/customer-admin/households');await expect(page.getByText('Shah Family',{exact:true})).toBeVisible();await page.goto('/customer-admin/visits');await expect(page.getByText('VST-001',{exact:true})).toBeVisible();expect(state.calls.some(x=>/tenantId/i.test(x))).toBe(false);});
