import {expect,Page,Route,test} from '@playwright/test';

const permissions=['TenantDashboard.View','Reports.View','Reports.Export'];
function jwt(){const header=Buffer.from(JSON.stringify({alg:'none',typ:'JWT'})).toString('base64url');const payload=Buffer.from(JSON.stringify({exp:Math.floor(Date.now()/1000)+3600})).toString('base64url');return `${header}.${payload}.signature`;}
const json=(route:Route,body:unknown,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(body)});
function identity(grants=permissions){return{userId:915,tenantId:42,tenantCode:'REPORT-DEMO',userName:'reporter',displayName:'Report Operator',email:'reporter@example.test',isPlatformAdmin:false,roles:['StoreManager'],permissions:grants,storeIds:[7]};}
async function mock(page:Page,grants=permissions){const user=identity(grants);const expires=new Date(Date.now()+3600000).toISOString();const auth=()=>({accessToken:jwt(),accessTokenExpiresUtc:expires,user});const bodies:unknown[]=[];await page.route('**/api/auth/login',route=>json(route,auth()));await page.route('**/api/auth/refresh',route=>json(route,auth()));await page.route('**/api/auth/me',route=>json(route,{user,accessTokenExpiresUtc:expires}));await page.route('**/api/tenant/**',route=>{const request=route.request();const path=new URL(request.url()).pathname.replace('/api/tenant/','');if(request.method()!=='GET')bodies.push(request.postDataJSON());if(path==='dashboard/summary')return json(route,{activeUsers:2,activeStores:1,activeStaff:1,activeCategories:2,openShifts:0,activePresenceSessions:0});if(path==='reports/catalog')return json(route,[{reportType:1,code:'operational-summary',name:'Operational summary',scope:2,requiredPermission:'Reports.View',supportsPaging:true}]);if(path==='reports/run/1')return json(route,{reportType:1,fromUtc:'2026-08-01T00:00:00Z',toUtc:'2026-08-26T00:00:00Z',page:1,pageSize:100,totalRows:1,rows:[{domain:'Visits',storeId:7,metric:'Customer visits',value:12,label:null,occurredUtc:'2026-08-25T00:00:00Z'}]});if(path==='reports/exports'&&request.method()==='POST')return json(route,{id:31,reportType:1,format:1,status:1,progress:0,createdUtc:'2026-08-25T00:00:00Z',startedUtc:null,completedUtc:null,expiresUtc:'2026-08-26T00:00:00Z',error:null,attemptCount:0,canDownload:false});if(path==='reports/exports')return json(route,[{id:30,reportType:1,format:2,status:3,progress:100,createdUtc:'2026-08-25T00:00:00Z',startedUtc:'2026-08-25T00:01:00Z',completedUtc:'2026-08-25T00:02:00Z',expiresUtc:'2026-08-26T00:00:00Z',error:null,attemptCount:1,canDownload:true}]);if(path==='reports/exports/30/download-ticket')return json(route,{token:'safe.token',expiresUtc:'2026-08-25T00:07:00Z'});return json(route,[]);});return bodies;}
async function signIn(page:Page){await page.goto('/login');await page.getByLabel('Tenant code').fill('REPORT-DEMO');await page.getByLabel('Email or username').fill('reporter');await page.getByLabel('Password').fill('safe-e2e-password');await page.getByRole('button',{name:'Sign in'}).click();await expect(page).toHaveURL(/\/customer-admin\/dashboard$/);}

test('reports run server-side and CSV export is queued without TenantId',async({page})=>{const bodies=await mock(page);await signIn(page);await page.goto('/customer-admin/reports');await expect(page.getByRole('heading',{name:'Reports & exports'})).toBeVisible();await page.getByRole('button',{name:'Run paged report'}).click();await expect(page.getByText('Customer visits')).toBeVisible();await page.getByRole('button',{name:'Queue export'}).click();await expect.poll(()=>bodies.length).toBeGreaterThan(1);expect(JSON.stringify(bodies)).not.toMatch(/tenantId/i);await expect(page.getByText(/browser receives only paged report rows/)).toBeVisible();});
test('reports route rejects users without Reports.View',async({page})=>{await mock(page,permissions.filter(x=>x!=='Reports.View'));await signIn(page);await page.goto('/customer-admin/reports');await expect(page).toHaveURL(/\/access-denied$/);});
