import {expect,Page,Route,test} from '@playwright/test';

const permissions=['TenantDashboard.View','Cameras.View','Cameras.Manage','Cameras.Preview'];
const cameras=Array.from({length:5},(_,index)=>({id:31+index,storeId:7,cameraCode:index===0?'ENTRY':`CAM-${index+1}`,name:index===0?'Entry camera':`Camera ${index+1}`,hasRtspConfiguration:true,rtspConfigurationHint:'***safe',status:index===4?1:2,location:index===0?'Front door':`Zone ${index+1}`,direction:index===0?1:4,isActive:true,lastHeartbeatUtc:'2026-08-25T09:00:00Z',createdUtc:'2026-08-25T08:00:00Z',updatedUtc:'2026-08-25T09:00:00Z'}));
function jwt(){const h=Buffer.from(JSON.stringify({alg:'none',typ:'JWT'})).toString('base64url');const p=Buffer.from(JSON.stringify({exp:Math.floor(Date.now()/1000)+3600})).toString('base64url');return `${h}.${p}.signature`;}
const json=(route:Route,body:unknown,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(body)});
function identity(grants=permissions){return{userId:813,tenantId:42,tenantCode:'CAMERA-DEMO',userName:'camera-operator',displayName:'Camera Operator',email:'camera@example.test',isPlatformAdmin:false,roles:['CameraOperator'],permissions:grants,storeIds:[7]};}
async function mock(page:Page,grants=permissions){
  const user=identity(grants);const expires=new Date(Date.now()+3600000).toISOString();const auth=()=>({accessToken:jwt(),accessTokenExpiresUtc:expires,user});const bodies:unknown[]=[];
  await page.route('**/api/auth/login',r=>json(r,auth()));await page.route('**/api/auth/refresh',r=>json(r,auth()));await page.route('**/api/auth/me',r=>json(r,{user,accessTokenExpiresUtc:expires}));
  await page.route('**/api/tenant/**',route=>{const request=route.request();const url=new URL(request.url());const path=url.pathname.replace('/api/tenant/','');const raw=request.postData();if(raw)bodies.push(JSON.parse(raw));
    if(path==='dashboard/summary')return json(route,{activeUsers:2,activeStores:1,activeStaff:1,activeCategories:2,openShifts:0,activePresenceSessions:0});
    if(path==='cameras/capabilities')return json(route,{demoMode:true,previewEnabled:true,environment:'Test',identityRecognition:false,databaseAccessFromPython:false});
    if(path==='cameras/quota')return json(route,{maxCameras:5,configuredCameras:5,activeCameras:5,availableCameras:0,canAddActiveCamera:false});
    if(path==='cameras')return json(route,cameras);
    if(path==='cameras/tracks')return json(route,[{id:41,storeId:7,cameraId:31,personTrackId:'anonymous-41',startUtc:'2026-08-25T09:00:00Z',endUtc:null,confidence:.91,trackingState:1,subjectKind:1,customerId:null,staffProfileId:null,updatedUtc:'2026-08-25T09:00:02Z'}]);
    if(path==='cameras/31/zones')return json(route,[{id:51,cameraId:31,zoneCode:'ENTRY',name:'Entry',zoneType:1,geometryJson:'{}',version:1,categoryId:null,effectiveUtc:'2026-08-25T08:00:00Z',supersededUtc:null,isActive:true}]);
    if(path==='cameras/31/preview-grants')return json(route,[]);
    const start=path.match(/^cameras\/(\d+)\/preview-sessions$/);if(start&&request.method()==='POST'){const cameraId=Number(start[1]);return json(route,{sessionId:`preview-session-${cameraId}`,cameraId,expiresUtc:expires,frameUrl:`/api/tenant/cameras/${cameraId}/preview-sessions/preview-session-${cameraId}/frame`,refreshMilliseconds:500});}
    const frame=path.match(/^cameras\/(\d+)\/preview-sessions\/preview-session-\d+\/frame$/);if(frame)return route.fulfill({status:200,contentType:'image/jpeg',body:Buffer.from([1,2,3])});
    const end=path.match(/^cameras\/(\d+)\/preview-sessions\/preview-session-\d+$/);if(end&&request.method()==='DELETE')return route.fulfill({status:204});
    return json(route,{message:`Unhandled ${request.method()} ${path}`},501);
  });return bodies;
}
async function signIn(page:Page){await page.goto('/login');await page.getByLabel('Tenant code').fill('CAMERA-DEMO');await page.getByLabel('Email or username').fill('camera-operator');await page.getByLabel('Password').fill('safe-e2e-password');await page.getByRole('button',{name:'Sign in'}).click();await expect(page).toHaveURL(/\/customer-admin\/dashboard$/);}

test('camera operations show deterministic demo and anonymous state without credentials',async({page})=>{const bodies=await mock(page);await signIn(page);await page.goto('/customer-admin/cameras');await expect(page.getByRole('heading',{name:'Camera operations'})).toBeVisible();await expect(page.getByText(/DEMO MODE/)).toBeVisible();await expect(page.getByText(/anonymous by default/i)).toBeVisible();await expect(page.getByText('anonymous-41')).toBeVisible();await expect(page.getByText('vault:entry')).toHaveCount(0);expect(JSON.stringify(bodies)).not.toMatch(/tenantId/i);});
test('camera route rejects users without Cameras.View',async({page})=>{await mock(page,permissions.filter(x=>x!=='Cameras.View'));await signIn(page);await page.goto('/customer-admin/cameras');await expect(page).toHaveURL(/\/access-denied$/);});
test('explicitly authorized camera user can start a secure preview without seeing RTSP data',async({page})=>{await mock(page);await signIn(page);await page.goto('/customer-admin/cameras');await page.getByText(/ENTRY · Entry camera/).click();await page.getByRole('button',{name:'Start preview'}).click();await expect(page.getByRole('status').filter({hasText:'Live'})).toHaveText('Live');await expect(page.getByAltText('Entry camera live preview')).toBeVisible();await expect(page.getByText(/rtsp:\/\//i)).toHaveCount(0);});
test('live monitoring starts at most five secure tiles and filters camera health',async({page})=>{await mock(page);await signIn(page);await page.goto('/customer-admin/live-monitoring');await expect(page.getByRole('heading',{name:'Live Camera Monitoring'})).toBeVisible();await expect(page.locator('article.camera-tile')).toHaveCount(5);await expect(page.getByText('5 / 5')).toBeVisible();await expect(page.getByAltText('Entry camera live camera frame')).toBeVisible();await page.getByRole('button',{name:'Online',exact:true}).click();await expect(page.locator('article.camera-tile')).toHaveCount(4);await page.getByRole('button',{name:'Offline',exact:true}).click();await expect(page.locator('article.camera-tile')).toHaveCount(1);await expect(page.getByText(/rtsp:\/\//i)).toHaveCount(0);});
test('live monitoring route requires preview permission',async({page})=>{await mock(page,permissions.filter(x=>x!=='Cameras.Preview'));await signIn(page);await page.goto('/customer-admin/live-monitoring');await expect(page).toHaveURL(/\/access-denied$/);});
