import { CommonModule } from '@angular/common';
import { HttpErrorResponse } from '@angular/common/http';
import { ChangeDetectionStrategy, Component, OnInit, computed, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { AuthSessionService } from '../../core/auth/auth-session.service';
import { PERMISSIONS } from '../../core/auth/permission-catalog';
import { AdminShell } from '../../shared/admin-shell/admin-shell';
import { HouseholdApiService, HouseholdDetail, HouseholdRelationshipSource } from './household-api.service';

@Component({
 selector:'app-household-detail-page',standalone:true,imports:[CommonModule,ReactiveFormsModule,RouterLink,AdminShell],changeDetection:ChangeDetectionStrategy.OnPush,
 styles:[`:host{display:block}.wrap{padding:24px}.back{display:inline-block;margin-bottom:12px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.card{border:1px solid #ddd;border-radius:12px;padding:16px;background:var(--mat-sys-surface,#fff)}form{display:grid;gap:9px}input,select,button{min-height:40px;padding:8px;border:1px solid #ccc;border-radius:8px}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:9px;border-bottom:1px solid #eee}.muted{opacity:.65}.error{color:#b3261e}.ok{color:#147d32}.actions{display:flex;gap:6px;flex-wrap:wrap}@media(max-width:900px){.grid{grid-template-columns:1fr}}`],
 template:`<app-admin-shell><main class="wrap"><a class="back" routerLink="/customer-admin/households">← Households</a>@if(error()){<p class="error">{{error()}}</p>}@if(message()){<p class="ok">{{message()}}</p>}@if(household();as h){<h1>{{h.name}}</h1><p class="muted">{{h.householdCode}} · Verified/customer-provided household relationships</p><div class="grid"><section class="card"><h2>Household profile</h2><form [formGroup]="profileForm" (ngSubmit)="saveProfile()"><input formControlName="name" placeholder="Household name"><input formControlName="notes" placeholder="Notes"><label><input type="checkbox" formControlName="isActive"> Active</label><button [disabled]="profileForm.invalid||!canEdit()||saving()">Save household</button></form></section>
 <section class="card"><h2>Add / update verified member</h2><p class="muted">Customer must already exist. Anonymous visitors must use the explicit customer conversion flow first.</p><form [formGroup]="memberForm" (ngSubmit)="saveMember()"><input type="number" formControlName="customerId" placeholder="Customer ID"><input formControlName="relationshipType" placeholder="Relationship (e.g. Parent, Spouse)"><select formControlName="relationshipSource"><option value="1">Customer provided</option><option value="2">Staff verified</option><option value="3">Admin verified</option><option value="4">Imported verified</option></select><button [disabled]="memberForm.invalid||!canManageMembers()||saving()">Save member</button></form></section></div>
 <section class="card" style="margin-top:18px"><h2>Members</h2><table><thead><tr><th>Customer</th><th>Relationship</th><th>Source</th><th>Status</th><th></th></tr></thead><tbody>@for(m of h.members;track m.customerId){<tr><td>{{m.customerCode}} · {{m.firstName}} {{m.lastName||''}}</td><td>{{m.relationshipType}}</td><td>{{sourceLabel(m.relationshipSource)}}</td><td>{{m.isActive?'Active':'Removed'}}</td><td class="actions"><button type="button" [disabled]="!canManageMembers()" (click)="editMember(m.customerId,m.relationshipType,m.relationshipSource,m.isActive)">Edit</button>@if(m.isActive){<button type="button" [disabled]="!canManageMembers()||saving()" (click)="removeMember(m.customerId)">Remove</button>}</td></tr>}@empty{<tr><td colspan="5">No verified members yet.</td></tr>}</tbody></table></section>}</main></app-admin-shell>`
})
export class HouseholdDetailPage implements OnInit{
 private readonly api=inject(HouseholdApiService);private readonly route=inject(ActivatedRoute);private readonly session=inject(AuthSessionService);private readonly fb=inject(FormBuilder);private readonly id=Number(this.route.snapshot.paramMap.get('id'));
 protected readonly household=signal<HouseholdDetail|null>(null);protected readonly saving=signal(false);protected readonly error=signal('');protected readonly message=signal('');
 protected readonly canEdit=computed(()=>this.session.hasPermission(PERMISSIONS.householdsEdit));protected readonly canManageMembers=computed(()=>this.session.hasPermission(PERMISSIONS.householdsManageMembers));
 protected readonly profileForm=this.fb.nonNullable.group({name:['',Validators.required],notes:'',isActive:true});
 protected readonly memberForm=this.fb.nonNullable.group({customerId:['',Validators.required],relationshipType:['',Validators.required],relationshipSource:'1',isActive:true});
 ngOnInit(){this.load();}
 protected saveProfile(){if(this.profileForm.invalid||!this.canEdit())return;this.saving.set(true);this.clear();const v=this.profileForm.getRawValue();this.api.update(this.id,{name:v.name.trim(),notes:v.notes.trim()||null,isActive:v.isActive}).subscribe({next:h=>{this.saving.set(false);this.household.set(h);this.message.set('Household saved.');},error:e=>this.fail(e)});}
 protected saveMember(){if(this.memberForm.invalid||!this.canManageMembers())return;this.saving.set(true);this.clear();const v=this.memberForm.getRawValue();const customerId=Number(v.customerId);const source=Number(v.relationshipSource) as HouseholdRelationshipSource;const existing=this.household()?.members.find(x=>x.customerId===customerId);const request=existing?this.api.updateMember(this.id,customerId,{relationshipType:v.relationshipType.trim(),relationshipSource:source,isActive:v.isActive}):this.api.addMember(this.id,{customerId,relationshipType:v.relationshipType.trim(),relationshipSource:source});request.subscribe({next:h=>{this.saving.set(false);this.household.set(h);this.message.set('Verified household member saved.');this.memberForm.reset({customerId:'',relationshipType:'',relationshipSource:'1',isActive:true});},error:e=>this.fail(e)});}
 protected removeMember(customerId:number){if(!this.canManageMembers())return;this.saving.set(true);this.clear();this.api.removeMember(this.id,customerId).subscribe({next:()=>{this.saving.set(false);this.message.set('Household member removed.');this.load(false);},error:e=>this.fail(e)});}
 protected editMember(customerId:number,relationshipType:string,relationshipSource:HouseholdRelationshipSource,isActive:boolean){this.memberForm.setValue({customerId:String(customerId),relationshipType,relationshipSource:String(relationshipSource),isActive});}
 protected sourceLabel(v:HouseholdRelationshipSource){return ({1:'Customer provided',2:'Staff verified',3:'Admin verified',4:'Imported verified'} as Record<number,string>)[v]??'Verified';}
 private load(clear=true){if(clear)this.clear();this.api.get(this.id).subscribe({next:h=>{this.household.set(h);this.profileForm.setValue({name:h.name,notes:h.notes??'',isActive:h.isActive});},error:e=>this.fail(e)});}
 private clear(){this.error.set('');this.message.set('');}private fail(e:unknown){this.saving.set(false);this.error.set(e instanceof HttpErrorResponse?(e.error?.message??e.message):'Request failed.');}
}