import { provideHttpClient } from '@angular/common/http';
import { HttpTestingController, provideHttpClientTesting } from '@angular/common/http/testing';
import { TestBed } from '@angular/core/testing';
import { firstValueFrom } from 'rxjs';
import { IntegrationsApiService, SaveIntegrationRequest } from './integrations-api.service';

describe('IntegrationsApiService',()=>{
  beforeEach(()=>TestBed.configureTestingModule({providers:[provideHttpClient(),provideHttpClientTesting()]}));afterEach(()=>TestBed.inject(HttpTestingController).verify());
  it('creates tenant-scoped configuration without browser TenantId',async()=>{const api=TestBed.inject(IntegrationsApiService);const http=TestBed.inject(HttpTestingController);const request:SaveIntegrationRequest={provider:'Demo POS',integrationType:3,enabled:true,endpointBaseUrl:'https://pos.example.test/hooks',credentialReference:'pos-prod',webhookSigningSecretReference:'pos-signing-v2',timeoutSeconds:10,retryMaxAttempts:5,retryBaseDelaySeconds:5};const result=firstValueFrom(api.create(request));const req=http.expectOne('/api/tenant/integrations');expect(req.request.method).toBe('POST');expect(JSON.stringify(req.request.body)).not.toMatch(/tenantId/i);req.flush(view());await expect(result).resolves.toMatchObject({provider:'Demo POS',credentialReferenceHint:'••••prod'});});
  it('rotates opaque references and never sends secret values from a response',async()=>{const api=TestBed.inject(IntegrationsApiService);const http=TestBed.inject(HttpTestingController);const result=firstValueFrom(api.rotate(7,{credentialReference:'pos-v3',webhookSigningSecretReference:'sign-v3',signingGraceMinutes:10}));const req=http.expectOne('/api/tenant/integrations/7/rotate-references');expect(req.request.method).toBe('POST');expect(req.request.body).toEqual({credentialReference:'pos-v3',webhookSigningSecretReference:'sign-v3',signingGraceMinutes:10});req.flush(view());await expect(result).resolves.toMatchObject({hasCredentialReference:true,hasWebhookSigningSecret:true});});
  it('loads delivery history and retries by authoritative outbox id',async()=>{const api=TestBed.inject(IntegrationsApiService);const http=TestBed.inject(HttpTestingController);const history=firstValueFrom(api.history(7,50));http.expectOne('/api/tenant/integrations/deliveries?integrationId=7&take=50').flush([]);await expect(history).resolves.toEqual([]);const retry=firstValueFrom(api.retry(91));const req=http.expectOne('/api/tenant/integrations/deliveries/91/retry');expect(req.request.body).toEqual({});req.flush({id:91});await expect(retry).resolves.toMatchObject({id:91});});
  const view=()=>({id:7,provider:'Demo POS',integrationType:3,enabled:true,endpointBaseUrl:'https://pos.example.test/hooks',hasCredentialReference:true,credentialReferenceHint:'••••prod',hasWebhookSigningSecret:true,webhookSigningSecretHint:'••••ng-v2',timeoutSeconds:10,retryMaxAttempts:5,retryBaseDelaySeconds:5,createdUtc:'2026-08-24T18:00:00Z',updatedUtc:'2026-08-24T18:00:00Z',connectionStatus:'Configured',webhookStatus:'Signing configured'});
});
