import { ChangeDetectionStrategy, Component, OnInit, computed, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { AuthSessionService } from '../../core/auth/auth-session.service';
import { PERMISSIONS } from '../../core/auth/permission-catalog';
import { AdminShell } from '../../shared/admin-shell/admin-shell';
import { IntegrationConfigurationView, IntegrationDeliveryLogView, IntegrationType, IntegrationsApiService, SaveIntegrationRequest } from './integrations-api.service';

@Component({selector:'app-integration-settings-page',imports:[AdminShell,FormsModule],changeDetection:ChangeDetectionStrategy.OnPush,template:`
<app-admin-shell pageTitle="Integration Settings" eyebrow="Phase 12 · Secure integrations">
  <section class="summary"><div><b>{{settings().length}}</b><span>Configured</span></div><div><b>{{enabledCount()}}</b><span>Enabled</span></div><div><b>{{failedCount()}}</b><span>Failed/dead-letter logs</span></div><button type="button" (click)="load()">Refresh</button></section>
  @if(error()){<p class="error" role="alert">{{error()}}</p>}
  <section class="layout">
    <div class="panel"><h2>Connections</h2>@for(item of settings();track item.id){<button type="button" class="connection" [class.selected]="selected()?.id===item.id" (click)="select(item)"><b>{{item.provider}}</b><span>{{typeName(item.integrationType)}} · {{item.enabled?'Enabled':'Disabled'}}</span><small>Connection: {{item.connectionStatus}} · Webhook: {{item.webhookStatus}}</small></button>}@if(settings().length===0){<p>No integrations configured.</p>}</div>
    <form class="panel form" (ngSubmit)="save()"><h2>{{selected()?'Edit integration':'New integration'}}</h2><label>Provider<input name="provider" [(ngModel)]="form.provider" required maxlength="100"></label><label>Type<select name="integrationType" [(ngModel)]="form.integrationType"><option [ngValue]="1">Inbound webhook</option><option [ngValue]="2">Outbound webhook</option><option [ngValue]="3">Bidirectional</option><option [ngValue]="4">API</option></select></label><label>HTTPS endpoint<input name="endpoint" [(ngModel)]="form.endpointBaseUrl" required type="url"></label><div class="row"><label>Timeout<input name="timeout" [(ngModel)]="form.timeoutSeconds" type="number" min="1" max="120"></label><label>Max attempts<input name="attempts" [(ngModel)]="form.retryMaxAttempts" type="number" min="1" max="10"></label><label>Base delay<input name="delay" [(ngModel)]="form.retryBaseDelaySeconds" type="number" min="1" max="300"></label></div><label class="check"><input name="enabled" [(ngModel)]="form.enabled" type="checkbox"> Enabled</label>@if(!selected()){<label>Credential reference<input name="credential" [(ngModel)]="form.credentialReference" type="password" autocomplete="new-password"></label><label>Signing-secret reference<input name="signing" [(ngModel)]="form.webhookSigningSecretReference" type="password" autocomplete="new-password"></label>}@if(canManage()){<button type="submit">Save configuration</button>}<button type="button" class="secondary" (click)="newConfiguration()">New</button></form>
  </section>
  @if(selected();as item){<section class="panel rotation"><h2>Credential rotation</h2><p>Stored references: credential {{item.credentialReferenceHint??'not configured'}}, signing {{item.webhookSigningSecretHint??'not configured'}}. Full values are never returned.</p><div class="row"><label>New credential reference<input [(ngModel)]="rotationCredential" type="password" autocomplete="new-password"></label><label>New signing reference<input [(ngModel)]="rotationSigning" type="password" autocomplete="new-password"></label><label>Grace minutes<input [(ngModel)]="rotationGrace" type="number" min="0" max="1440"></label></div>@if(canManage()){<button type="button" (click)="rotate(item.id)">Rotate references</button>}@if(canWebhookManage()){<button type="button" class="secondary" (click)="test(item.id)">Queue test delivery</button>}</section>}
  <section class="panel"><h2>Delivery history</h2><div class="table"><b>Provider</b><b>Direction</b><b>Status</b><b>HTTP</b><b>Duration</b><b>Correlation</b><span></span>@for(log of history();track log.id){<span>{{log.provider}}</span><span>{{log.direction===1?'Inbound':'Outbound'}}</span><span>{{deliveryStatus(log.status)}}</span><span>{{log.httpStatusCode??'—'}}</span><span>{{log.durationMilliseconds}} ms</span><span>{{log.correlationId}}</span><span>@if(canWebhookManage()&&log.outboxMessageId&&(log.status===3||log.status===4||log.status===5)){<button type="button" (click)="retry(log.outboxMessageId)">Retry</button>}</span>}</div></section>
</app-admin-shell>`,styles:[`:host{display:block}.summary{display:grid;grid-template-columns:repeat(3,minmax(0,1fr)) auto;gap:.75rem;margin-bottom:1rem}.summary div,.panel{background:var(--color-surface);border:1px solid var(--color-border);border-radius:var(--radius-sm)}.summary div{display:grid;padding:1rem}.summary span,small{color:var(--color-muted);font-size:.78rem}.layout{display:grid;grid-template-columns:minmax(18rem,.8fr) minmax(22rem,1.2fr);gap:1rem}.panel{padding:1rem;margin-bottom:1rem}.panel h2{margin-top:0}.connection{background:transparent;border:0;border-bottom:1px solid var(--color-border);color:var(--color-text);display:grid;gap:.25rem;padding:.8rem;text-align:left;width:100%}.connection.selected,.connection:hover{background:var(--color-nav-active)}.form,.form label,.rotation label{display:grid;gap:.35rem}.form{gap:.75rem}.row{display:grid;grid-template-columns:repeat(3,1fr);gap:.75rem}.check{display:flex!important}.panel input,.panel select{background:var(--color-background);border:1px solid var(--color-border);border-radius:var(--radius-sm);color:var(--color-text);padding:.65rem}.panel button,.summary button{background:var(--color-accent);border:0;border-radius:var(--radius-sm);color:var(--color-on-accent);font-weight:700;padding:.7rem 1rem}.secondary{background:var(--color-nav-active)!important;color:var(--color-text)!important;margin-left:.5rem}.table{display:grid;grid-template-columns:1fr .7fr .8fr .5fr .7fr 1.3fr .5fr;gap:.5rem;overflow:auto}.table>*{border-bottom:1px solid var(--color-border);padding:.5rem}.error{color:var(--color-danger)}@media(max-width:850px){.summary,.layout,.row{grid-template-columns:1fr}.table{grid-template-columns:repeat(7,minmax(7rem,1fr))}}`],})
export class IntegrationSettingsPage implements OnInit{
  private readonly api=inject(IntegrationsApiService);private readonly session=inject(AuthSessionService);protected readonly settings=signal<IntegrationConfigurationView[]>([]);protected readonly history=signal<IntegrationDeliveryLogView[]>([]);protected readonly selected=signal<IntegrationConfigurationView|null>(null);protected readonly error=signal('');protected readonly enabledCount=computed(()=>this.settings().filter(x=>x.enabled).length);protected readonly failedCount=computed(()=>this.history().filter(x=>x.status>=3).length);protected readonly canManage=computed(()=>this.session.hasPermission(PERMISSIONS.integrationsManage));protected readonly canWebhookManage=computed(()=>this.session.hasPermission(PERMISSIONS.webhooksManage));protected rotationCredential='';protected rotationSigning='';protected rotationGrace=10;protected form:SaveIntegrationRequest=this.blank();
  ngOnInit():void{this.load();}
  protected load():void{this.error.set('');this.api.list().subscribe({next:items=>{this.settings.set(items);const selected=this.selected();if(selected)this.selected.set(items.find(x=>x.id===selected.id)??null);},error:()=>this.error.set('Unable to load integration settings.')});this.api.history(undefined,100).subscribe({next:items=>this.history.set(items),error:()=>this.error.set('Unable to load delivery history.')});}
  protected select(item:IntegrationConfigurationView):void{this.selected.set(item);this.form={provider:item.provider,integrationType:item.integrationType,enabled:item.enabled,endpointBaseUrl:item.endpointBaseUrl,timeoutSeconds:item.timeoutSeconds,retryMaxAttempts:item.retryMaxAttempts,retryBaseDelaySeconds:item.retryBaseDelaySeconds};}
  protected newConfiguration():void{this.selected.set(null);this.form=this.blank();}
  protected save():void{const selected=this.selected();const request=selected?{...this.form,credentialReference:null,webhookSigningSecretReference:null}:this.form;const result=selected?this.api.update(selected.id,request):this.api.create(request);result.subscribe({next:item=>{this.upsert(item);this.form.credentialReference='';this.form.webhookSigningSecretReference='';},error:()=>this.error.set('Integration configuration was rejected.')});}
  protected rotate(id:number):void{this.api.rotate(id,{credentialReference:this.rotationCredential||null,webhookSigningSecretReference:this.rotationSigning||null,signingGraceMinutes:this.rotationGrace}).subscribe({next:item=>{this.upsert(item);this.rotationCredential='';this.rotationSigning='';},error:()=>this.error.set('Credential rotation was rejected.')});}
  protected test(id:number):void{this.api.testDelivery(id).subscribe({next:()=>this.load(),error:()=>this.error.set('Test delivery could not be queued.')});}
  protected retry(outboxId:number):void{this.api.retry(outboxId).subscribe({next:()=>this.load(),error:()=>this.error.set('Manual retry was rejected.')});}
  protected typeName(value:IntegrationType):string{return({1:'Inbound webhook',2:'Outbound webhook',3:'Bidirectional',4:'API'} as const)[value];}protected deliveryStatus(value:number):string{return({1:'Accepted',2:'Delivered',3:'Failed',4:'Retrying',5:'Dead letter'} as Record<number,string>)[value]??'Unknown';}
  private upsert(item:IntegrationConfigurationView):void{this.settings.update(items=>[item,...items.filter(x=>x.id!==item.id)].sort((a,b)=>a.provider.localeCompare(b.provider)));this.select(item);}
  private blank():SaveIntegrationRequest{return{provider:'',integrationType:3,enabled:true,endpointBaseUrl:'https://',credentialReference:'',webhookSigningSecretReference:'',timeoutSeconds:10,retryMaxAttempts:5,retryBaseDelaySeconds:5};}
}
