import { CommonModule } from '@angular/common';
import { HttpErrorResponse } from '@angular/common/http';
import { ChangeDetectionStrategy, Component, OnInit, computed, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { AuthSessionService } from '../../core/auth/auth-session.service';
import { PERMISSIONS } from '../../core/auth/permission-catalog';
import { AdminShell } from '../../shared/admin-shell/admin-shell';
import { RetailApiService, RetailInvoiceDetail } from './retail-api.service';

@Component({selector:'app-invoice-detail-page',standalone:true,imports:[CommonModule,ReactiveFormsModule,AdminShell],changeDetection:ChangeDetectionStrategy.OnPush,
styles:[`:host{display:block}.wrap{padding:24px}.summary{display:grid;grid-template-columns:repeat(4,minmax(140px,1fr));gap:12px}.card{border:1px solid #ddd;border-radius:12px;padding:16px;margin-top:16px;background:var(--mat-sys-surface,#fff)}.actions{display:flex;gap:8px;flex-wrap:wrap}table{width:100%;border-collapse:collapse}th,td{padding:9px;border-bottom:1px solid #eee;text-align:left}form{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}input,select,button{min-height:40px;padding:8px;border:1px solid #ccc;border-radius:8px}.error{color:#b3261e}.ok{color:#147d32}.muted{opacity:.65}@media(max-width:800px){.summary{grid-template-columns:1fr 1fr}}`],
template:`<app-admin-shell><main class="wrap">@if(error()){<p class="error">{{error()}}</p>}@if(message()){<p class="ok">{{message()}}</p>}@if(invoice();as i){<div class="actions"><div><h1>{{i.invoiceNumber}}</h1><p class="muted">Store {{i.storeId}} · {{status(i.status)}}</p></div>@if(canFinalize()&&i.status===1){<button (click)="finalize()">Finalize</button>}@if(canCancel()&&i.status!==5&&i.paidAmount===0){<button (click)="cancel()">Cancel</button>}</div><section class="summary"><div class="card"><b>Subtotal</b><div>₹{{i.subtotal}}</div></div><div class="card"><b>Total</b><div>₹{{i.grandTotal}}</div></div><div class="card"><b>Paid</b><div>₹{{i.paidAmount}}</div></div><div class="card"><b>Balance</b><div>₹{{i.balanceAmount}}</div></div></section><section class="card"><h2>Items</h2><table><thead><tr><th>Product</th><th>Qty</th><th>Unit</th><th>Discount</th><th>Tax</th><th>Total</th></tr></thead><tbody>@for(x of i.items;track x.id){<tr><td>{{x.productCode}} — {{x.productName}}</td><td>{{x.quantity}}</td><td>₹{{x.unitPrice}}</td><td>₹{{x.discountAmount}}</td><td>₹{{x.taxAmount}}</td><td>₹{{x.lineTotal}}</td></tr>}</tbody></table></section>
@if(canPay()&&i.status!==1&&i.status!==5&&i.balanceAmount>0){<section class="card"><h2>Add payment</h2><form [formGroup]="paymentForm" (ngSubmit)="pay()"><select formControlName="paymentMethod"><option value="1">Cash</option><option value="2">UPI</option><option value="3">Card</option><option value="4">Bank transfer</option><option value="5">Other</option></select><input type="number" step="0.01" formControlName="amount" placeholder="Amount"><input formControlName="paymentReference" placeholder="Reference optional"><button [disabled]="paymentForm.invalid">Record payment</button></form></section>}
<section class="card"><h2>Payments</h2><table><tbody>@for(p of i.payments;track p.id){<tr><td>{{p.paymentReference}}</td><td>{{p.paymentUtc|date:'medium'}}</td><td>₹{{p.amount}}</td><td>{{p.paymentMethod}}</td></tr>}@empty{<tr><td>No payments.</td></tr>}</tbody></table></section>
@if(canEdit()){<section class="card"><h2>Explicit participant</h2><form [formGroup]="participantForm" (ngSubmit)="participant()"><input type="number" formControlName="customerId" placeholder="Customer ID"><select formControlName="participationType"><option value="1">Payer</option><option value="2">Shopper</option><option value="3">Beneficiary</option><option value="4">Other</option></select><label><input type="checkbox" formControlName="isPayer"> Is payer</label><button>Save</button></form></section>}
@if(canAttribute()){<section class="card"><h2>Spend attribution</h2><p>Attributed ₹{{i.attributedTotal}} · Unattributed ₹{{i.unattributedTotal}}</p><form [formGroup]="attributionForm" (ngSubmit)="attribute()"><input type="number" formControlName="invoiceItemId" placeholder="Invoice item ID"><input type="number" formControlName="customerId" placeholder="Customer ID"><input type="number" step="0.01" formControlName="amountAttributed" placeholder="Amount"><input type="number" step="0.0001" formControlName="quantityAttributed" placeholder="Qty optional"><button>Save attribution</button></form></section>}
<section class="card"><h2>Participants</h2>@for(p of i.participants;track p.customerId){<p>{{p.customerCode}} — {{p.customerName}} · {{p.isPayer?'Payer':'Participant'}}</p>}@empty{<p>No explicit participants.</p>}<h2>Attributions</h2>@for(a of i.attributions;track a.id){<p>Item {{a.invoiceItemId}} → {{a.customerCode}} {{a.customerName}}: ₹{{a.amountAttributed}}</p>}@empty{<p>No explicit attribution.</p>}</section>}</main></app-admin-shell>`})
export class InvoiceDetailPage implements OnInit{
 private readonly api=inject(RetailApiService);private readonly route=inject(ActivatedRoute);private readonly session=inject(AuthSessionService);private readonly fb=inject(FormBuilder);private id=0;protected readonly invoice=signal<RetailInvoiceDetail|null>(null);protected readonly error=signal('');protected readonly message=signal('');
 protected readonly canFinalize=computed(()=>this.session.hasPermission(PERMISSIONS.retailInvoicesFinalize));protected readonly canCancel=computed(()=>this.session.hasPermission(PERMISSIONS.retailInvoicesCancel));protected readonly canPay=computed(()=>this.session.hasPermission(PERMISSIONS.retailPaymentsCreate));protected readonly canEdit=computed(()=>this.session.hasPermission(PERMISSIONS.retailInvoicesEdit));protected readonly canAttribute=computed(()=>this.session.hasPermission(PERMISSIONS.retailSpendAttributionManage));
 protected readonly paymentForm=this.fb.nonNullable.group({paymentMethod:['1',Validators.required],amount:['',Validators.required],paymentReference:''});protected readonly participantForm=this.fb.nonNullable.group({customerId:['',Validators.required],participationType:['2',Validators.required],isPayer:false});protected readonly attributionForm=this.fb.nonNullable.group({invoiceItemId:['',Validators.required],customerId:['',Validators.required],amountAttributed:['',Validators.required],quantityAttributed:''});
 ngOnInit(){this.id=Number(this.route.snapshot.paramMap.get('id'));this.load();}protected finalize(){this.run(this.api.finalizeInvoice(this.id),'Invoice finalized.');}protected cancel(){const reason=window.prompt('Cancellation reason');if(reason?.trim())this.run(this.api.cancelInvoice(this.id,reason.trim()),'Invoice cancelled.');}
 protected pay(){if(this.paymentForm.invalid)return;const v=this.paymentForm.getRawValue();this.run(this.api.addPayment(this.id,{paymentReference:v.paymentReference.trim()||null,paymentMethod:Number(v.paymentMethod),amount:Number(v.amount),paymentUtc:null,externalTransactionId:null,notes:null}),'Payment recorded.');}
 protected participant(){if(this.participantForm.invalid)return;const v=this.participantForm.getRawValue();this.run(this.api.saveParticipant(this.id,{customerId:Number(v.customerId),participationType:Number(v.participationType),isPayer:v.isPayer}),'Participant saved.');}
 protected attribute(){if(this.attributionForm.invalid)return;const v=this.attributionForm.getRawValue();const q=Number(v.quantityAttributed);this.run(this.api.saveAttribution(this.id,{invoiceItemId:Number(v.invoiceItemId),customerId:Number(v.customerId),attributionType:q>0?2:1,quantityAttributed:q>0?q:null,amountAttributed:Number(v.amountAttributed),source:1}),'Attribution saved.');}
 protected status(v:number){return ['','Draft','Finalized','Partially paid','Paid','Cancelled'][v]||String(v);}private load(){this.error.set('');this.api.getInvoice(this.id).subscribe({next:x=>this.invoice.set(x),error:e=>this.fail(e)});}private run(obs:{subscribe:(x:{next:(v:RetailInvoiceDetail)=>void;error:(e:unknown)=>void})=>unknown},msg:string){this.error.set('');obs.subscribe({next:v=>{this.invoice.set(v);this.message.set(msg);},error:e=>this.fail(e)});}private fail(e:unknown){this.error.set(e instanceof HttpErrorResponse?(e.error?.message??e.message):'Request failed.');}
}
