import { CommonModule } from '@angular/common';
import { HttpErrorResponse } from '@angular/common/http';
import { ChangeDetectionStrategy, Component, OnInit, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { AdminShell } from '../../shared/admin-shell/admin-shell';
import { RetailApiService, RetailInvoiceListItem } from './retail-api.service';

@Component({selector:'app-invoice-list-page',standalone:true,imports:[CommonModule,ReactiveFormsModule,RouterLink,AdminShell],changeDetection:ChangeDetectionStrategy.OnPush,
styles:[`:host{display:block}.wrap{padding:24px}.toolbar{display:flex;justify-content:space-between;gap:12px;align-items:end;flex-wrap:wrap}.filters{display:flex;gap:8px;flex-wrap:wrap}.card{border:1px solid #ddd;border-radius:12px;padding:16px;margin-top:18px;background:var(--mat-sys-surface,#fff)}table{width:100%;border-collapse:collapse}th,td{padding:10px;border-bottom:1px solid #eee;text-align:left}input,select,button,a.new{min-height:40px;padding:8px;border:1px solid #ccc;border-radius:8px}.muted{opacity:.65}.error{color:#b3261e}`],
template:`<app-admin-shell><main class="wrap"><div class="toolbar"><div><h1>Retail invoices</h1><p class="muted">Factual customer purchase and payment records</p></div><div><a class="new" routerLink="/customer-admin/retail/invoices/new">New invoice</a></div><form class="filters" [formGroup]="form" (ngSubmit)="load()"><input formControlName="search" placeholder="Invoice/customer"><input type="number" formControlName="storeId" placeholder="Store ID"><input type="number" formControlName="customerId" placeholder="Customer ID"><select formControlName="status"><option value="">All status</option><option value="1">Draft</option><option value="2">Finalized</option><option value="3">Partially paid</option><option value="4">Paid</option><option value="5">Cancelled</option></select><button>Search</button></form></div>@if(error()){<p class="error">{{error()}}</p>}<section class="card"><table><thead><tr><th>Invoice</th><th>Customer</th><th>Store</th><th>Total</th><th>Paid</th><th>Balance</th><th>Status</th></tr></thead><tbody>@for(x of rows();track x.id){<tr><td><a [routerLink]="['/customer-admin/retail/invoices',x.id]">{{x.invoiceNumber}}</a><div class="muted">{{x.invoiceUtc|date:'medium'}}</div></td><td>{{x.customerCode||'-'}} {{x.customerName||''}}</td><td>{{x.storeId}}</td><td>₹{{x.grandTotal}}</td><td>₹{{x.paidAmount}}</td><td>₹{{x.balanceAmount}}</td><td>{{status(x.status)}}</td></tr>}@empty{<tr><td colspan="7">No invoices found.</td></tr>}</tbody></table><p class="muted">{{totalCount()}} invoices</p></section></main></app-admin-shell>`})
export class InvoiceListPage implements OnInit{
 private readonly api=inject(RetailApiService);private readonly fb=inject(FormBuilder);protected readonly rows=signal<RetailInvoiceListItem[]>([]);protected readonly totalCount=signal(0);protected readonly error=signal('');protected readonly form=this.fb.nonNullable.group({search:'',storeId:'',customerId:'',status:''});ngOnInit(){this.load();}
 protected load(){this.error.set('');const v=this.form.getRawValue();const filters:Record<string,string|number|boolean>={};for(const [k,raw] of [['storeId',v.storeId],['customerId',v.customerId],['status',v.status]] as const){const n=Number(raw);if(Number.isInteger(n)&&n>0)filters[k]=n;}this.api.searchInvoices({pageNumber:1,pageSize:50,search:v.search.trim()||undefined,filters}).subscribe({next:r=>{this.rows.set(r.data);this.totalCount.set(r.totalCount);},error:e=>this.fail(e)});}
 protected status(v:number){return ['','Draft','Finalized','Partially paid','Paid','Cancelled'][v]||String(v);}private fail(e:unknown){this.error.set(e instanceof HttpErrorResponse?(e.error?.message??e.message):'Request failed.');}
}
