import { CommonModule } from '@angular/common';
import { HttpErrorResponse } from '@angular/common/http';
import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { FormArray, FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { AdminShell } from '../../shared/admin-shell/admin-shell';
import { RetailApiService } from './retail-api.service';

@Component({selector:'app-invoice-editor-page',standalone:true,imports:[CommonModule,ReactiveFormsModule,AdminShell],changeDetection:ChangeDetectionStrategy.OnPush,
styles:[`:host{display:block}.wrap{padding:24px;max-width:980px;margin:auto}.card{border:1px solid #ddd;border-radius:12px;padding:18px;background:var(--mat-sys-surface,#fff)}form{display:grid;gap:12px}.row{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.item{display:grid;grid-template-columns:2fr 1fr 1fr auto;gap:8px;align-items:end;padding:10px;border:1px solid #eee;border-radius:10px}input,textarea,button{min-height:40px;padding:8px;border:1px solid #ccc;border-radius:8px}.error{color:#b3261e}.muted{opacity:.65}@media(max-width:700px){.row,.item{grid-template-columns:1fr}}`],
template:`<app-admin-shell><main class="wrap"><h1>Create retail invoice</h1><p class="muted">Totals are recalculated by the server from current catalog snapshots.</p>@if(error()){<p class="error">{{error()}}</p>}<section class="card"><form [formGroup]="form" (ngSubmit)="save()"><div class="row"><input type="number" formControlName="storeId" placeholder="Store ID"><input type="number" formControlName="customerId" placeholder="Customer ID optional"><input type="number" formControlName="householdId" placeholder="Household ID optional"></div><div class="row"><input type="number" formControlName="customerVisitId" placeholder="Visit ID optional"><input type="number" formControlName="visitPartyId" placeholder="Visit Party ID optional"><input formControlName="notes" placeholder="Notes"></div><h2>Items</h2><div formArrayName="items">@for(ctrl of items.controls;track $index;let i=$index){<div class="item" [formGroupName]="i"><input type="number" formControlName="productId" placeholder="Product ID"><input type="number" step="0.0001" formControlName="quantity" placeholder="Qty"><input type="number" step="0.01" formControlName="discountAmount" placeholder="Discount"><button type="button" (click)="remove(i)" [disabled]="items.length===1">Remove</button></div>}</div><button type="button" (click)="add()">Add item</button><button [disabled]="form.invalid||saving()">Create invoice</button></form></section></main></app-admin-shell>`})
export class InvoiceEditorPage{
 private readonly fb=inject(FormBuilder);private readonly api=inject(RetailApiService);private readonly router=inject(Router);protected readonly saving=signal(false);protected readonly error=signal('');
 protected readonly form=this.fb.group({storeId:['',Validators.required],customerId:[''],householdId:[''],customerVisitId:[''],visitPartyId:[''],notes:[''],items:this.fb.array([this.itemGroup()])});
 protected get items(){return this.form.controls.items as FormArray;}protected add(){this.items.push(this.itemGroup());}protected remove(i:number){if(this.items.length>1)this.items.removeAt(i);}
 protected save(){if(this.form.invalid)return;this.saving.set(true);this.error.set('');const v=this.form.getRawValue();this.api.createInvoice({storeId:Number(v.storeId),customerId:this.id(v.customerId),householdId:this.id(v.householdId),customerVisitId:this.id(v.customerVisitId),visitPartyId:this.id(v.visitPartyId),notes:(v.notes??'').trim()||null,items:(v.items??[]).map(x=>({productId:Number(x?.productId),quantity:Number(x?.quantity),discountAmount:Number(x?.discountAmount)||0}))}).subscribe({next:r=>void this.router.navigate(['/customer-admin/retail/invoices',r.id]),error:e=>{this.saving.set(false);this.error.set(e instanceof HttpErrorResponse?(e.error?.message??e.message):'Request failed.');}});}
 private itemGroup(){return this.fb.group({productId:['',Validators.required],quantity:[1,Validators.required],discountAmount:[0]});}private id(v:unknown){const n=Number(v);return Number.isInteger(n)&&n>0?n:null;}
}
