import { CommonModule } from '@angular/common';
import { HttpErrorResponse } from '@angular/common/http';
import { ChangeDetectionStrategy, Component, OnInit, computed, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { AuthSessionService } from '../../core/auth/auth-session.service';
import { PERMISSIONS } from '../../core/auth/permission-catalog';
import { AdminShell } from '../../shared/admin-shell/admin-shell';
import { ProductListItem, RetailApiService } from './retail-api.service';

@Component({selector:'app-product-list-page',standalone:true,imports:[CommonModule,ReactiveFormsModule,AdminShell],changeDetection:ChangeDetectionStrategy.OnPush,
styles:[`:host{display:block}.wrap{padding:24px}.toolbar{display:flex;gap:12px;justify-content:space-between;align-items:end;flex-wrap:wrap}.grid{display:grid;grid-template-columns:minmax(0,1fr) 360px;gap:18px}.card{border:1px solid #ddd;border-radius:12px;padding:16px;background:var(--mat-sys-surface,#fff)}table{width:100%;border-collapse:collapse}th,td{padding:10px;text-align:left;border-bottom:1px solid #eee}form{display:grid;gap:9px}input,button{min-height:40px;padding:8px;border:1px solid #ccc;border-radius:8px}.filters{display:flex;gap:8px;flex-wrap:wrap}.muted{opacity:.65}.error{color:#b3261e}.ok{color:#147d32}@media(max-width:900px){.grid{grid-template-columns:1fr}}`],
template:`<app-admin-shell><main class="wrap"><div class="toolbar"><div><h1>Products</h1><p class="muted">Tenant/store-aware Phase 8 catalog</p></div><form class="filters" [formGroup]="searchForm" (ngSubmit)="search()"><input formControlName="search" placeholder="SKU, barcode, product"><input type="number" formControlName="storeId" placeholder="Store ID"><input type="number" formControlName="categoryId" placeholder="Category ID"><label><input type="checkbox" formControlName="activeOnly"> Active</label><button>Search</button></form></div>@if(error()){<p class="error">{{error()}}</p>}@if(message()){<p class="ok">{{message()}}</p>}<div class="grid"><section class="card"><table><thead><tr><th>SKU</th><th>Product</th><th>Category</th><th>Price</th><th>Status</th></tr></thead><tbody>@for(x of rows();track x.id){<tr><td>{{x.productCode}}</td><td>{{x.name}}<div class="muted">{{x.barcode||'-'}}</div></td><td>{{x.categoryName}}</td><td>₹{{x.salePrice}}</td><td>{{x.isActive?'Active':'Inactive'}}</td></tr>}@empty{<tr><td colspan="5">No products found.</td></tr>}</tbody></table><p class="muted">{{totalCount()}} products</p></section>@if(canCreate()){<aside class="card"><h2>Add product</h2><form [formGroup]="form" (ngSubmit)="create()"><input formControlName="productCode" placeholder="SKU"><input formControlName="barcode" placeholder="Barcode"><input formControlName="name" placeholder="Product name"><input type="number" formControlName="categoryId" placeholder="Category ID"><input formControlName="brand" placeholder="Brand"><input formControlName="unitName" placeholder="Unit"><input type="number" step="0.01" formControlName="salePrice" placeholder="Sale price"><input type="number" step="0.01" formControlName="costPrice" placeholder="Cost price"><input type="number" step="0.01" formControlName="taxPercent" placeholder="Tax %"><input formControlName="storeIds" placeholder="Store IDs comma separated"><button [disabled]="form.invalid||saving()">Create</button></form></aside>}</div></main></app-admin-shell>`})
export class ProductListPage implements OnInit{
 private readonly api=inject(RetailApiService);private readonly session=inject(AuthSessionService);private readonly fb=inject(FormBuilder);protected readonly rows=signal<ProductListItem[]>([]);protected readonly totalCount=signal(0);protected readonly saving=signal(false);protected readonly error=signal('');protected readonly message=signal('');protected readonly canCreate=computed(()=>this.session.hasPermission(PERMISSIONS.productsCreate));
 protected readonly searchForm=this.fb.nonNullable.group({search:'',storeId:'',categoryId:'',activeOnly:true});protected readonly form=this.fb.nonNullable.group({productCode:['',Validators.required],barcode:'',name:['',Validators.required],categoryId:['',Validators.required],brand:'',unitName:['Each',Validators.required],salePrice:['',Validators.required],costPrice:'',taxPercent:'',storeIds:''});
 ngOnInit(){this.load();}protected search(){this.load();}protected create(){if(this.form.invalid)return;this.saving.set(true);this.clear();const v=this.form.getRawValue();this.api.createProduct({productCode:v.productCode,barcode:this.text(v.barcode),name:v.name,description:null,categoryId:Number(v.categoryId),brand:this.text(v.brand),unitName:v.unitName,salePrice:Number(v.salePrice),costPrice:this.num(v.costPrice),taxPercent:this.num(v.taxPercent),storeIds:this.ids(v.storeIds)}).subscribe({next:()=>{this.saving.set(false);this.message.set('Product created.');this.form.reset({productCode:'',barcode:'',name:'',categoryId:'',brand:'',unitName:'Each',salePrice:'',costPrice:'',taxPercent:'',storeIds:''});this.load(false);},error:e=>this.fail(e)});}
 private load(clear=true){if(clear)this.clear();const v=this.searchForm.getRawValue();const filters:Record<string,string|number|boolean>={activeOnly:v.activeOnly};const s=this.num(v.storeId),c=this.num(v.categoryId);if(s)filters['storeId']=s;if(c)filters['categoryId']=c;this.api.searchProducts({pageNumber:1,pageSize:50,search:v.search.trim()||undefined,filters}).subscribe({next:r=>{this.rows.set(r.data);this.totalCount.set(r.totalCount);},error:e=>this.fail(e)});}
 private ids(v:string){return v.split(',').map(x=>Number(x.trim())).filter(x=>Number.isInteger(x)&&x>0);}private num(v:string){const n=Number(v);return Number.isFinite(n)&&n>=0?n:null;}private text(v:string){return v.trim()||null;}private clear(){this.error.set('');this.message.set('');}private fail(e:unknown){this.saving.set(false);this.error.set(e instanceof HttpErrorResponse?(e.error?.message??e.message):'Request failed.');}
}
