import { CommonModule } from '@angular/common';
import { HttpErrorResponse } from '@angular/common/http';
import { ChangeDetectionStrategy, Component, OnInit, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule } from '@angular/forms';
import { AdminShell } from '../../shared/admin-shell/admin-shell';
import { RetailApiService, RetailBreakdownItem, RetailPaymentSummaryItem, RetailSalesSummary } from './retail-api.service';

@Component({selector:'app-retail-reports-page',standalone:true,imports:[CommonModule,ReactiveFormsModule,AdminShell],changeDetection:ChangeDetectionStrategy.OnPush,
styles:[`:host{display:block}.wrap{padding:24px}.filters{display:flex;gap:8px;flex-wrap:wrap}.cards{display:grid;grid-template-columns:repeat(4,minmax(140px,1fr));gap:12px}.card{border:1px solid #ddd;border-radius:12px;padding:16px;margin-top:16px;background:var(--mat-sys-surface,#fff)}table{width:100%;border-collapse:collapse}th,td{padding:9px;border-bottom:1px solid #eee;text-align:left}input,button{min-height:40px;padding:8px;border:1px solid #ccc;border-radius:8px}.error{color:#b3261e}.muted{opacity:.65}@media(max-width:800px){.cards{grid-template-columns:1fr 1fr}}`],
template:`<app-admin-shell><main class="wrap"><h1>Retail reports</h1><p class="muted">Tenant/store-scoped factual sales, product/category and payment summaries.</p><form class="filters" [formGroup]="form" (ngSubmit)="load()"><input type="number" formControlName="storeId" placeholder="Store ID optional"><input type="date" formControlName="from"><input type="date" formControlName="to"><button>Apply</button></form>@if(error()){<p class="error">{{error()}}</p>}@if(summary();as s){<section class="cards"><div class="card"><b>Net sales</b><div>₹{{s.netSales}}</div></div><div class="card"><b>Paid</b><div>₹{{s.paidAmount}}</div></div><div class="card"><b>Outstanding</b><div>₹{{s.outstandingAmount}}</div></div><div class="card"><b>Invoices</b><div>{{s.invoiceCount}}</div></div></section>}<section class="card"><h2>Top products</h2><table><tbody>@for(x of products();track x.id){<tr><td>{{x.code}} — {{x.name}}</td><td>₹{{x.netSales}}</td><td>{{x.invoiceCount}} invoices</td></tr>}@empty{<tr><td>No product sales.</td></tr>}</tbody></table></section><section class="card"><h2>Top categories</h2><table><tbody>@for(x of categories();track x.id){<tr><td>{{x.code}} — {{x.name}}</td><td>₹{{x.netSales}}</td><td>{{x.invoiceCount}} invoices</td></tr>}@empty{<tr><td>No category sales.</td></tr>}</tbody></table></section><section class="card"><h2>Payment methods</h2><table><tbody>@for(x of payments();track x.paymentMethod){<tr><td>{{method(x.paymentMethod)}}</td><td>₹{{x.amount}}</td><td>{{x.paymentCount}}</td></tr>}@empty{<tr><td>No successful payments.</td></tr>}</tbody></table></section></main></app-admin-shell>`})
export class RetailReportsPage implements OnInit{
 private readonly api=inject(RetailApiService);private readonly fb=inject(FormBuilder);protected readonly form=this.fb.nonNullable.group({storeId:'',from:'',to:''});protected readonly summary=signal<RetailSalesSummary|null>(null);protected readonly products=signal<RetailBreakdownItem[]>([]);protected readonly categories=signal<RetailBreakdownItem[]>([]);protected readonly payments=signal<RetailPaymentSummaryItem[]>([]);protected readonly error=signal('');ngOnInit(){this.load();}
 protected load(){this.error.set('');const q=this.query();this.api.salesSummary(q).subscribe({next:x=>this.summary.set(x),error:e=>this.fail(e)});this.api.salesByProduct(q).subscribe({next:x=>this.products.set(x),error:e=>this.fail(e)});this.api.salesByCategory(q).subscribe({next:x=>this.categories.set(x),error:e=>this.fail(e)});this.api.paymentSummary(q).subscribe({next:x=>this.payments.set(x),error:e=>this.fail(e)});}
 protected method(v:number){return ['','Cash','UPI','Card','Bank transfer','Other'][v]||String(v);}private query(){const v=this.form.getRawValue();const p=new URLSearchParams();const store=Number(v.storeId);if(Number.isInteger(store)&&store>0)p.set('storeId',String(store));if(v.from)p.set('fromUtc',new Date(`${v.from}T00:00:00Z`).toISOString());if(v.to)p.set('toUtc',new Date(`${v.to}T00:00:00Z`).toISOString());const s=p.toString();return s?`?${s}`:'';}private fail(e:unknown){this.error.set(e instanceof HttpErrorResponse?(e.error?.message??e.message):'Request failed.');}
}
