import { provideHttpClient } from '@angular/common/http';
import { HttpTestingController, provideHttpClientTesting } from '@angular/common/http/testing';
import { TestBed } from '@angular/core/testing';
import { firstValueFrom } from 'rxjs';
import { VisitApiService } from './visit-api.service';

describe('VisitApiService',()=>{
 beforeEach(()=>TestBed.configureTestingModule({providers:[provideHttpClient(),provideHttpClientTesting()]}));afterEach(()=>TestBed.inject(HttpTestingController).verify());
 it('searches factual visits with store scope but no TenantId',async()=>{const api=TestBed.inject(VisitApiService);const http=TestBed.inject(HttpTestingController);const result=firstValueFrom(api.searchVisits({pageNumber:1,pageSize:25,search:'CUST-1',filters:{storeId:101,customerId:501}}));const req=http.expectOne(x=>x.url==='/api/tenant/visits');expect(req.request.params.get('storeId')).toBe('101');expect(req.request.params.get('customerId')).toBe('501');expect(req.request.params.has('tenantId')).toBe(false);req.flush({data:[],pageNumber:1,pageSize:25,totalCount:0,totalPages:0});await expect(result).resolves.toMatchObject({totalCount:0});});
 it('creates only a manual visit request contract without source or TenantId spoofing',async()=>{const api=TestBed.inject(VisitApiService);const http=TestBed.inject(HttpTestingController);const result=firstValueFrom(api.createVisit({storeId:101,customerId:501,visitPartyId:null,enteredUtc:null}));const req=http.expectOne('/api/tenant/visits');expect(req.request.method).toBe('POST');expect(req.request.body).toEqual({storeId:101,customerId:501,visitPartyId:null,enteredUtc:null});expect(JSON.stringify(req.request.body)).not.toMatch(/tenantId|source/i);req.flush({id:1,visitCode:'VST-1',customerId:501,customerCode:'C-1',customerName:'Priya',storeId:101,visitPartyId:null,enteredUtc:'2026-08-23T00:00:00Z',exitedUtc:null,source:1,status:1,createdUtc:'2026-08-23T00:00:00Z',updatedUtc:'2026-08-23T00:00:00Z'});await expect(result).resolves.toMatchObject({visitCode:'VST-1'});});
 it('uses a distinct Visit Party co-visit endpoint',async()=>{const api=TestBed.inject(VisitApiService);const http=TestBed.inject(HttpTestingController);const result=firstValueFrom(api.searchParties({pageNumber:1,pageSize:25,filters:{storeId:101}}));const req=http.expectOne(x=>x.url==='/api/tenant/visit-parties');expect(req.request.params.get('storeId')).toBe('101');expect(req.request.params.has('tenantId')).toBe(false);req.flush({data:[],pageNumber:1,pageSize:25,totalCount:0,totalPages:0});await expect(result).resolves.toMatchObject({totalCount:0});});
});