import { CommonModule } from '@angular/common';
import { HttpErrorResponse } from '@angular/common/http';
import { ChangeDetectionStrategy, Component, OnInit, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule } from '@angular/forms';
import { AdminShell } from '../../shared/admin-shell/admin-shell';
import { VisitApiService, VisitPartyDetail, VisitPartyListItem } from './visit-api.service';

@Component({selector:'app-visit-party-list-page',standalone:true,imports:[CommonModule,ReactiveFormsModule,AdminShell],changeDetection:ChangeDetectionStrategy.OnPush,
 styles:[`:host{display:block}.wrap{padding:24px}.toolbar{display:flex;gap:12px;justify-content:space-between;align-items:end;flex-wrap:wrap}.filters{display:flex;gap:8px;flex-wrap:wrap}.grid{display:grid;grid-template-columns:minmax(0,1fr) 360px;gap:18px;margin-top:18px}.card{border:1px solid #ddd;border-radius:12px;padding:16px;background:var(--mat-sys-surface,#fff)}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:9px;border-bottom:1px solid #eee}input,button{min-height:40px;padding:8px;border:1px solid #ccc;border-radius:8px}.muted{opacity:.65}.warning{padding:10px;border:1px solid #b26a00;border-radius:8px}.error{color:#b3261e}@media(max-width:900px){.grid{grid-template-columns:1fr}}`],
 template:`<app-admin-shell><main class="wrap"><div class="toolbar"><div><h1>Visit Party / Co-Visit</h1><p class="muted">Observed together ≠ family. Household relationships require separate verification.</p></div><form class="filters" [formGroup]="filterForm" (ngSubmit)="search()"><input formControlName="search" placeholder="Search party code"><input type="number" formControlName="storeId" placeholder="Store ID"><button>Search</button></form></div>@if(error()){<p class="error">{{error()}}</p>}<div class="grid"><section class="card"><table><thead><tr><th>Party</th><th>Store</th><th>Started</th><th>Members</th><th></th></tr></thead><tbody>@for(p of parties();track p.id){<tr><td>{{p.partyCode}}</td><td>{{p.storeId}}</td><td>{{p.startedUtc|date:'short'}}</td><td>{{p.memberCount}}</td><td><button type="button" (click)="open(p.id)">View</button></td></tr>}@empty{<tr><td colspan="5">No visit parties found.</td></tr>}</tbody></table></section><aside class="card"><p class="warning"><strong>Privacy rule:</strong> A Visit Party records co-visit evidence only. Do not label it as a family unless a separately verified Household exists.</p>@if(selected();as d){<h2>{{d.partyCode}}</h2><p>Store {{d.storeId}} · {{d.startedUtc|date:'short'}}</p><h3>Separate identities</h3><ul>@for(m of d.members;track m.id){<li>@if(m.customerId){Customer {{m.customerCode}} (#{{m.customerId}})}@else{Anonymous visitor {{m.visitorCode}} (#{{m.anonymousVisitorId}})}</li>}@empty{<li>No members.</li>}</ul>}@else{<p class="muted">Select a party to review its separately tracked identities.</p>}</aside></div></main></app-admin-shell>`})
export class VisitPartyListPage implements OnInit{
 private readonly api=inject(VisitApiService);private readonly fb=inject(FormBuilder);protected readonly parties=signal<VisitPartyListItem[]>([]);protected readonly selected=signal<VisitPartyDetail|null>(null);protected readonly error=signal('');protected readonly filterForm=this.fb.nonNullable.group({search:'',storeId:''});
 ngOnInit(){this.load();}protected search(){this.load();}protected open(id:number){this.error.set('');this.api.getParty(id).subscribe({next:x=>this.selected.set(x),error:e=>this.fail(e)});}
 private load(){this.error.set('');const v=this.filterForm.getRawValue();const filters:Record<string,string|number>={};const n=Number(v.storeId);if(Number.isInteger(n)&&n>0)filters['storeId']=n;this.api.searchParties({pageNumber:1,pageSize:50,search:v.search.trim()||undefined,filters}).subscribe({next:r=>{this.parties.set(r.data);this.selected.set(null);},error:e=>this.fail(e)});}
 private fail(e:unknown){this.error.set(e instanceof HttpErrorResponse?(e.error?.message??e.message):'Request failed.');}
}