import { CommonModule } from '@angular/common';
import { HttpErrorResponse } from '@angular/common/http';
import { ChangeDetectionStrategy, Component, OnInit, computed, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { AuthSessionService } from '../../core/auth/auth-session.service';
import { PERMISSIONS } from '../../core/auth/permission-catalog';
import { AdminShell } from '../../shared/admin-shell/admin-shell';
import { CustomerVisitListItem, VisitApiService } from './visit-api.service';

@Component({selector:'app-visit-list-page',standalone:true,imports:[CommonModule,ReactiveFormsModule,AdminShell],changeDetection:ChangeDetectionStrategy.OnPush,
 styles:[`:host{display:block}.wrap{padding:24px}.toolbar{display:flex;gap:12px;justify-content:space-between;align-items:end;flex-wrap:wrap}.filters{display:flex;gap:8px;flex-wrap:wrap}.grid{display:grid;grid-template-columns:minmax(0,1fr) 330px;gap:18px;margin-top:18px}.card{border:1px solid #ddd;border-radius:12px;padding:16px;background:var(--mat-sys-surface,#fff)}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:9px;border-bottom:1px solid #eee}input,button{min-height:40px;padding:8px;border:1px solid #ccc;border-radius:8px}form{display:grid;gap:8px}.pager{display:flex;gap:8px;margin-top:12px}.muted{opacity:.65}.error{color:#b3261e}.ok{color:#147d32}@media(max-width:900px){.grid{grid-template-columns:1fr}}`],
 template:`<app-admin-shell><main class="wrap"><div class="toolbar"><div><h1>Customer Visits</h1><p class="muted">Factual visit history only; purchase history remains separate.</p></div><form class="filters" [formGroup]="filterForm" (ngSubmit)="search()"><input formControlName="search" placeholder="Search visit or customer"><input type="number" formControlName="storeId" placeholder="Store ID"><input type="number" formControlName="customerId" placeholder="Customer ID"><button>Search</button></form></div>@if(error()){<p class="error">{{error()}}</p>}@if(message()){<p class="ok">{{message()}}</p>}<div class="grid"><section class="card"><table><thead><tr><th>Visit</th><th>Customer</th><th>Store</th><th>Entered</th><th>Exited</th></tr></thead><tbody>@for(v of visits();track v.id){<tr><td>{{v.visitCode}}</td><td>{{v.customerCode}} · {{v.customerName}}</td><td>{{v.storeId}}</td><td>{{v.enteredUtc|date:'short'}}</td><td>{{v.exitedUtc?(v.exitedUtc|date:'short'):'Inside / open'}}</td></tr>}@empty{<tr><td colspan="5">No visits found.</td></tr>}</tbody></table><div class="pager"><button type="button" [disabled]="pageNumber()<=1" (click)="previous()">Previous</button><span>Page {{pageNumber()}} · {{totalCount()}} records</span><button type="button" [disabled]="pageNumber()*pageSize()>=totalCount()" (click)="next()">Next</button></div></section>
 @if(canEdit()){<aside class="card"><h2>Record manual visit</h2><form [formGroup]="createForm" (ngSubmit)="create()"><input type="number" formControlName="storeId" placeholder="Store ID"><input type="number" formControlName="customerId" placeholder="Customer ID"><input type="number" formControlName="visitPartyId" placeholder="Visit Party ID (optional)"><button [disabled]="createForm.invalid||saving()">Record visit</button></form></aside>}</div></main></app-admin-shell>`})
export class VisitListPage implements OnInit{
 private readonly api=inject(VisitApiService);private readonly session=inject(AuthSessionService);private readonly fb=inject(FormBuilder);
 protected readonly visits=signal<CustomerVisitListItem[]>([]);protected readonly pageNumber=signal(1);protected readonly pageSize=signal(25);protected readonly totalCount=signal(0);protected readonly saving=signal(false);protected readonly error=signal('');protected readonly message=signal('');protected readonly canEdit=computed(()=>this.session.hasPermission(PERMISSIONS.visitsEdit));
 protected readonly filterForm=this.fb.nonNullable.group({search:'',storeId:'',customerId:''});protected readonly createForm=this.fb.nonNullable.group({storeId:['',Validators.required],customerId:['',Validators.required],visitPartyId:''});
 ngOnInit(){this.load();}protected search(){this.pageNumber.set(1);this.load();}protected previous(){this.pageNumber.update(x=>Math.max(1,x-1));this.load();}protected next(){if(this.pageNumber()*this.pageSize()<this.totalCount()){this.pageNumber.update(x=>x+1);this.load();}}
 protected create(){if(this.createForm.invalid)return;const v=this.createForm.getRawValue();this.saving.set(true);this.clear();this.api.createVisit({storeId:Number(v.storeId),customerId:Number(v.customerId),visitPartyId:this.num(v.visitPartyId),enteredUtc:null}).subscribe({next:()=>{this.saving.set(false);this.message.set('Manual customer visit recorded.');this.createForm.reset({storeId:'',customerId:'',visitPartyId:''});this.load(false);},error:e=>this.fail(e)});}
 private load(clear=true){if(clear)this.clear();const v=this.filterForm.getRawValue();const filters:Record<string,string|number>={};const store=this.num(v.storeId);const customer=this.num(v.customerId);if(store)filters['storeId']=store;if(customer)filters['customerId']=customer;this.api.searchVisits({pageNumber:this.pageNumber(),pageSize:this.pageSize(),search:v.search.trim()||undefined,filters}).subscribe({next:r=>{this.visits.set(r.data);this.totalCount.set(r.totalCount);},error:e=>this.fail(e)});}
 private num(v:string){const n=Number(v);return Number.isInteger(n)&&n>0?n:null;}private clear(){this.error.set('');this.message.set('');}private fail(e:unknown){this.saving.set(false);this.error.set(e instanceof HttpErrorResponse?(e.error?.message??e.message):'Request failed.');}
}