import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component, OnInit, inject, signal } from '@angular/core';
import { RouterLink } from '@angular/router';
import { AdminShell } from '../../shared/admin-shell/admin-shell';
import { DashboardSummary, PhaseFiveApiService } from './phase-five-api.service';

/** Phase 5G — API-backed Customer Admin dashboard; no hard-coded business statistics. */
@Component({selector:'app-phase-five-dashboard',standalone:true,imports:[CommonModule,RouterLink,AdminShell],changeDetection:ChangeDetectionStrategy.OnPush,styles:[`:host{display:block}.wrap{padding:24px}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:14px}.card{border:1px solid #e2e2e2;border-radius:12px;padding:18px}.value{font-size:28px;font-weight:700}.nav{display:flex;gap:8px;flex-wrap:wrap;margin:18px 0}.nav a{padding:9px 12px;border:1px solid #ddd;border-radius:8px;text-decoration:none;color:inherit}`],template:`<app-admin-shell><main class="wrap"><h1>Customer Admin</h1><p>Phase 5 operational dashboard</p><nav class="nav"><a routerLink="/customer-admin/stores">Stores</a><a routerLink="/customer-admin/users">Users</a><a routerLink="/customer-admin/staff">Staff</a><a routerLink="/customer-admin/categories">Categories</a><a routerLink="/customer-admin/voice-settings">Voice settings</a></nav>@if(error()){<p>{{error()}}</p>}@if(summary();as s){<section class="cards"><div class="card"><span>Active users</span><div class="value">{{s.activeUsers}}</div></div><div class="card"><span>Active stores</span><div class="value">{{s.activeStores}}</div></div><div class="card"><span>Active staff</span><div class="value">{{s.activeStaff}}</div></div><div class="card"><span>Categories</span><div class="value">{{s.activeCategories}}</div></div><div class="card"><span>Open shifts</span><div class="value">{{s.openShifts}}</div></div><div class="card"><span>Presence sessions</span><div class="value">{{s.activePresenceSessions}}</div></div></section>}</main></app-admin-shell>`})
export class PhaseFiveDashboardPage implements OnInit{private readonly api=inject(PhaseFiveApiService);protected readonly summary=signal<DashboardSummary|null>(null);protected readonly error=signal('');ngOnInit(){this.api.dashboard().subscribe({next:x=>this.summary.set(x),error:e=>this.error.set(e?.error?.message??'Dashboard could not be loaded.')});}}
