import { CommonModule } from '@angular/common';
import { HttpErrorResponse } from '@angular/common/http';
import { ChangeDetectionStrategy, Component, OnInit, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { AdminShell } from '../../shared/admin-shell/admin-shell';
import { Category, PhaseFiveApiService, Staff, Store, TenantUser, VoiceSetting } from './phase-five-api.service';

/** Phase 5 tenant CRUD shell. Forms never expose TenantId; tenant/store scope is enforced by the API. */
@Component({
  selector: 'app-phase-five-management',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, RouterLink, AdminShell],
  changeDetection: ChangeDetectionStrategy.OnPush,
  styles: [`:host{display:block}.wrap{padding:24px}.toolbar{display:flex;gap:12px;align-items:center;justify-content:space-between;margin-bottom:18px}.tabs{display:flex;gap:8px;flex-wrap:wrap}.tabs a{padding:8px 12px;border:1px solid #d6d6d6;border-radius:8px;text-decoration:none;color:inherit}.grid{display:grid;grid-template-columns:minmax(0,1.4fr) minmax(320px,.6fr);gap:20px}.card{border:1px solid #e2e2e2;border-radius:12px;padding:16px;background:var(--mat-sys-surface,#fff)}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:10px;border-bottom:1px solid #eee;font-size:13px}form{display:grid;gap:10px}input,select,button{min-height:40px;padding:8px;border-radius:8px;border:1px solid #ccc}button{cursor:pointer}.actions{display:flex;gap:6px;flex-wrap:wrap}.row{display:grid;grid-template-columns:1fr 1fr;gap:8px}.muted{opacity:.65;font-size:12px}.error{color:#b3261e}.ok{color:#147d32}@media(max-width:900px){.grid{grid-template-columns:1fr}}`],
  template: `<app-admin-shell>
  <main class="wrap">
    <div class="toolbar"><div><h1>{{title()}}</h1><p class="muted">Phase 5 tenant-scoped management</p></div><nav class="tabs"><a routerLink="/customer-admin/dashboard">Dashboard</a><a routerLink="/customer-admin/stores">Stores</a><a routerLink="/customer-admin/users">Users</a><a routerLink="/customer-admin/staff">Staff</a><a routerLink="/customer-admin/store-categories">Categories</a><a routerLink="/customer-admin/voice-commands">Voice</a></nav></div>
    @if(error()){<p class="error">{{error()}}</p>} @if(message()){<p class="ok">{{message()}}</p>}
    <div class="grid"><section class="card">
      @switch(mode()){
        @case('stores'){<table><thead><tr><th>Code</th><th>Store</th><th>City</th><th>Verified</th><th>Status</th><th>Actions</th></tr></thead><tbody>@for(x of stores();track x.id){<tr><td>{{x.storeCode}}</td><td>{{x.storeName}}</td><td>{{x.city}}</td><td>{{x.isLocationVerified?'Yes':'No'}}</td><td>{{x.isActive?'Active':'Inactive'}}</td><td><div class="actions"><button type="button" (click)="editStore(x)">Edit</button>@if(!x.isLocationVerified && x.latitude!==null && x.longitude!==null){<button type="button" (click)="verifyStore(x)">Verify location</button>}<button type="button" (click)="toggleStore(x)">{{x.isActive?'Deactivate':'Activate'}}</button></div></td></tr>}</tbody></table>}
        @case('users'){<table><thead><tr><th>User</th><th>Email</th><th>Roles</th><th>Stores</th><th>Status</th><th></th></tr></thead><tbody>@for(x of users();track x.id){<tr><td>{{x.displayName}}<div class="muted">{{x.userName}}</div></td><td>{{x.email}}</td><td>{{x.roles.join(', ')}}</td><td>{{x.storeIds.join(', ')||'Tenant-wide / none'}}</td><td>{{x.isActive?'Active':'Inactive'}}</td><td><button type="button" (click)="editUser(x)">Edit</button></td></tr>}</tbody></table>}
        @case('staff'){<table><thead><tr><th>Employee</th><th>Name</th><th>Mobile</th><th>Stores</th><th>Status</th><th></th></tr></thead><tbody>@for(x of staff();track x.id){<tr><td>{{x.employeeCode}}</td><td><a [routerLink]="['/customer-admin/staff',x.id]">{{x.firstName}} {{x.lastName}}</a></td><td>{{x.mobile||'-'}}</td><td>{{x.storeIds.join(', ')}}</td><td>{{x.isActive?'Active':'Inactive'}}</td><td><button type="button" (click)="editStaff(x)">Edit</button></td></tr>}</tbody></table>}
        @case('categories'){<table><thead><tr><th>Code</th><th>Name</th><th>Store</th><th>Status</th><th></th></tr></thead><tbody>@for(x of categories();track x.id){<tr><td>{{x.categoryCode}}</td><td>{{x.name}}</td><td>{{x.storeId||'Tenant-wide'}}</td><td>{{x.isActive?'Active':'Inactive'}}</td><td><button type="button" (click)="editCategory(x)">Edit</button></td></tr>}</tbody></table>}
        @case('voice'){<table><thead><tr><th>Store</th><th>Trigger</th><th>Aliases</th><th>Enabled</th></tr></thead><tbody>@if(voice()){<tr><td>{{voice()!.storeId}}</td><td>{{voice()!.triggerKeyword}}</td><td>{{voice()!.aliases.join(', ')}}</td><td>{{voice()!.isEnabled?'Yes':'No'}}</td></tr>}</tbody></table>}
      }
    </section><aside class="card">
      @switch(mode()){
        @case('stores'){<h2>{{selectedId()?'Edit':'Add'}} store</h2><form [formGroup]="storeForm" (ngSubmit)="saveStore()"><input formControlName="storeCode" placeholder="Store code (optional)"><input formControlName="storeName" placeholder="Store name"><input formControlName="addressLine1" placeholder="Address"><div class="row"><input formControlName="city" placeholder="City"><input formControlName="stateOrProvince" placeholder="State"></div><div class="row"><input formControlName="postalCode" placeholder="Postal code"><input formControlName="countryCode" maxlength="2" placeholder="IN"></div><div class="row"><input type="number" formControlName="latitude" placeholder="Latitude"><input type="number" formControlName="longitude" placeholder="Longitude"></div><input type="number" formControlName="geoFenceRadiusMeters" placeholder="Geofence metres"><input formControlName="timeZone" placeholder="India Standard Time"><input formControlName="contactEmail" placeholder="Contact email"><button [disabled]="storeForm.invalid||saving()">Save</button><button type="button" (click)="resetForms()">Clear</button></form>}
        @case('users'){<h2>{{selectedId()?'Edit':'Add'}} user</h2><form [formGroup]="userForm" (ngSubmit)="saveUser()"><input formControlName="userName" placeholder="Username"><input formControlName="displayName" placeholder="Display name"><input formControlName="email" placeholder="Email"><input type="password" formControlName="password" placeholder="Password (new user)"><input formControlName="roles" placeholder="Roles comma separated"><input formControlName="storeIds" placeholder="Store IDs comma separated"><label><input type="checkbox" formControlName="isActive"> Active</label><button [disabled]="userForm.invalid||saving()">Save</button><button type="button" (click)="resetForms()">Clear</button></form>}
        @case('staff'){<h2>{{selectedId()?'Edit':'Add'}} staff</h2><form [formGroup]="staffForm" (ngSubmit)="saveStaff()"><input formControlName="employeeCode" placeholder="Employee code"><div class="row"><input formControlName="firstName" placeholder="First name"><input formControlName="lastName" placeholder="Last name"></div><input formControlName="mobile" placeholder="Mobile"><input formControlName="userName" placeholder="Login username"><input formControlName="email" placeholder="Email"><input type="password" formControlName="password" placeholder="Password (new staff)"><input formControlName="roles" placeholder="Roles e.g. SalesStaff"><input formControlName="storeIds" placeholder="Store IDs comma separated"><label><input type="checkbox" formControlName="isActive"> Active</label><button [disabled]="staffForm.invalid||saving()">Save</button><button type="button" (click)="resetForms()">Clear</button></form>}
        @case('categories'){<h2>{{selectedId()?'Edit':'Add'}} category</h2><form [formGroup]="categoryForm" (ngSubmit)="saveCategory()"><input formControlName="categoryCode" placeholder="Category code"><input formControlName="name" placeholder="Category name"><input type="number" formControlName="storeId" placeholder="Store ID (blank = tenant-wide)"><input type="number" formControlName="parentCategoryId" placeholder="Parent ID"><label><input type="checkbox" formControlName="isActive"> Active</label><button [disabled]="categoryForm.invalid||saving()">Save</button><button type="button" (click)="resetForms()">Clear</button></form>}
        @case('voice'){<h2>Store voice settings</h2><form [formGroup]="voiceForm" (ngSubmit)="saveVoice()"><select formControlName="storeId" (change)="loadVoice()"><option value="">Select store</option>@for(s of stores();track s.id){<option [value]="s.id">{{s.storeName}}</option>}</select><input formControlName="triggerKeyword" placeholder="Dynamic trigger"><input formControlName="aliases" placeholder="Aliases comma separated"><select formControlName="responseMode"><option [value]="1">In app</option><option [value]="2">Toast</option><option [value]="3">Voice</option><option [value]="4">In app + voice</option></select><label><input type="checkbox" formControlName="isEnabled"> Enabled</label><label><input type="checkbox" formControlName="requireConfirmationForAmbiguousCategory"> Confirm ambiguous category</label><button [disabled]="voiceForm.invalid||saving()">Save</button></form>}
      }
    </aside></div>
  </main></app-admin-shell>`
})
export class PhaseFiveManagementPage implements OnInit {
  private readonly api=inject(PhaseFiveApiService); private readonly route=inject(ActivatedRoute); private readonly fb=inject(FormBuilder);
  protected readonly mode=signal('stores'); protected readonly title=signal('Stores'); protected readonly stores=signal<Store[]>([]); protected readonly users=signal<TenantUser[]>([]); protected readonly staff=signal<Staff[]>([]); protected readonly categories=signal<Category[]>([]); protected readonly voice=signal<VoiceSetting|null>(null); protected readonly saving=signal(false); protected readonly error=signal(''); protected readonly message=signal(''); protected readonly selectedId=signal<number|null>(null);
  protected readonly storeForm=this.fb.nonNullable.group({storeCode:'',storeName:['',Validators.required],addressLine1:['',Validators.required],city:['',Validators.required],stateOrProvince:['Gujarat',Validators.required],postalCode:['',Validators.required],countryCode:['IN',[Validators.required,Validators.minLength(2)]],latitude:this.fb.control<number|null>(null),longitude:this.fb.control<number|null>(null),geoFenceRadiusMeters:this.fb.control<number|null>(50),timeZone:['India Standard Time',Validators.required],contactEmail:'',isActive:true});
  protected readonly userForm=this.fb.nonNullable.group({userName:['',Validators.required],displayName:['',Validators.required],email:['',[Validators.required,Validators.email]],password:'',roles:['TenantAdmin',Validators.required],storeIds:'',isActive:true});
  protected readonly staffForm=this.fb.nonNullable.group({employeeCode:['',Validators.required],firstName:['',Validators.required],lastName:['',Validators.required],mobile:'',userName:['',Validators.required],email:['',[Validators.required,Validators.email]],password:'',roles:'SalesStaff',storeIds:'',isActive:true});
  protected readonly categoryForm=this.fb.nonNullable.group({categoryCode:['',Validators.required],name:['',Validators.required],storeId:this.fb.control<number|null>(null),parentCategoryId:this.fb.control<number|null>(null),isActive:true});
  protected readonly voiceForm=this.fb.nonNullable.group({storeId:['',Validators.required],triggerKeyword:['Aasha Add',Validators.required],aliases:'',responseMode:4,isEnabled:true,requireConfirmationForAmbiguousCategory:true});
  ngOnInit(){this.route.data.subscribe(d=>{this.mode.set(String(d['mode']??'stores'));this.title.set(String(d['title']??'Phase 5'));this.resetForms();this.load();});}
  private load(clearStatus=true){if(clearStatus)this.clearStatus();const m=this.mode();if(m==='stores'||m==='voice')this.api.stores().subscribe({next:x=>this.stores.set(x),error:e=>this.fail(e)});if(m==='users')this.api.users().subscribe({next:x=>this.users.set(x),error:e=>this.fail(e)});if(m==='staff')this.api.staff().subscribe({next:x=>this.staff.set(x),error:e=>this.fail(e)});if(m==='categories')this.api.categories().subscribe({next:x=>this.categories.set(x),error:e=>this.fail(e)});}
  protected editStore(x:Store){this.selectedId.set(x.id);this.storeForm.patchValue({...x,contactEmail:x.contactEmail??'',latitude:x.latitude??null,longitude:x.longitude??null,geoFenceRadiusMeters:x.geoFenceRadiusMeters??null});}
  protected verifyStore(x:Store){this.busy();this.api.verifyStore(x.id).subscribe({next:()=>this.done('Store location verified.'),error:e=>this.fail(e)});}
  protected toggleStore(x:Store){this.busy();this.api.setStoreActive(x.id,!x.isActive).subscribe({next:()=>this.done(`Store ${x.isActive?'deactivated':'activated'}.`),error:e=>this.fail(e)});}
  protected editUser(x:TenantUser){this.selectedId.set(x.id);this.userForm.patchValue({userName:x.userName,displayName:x.displayName,email:x.email,password:'',roles:x.roles.join(','),storeIds:x.storeIds.join(','),isActive:x.isActive});this.userForm.controls.userName.disable();}
  protected editStaff(x:Staff){this.selectedId.set(x.id);this.staffForm.patchValue({employeeCode:x.employeeCode,firstName:x.firstName,lastName:x.lastName,mobile:x.mobile??'',userName:'existing',email:'existing@example.invalid',password:'',roles:'SalesStaff',storeIds:x.storeIds.join(','),isActive:x.isActive});this.staffForm.controls.employeeCode.disable();this.staffForm.controls.userName.disable();this.staffForm.controls.email.disable();}
  protected editCategory(x:Category){this.selectedId.set(x.id);this.categoryForm.patchValue({categoryCode:x.categoryCode,name:x.name,storeId:x.storeId??null,parentCategoryId:x.parentCategoryId??null,isActive:x.isActive});this.categoryForm.controls.categoryCode.disable();}
  protected saveStore(){if(this.storeForm.invalid)return;this.busy();const v=this.storeForm.getRawValue();const body={...v,addressLine2:null,landmark:null,district:null,externalPlaceId:null,locationSource:1};const call=this.selectedId()?this.api.updateStore(this.selectedId()!,body):this.api.createStore(body);call.subscribe({next:()=>this.done('Store saved.'),error:e=>this.fail(e)});}
  protected saveUser(){if(this.userForm.invalid)return;this.busy();const v=this.userForm.getRawValue();const id=this.selectedId();if(id){this.api.updateUser(id,{email:v.email,displayName:v.displayName,isActive:v.isActive}).subscribe({next:()=>this.api.setUserRoles(id,this.csv(v.roles)).subscribe({next:()=>this.api.setUserStores(id,this.ids(v.storeIds),this.ids(v.storeIds)[0]??null).subscribe({next:()=>this.done('User saved.'),error:e=>this.fail(e)}),error:e=>this.fail(e)}),error:e=>this.fail(e)});}else{this.api.createUser({userName:v.userName,email:v.email,displayName:v.displayName,password:v.password,roles:this.csv(v.roles),storeIds:this.ids(v.storeIds)}).subscribe({next:()=>this.done('User created.'),error:e=>this.fail(e)});}}
  protected saveStaff(){if(this.staffForm.invalid)return;this.busy();const v=this.staffForm.getRawValue();const id=this.selectedId();const call=id?this.api.updateStaff(id,{firstName:v.firstName,lastName:v.lastName,mobile:v.mobile||null,isActive:v.isActive,storeIds:this.ids(v.storeIds)}):this.api.createStaff({employeeCode:v.employeeCode,firstName:v.firstName,lastName:v.lastName,mobile:v.mobile||null,userName:v.userName,email:v.email,password:v.password,roles:this.csv(v.roles),storeIds:this.ids(v.storeIds)});call.subscribe({next:()=>this.done(id?'Staff saved.':'Staff created.'),error:e=>this.fail(e)});}
  protected saveCategory(){if(this.categoryForm.invalid)return;this.busy();const v=this.categoryForm.getRawValue();const id=this.selectedId();const body={...v,storeId:v.storeId||null,parentCategoryId:v.parentCategoryId||null};const call=id?this.api.updateCategory(id,body):this.api.createCategory(body);call.subscribe({next:()=>this.done(id?'Category saved.':'Category created.'),error:e=>this.fail(e)});}
  protected loadVoice(){const id=Number(this.voiceForm.controls.storeId.value);if(!id)return;this.api.voiceSetting(id).subscribe({next:x=>{this.voice.set(x);this.voiceForm.patchValue({triggerKeyword:x.triggerKeyword,aliases:x.aliases.join(','),responseMode:x.responseMode,isEnabled:x.isEnabled,requireConfirmationForAmbiguousCategory:x.requireConfirmationForAmbiguousCategory});},error:e=>this.fail(e)});}
  protected saveVoice(){if(this.voiceForm.invalid)return;this.busy();const v=this.voiceForm.getRawValue();this.api.saveVoiceSetting(Number(v.storeId),{triggerKeyword:v.triggerKeyword,responseMode:Number(v.responseMode),isEnabled:v.isEnabled,requireConfirmationForAmbiguousCategory:v.requireConfirmationForAmbiguousCategory,aliases:this.csv(v.aliases)}).subscribe({next:x=>{this.voice.set(x);this.done('Voice settings saved.');},error:e=>this.fail(e)});}
  protected resetForms(){this.selectedId.set(null);this.userForm.controls.userName.enable();this.staffForm.controls.employeeCode.enable();this.staffForm.controls.userName.enable();this.staffForm.controls.email.enable();this.categoryForm.controls.categoryCode.enable();}
  private done(msg:string){this.saving.set(false);this.resetForms();this.load(false);this.error.set('');this.message.set(msg);}
  private busy(){this.saving.set(true);this.clearStatus();}
  private fail(error:unknown){this.saving.set(false);this.error.set(this.errorMessage(error));}
  private errorMessage(error:unknown){if(error instanceof HttpErrorResponse){const payload=error.error as {message?:string}|null;return payload?.message??error.message??'Request failed.';}return error instanceof Error?error.message:'Request failed.';}
  private clearStatus(){this.error.set('');this.message.set('');}
  private csv(v:string){return v.split(',').map(x=>x.trim()).filter(Boolean);}
  private ids(v:string){return this.csv(v).map(Number).filter(x=>Number.isInteger(x)&&x>0);}
}
