using System.Globalization;
using System.Text.Json;
using CustSearch.Application.Authentication;
using CustSearch.Application.CamerasTracking;
using CustSearch.Application.TenantOperations;
using CustSearch.Domain.Entities;
using CustSearch.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;

namespace CustSearch.Infrastructure.CamerasTracking;

public sealed class CameraMotionRuleService(CustSearchDbContext db,ICurrentUserContext currentUser,TimeProvider clock):ICameraMotionRuleService
{
    private sealed record Definition(string Code,string Name,string Group,bool ZoneRequired,bool Available,string Description);
    private static readonly Definition[]Definitions=[
        new("PERSON_DETECTED","Person Detected","Basic Detection",false,true,"Detect a person above the configured confidence."),new("ENTRY_CROSSED","Entry Crossed","Entry / Exit",true,true,"Detect a track crossing an entry zone."),new("EXIT_CROSSED","Exit Crossed","Entry / Exit",true,true,"Detect a track crossing an exit zone."),new("DWELL_THRESHOLD","Dwell Threshold","Customer Behaviour",false,true,"Detect a person remaining beyond the configured duration."),new("RESTRICTED_ZONE_ENTRY","Restricted Zone Entry","Restricted Areas",true,true,"Detect entry into an active restricted zone."),new("CAMERA_OFFLINE","Camera Offline","Camera Health",false,true,"Alert when camera health becomes offline."),
        new("MOTION_GENERAL","General Motion","Basic Detection",false,false,"Advanced catalog item."),new("PERSON_TRACK_STARTED","Person Track Started","Basic Detection",false,false,"Advanced catalog item."),new("PERSON_TRACK_ENDED","Person Track Ended","Basic Detection",false,false,"Advanced catalog item."),new("CHECKOUT_ENTERED","Checkout Entered","Entry / Exit",true,false,"Advanced catalog item."),new("CHECKOUT_EXITED","Checkout Exited","Entry / Exit",true,false,"Advanced catalog item."),new("SHELF_ZONE_APPROACHED","Shelf Zone Approached","Customer Behaviour",true,false,"Advanced catalog item."),new("SHELF_INTERACTION","Shelf Interaction","Retail Security",true,false,"Phase G catalog item."),new("ITEM_PICKUP_CANDIDATE","Item Pickup Candidate","Retail Security",true,false,"Phase G catalog item."),new("ITEM_PUTBACK_CANDIDATE","Item Put-Back Candidate","Retail Security",true,false,"Phase G catalog item."),new("ITEM_REMAINS_WITH_TRACK","Item Remains With Track","Retail Security",false,false,"Phase G catalog item."),new("SUSPECTED_UNPAID_EXIT","Suspected Unpaid Exit","Retail Security",false,false,"Phase G catalog item."),new("STAFF_ONLY_ZONE_ENTRY","Staff-Only Area Entry","Restricted Areas",true,false,"Advanced catalog item."),new("HIGH_VALUE_ZONE_ACTIVITY","High-Value Zone Activity","Restricted Areas",true,false,"Advanced catalog item."),new("LOW_CONFIDENCE_CONDITION","Low Confidence Condition","Restricted Areas",true,false,"Advanced catalog item."),new("CAMERA_ONLINE","Camera Online","Camera Health",false,false,"Advanced catalog item."),new("CAMERA_OCCLUDED","Camera Occluded","Camera Health",false,false,"Advanced catalog item."),new("ANONYMOUS_VISITOR_DETECTED","Anonymous Visitor Detected","Customer Intelligence",false,false,"Advanced catalog item."),new("VISIT_PARTY_DETECTED","Visit Party Detected","Customer Intelligence",false,false,"Advanced catalog item."),new("STAFF_CUSTOMER_PROXIMITY","Staff / Customer Proximity","Customer Intelligence",false,false,"Advanced catalog item."),new("RECOGNITION_REVIEW_REQUIRED","Recognition Review Required","Customer Intelligence",false,false,"Advanced catalog item.")];
    public IReadOnlyList<MotionRuleCatalogItem>GetCatalog()=>Definitions.Select(x=>new MotionRuleCatalogItem(x.Code,x.Name,x.Group,x.ZoneRequired,x.Available,x.Description)).ToArray();
    public async Task<CameraMotionSettingsView>GetSettingsAsync(long cameraId,CancellationToken ct=default){var camera=await Camera(cameraId,false,ct);return new(camera.Id,camera.MotionRulesEnabled,camera.UseDetectionZone);}
    public async Task<CameraMotionSettingsView>SetSettingsAsync(long cameraId,bool enabled,TenantAuditContext audit,CancellationToken ct=default){var camera=await Camera(cameraId,true,ct);var now=clock.GetUtcNow().UtcDateTime;camera.SetMotionRulesEnabled(enabled,now);Audit(audit,camera,"CameraMotionRulesSettingChanged","Camera",camera.Id,new{cameraId,enabled},now);await db.SaveChangesAsync(ct);return new(camera.Id,camera.MotionRulesEnabled,camera.UseDetectionZone);}
    public async Task<CameraMotionSettingsView>SetDetectionZoneAsync(long cameraId,bool enabled,TenantAuditContext audit,CancellationToken ct=default){var camera=await Camera(cameraId,true,ct);if(enabled&&!await db.CameraZoneConfigurations.AnyAsync(x=>x.TenantId==camera.TenantId&&x.StoreId==camera.StoreId&&x.CameraId==camera.Id&&x.IsActive,ct))throw Fail("Use Detection Zone requires at least one active zone for this camera.");var now=clock.GetUtcNow().UtcDateTime;camera.SetUseDetectionZone(enabled,now);Audit(audit,camera,"CameraDetectionZoneSettingChanged","Camera",camera.Id,new{cameraId,enabled},now);await db.SaveChangesAsync(ct);return new(camera.Id,camera.MotionRulesEnabled,camera.UseDetectionZone);}
    public async Task<IReadOnlyList<CameraMotionRuleView>>ListAsync(long cameraId,CancellationToken ct=default){var camera=await Camera(cameraId,false,ct);return await db.CameraMotionRules.AsNoTracking().Where(x=>x.TenantId==camera.TenantId&&x.StoreId==camera.StoreId&&x.CameraId==camera.Id).OrderBy(x=>x.RuleCode).Select(x=>Map(x)).ToListAsync(ct);}
    public async Task<CameraMotionRuleView>SaveAsync(long cameraId,long?ruleId,SaveCameraMotionRuleCommand command,TenantAuditContext audit,CancellationToken ct=default){ArgumentNullException.ThrowIfNull(command);var camera=await Camera(cameraId,false,ct);var definition=Definitions.SingleOrDefault(x=>string.Equals(x.Code,command.RuleCode.Trim(),StringComparison.OrdinalIgnoreCase))??throw Fail("Motion rule code is not recognized.");if(!definition.Available)throw Fail("This motion rule is planned but is not available in the current phase.");var days=Days(command.DaysOfWeek);if(command.ZoneId.HasValue){var valid=await db.CameraZoneConfigurations.AnyAsync(x=>x.Id==command.ZoneId&&x.TenantId==camera.TenantId&&x.StoreId==camera.StoreId&&x.CameraId==camera.Id&&x.IsActive,ct);if(!valid)throw new CameraTrackingException("Active camera zone was not found in scope.",CameraTrackingFailureKind.NotFound);}var now=clock.GetUtcNow().UtcDateTime;CameraMotionRule rule;if(ruleId.HasValue){rule=await db.CameraMotionRules.SingleOrDefaultAsync(x=>x.Id==ruleId&&x.TenantId==camera.TenantId&&x.StoreId==camera.StoreId&&x.CameraId==camera.Id,ct)??throw new CameraTrackingException("Motion rule was not found.",CameraTrackingFailureKind.NotFound);if(!string.Equals(rule.RuleCode,definition.Code,StringComparison.Ordinal))throw Fail("Motion rule code is immutable.");}else{rule=CameraMotionRule.Create(camera.TenantId,camera.StoreId,camera.Id,definition.Code,command.RuleName,definition.ZoneRequired,now);db.CameraMotionRules.Add(rule);}try{rule.Configure(command.RuleName,command.IsEnabled,command.MinimumConfidence,command.Sensitivity,command.MinimumDurationSeconds,command.CooldownSeconds,command.StartTime,command.EndTime,days,command.EvidenceSnapshotEnabled,command.EvidenceClipEnabled,command.EvidencePreEventSeconds,command.EvidencePostEventSeconds,command.Severity,command.CreateAlert,command.RealtimeNotificationEnabled,command.ZoneId,now);}catch(ArgumentException ex){if(rule.Id==0)db.Entry(rule).State=EntityState.Detached;throw Fail(ex.Message);}try{await db.SaveChangesAsync(ct);}catch(DbUpdateException){throw new CameraTrackingException("This camera already has the selected motion rule.",CameraTrackingFailureKind.Conflict);}Audit(audit,camera,"CameraMotionRuleSaved","CameraMotionRule",rule.Id,new{rule.Id,rule.RuleCode,rule.IsEnabled,rule.ZoneId},now);await db.SaveChangesAsync(ct);return Map(rule);}
    private async Task<Camera>Camera(long id,bool tracked,CancellationToken ct){var tenant=RequireTenant();var query=tracked?db.Cameras:db.Cameras.AsNoTracking();var camera=await query.SingleOrDefaultAsync(x=>x.Id==id&&x.TenantId==tenant,ct)??throw new CameraTrackingException("Camera was not found.",CameraTrackingFailureKind.NotFound);if(!TenantWide()&&!currentUser.StoreIds.Contains(camera.StoreId))throw new CameraTrackingException("Camera store is outside the server-authorized scope.",CameraTrackingFailureKind.Forbidden);return camera;}
    private long RequireTenant()=>currentUser.IsAuthenticated&&!currentUser.IsPlatformAdmin&&currentUser.TenantId is>0?currentUser.TenantId.Value:throw new CameraTrackingException("Tenant session is required.",CameraTrackingFailureKind.Forbidden);private bool TenantWide()=>PhaseFiveAccessRules.ContainsTenantWideRole(currentUser.Roles);
    private static string Days(string value){var input=string.IsNullOrWhiteSpace(value)?"*":value.Trim().ToUpperInvariant();if(input=="*")return input;var allowed=new HashSet<string>(["MON","TUE","WED","THU","FRI","SAT","SUN"]);var days=input.Split(',',StringSplitOptions.TrimEntries|StringSplitOptions.RemoveEmptyEntries).Distinct().ToArray();if(days.Length==0||days.Any(x=>!allowed.Contains(x)))throw Fail("DaysOfWeek must be * or a comma-separated MON..SUN list.");return string.Join(',',days);}
    private void Audit(TenantAuditContext audit,Camera camera,string action,string entity,long id,object value,DateTime now)=>db.AuditLogs.Add(AuditLog.Record(camera.TenantId,camera.StoreId,audit.ActorUserId,"User",action,entity,id.ToString(CultureInfo.InvariantCulture),null,JsonSerializer.Serialize(value),audit.IpAddress,audit.UserAgent,audit.CorrelationId,now));private static CameraTrackingException Fail(string message)=>new(message,CameraTrackingFailureKind.Validation);
    private static CameraMotionRuleView Map(CameraMotionRule x)=>new(x.Id,x.CameraId,x.RuleCode,x.RuleName,x.IsEnabled,x.MinimumConfidence,x.Sensitivity,x.MinimumDurationSeconds,x.CooldownSeconds,x.StartTime,x.EndTime,x.DaysOfWeek,x.EvidenceSnapshotEnabled,x.EvidenceClipEnabled,x.EvidencePreEventSeconds,x.EvidencePostEventSeconds,x.Severity,x.CreateAlert,x.RealtimeNotificationEnabled,x.ZoneRequired,x.ZoneId,x.CreatedUtc,x.UpdatedUtc);
}
