using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using CustSearch.Application.Authentication;
using CustSearch.Application.CamerasTracking;
using CustSearch.Application.TenantOperations;
using CustSearch.Domain.Entities;
using CustSearch.Domain.Enums;
using CustSearch.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;

namespace CustSearch.Infrastructure.CamerasTracking;

/// <summary>Tenant/store authorization boundary and authenticated normalized CCTV event processor.</summary>
public sealed class CameraTrackingService(CustSearchDbContext db,ICurrentUserContext currentUser,ICctvServiceSecretResolver secrets,TimeProvider clock,IOptions<CctvSecurityOptions> options):ICameraTrackingService
{
    private static readonly JsonSerializerOptions JsonOptions=new(JsonSerializerDefaults.Web){UnmappedMemberHandling=JsonUnmappedMemberHandling.Disallow};
    private static readonly HashSet<string> EventTypes=["person.entered","person.updated","person.exited","person.lost","person.handoff","camera.heartbeat"];
    private static readonly string[] ForbiddenCctvFields=["face","identity","embedding","biometric","customerid","staffprofileid","rawframe","image"];
    private readonly CctvSecurityOptions security=options.Value;

    public async Task<IReadOnlyList<CameraView>>ListCamerasAsync(long?storeId,CancellationToken ct=default){var tenant=RequireTenant();if(storeId.HasValue)RequireStore(storeId.Value);var query=db.Cameras.AsNoTracking().Where(x=>x.TenantId==tenant);if(storeId.HasValue)query=query.Where(x=>x.StoreId==storeId);else if(!TenantWide())query=query.Where(x=>currentUser.StoreIds.Contains(x.StoreId));return await query.OrderBy(x=>x.StoreId).ThenBy(x=>x.CameraCode).Select(x=>Map(x)).ToListAsync(ct).ConfigureAwait(false);}
    public async Task<CameraView>SaveCameraAsync(long?cameraId,SaveCameraCommand command,TenantAuditContext audit,CancellationToken ct=default)
    {ArgumentNullException.ThrowIfNull(command);ArgumentNullException.ThrowIfNull(audit);var tenant=RequireTenant();RequireStore(command.StoreId);var now=clock.GetUtcNow().UtcDateTime;Camera camera;string action;if(cameraId.HasValue){camera=await RequireCamera(tenant,cameraId.Value,true,ct).ConfigureAwait(false);RequireStore(camera.StoreId);if(camera.StoreId!=command.StoreId||!string.Equals(camera.CameraCode,command.CameraCode.Trim(),StringComparison.OrdinalIgnoreCase))throw new CameraTrackingException("Camera store and code are immutable.",CameraTrackingFailureKind.Validation);camera.Update(command.Name,command.RtspConfigurationReference,command.Location,command.Direction,command.IsActive,now);action="CameraUpdated";}else{if(string.IsNullOrWhiteSpace(command.RtspConfigurationReference))throw new CameraTrackingException("An opaque RTSP configuration reference is required.",CameraTrackingFailureKind.Validation);if(!await db.Stores.AnyAsync(x=>x.Id==command.StoreId&&x.TenantId==tenant&&x.IsActive,ct).ConfigureAwait(false))throw new CameraTrackingException("Store was not found.",CameraTrackingFailureKind.NotFound);camera=Camera.Create(tenant,command.StoreId,command.CameraCode,command.Name,command.RtspConfigurationReference,command.Location,command.Direction,command.IsActive,now);db.Cameras.Add(camera);action="CameraCreated";}try{await db.SaveChangesAsync(ct).ConfigureAwait(false);}catch(DbUpdateException){throw new CameraTrackingException("Camera code already exists in the store.",CameraTrackingFailureKind.Conflict);}Audit(audit,tenant,camera.StoreId,action,"Camera",camera.Id,new{camera.Id,camera.StoreId,camera.CameraCode,camera.Name,camera.Status,camera.Direction,camera.IsActive,HasRtspConfiguration=true},now);await db.SaveChangesAsync(ct).ConfigureAwait(false);return Map(camera);}
    public async Task<IReadOnlyList<CameraZoneView>>ListZonesAsync(long cameraId,CancellationToken ct=default){var tenant=RequireTenant();var camera=await RequireCamera(tenant,cameraId,false,ct).ConfigureAwait(false);RequireStore(camera.StoreId);return await db.CameraZoneConfigurations.AsNoTracking().Where(x=>x.TenantId==tenant&&x.CameraId==cameraId).OrderBy(x=>x.ZoneCode).ThenByDescending(x=>x.Version).Select(x=>Map(x)).ToListAsync(ct).ConfigureAwait(false);}
    public async Task<CameraZoneView>AddZoneVersionAsync(long cameraId,SaveCameraZoneCommand command,TenantAuditContext audit,CancellationToken ct=default)
    {ArgumentNullException.ThrowIfNull(command);ArgumentNullException.ThrowIfNull(audit);ValidateGeometry(command.GeometryJson);var tenant=RequireTenant();var camera=await RequireCamera(tenant,cameraId,false,ct).ConfigureAwait(false);RequireStore(camera.StoreId);if(command.ZoneType==CameraZoneType.Category&&command.CategoryId is null)throw new CameraTrackingException("Category zone requires CategoryId.",CameraTrackingFailureKind.Validation);if(command.CategoryId.HasValue&&!await db.ProductCategories.AnyAsync(x=>x.Id==command.CategoryId&&x.TenantId==tenant&&(x.StoreId==null||x.StoreId==camera.StoreId)&&x.IsActive,ct).ConfigureAwait(false))throw new CameraTrackingException("Category was not found in the camera store.",CameraTrackingFailureKind.NotFound);var now=clock.GetUtcNow().UtcDateTime;var code=command.ZoneCode.Trim().ToUpperInvariant();var existing=await db.CameraZoneConfigurations.Where(x=>x.TenantId==tenant&&x.CameraId==cameraId&&x.ZoneCode==code).OrderByDescending(x=>x.Version).FirstOrDefaultAsync(ct).ConfigureAwait(false);var version=(existing?.Version??0)+1;if(existing?.IsActive==true)existing.Supersede(now);var zone=CameraZoneConfiguration.Create(tenant,camera.StoreId,cameraId,code,command.Name,command.ZoneType,NormalizeJson(command.GeometryJson),version,command.CategoryId,now);db.CameraZoneConfigurations.Add(zone);await db.SaveChangesAsync(ct).ConfigureAwait(false);Audit(audit,tenant,camera.StoreId,"CameraZoneVersionCreated","CameraZoneConfiguration",zone.Id,new{zone.Id,zone.CameraId,zone.ZoneCode,zone.ZoneType,zone.Version},now);await db.SaveChangesAsync(ct).ConfigureAwait(false);return Map(zone);}
    public async Task<IReadOnlyList<PersonTrackView>>ListTracksAsync(long?storeId,long?afterId,int take=100,CancellationToken ct=default){var tenant=RequireTenant();take=Math.Clamp(take,1,500);if(storeId.HasValue)RequireStore(storeId.Value);var query=db.PersonTrackSessions.AsNoTracking().Where(x=>x.TenantId==tenant);if(storeId.HasValue)query=query.Where(x=>x.StoreId==storeId);else if(!TenantWide())query=query.Where(x=>currentUser.StoreIds.Contains(x.StoreId));if(afterId.HasValue)query=query.Where(x=>x.Id>afterId);return await query.OrderBy(x=>x.Id).Take(take).Select(x=>Map(x)).ToListAsync(ct).ConfigureAwait(false);}
    public async Task<PersonTrackView>AssociateAsync(long trackId,AssociateTrackCommand command,TenantAuditContext audit,CancellationToken ct=default)
    {ArgumentNullException.ThrowIfNull(command);ArgumentNullException.ThrowIfNull(audit);if(command.SubjectKind==TrackingSubjectKind.Anonymous)throw new CameraTrackingException("Anonymous is the default and cannot be associated as an identity.",CameraTrackingFailureKind.Validation);var tenant=RequireTenant();var track=await db.PersonTrackSessions.SingleOrDefaultAsync(x=>x.Id==trackId&&x.TenantId==tenant,ct).ConfigureAwait(false)??throw new CameraTrackingException("Track was not found.",CameraTrackingFailureKind.NotFound);RequireStore(track.StoreId);var now=clock.GetUtcNow().UtcDateTime;if(command.SubjectKind==TrackingSubjectKind.Customer){var eligible=await db.Customers.AnyAsync(x=>x.Id==command.SubjectId&&x.TenantId==tenant&&x.IsActive,ct).ConfigureAwait(false)&&await db.CustomerStoreAssignments.AnyAsync(x=>x.TenantId==tenant&&x.CustomerId==command.SubjectId&&x.StoreId==track.StoreId,ct).ConfigureAwait(false);if(!eligible)throw new CameraTrackingException("Customer is not eligible in this store.",CameraTrackingFailureKind.NotFound);track.AssociateCustomer(command.SubjectId,now);}else if(command.SubjectKind==TrackingSubjectKind.Staff){var eligible=await db.StaffProfiles.AnyAsync(x=>x.Id==command.SubjectId&&x.TenantId==tenant&&x.IsActive,ct).ConfigureAwait(false)&&await(from staff in db.StaffProfiles join assignment in db.UserStoreAssignments on new{staff.TenantId,staff.UserId} equals new{assignment.TenantId,assignment.UserId} where staff.Id==command.SubjectId&&assignment.StoreId==track.StoreId select staff.Id).AnyAsync(ct).ConfigureAwait(false);if(!eligible)throw new CameraTrackingException("Staff member is not assigned to this store.",CameraTrackingFailureKind.NotFound);track.AssociateStaff(command.SubjectId,now);}else throw new CameraTrackingException("Unsupported subject kind.",CameraTrackingFailureKind.Validation);Audit(audit,tenant,track.StoreId,"PersonTrackAssociated","PersonTrackSession",track.Id,new{track.Id,track.SubjectKind,SubjectId=command.SubjectId,OperationalOnly=track.SubjectKind==TrackingSubjectKind.Staff},now);await db.SaveChangesAsync(ct).ConfigureAwait(false);return Map(track);}

    public async Task<CctvEventAcknowledgement>ReceiveAsync(CctvInboundEnvelope envelope,CancellationToken ct=default)
    {
        ArgumentNullException.ThrowIfNull(envelope);if(envelope.Body.Length==0||envelope.Body.Length>security.MaximumBodyBytes)throw new CameraTrackingException("CCTV event body size is invalid.",CameraTrackingFailureKind.Validation);var now=clock.GetUtcNow().UtcDateTime;var timestamp=ParseTimestamp(envelope.Timestamp);if(Math.Abs((now-timestamp).TotalSeconds)>security.AllowedClockSkewSeconds)throw new CameraTrackingException("CCTV event timestamp is outside the allowed clock skew.",CameraTrackingFailureKind.Unauthorized);var credential=await secrets.ResolveAsync(envelope.ServiceId,ct).ConfigureAwait(false);if(credential is null)throw new CameraTrackingException("CCTV service is not configured.",CameraTrackingFailureKind.Unauthorized);var canonical=Encoding.UTF8.GetBytes($"{envelope.ServiceId}\n{envelope.Timestamp}\n{envelope.EventId}\n{envelope.IdempotencyKey}\n").Concat(envelope.Body.ToArray()).ToArray();var expected=HMACSHA256.HashData(Encoding.UTF8.GetBytes(credential.Secret),canonical);byte[] supplied;try{var value=envelope.Signature.StartsWith("sha256=",StringComparison.OrdinalIgnoreCase)?envelope.Signature[7..]:envelope.Signature;supplied=Convert.FromHexString(value);}catch(FormatException){throw new CameraTrackingException("CCTV service signature is invalid.",CameraTrackingFailureKind.Unauthorized);}if(supplied.Length!=expected.Length||!CryptographicOperations.FixedTimeEquals(supplied,expected))throw new CameraTrackingException("CCTV service signature is invalid.",CameraTrackingFailureKind.Unauthorized);
        RejectIdentityPayload(envelope.Body);CctvNormalizedEvent evt;try{evt=JsonSerializer.Deserialize<CctvNormalizedEvent>(envelope.Body.Span,JsonOptions)??throw new JsonException();}catch(JsonException){throw new CameraTrackingException("CCTV event JSON does not match contract v1.",CameraTrackingFailureKind.Validation);}if(evt.ContractVersion!=1||!EventTypes.Contains(evt.EventType))throw new CameraTrackingException("Unsupported CCTV event contract.",CameraTrackingFailureKind.Validation);if(evt.OccurredUtc.Kind!=DateTimeKind.Utc||evt.Confidence is<0 or>1)throw new CameraTrackingException("CCTV event timestamp/confidence is invalid.",CameraTrackingFailureKind.Validation);if(evt.TenantId!=credential.TenantId||(!credential.AllowAllStores&&!credential.StoreIds.Contains(evt.StoreId)))throw new CameraTrackingException("CCTV event is outside the configured service tenant/store scope.",CameraTrackingFailureKind.Forbidden);
        var camera=await db.Cameras.SingleOrDefaultAsync(x=>x.TenantId==evt.TenantId&&x.StoreId==evt.StoreId&&x.CameraCode==evt.CameraCode&&x.IsActive,ct).ConfigureAwait(false)??throw new CameraTrackingException("Active camera was not found in the signed event scope.",CameraTrackingFailureKind.NotFound);var hash=Convert.ToHexString(SHA256.HashData(envelope.Body.Span)).ToLowerInvariant();var duplicate=await db.CameraOperationalEvents.AsNoTracking().SingleOrDefaultAsync(x=>x.ServiceId==envelope.ServiceId&&(x.EventId==envelope.EventId||x.IdempotencyKey==envelope.IdempotencyKey),ct).ConfigureAwait(false);if(duplicate is not null){if(!string.Equals(duplicate.PayloadHash,hash,StringComparison.Ordinal))throw new CameraTrackingException("CCTV idempotency key was reused with different metadata.",CameraTrackingFailureKind.Conflict);return new(duplicate.Id,null,true,"duplicate",envelope.CorrelationId);}
        var receipt=CameraOperationalEvent.Accept(evt.TenantId,evt.StoreId,camera.Id,envelope.ServiceId,envelope.EventId,envelope.IdempotencyKey,evt.EventType,evt.ContractVersion,hash,envelope.CorrelationId,evt.OccurredUtc,now);db.CameraOperationalEvents.Add(receipt);PersonTrackSession? track=null;if(evt.EventType=="camera.heartbeat"){camera.Heartbeat(evt.CameraStatus??CameraStatus.Online,evt.OccurredUtc);}else{if(string.IsNullOrWhiteSpace(evt.PersonTrackId))throw new CameraTrackingException("PersonTrackId is required for tracking events.",CameraTrackingFailureKind.Validation);track=await db.PersonTrackSessions.SingleOrDefaultAsync(x=>x.TenantId==evt.TenantId&&x.StoreId==evt.StoreId&&x.PersonTrackId==evt.PersonTrackId,ct).ConfigureAwait(false);if(evt.EventType=="person.entered"){track??=PersonTrackSession.Start(evt.TenantId,evt.StoreId,camera.Id,evt.PersonTrackId,evt.OccurredUtc,evt.Confidence);if(track.Id==0)db.PersonTrackSessions.Add(track);else track.Observe(camera.Id,evt.Confidence,evt.OccurredUtc);}else if(track is null)throw new CameraTrackingException("Tracking session was not found.",CameraTrackingFailureKind.NotFound);else if(evt.EventType=="person.handoff"){if(string.IsNullOrWhiteSpace(evt.FromCameraCode))throw new CameraTrackingException("FromCameraCode is required for a handoff.",CameraTrackingFailureKind.Validation);var from=await db.Cameras.SingleOrDefaultAsync(x=>x.TenantId==evt.TenantId&&x.StoreId==evt.StoreId&&x.CameraCode==evt.FromCameraCode,ct).ConfigureAwait(false)??throw new CameraTrackingException("Handoff source camera was not found in the same store.",CameraTrackingFailureKind.NotFound);db.CameraTrackHandoffs.Add(CameraTrackHandoff.Create(evt.TenantId,evt.StoreId,track.Id,from.Id,camera.Id,evt.Confidence,evt.GapMilliseconds??0,evt.OccurredUtc));track.Observe(camera.Id,evt.Confidence,evt.OccurredUtc,true);}else if(evt.EventType is "person.exited" or "person.lost")track.End(evt.OccurredUtc,evt.EventType=="person.lost");else track.Observe(camera.Id,evt.Confidence,evt.OccurredUtc);}
        receipt.MarkProcessed();try{await db.SaveChangesAsync(ct).ConfigureAwait(false);}catch(DbUpdateException){db.ChangeTracker.Clear();var concurrent=await db.CameraOperationalEvents.AsNoTracking().SingleOrDefaultAsync(x=>x.ServiceId==envelope.ServiceId&&(x.EventId==envelope.EventId||x.IdempotencyKey==envelope.IdempotencyKey),ct).ConfigureAwait(false);if(concurrent is not null&&concurrent.PayloadHash==hash)return new(concurrent.Id,null,true,"duplicate",envelope.CorrelationId);throw;}return new(receipt.Id,track?.Id,false,"processed",envelope.CorrelationId);
    }

    private long RequireTenant()=>currentUser.IsAuthenticated&&!currentUser.IsPlatformAdmin&&currentUser.TenantId is>0?currentUser.TenantId.Value:throw new CameraTrackingException("Tenant session is required.",CameraTrackingFailureKind.Forbidden);
    private bool TenantWide()=>PhaseFiveAccessRules.ContainsTenantWideRole(currentUser.Roles);
    private void RequireStore(long storeId){ArgumentOutOfRangeException.ThrowIfNegativeOrZero(storeId);if(!TenantWide()&&!currentUser.StoreIds.Contains(storeId))throw new CameraTrackingException("Store is outside the server-authorized scope.",CameraTrackingFailureKind.Forbidden);}
    private async Task<Camera>RequireCamera(long tenant,long id,bool tracked,CancellationToken ct){var query=tracked?db.Cameras:db.Cameras.AsNoTracking();return await query.SingleOrDefaultAsync(x=>x.Id==id&&x.TenantId==tenant,ct).ConfigureAwait(false)??throw new CameraTrackingException("Camera was not found.",CameraTrackingFailureKind.NotFound);}
    private void Audit(TenantAuditContext audit,long tenant,long store,string action,string entity,long id,object value,DateTime now)=>db.AuditLogs.Add(AuditLog.Record(tenant,store,audit.ActorUserId,"User",action,entity,id.ToString(CultureInfo.InvariantCulture),null,JsonSerializer.Serialize(value),audit.IpAddress,audit.UserAgent,audit.CorrelationId,now));
    private static CameraView Map(Camera x)=>new(x.Id,x.StoreId,x.CameraCode,x.Name,true,Hint(x.RtspConfigurationReference),x.Status,x.Location,x.Direction,x.IsActive,x.LastHeartbeatUtc,x.CreatedUtc,x.UpdatedUtc);
    private static CameraZoneView Map(CameraZoneConfiguration x)=>new(x.Id,x.CameraId,x.ZoneCode,x.Name,x.ZoneType,x.GeometryJson,x.Version,x.CategoryId,x.EffectiveUtc,x.SupersededUtc,x.IsActive);
    private static PersonTrackView Map(PersonTrackSession x)=>new(x.Id,x.StoreId,x.CameraId,x.PersonTrackId,x.StartUtc,x.EndUtc,x.Confidence,x.TrackingState,x.SubjectKind,x.CustomerId,x.StaffProfileId,x.UpdatedUtc);
    private static string Hint(string value)=>value.Length<=4?"configured":$"***{value[^4..]}";
    private static DateTime ParseTimestamp(string value){if(!long.TryParse(value,NumberStyles.None,CultureInfo.InvariantCulture,out var unix))throw new CameraTrackingException("CCTV timestamp is invalid.",CameraTrackingFailureKind.Unauthorized);try{return DateTimeOffset.FromUnixTimeSeconds(unix).UtcDateTime;}catch(ArgumentOutOfRangeException){throw new CameraTrackingException("CCTV timestamp is invalid.",CameraTrackingFailureKind.Unauthorized);}}
    private static void RejectIdentityPayload(ReadOnlyMemory<byte> body){try{using var doc=JsonDocument.Parse(body);Walk(doc.RootElement);}catch(JsonException){throw new CameraTrackingException("CCTV event JSON is invalid.",CameraTrackingFailureKind.Validation);}static void Walk(JsonElement node){if(node.ValueKind==JsonValueKind.Object)foreach(var property in node.EnumerateObject()){if(ForbiddenCctvFields.Any(x=>property.Name.Contains(x,StringComparison.OrdinalIgnoreCase)))throw new CameraTrackingException("Identity, biometric and raw image fields are forbidden in Phase 13 CCTV events.",CameraTrackingFailureKind.Validation);Walk(property.Value);}else if(node.ValueKind==JsonValueKind.Array)foreach(var child in node.EnumerateArray())Walk(child);}}
    private static void ValidateGeometry(string json){try{using var doc=JsonDocument.Parse(json);if(doc.RootElement.ValueKind!=JsonValueKind.Object||!doc.RootElement.TryGetProperty("points",out var points)||points.ValueKind!=JsonValueKind.Array||points.GetArrayLength()<3||points.GetArrayLength()>100)throw new JsonException();foreach(var point in points.EnumerateArray()){if(point.ValueKind!=JsonValueKind.Array||point.GetArrayLength()!=2)throw new JsonException();var values=point.EnumerateArray().Select(x=>x.GetDecimal()).ToArray();if(values.Any(x=>x is<0 or>1))throw new JsonException();}}catch(JsonException){throw new CameraTrackingException("Zone geometry must contain 3-100 normalized [x,y] points between 0 and 1.",CameraTrackingFailureKind.Validation);}}
    private static string NormalizeJson(string json){using var doc=JsonDocument.Parse(json);return JsonSerializer.Serialize(doc.RootElement);}
}
