using System.Data;
using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using CustSearch.Application.Authentication;
using CustSearch.Application.CamerasTracking;
using CustSearch.Application.Security;
using CustSearch.Application.TenantOperations;
using CustSearch.Domain.Entities;
using CustSearch.Domain.Enums;
using CustSearch.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;

namespace CustSearch.Infrastructure.CamerasTracking;

public sealed class CameraEvidenceStorageService(CustSearchDbContext db,ICurrentUserContext currentUser,ICctvServiceSecretResolver secrets,ISecurityEvidenceStore files,TimeProvider clock,IOptions<CctvSecurityOptions>cctvOptions,IOptions<SecurityEvidenceOptions>evidenceOptions):ICameraEvidenceStorageService
{
    private static readonly JsonSerializerOptions JsonOptions=new(JsonSerializerDefaults.Web){UnmappedMemberHandling=JsonUnmappedMemberHandling.Disallow};private readonly CctvSecurityOptions cctv=cctvOptions.Value;private readonly SecurityEvidenceOptions evidence=evidenceOptions.Value;
    public async Task<TenantStorageSummaryView>GetTenantStorageAsync(CancellationToken ct=default)=>await SummaryAsync(RequireTenant(),ct);
    public async Task<TenantStorageSummaryView>GetPlatformStorageAsync(long tenantId,CancellationToken ct=default){RequirePlatform();return await SummaryAsync(tenantId,ct);}
    public async Task<TenantStorageSummaryView>SavePlatformPolicyAsync(long tenantId,SaveTenantStoragePolicyCommand command,TenantAuditContext audit,CancellationToken ct=default)
    {RequirePlatform();ArgumentNullException.ThrowIfNull(command);if(!await db.Tenants.AnyAsync(x=>x.Id==tenantId,ct))throw Fail("Tenant was not found.",CameraTrackingFailureKind.NotFound);var now=Now();await using var tx=await db.Database.BeginTransactionAsync(IsolationLevel.Serializable,ct);await LockAsync(tenantId,ct);var policy=await db.TenantStoragePolicies.SingleOrDefaultAsync(x=>x.TenantId==tenantId,ct)??TenantStoragePolicy.CreateDefault(tenantId,now);if(policy.Id==0)db.TenantStoragePolicies.Add(policy);var usage=await db.TenantStorageUsage.SingleOrDefaultAsync(x=>x.TenantId==tenantId,ct)??TenantStorageUsage.Create(tenantId,policy.StorageQuotaBytes,now);if(db.Entry(usage).State==EntityState.Detached)db.TenantStorageUsage.Add(usage);try{policy.Configure(command.StorageEnabled,command.StorageQuotaBytes,command.DefaultRetentionDays,command.MotionSnapshotRetentionDays,command.MotionClipRetentionDays,command.FalsePositiveRetentionDays,command.UnreviewedEvidenceRetentionDays,command.ConfirmedIncidentRetentionDays,command.WarningPercent,command.CriticalPercent,command.AllowSnapshots,command.AllowMotionClips,command.AutoCleanupEnabled,command.QuotaPressurePolicy,now);usage.SetQuota(command.StorageQuotaBytes,now);}catch(Exception ex)when(ex is ArgumentException or InvalidOperationException){throw Fail(ex.Message);}db.AuditLogs.Add(AuditLog.Record(tenantId,null,currentUser.UserId,"PlatformUser","TenantStoragePolicyChanged","TenantStoragePolicy",tenantId.ToString(CultureInfo.InvariantCulture),null,JsonSerializer.Serialize(command,JsonOptions),audit.IpAddress,audit.UserAgent,audit.CorrelationId,now));await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return Map(policy,usage);}
    public async Task<IReadOnlyList<CameraEvidenceView>>ListEvidenceAsync(long?storeId,long?cameraId,int take=100,CancellationToken ct=default)
    {var tenant=RequireTenant();take=Math.Clamp(take,1,500);if(storeId.HasValue)RequireStore(storeId.Value);var query=db.CameraEvidence.AsNoTracking().Where(x=>x.TenantId==tenant);if(storeId.HasValue)query=query.Where(x=>x.StoreId==storeId);else if(!TenantWide())query=query.Where(x=>currentUser.StoreIds.Contains(x.StoreId));if(cameraId.HasValue)query=query.Where(x=>x.CameraId==cameraId);return await query.OrderByDescending(x=>x.CapturedUtc).ThenByDescending(x=>x.Id).Take(take).Select(x=>new CameraEvidenceView(x.Id,x.StoreId,x.CameraId,x.EvidenceType,x.FileSizeBytes,x.ContentType,x.CapturedUtc,x.RetentionUntilUtc,x.IsRestricted,x.IsPinned,x.DeletedUtc!=null,x.CreatedUtc)).ToListAsync(ct);}
    public async Task<CameraEvidenceIngestionResult>IngestAsync(CctvEvidenceEnvelope envelope,CancellationToken ct=default)
    {ArgumentNullException.ThrowIfNull(envelope);if(envelope.Body.IsEmpty||envelope.Body.Length>evidence.MaximumUploadBytes)throw Fail("Evidence body size is invalid.");var now=Now();var timestamp=ParseUtc(envelope.Timestamp);if(Math.Abs((now-timestamp).TotalSeconds)>cctv.AllowedClockSkewSeconds)throw Fail("CCTV evidence timestamp is outside the allowed clock skew.",CameraTrackingFailureKind.Unauthorized);var credential=await secrets.ResolveAsync(envelope.ServiceId,ct)??throw Fail("CCTV service is not configured.",CameraTrackingFailureKind.Unauthorized);var canonicalPrefix=$"{envelope.ServiceId}\n{envelope.Timestamp}\n{envelope.EventId}\n{envelope.IdempotencyKey}\n{envelope.MetadataHeader}\n";var canonical=Encoding.UTF8.GetBytes(canonicalPrefix).Concat(envelope.Body.ToArray()).ToArray();ValidateSignature(credential.Secret,envelope.Signature,canonical);CctvEvidenceMetadata metadata;try{metadata=JsonSerializer.Deserialize<CctvEvidenceMetadata>(Convert.FromBase64String(envelope.MetadataHeader),JsonOptions)??throw new JsonException();}catch(Exception ex)when(ex is FormatException or JsonException){throw Fail("CCTV evidence metadata does not match contract v1.");}ValidateMetadata(metadata,credential,now);var ingestionHash=Convert.ToHexString(SHA256.HashData(canonical)).ToLowerInvariant();var duplicate=await db.CameraEvidence.AsNoTracking().SingleOrDefaultAsync(x=>x.ServiceId==envelope.ServiceId&&x.IdempotencyKey==envelope.IdempotencyKey,ct);if(duplicate is not null){if(duplicate.IngestionHash!=ingestionHash)throw Fail("Evidence idempotency key was reused with different content.",CameraTrackingFailureKind.Conflict);var existingUsage=await db.TenantStorageUsage.AsNoTracking().SingleAsync(x=>x.TenantId==metadata.TenantId,ct);return new(duplicate.Id,true,existingUsage.UsedBytes,existingUsage.QuotaBytes,duplicate.RetentionUntilUtc,"duplicate");}
        await using var tx=await db.Database.BeginTransactionAsync(IsolationLevel.Serializable,ct);await LockAsync(metadata.TenantId,ct);duplicate=await db.CameraEvidence.SingleOrDefaultAsync(x=>x.ServiceId==envelope.ServiceId&&x.IdempotencyKey==envelope.IdempotencyKey,ct);if(duplicate is not null){if(duplicate.IngestionHash!=ingestionHash)throw Fail("Evidence idempotency key was reused with different content.",CameraTrackingFailureKind.Conflict);var u=await db.TenantStorageUsage.SingleAsync(x=>x.TenantId==metadata.TenantId,ct);return new(duplicate.Id,true,u.UsedBytes,u.QuotaBytes,duplicate.RetentionUntilUtc,"duplicate");}var camera=await db.Cameras.SingleOrDefaultAsync(x=>x.TenantId==metadata.TenantId&&x.StoreId==metadata.StoreId&&x.CameraCode==metadata.CameraCode&&x.IsActive,ct)??throw Fail("Active camera was not found in the signed evidence scope.",CameraTrackingFailureKind.NotFound);var policy=await PolicyAsync(metadata.TenantId,now,ct);if(!policy.StorageEnabled)throw Fail("Tenant evidence storage is disabled.",CameraTrackingFailureKind.Unavailable);if(metadata.EvidenceType==CameraEvidenceType.MotionSnapshot&&!policy.AllowSnapshots||metadata.EvidenceType==CameraEvidenceType.MotionClip&&!policy.AllowMotionClips)throw Fail("This evidence type is disabled by tenant storage policy.",CameraTrackingFailureKind.Unavailable);var usage=await UsageAsync(metadata.TenantId,policy.StorageQuotaBytes,now,ct);try{usage.Reserve(metadata.EvidenceType,envelope.Body.Length,now);}catch(InvalidOperationException ex){throw Fail(ex.Message,CameraTrackingFailureKind.Conflict);}var retention=metadata.CapturedUtc.AddDays(policy.RetentionDays(metadata.EvidenceType));var objectKey=ObjectKey(metadata,camera.Id,now);var hash=SHA256.HashData(envelope.Body.Span);var record=CameraEvidence.Create(metadata.TenantId,metadata.StoreId,camera.Id,metadata.MotionEventId,metadata.SecurityIncidentId,metadata.EvidenceType,objectKey,envelope.Body.Length,metadata.ContentType,hash,metadata.CapturedUtc,retention,metadata.IsRestricted,metadata.IsPinned,envelope.ServiceId,envelope.EventId,envelope.IdempotencyKey,ingestionHash,now);db.CameraEvidence.Add(record);var written=false;try{await files.SaveEncryptedAsync(objectKey,envelope.Body,ct);written=true;await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);}catch{if(written)await files.DeleteAsync(objectKey,CancellationToken.None);throw;}return new(record.Id,false,usage.UsedBytes,usage.QuotaBytes,retention,"stored");}
    private async Task<TenantStorageSummaryView>SummaryAsync(long tenantId,CancellationToken ct){if(!await db.Tenants.AsNoTracking().AnyAsync(x=>x.Id==tenantId,ct))throw Fail("Tenant was not found.",CameraTrackingFailureKind.NotFound);var now=Now();var policy=await db.TenantStoragePolicies.AsNoTracking().SingleOrDefaultAsync(x=>x.TenantId==tenantId,ct);var usage=await db.TenantStorageUsage.AsNoTracking().SingleOrDefaultAsync(x=>x.TenantId==tenantId,ct);if(policy is null||usage is null){await using var tx=await db.Database.BeginTransactionAsync(IsolationLevel.Serializable,ct);await LockAsync(tenantId,ct);policy=await PolicyAsync(tenantId,now,ct);usage=await UsageAsync(tenantId,policy.StorageQuotaBytes,now,ct);await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);}return Map(policy,usage);}
    private async Task<TenantStoragePolicy>PolicyAsync(long tenant,DateTime now,CancellationToken ct){var x=await db.TenantStoragePolicies.SingleOrDefaultAsync(p=>p.TenantId==tenant,ct);if(x is not null)return x;x=TenantStoragePolicy.CreateDefault(tenant,now);db.TenantStoragePolicies.Add(x);return x;}
    private async Task<TenantStorageUsage>UsageAsync(long tenant,long quota,DateTime now,CancellationToken ct){var x=await db.TenantStorageUsage.SingleOrDefaultAsync(p=>p.TenantId==tenant,ct);if(x is not null)return x;x=TenantStorageUsage.Create(tenant,quota,now);db.TenantStorageUsage.Add(x);return x;}
    private static TenantStorageSummaryView Map(TenantStoragePolicy p,TenantStorageUsage u){var percent=u.QuotaBytes==0?0:Math.Round((decimal)u.UsedBytes/u.QuotaBytes*100,2);var pressure=percent>=p.CriticalPercent?"Critical":percent>=p.WarningPercent?"Warning":"Normal";return new(new(p.TenantId,p.StorageEnabled,p.StorageQuotaBytes,p.DefaultRetentionDays,p.MotionSnapshotRetentionDays,p.MotionClipRetentionDays,p.FalsePositiveRetentionDays,p.UnreviewedEvidenceRetentionDays,p.ConfirmedIncidentRetentionDays,p.WarningPercent,p.CriticalPercent,p.AllowSnapshots,p.AllowMotionClips,p.AutoCleanupEnabled,p.QuotaPressurePolicy,p.UpdatedUtc),new(u.TenantId,u.QuotaBytes,u.UsedBytes,Math.Max(0,u.QuotaBytes-u.UsedBytes),u.SnapshotBytes,u.MotionClipBytes,u.SecurityEvidenceBytes,u.OtherBytes,percent,pressure,u.LastCalculatedUtc,u.LastCleanupUtc));}
    private static void ValidateMetadata(CctvEvidenceMetadata m,CctvServiceCredential c,DateTime now){if(m.ContractVersion!=1||m.CapturedUtc.Kind!=DateTimeKind.Utc||m.CapturedUtc>now.AddMinutes(1)||m.EvidenceType is not(CameraEvidenceType.MotionSnapshot or CameraEvidenceType.MotionClip))throw Fail("CCTV evidence metadata values are invalid.");if(m.TenantId!=c.TenantId||(!c.AllowAllStores&&!c.StoreIds.Contains(m.StoreId)))throw Fail("CCTV evidence is outside the configured service tenant/store scope.",CameraTrackingFailureKind.Forbidden);var expected=m.EvidenceType==CameraEvidenceType.MotionSnapshot?new[]{"image/jpeg","image/png"}:new[]{"video/mp4"};if(!expected.Contains(m.ContentType,StringComparer.OrdinalIgnoreCase))throw Fail("Evidence content type does not match its type.");if(m.MotionEventId.HasValue||m.SecurityIncidentId.HasValue)throw Fail("Event linkage is not available at this ingestion phase.");}
    private static void ValidateSignature(string secret,string suppliedValue,byte[]canonical){var expected=HMACSHA256.HashData(Encoding.UTF8.GetBytes(secret),canonical);byte[]supplied;try{var x=suppliedValue.StartsWith("sha256=",StringComparison.OrdinalIgnoreCase)?suppliedValue[7..]:suppliedValue;supplied=Convert.FromHexString(x);}catch(FormatException){throw Fail("CCTV evidence signature is invalid.",CameraTrackingFailureKind.Unauthorized);}if(supplied.Length!=expected.Length||!CryptographicOperations.FixedTimeEquals(supplied,expected))throw Fail("CCTV evidence signature is invalid.",CameraTrackingFailureKind.Unauthorized);}
    private static string ObjectKey(CctvEvidenceMetadata m,long cameraId,DateTime now){var folder=m.EvidenceType==CameraEvidenceType.MotionSnapshot?"snapshots":"clips";return $"tenants/{m.TenantId:D12}/stores/{m.StoreId:D12}/cameras/{cameraId:D12}/{now:yyyy/MM/dd}/{folder}/{Guid.NewGuid():N}.enc";}
    private async Task LockAsync(long tenant,CancellationToken ct){if(!db.Database.IsSqlServer())return;await db.Database.ExecuteSqlInterpolatedAsync($"EXEC sys.sp_getapplock @Resource={"tenant-storage:"+tenant.ToString(CultureInfo.InvariantCulture)}, @LockMode='Exclusive', @LockOwner='Transaction', @LockTimeout=10000",ct);}
    private long RequireTenant()=>currentUser.IsAuthenticated&&!currentUser.IsPlatformAdmin&&currentUser.TenantId is>0?currentUser.TenantId.Value:throw Fail("A tenant session is required.",CameraTrackingFailureKind.Unauthorized);private void RequirePlatform(){if(!currentUser.IsAuthenticated||!currentUser.IsPlatformAdmin)throw Fail("A platform session is required.",CameraTrackingFailureKind.Forbidden);}private bool TenantWide()=>currentUser.Roles.Any(x=>x is "TenantAdmin" or "TenantOwner" or "ShopOwner");private void RequireStore(long id){if(id<=0||(!TenantWide()&&!currentUser.StoreIds.Contains(id)))throw Fail("Store access is not assigned.",CameraTrackingFailureKind.Forbidden);}private DateTime Now()=>clock.GetUtcNow().UtcDateTime;private static DateTime ParseUtc(string x)=>DateTimeOffset.TryParse(x,CultureInfo.InvariantCulture,DateTimeStyles.AssumeUniversal|DateTimeStyles.AdjustToUniversal,out var v)?v.UtcDateTime:throw Fail("CCTV evidence timestamp is invalid.",CameraTrackingFailureKind.Unauthorized);private static CameraTrackingException Fail(string message,CameraTrackingFailureKind kind=CameraTrackingFailureKind.Validation)=>new(message,kind);
}
