import { provideHttpClient } from '@angular/common/http';
import { HttpTestingController, provideHttpClientTesting } from '@angular/common/http/testing';
import { TestBed } from '@angular/core/testing';
import { firstValueFrom } from 'rxjs';
import { PlatformTenantApiService } from './platform-tenant-api.service';

describe('PlatformTenantApiService',()=>{let api:PlatformTenantApiService;let http:HttpTestingController;beforeEach(()=>{TestBed.configureTestingModule({providers:[provideHttpClient(),provideHttpClientTesting()]});api=TestBed.inject(PlatformTenantApiService);http=TestBed.inject(HttpTestingController);});afterEach(()=>http.verify());
  it('sends canonical paging filters without client authority headers',async()=>{const result=firstValueFrom(api.list({page:2,pageSize:10,search:'north',status:'Active',planId:4}));const req=http.expectOne(r=>r.url==='/api/platform/tenants');expect(req.request.params.get('page')).toBe('2');expect(req.request.params.get('planId')).toBe('4');expect(req.request.headers.has('X-Tenant-Id')).toBe(false);req.flush({items:[],page:2,pageSize:10,totalCount:0});await result;});
  it('preserves opaque version and audit reason on subscription assignment',async()=>{const result=firstValueFrom(api.assignSubscription(7,{subscriptionPlanId:3,billingCycle:'Monthly',status:'Active',startsUtc:'2026-08-16T00:00:00.000Z',endsUtc:null,autoRenew:true,maxStores:4,maxUsers:null,maxCameras:null,maxMonthlyRecognitions:null,maxMonthlyApiCalls:null,expectedVersion:'opaque-token',auditReason:'Approved expansion'}));const req=http.expectOne('/api/platform/tenants/7/subscription');expect(req.request.method).toBe('PUT');expect(req.request.body.expectedVersion).toBe('opaque-token');expect(req.request.body.auditReason).toBe('Approved expansion');req.flush({id:7});await result;});
  it('loads dashboard from the same-origin platform route',async()=>{const result=firstValueFrom(api.dashboard());const req=http.expectOne('/api/platform/dashboard');req.flush({totalTenants:1});await result;});
  it('preserves quota audit evidence in tenant creation',async()=>{const result=firstValueFrom(api.create({legalName:'North Retail Ltd',displayName:'North',timeZone:'Asia/Kolkata',primaryContactName:'Asha',primaryEmail:'asha@example.test',primaryMobile:null,countryCode:'IN',currencyCode:'INR',planId:2,maxStores:12,maxUsers:null,maxCameras:null,auditReason:'Approved launch capacity'}));const req=http.expectOne('/api/platform/tenants');expect(req.request.method).toBe('POST');expect(req.request.body.maxStores).toBe(12);expect(req.request.body.auditReason).toBe('Approved launch capacity');req.flush({id:7});await result;});
});
