import { ChangeDetectionStrategy, Component, OnInit, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { finalize } from 'rxjs';
import { AdminShell } from '../../shared/admin-shell/admin-shell';
import { PlatformTenantApiService } from './platform-tenant-api.service';
import { CreateTenantRequest, SubscriptionPlanOption, UpdateTenantRequest } from './platform-tenant.models';

/** Provides validated create/edit tenant forms while preserving the API concurrency token on edits. */
@Component({selector:'app-tenant-editor-page',imports:[AdminShell,ReactiveFormsModule,RouterLink],templateUrl:'./tenant-editor-page.html',styleUrl:'./tenant-management.scss',changeDetection:ChangeDetectionStrategy.OnPush})
export class TenantEditorPage implements OnInit {
  private readonly fb=inject(FormBuilder); private readonly api=inject(PlatformTenantApiService); private readonly route=inject(ActivatedRoute); private readonly router=inject(Router);
  protected readonly plans=signal<SubscriptionPlanOption[]>([]); protected readonly busy=signal(false); protected readonly error=signal(''); protected readonly tenantId=Number(this.route.snapshot.paramMap.get('tenantId'))||null; private version='';
  protected readonly form=this.fb.nonNullable.group({legalName:['',[Validators.required,Validators.maxLength(200)]],displayName:['',[Validators.required,Validators.maxLength(150)]],primaryContactName:['',[Validators.required,Validators.maxLength(150)]],primaryEmail:['',[Validators.required,Validators.email]],primaryMobile:[''],countryCode:['IN',[Validators.required,Validators.minLength(2),Validators.maxLength(2)]],timeZone:['Asia/Kolkata',Validators.required],currencyCode:['INR',[Validators.required,Validators.minLength(3),Validators.maxLength(3)]],planId:[''],maxStores:[''],maxUsers:[''],maxCameras:[''],auditReason:['',[Validators.maxLength(500)]]});
  ngOnInit():void { this.api.plans().subscribe({next:v=>this.plans.set(v),error:()=>this.plans.set([])}); if(this.tenantId){this.form.controls.planId.disable();this.form.controls.maxStores.disable();this.form.controls.maxUsers.disable();this.form.controls.maxCameras.disable();this.busy.set(true);this.api.get(this.tenantId).pipe(finalize(()=>this.busy.set(false))).subscribe({next:t=>{this.version=t.version;this.form.patchValue({legalName:t.legalName,displayName:t.displayName,primaryContactName:t.primaryContactName,primaryEmail:t.primaryEmail,primaryMobile:t.primaryMobile??'',countryCode:t.countryCode,timeZone:t.timeZone,currencyCode:t.currencyCode});},error:()=>this.error.set('Tenant profile could not be loaded.')});}}
  protected save():void { if(this.form.invalid){this.form.markAllAsTouched();return;} const v=this.form.getRawValue();const hasQuotaOverride=Boolean(v.maxStores||v.maxUsers||v.maxCameras);if(!this.tenantId&&hasQuotaOverride&&v.auditReason.trim().length<3){this.form.controls.auditReason.setErrors({auditReasonRequired:true});this.error.set('Explain custom quota overrides with an audit reason of at least 3 characters.');return;} this.busy.set(true);this.error.set('');const request$=this.tenantId?this.api.update(this.tenantId,{legalName:v.legalName,displayName:v.displayName,timeZone:v.timeZone,primaryContactName:v.primaryContactName,primaryEmail:v.primaryEmail,primaryMobile:v.primaryMobile||null,countryCode:v.countryCode.toUpperCase(),currencyCode:v.currencyCode.toUpperCase(),expectedVersion:this.version} satisfies UpdateTenantRequest):this.api.create({legalName:v.legalName,displayName:v.displayName,timeZone:v.timeZone,primaryContactName:v.primaryContactName,primaryEmail:v.primaryEmail,primaryMobile:v.primaryMobile||null,countryCode:v.countryCode.toUpperCase(),currencyCode:v.currencyCode.toUpperCase(),planId:v.planId?Number(v.planId):null,maxStores:v.maxStores?Number(v.maxStores):null,maxUsers:v.maxUsers?Number(v.maxUsers):null,maxCameras:v.maxCameras?Number(v.maxCameras):null,auditReason:v.auditReason.trim()||null} satisfies CreateTenantRequest);request$.pipe(finalize(()=>this.busy.set(false))).subscribe({next:t=>void this.router.navigate(['/admin/tenants',t.id]),error:e=>this.error.set(e.status===409?'This tenant changed elsewhere. Reload before saving.':'Tenant could not be saved. Check the form and retry.')});}
}
